### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by superche** [yihong0618/running_page#10]
As this project support globalized running app (Nike, Adidas and Strava), you should consider about involving i18n into this project

**Comment by yihong0618** [comment]
I think so, but I am not familiar with i18n, I will look into it later.
Thank you very much~

**Comment by superche** [comment]
> I think so, but I am not familiar with i18n, I will look into it later.
> Thank you very much~

try react-i18next or react-intl-hooks :)
you can also add this task into todo list

**Comment by yihong0618** [comment]
@superche 

OK~
