### ISSUE TITLE
sync gpx to strava support

### ISSUE THREAD

**Issue by qudongfang** [yihong0618/running_page#100]
Does anyone want the feature of syncing GPX files to [Strava](http://strava.com/)?

I've made it working locally

And I can make a PR if anyone else wants it.

**Comment by yihong0618** [comment]
Of course you can add like "keep" with command that --with-gpx

**Comment by yihong0618** [comment]
And I think we can make it default in GitHub Actions

**Comment by yihong0618** [comment]
I think we need this feat~
And nike_to_strava is using send gpx to strava way<
