### ISSUE TITLE
[小帮助]running page 的iOS app版本

### ISSUE THREAD

**Issue by L1cardo** [yihong0618/running_page#102]
您好
我正在打算开发一款iOS的app，可以通过iOS14小组件在桌面显示跑步的方格图，我目前的方式是解析running page生成的`github.svg`文件，但是这样会有个问题：如果svg文件包含多个年份的跑步记录，那么我就没办法很好的进行区分。我也试过通过`activities.json`文件来操作，也是遇到了一点问题：只包含有数据的天，没办法很好的遍历

所以您看这样行吗：
1. 在svg文件里面将每一个年份分别放进一个容器（元素）里面，我提取一个容器就是一个年的数据
2. `activities.json`目前只包含有数据的天，希望能将没有跑步数据的天也进行填充（只包含日期，不包含跑步数据），我通过日期来操作

以上任意一个都可以极大的帮助到我，等开发完毕，我将免费上架app store
如果您没时间，那么我就做成只显示今年的数据
感谢

<img width="1314" alt="image" src="https://user-images.githubusercontent.com/33802186/112088669-36444d80-8bcb-11eb-826a-db12f3208189.png">

**Comment by yihong0618** [comment]
@L1cardo 
Hi 
这个 svg 是包含 title 的， title 里面有日期、你鼠标移动到上面就可以显示出来，还有点击事件的~

**Comment by yihong0618** [comment]
也可以单独生成一年的数据，加上 --year 就行。

![image](https://user-images.githubusercontent.com/15976103/112090050-c7b4bf00-8bcd-11eb-8de5-1eb4e6ae7fa9.png)

**Comment by L1cardo** [comment]
想的是弄成大家通用的，单独生成一年的，别人可能不会弄
不过我用title里面的日期来进行年份的分类吧
谢谢了

**Comment by yihong0618** [comment]
> 想的是弄成大家通用的，单独生成一年的，别人可能不会弄
> 不过我用title里面的日期来进行年份的分类吧
> 谢谢了

没事儿，我感觉可以加个年在 title 里，我看看有啥更好的方法没。

**Comment by L1cardo** [comment]
> > 想的是弄成大家通用的，单独生成一年的，别人可能不会弄
> > 不过我用title里面的日期来进行年份的分类吧
> > 谢谢了
> 
> 没事儿，我感觉可以加个年在 title 里，我看看有啥更好的方法没。

我想的是svg里面添加类似<div>的标签来分割不同的年份，不知道能不能实现

**Comment by yihong0618** [comment]
我理解的是不能，我查一下哈

**Comment by L1cardo** [comment]
或者在每一个rect里面加一个year 来区分，这个也可以的

**Comment by yihong0618** [comment]
好，我晚上看一下。

**Comment by L1cardo** [comment]
如果您实在没时间，也不是很好搞的话，那我就显示今年一年的数据吧，也是可以的

**Comment by yihong0618** [comment]
应该有哈哈
hint....其实你可以从 data.db 入手，我理解的 swift 应该有一些 orm 之类读 sqlite3 之类的库，拿到local_time -> parse year -> generate year list [....] 类似这样。

**Comment by L1cardo** [comment]
> 应该有哈哈
> hint....其实你可以从 data.db 入手，我理解的 swift 应该有一些 orm 之类读 sqlite3 之类的库，拿到local_time -> parse year -> generate year list [....] 类似这样。

嗯嗯  我试试

**Comment by L1cardo** [comment]
基本上搞定了，是从`activities.json`文件入手，虽然填充没有数据的天数（因为没有数据的天数也要遍历，来显示相应天的空白方块）有点麻烦，但是还是搞定了
网页版可以加一个小圆角，还挺好看的
<img width="975" alt="image" src="https://user-images.githubusercontent.com/33802186/112126374-5a218680-8bff-11eb-89f2-8e5d60a64ba9.png">

**Comment by yihong0618** [comment]
帅啊，真漂亮。
---
我感觉你可以做的直接支持 strava....因为 strava api 是开放的（他们还没支持 iOS 14）

**Comment by L1cardo** [comment]
这个其实是为了满足自己的小需求吧，最近忙着学校的事情，时间也不是很多，数据用的running page生成的数据，其他的不搞啦，哈哈

**Comment by yihong0618** [comment]
如果开源的话，我可以尝试下帮忙加入 strava 的支持。

**Comment by L1cardo** [comment]
> 如果开源的话，我可以尝试下帮忙加入 strava 的支持。

开不开源其实无所谓，但是我的代码太烂了，不好看，哈哈

**Comment by yihong0618** [comment]
好的~

**Comment by L1cardo** [comment]
刚刚通过审核，可以测试了
https://testflight.apple.com/join/oUDAMoCn

最后还是用了处理svg文件的方法，比处理json要快很多，不知道为什么😂
相同数据的json文件大小是svg的三倍，可能和这个有关，也可能和我写的代码有关

**Comment by yihong0618** [comment]
我试了下，好像没解析成功。下面这俩，都是 0 km

https://raw.githubusercontent.com/yihong0618/running_page/master/assets/github.svg
https://raw.githubusercontent.com/yihong0618/blog/master/assets/github.svg

**Comment by L1cardo** [comment]
> 我试了下，好像没解析成功。下面这俩，都是 0 km
> 
> 
> 
> https://raw.githubusercontent.com/yihong0618/running_page/master/assets/github.svg
> 
> https://raw.githubusercontent.com/yihong0618/blog/master/assets/github.svg

我这里可以哎，是您网络问题吗
![image](https://user-images.githubusercontent.com/33802186/112405082-91ea1480-8d4c-11eb-9e6d-ceaa4bf32382.jpeg)

**Comment by yihong0618** [comment]
帅，看起来是网络问题。raw.github是墙的。
![image](https://user-images.githubusercontent.com/15976103/112405741-d3c78a80-8d4d-11eb-9bc9-58d9f562634b.png)

**Comment by L1cardo** [comment]
请问一下nike run club那个的字体可商用吗？
虽然我这个app是免费的app，那我用的话算不算商用呢，还是得要开源呀

**Comment by yihong0618** [comment]
@L1cardo 你计算是不是没考虑时区。理论上空白那天是有的。
![image](https://user-images.githubusercontent.com/15976103/112406279-da0a3680-8d4e-11eb-89b5-d66063eb5d04.png)

**Comment by yihong0618** [comment]
> 请问一下nike run club那个的字体可商用吗？
> 虽然我这个app是免费的app，那我用的话算不算商用呢，还是得要开源呀

这个我不太懂，不过可以换一个能商用的字体啊，像你之前的 app 一样。

**Comment by L1cardo** [comment]
> @L1cardo 你计算是不是没考虑时区。理论上空白那天是有的。
> 
> ![image](https://user-images.githubusercontent.com/15976103/112406279-da0a3680-8d4e-11eb-89b5-d66063eb5d04.png)
> 
> 

您在设置里面改一改颜色的阈值试一试

**Comment by yihong0618** [comment]
> > @L1cardo 你计算是不是没考虑时区。理论上空白那天是有的。
> > ![image](https://user-images.githubusercontent.com/15976103/112406279-da0a3680-8d4e-11eb-89b5-d66063eb5d04.png)
> 
> 您在设置里面改一改颜色的阈值试一试

cool, 把 year ascending 选上好用了

**Comment by L1cardo** [comment]
> > > @L1cardo 你计算是不是没考虑时区。理论上空白那天是有的。
> 
> > > ![image](https://user-images.githubusercontent.com/15976103/112406279-da0a3680-8d4e-11eb-89b5-d66063eb5d04.png)
> 
> > 
> 
> > 您在设置里面改一改颜色的阈值试一试
> 
> 
> 
> cool, 把 year ascending 选上好用了

不知道为什么，有些人的svg是2021年在最前面，而有些人的是2021年在最后面
所以得要手动选一下

**Comment by yihong0618** [comment]
啊。。。是因为我后来更新了，把 2021放在最上了哈哈。

**Comment by L1cardo** [comment]
> 啊。是因为我后来更新了，把 2021 放在最上了哈哈。

哈哈，那可能他们没更新源码
那我下个版本去掉升序，然后让他们更新一下running page源码，我这边处理起来也方便😄

**Comment by w4mxl** [comment]
@L1cardo 👏 做的挺好的，一直也有用小组件展示跑步方格的需求。
很希望作者可以考虑将代码开源出来，可以在此基础上加一下自己想要实现的其它功能
