### ISSUE TITLE
HELP

### ISSUE THREAD

**Issue by OrdinarySK** [yihong0618/running_page#103]
我在把该项目下载后，进行了部分改造后，提交到了自己的guthub仓库，并托管在vercel. 我也标注了作者您的原创和链接。但是前两天貌似给我把仓库删了。

**Comment by yihong0618** [comment]
@OrdinarySK 嗯？您想问什么？可以重新生成啊

**Comment by OrdinarySK** [comment]
Hello,

We received a DMCA takedown notice regarding your repository OrdinarySK/Running.
As such, we have disabled public access to the repository.

The notice has been publicly posted at:

https://github.com/github/dmca/blob/master/2021/03/2021-03-05-adidas-runtastic.md

If you believe that your repository was disabled as a result of mistake or misidentification, you have the right to file a counter notice and have the repository reinstated. Our help articles provide more details about how the DMCA notice-and-takedown process works at GitHub and how to file a counter notice with us if you choose:

https://docs.github.com/articles/dmca-takedown-policy
https://docs.github.com/articles/guide-to-submitting-a-dmca-counter-notice 

If you have any questions about the process or the risks in filing a counter notice, we suggest that you consult with a lawyer.

Thanks,
The GitHub Team
这是官方的邮件，目前我的仓库的该项目的代码已经被隐藏。

**Comment by yihong0618** [comment]
@OrdinarySK 
是 adidas-runtastic 报告下架的。。。
你需要建私人仓库生成了。

**Comment by OrdinarySK** [comment]
好的  谢谢

**Comment by yihong0618** [comment]
看起来我也需要移除 runtastic 了。

**Comment by yihong0618** [comment]
@OrdinarySK 你能说下你改啥代码了么？关于 runtastic 的。

**Comment by yihong0618** [comment]
@OrdinarySK 另外你重新生成最好不用 runtastic 了，你可以导出 gpx 迁移到其它的。。。

**Comment by OrdinarySK** [comment]
在你的代码的基础上  主要改了界面上的一些 标识  比如 
![image](https://user-images.githubusercontent.com/22768392/112110743-491c4980-8bee-11eb-8002-accc22673b15.png)
主要是改了界面的一些名字 再就是mapbox的token

**Comment by yihong0618** [comment]
@OrdinarySK 奇怪了，那我主动下架 runtastic 这个吧。

**Comment by OrdinarySK** [comment]
我的仓库已经被隐藏了，已经访问不到了。是的 ，还是小心点好。

**Comment by yihong0618** [comment]
@OrdinarySK 你重新生成试试吧。哈哈，谢谢你。

**Comment by OrdinarySK** [comment]
我可以直接不用runtastic_sync.py脚本吧，我用的keep.

**Comment by yihong0618** [comment]
@OrdinarySK 最好 fork 最新的代码.... 新的里应该没有 runtastic 相关的代码了。

**Comment by OrdinarySK** [comment]
好的  谢谢。

**Comment by yihong0618** [comment]
@OrdinarySK 不好意思你可能得删除 fork 重新拉一下。刚才操作错了我们
