### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by 965962591** [yihong0618/running_page#105]
请问出现如题的问题，如何解决？谢谢

**Comment by yihong0618** [comment]
> 请问出现如题的问题，如何解决？谢谢

能提供更多信息么^_^
比如错误截图
python 版本
你用的app

**Comment by 965962591** [comment]
我尝试本地构建但是也会报错，我就想可以用您的工具，将keep的gpx数据导出来，然后我再自己处理。
本地构建报如下错误：
![image](https://user-images.githubusercontent.com/34186275/112453847-0e074b00-8d93-11eb-9f63-a95176323356.png)
python 版本：3.9.0
当我使用自带的cmd管理员方式运行时，并无报错。

**Comment by yihong0618** [comment]
导出 gpx 的话不需要node 直接 sync 就行

**Comment by 965962591** [comment]
感谢您的解惑。

**Comment by yihong0618** [comment]
@965962591 客气了

**Comment by yihong0618** [comment]
@965962591 请问这个问题解决了么？
我关掉这个 issue 了。
