### ISSUE TITLE
不打包 svg 至 js

### ISSUE THREAD

**Issue by Mayandev** [yihong0618/running_page#106]
请问在 gatsby build 生成页面时，能否不打包 svg 到 js 文件里，而是作为静态文件引入。这样的话， svg 可以作为 url，很容易引入到任何其他的网页中。

**Comment by yihong0618** [comment]
@Mayandev  我不确定 gatsby 可不可以，大约半年前我试验是引入不进去的不知道为什么。必须用 gatsby 的一个 svg 插件。不知道你能成功么~ PR welcome. 哈哈。

btw. 我引入其他网页是用的 GitHub 的链接， 墙内我用的是 gitee 的链接。

同步 gitee 见 —— https://github.com/yihong0618/blog/blob/master/.github/workflows/run_data_sync.yml

![image](https://user-images.githubusercontent.com/15976103/113265826-27fedb80-9307-11eb-989c-06d13865e157.png)

**Comment by Mayandev** [comment]
> @Mayandev 我不确定 gatsby 可不可以，大约半年前我试验是引入不进去的不知道为什么。必须用 gatsby 的一个 svg 插件。不知道你能成功么~ PR welcome. 哈哈。
> 
> btw. 我引入其他网页是用的 GitHub 的链接， 墙内我用的是 gitee 的链接。
> 
> 同步 gitee 见 —— https://github.com/yihong0618/blog/blob/master/.github/workflows/run_data_sync.yml
> 
> ![image](https://user-images.githubusercontent.com/15976103/113265826-27fedb80-9307-11eb-989c-06d13865e157.png)

感谢回复，我会尝试的。另外，如果直接引入 GitHub 仓库里的图片应该是会有跨域问题的，例如你在其他网站插入下面的 html

```html
<img src="https://github.com/yihong0618/running_page/blob/master/assets/github.svg">
```
图片是显示不了的，除非使用 raw.githubusercontent.com 域的图片。

```html
<img src="https://raw.githubusercontent.com/yihong0618/running_page/da9c4f161650198ba346bd388edec617391c12db/assets/github.svg">
```

但是 GitHub Action 运行会导致这个 raw 域下的 svg 的地址更新，所以最好还是可以在 build 的时候，把 svg 单独提出来，然后通过 github io 或者自定义的域名拿到这个 svg。

Thx a lot, BTW.

**Comment by MFYDev** [comment]
@yihong0618 @Mayandev 
对于这个问题我提供一个我自己用的解决方法吧。

之前我用github page的时候尽管svg不在静态文件中，但是由于raw.githubusercontent.com的存在，依然可以通过仓库源文件跨域调用。

但是由于今天garmin同步出现了问题，我不得不切换到strava，正好strava没有屏蔽掉我服务器idc的ip段，所以就把整体代码移动到自己的服务器而不是github page上了，此时遇到了和 @Mayandev 一样的问题，原来能直接调用的svg现在不能调用了。

所以参考之前的思路，我**设置了一个中转**，即 api.yourowndomain.com，每次更新build之后在服务器上自动将svg拷贝至此api中间件的某个目录下并允许跨域引用，**此时就变得可以随时访问并且跟随每一次build更新了**。

当然，不一定非得用新域名，你拷贝到 **`/public/static`** 下应该也可以，无非只是一行命令的事情而已。

尽管这样也能达到同样效果，但是我同意 @Mayandev 的建议，svg如果能在build过程中自动到static中会省事一些，**但是这个需求并不强烈，如果较难做到，那么没有必要花费时间去更改**，无非就是用户多拷贝一下而已。

**Comment by Mayandev** [comment]
命令解决是一个不错的思路呀，可以在 build script 里加上复制的命令

**Comment by MFYDev** [comment]
> 命令解决是一个不错的思路呀，可以在 build script 里加上复制的命令

是的，直接在服务器中写一个 sh 文件，每次跑完运行一下即可。我在看了你的部署方式之后觉得你可以在你的github actions里面加一个复制命令把svg复制到 `gh-pages` 分支中的static文件夹即可，这样在你的自定义域名下又能访问完整running page又可以随意引用svg了
