### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by hishark** [yihong0618/running_page#108]
你好，我按照[安装步骤](https://github.com/yihong0618/running_page#installation-and-testing)进行安装，输入 `yarn develop` 之后报错日志如下：

```
yarn run v1.22.10
$ gatsby develop
success open and validate gatsby-configs - 0.088s
success load plugins - 1.492s
success onPreInit - 0.065s
success initialize cache - 0.017s
success copy gatsby files - 0.084s
success onPreBootstrap - 0.017s
success createSchemaCustomization - 0.201s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.499s
success building schema - 0.257s
info Total nodes: 1795, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.002s
success Checking for changed pages - 0.000s
success createPagesStatefully - 0.053s
success update schema - 0.024s
success write out redirect data - 0.001s
success onPostBootstrap - 0.002s
info bootstrap finished - 6.159s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.387s
success write out requires - 0.006s
success run static queries - 0.098s - 2/2 20.38/s
success run page queries - 0.014s - 3/3 209.83/s

ERROR

Cannot read property 'get' of undefined



  TypeError: Cannot read property 'get' of undefined

  - DefinePlugin.js:549 Object.keys.forEach.key
    [running_page]/[webpack]/lib/DefinePlugin.js:549:57

  - Array.forEach

  - DefinePlugin.js:545 walkDefinitionsForValues
    [running_page]/[webpack]/lib/DefinePlugin.js:545:31

  - DefinePlugin.js:571 compiler.hooks.compilation.tap
    [running_page]/[webpack]/lib/DefinePlugin.js:571:5


  - Hook.js:154 SyncHook.lazyCompileHook
    [running_page]/[tapable]/lib/Hook.js:154:20

  - Compiler.js:631 Compiler.newCompilation
    [running_page]/[gatsby]/[webpack]/lib/Compiler.js:631:26

  - Compiler.js:667 hooks.beforeCompile.callAsync.err
    [running_page]/[gatsby]/[webpack]/lib/Compiler.js:667:29


  - Hook.js:154 AsyncSeriesHook.lazyCompileHook
    [running_page]/[tapable]/lib/Hook.js:154:20

  - Compiler.js:662 Compiler.compile
    [running_page]/[gatsby]/[webpack]/lib/Compiler.js:662:28

  - Watching.js:77 compiler.hooks.watchRun.callAsync.err
    [running_page]/[gatsby]/[webpack]/lib/Watching.js:77:18



  - index.js:173 watchRunHook
    [running_page]/[webpack-virtual-modules]/index.js:173:5



not finished Building development bundle - 2.619s

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

我自己查了查也找不到解决方法，想请教一下是哪里出了问题呢？感谢 ☺️

**Comment by shaonianche** [comment]
@hishark 
Hi，我尝试在 mac 下使用 yarn develop 和 gatsby develop 都可以构建成功，请问你使用的什么操作系统运行命令呢？
![38851617677245_ pic_hd](https://user-images.githubusercontent.com/16186646/113651991-9526be00-96c5-11eb-9dc6-a46b5d378cdc.jpg)

**Comment by yihong0618** [comment]
@hishark 
我按报错信息搜了下，https://github.com/gatsbyjs/gatsby/issues/26403
不知道是不是这个问题~

**Comment by hishark** [comment]
> @hishark
> Hi，我尝试在 mac 下使用 yarn develop 和 gatsby develop 都可以构建成功，请问你使用的什么操作系统运行命令呢？
> ![38851617677245_ pic_hd](https://user-images.githubusercontent.com/16186646/113651991-9526be00-96c5-11eb-9dc6-a46b5d378cdc.jpg)

我也是用的 macos 耶哭了

**Comment by hishark** [comment]
> @hishark
> 我按报错信息搜了下，[gatsbyjs/gatsby#26403](https://github.com/gatsbyjs/gatsby/issues/26403)
> [gatsbyjs/gatsby#11637](https://github.com/gatsbyjs/gatsby/issues/11637)
> 不知道是不是这个问题~

好的呀谢谢～我来看看

**Comment by yihong0618** [comment]
> > @hishark
> > 我按报错信息搜了下，[gatsbyjs/gatsby#26403](https://github.com/gatsbyjs/gatsby/issues/26403)
> > [gatsbyjs/gatsby#11637](https://github.com/gatsbyjs/gatsby/issues/11637)
> > 不知道是不是这个问题~
> 
> 好的呀谢谢～我来看看

没事儿哈哈，不过，如果本地有问题，前期数据不多的话，可以全交给 GitHub Actions, 修改 yml 文件, 让 actions 把数据跑出来。

**Comment by hishark** [comment]
> > > @hishark
> > > 我按报错信息搜了下，[gatsbyjs/gatsby#26403](https://github.com/gatsbyjs/gatsby/issues/26403)
> > > [gatsbyjs/gatsby#11637](https://github.com/gatsbyjs/gatsby/issues/11637)
> > > 不知道是不是这个问题~
> > 
> > 
> > 好的呀谢谢～我来看看
> 
> 没事儿哈哈，不过，如果本地有问题，前期数据不多的话，可以全交给 GitHub Actions, 修改 yml 文件, 让 actions 把数据跑出来。

哇哈哈哈哈开心！跑起来了，`npm install` 的时候报了个错，是本地 xcode 的问题，查了下按照[这里](https://segmentfault.com/a/1190000021394623)说的解决了，之后重新拉了一下 running_page 再按照步骤做就好啦！

**Comment by yihong0618** [comment]
#cool

**Comment by phh95** [comment]
感谢yihong老师和上面的这位网友 @hishark ，我也把自己在本地部署这个项目遇到的 3 个问题及解决方法，放在这里，可能会帮到以后遇到同样问题的新朋友     

![image](https://user-images.githubusercontent.com/29042617/134886267-69005a89-eba8-4e3a-ad45-8cefe53562ea.png)

**Comment by yihong0618** [comment]
@MFYDev can you help to add this issue to `wiki`?

**Comment by MFYDev** [comment]
> @MFYDev can you help to add this issue to `wiki`?

Sure. Will do that ASAP.

**Comment by yihong0618** [comment]
> > @MFYDev can you help to add this issue to `wiki`?
> 
> Sure. Will do that ASAP.

Cooooool

**Comment by MFYDev** [comment]
@yihong0618 
Done! Please have a look:

Chinese Version: https://wiki.mfydev.run/zh/FAQ/no-xcode-or-clt/
English Version: https://wiki.mfydev.run/en/FAQ/no-xcode-or-clt/

**Comment by yihong0618** [comment]
@ Thanks a lot
