### ISSUE TITLE
关于自定义颜色的问题

### ISSUE THREAD

**Issue by hishark** [yihong0618/running_page#109]
看到 `src/utils/const.js` 里有颜色变量：

```js
const nike = 'rgb(175,238,238)';
export const MAIN_COLOR = nike;
```

我估摸着应该就是全局颜色的设定，于是就改了个喜欢的蓝色，刷新后发现左边字体仍然是原来的默认色，只有地图中的路线图变成了我设定的蓝色。

请问是还有其他地方需要设置吗，我全局搜索了一下没找到其他自定义颜色的地方啦。

![image](https://user-images.githubusercontent.com/29684201/113712324-93d2b100-9718-11eb-9cb9-657162987962.png)

**Comment by yihong0618** [comment]
不好意思，这块比较乱，点击更改颜色的方式用的也比较 tricky
是下面这行
https://github.com/yihong0618/running_page/blob/658ea1c4485f53fbe7d101d5e4156c9f36d5f8c6/src/styles/variables.scss#L6

之后我也会整理一下~这地方。

这个 fork 对颜色样式做了些更改你有兴趣可以参考下。
btw, https://github.com/sheben404/running_page

https://sheben404.github.io/running_page/

**Comment by hishark** [comment]
> 不好意思，这块比较乱，点击更改颜色的方式用的也比较 tricky
> 是下面这行
> https://github.com/yihong0618/running_page/blob/658ea1c4485f53fbe7d101d5e4156c9f36d5f8c6/src/styles/variables.scss#L6
> 
> 之后我会把这地方整理一下~。
> 
> btw, 这个 fork 对颜色样式做了些更改你有兴趣可以参考下。
> https://github.com/sheben404/running_page
> 
> https://sheben404.github.io/running_page/

啊我说我怎么全局搜 rgb 没搜到，我刚刚搜的是 `224,237,94`，逗号后面忘记空一格啦哈哈。

好的我改好颜色了嘿嘿！之后有空我去看看这个 fork～

以及今天终于抽空把我自己的 [running_page](https://hishark777.com/running_page/) 弄好啦，今年还没出门跑过步，我觉得这个 page 会激励我出去跑起来填格子的哈哈哈哈哈哈！

看 README 的时候本来想拉到最后看看有没有赞赏的二维码扫一下，发现一句【谢谢就够了】，那就谢谢你啦哈哈哈做出这么棒的项目，我真滴超喜欢 😆

**Comment by yihong0618** [comment]
帅～ 加油加油(^^) 一切顺利。
