### ISSUE TITLE
使用悦跑圈数据生成 svg 时报错

### ISSUE THREAD

**Issue by weijiew** [yihong0618/running_page#112]
导入数据后，执这条命令后报错，搜了很多不知道为什么。

$ python3 scripts/gen_svg.py --from-db --title "${{ env.TITLE }}" --type github --athlete "${{ env.ATHLETE }}" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5 

zsh: bad substitution

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/114125032-38770d80-9928-11eb-839f-3e017367d748.png)

本地执行的话，需要把红框这两个改成你的变量如：

```shell
python3 scripts/gen_svg.py --from-db --title Running --type github --athlete weijiew --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5
```

env 是 Actions 中的配的。如：
https://github.com/yihong0618/running_page/blob/1fdfedf1b1d0fdde3bac65ae63d68e13fc5f87c8/.github/workflows/run_data_sync.yml#L24

**Comment by weijiew** [comment]
哇，搞定了，非常感谢！

**Comment by yihong0618** [comment]
客气了。

如果你想切换 app 的话，可以加上 --with-gpx 命令把 gpx 文件都下载下来

然后传到 strava 或其他

传到 nike 的话可以参考这篇文章 https://github.com/superleeyom/blog/issues/18

目前，咕咚，悦跑圈是无法利用 Actions 自动化的。

**Comment by weijiew** [comment]
好的，正有此意，我折腾一下。
