### ISSUE TITLE
跑步数据不匹配问题

### ISSUE THREAD

**Issue by hishark** [yihong0618/running_page#116]
> 终于出门跑步了

看了一下发现 page 拉取的数据和我手机上看到的 NRC 记录的数据有出入，请问这可能会是什么原因导致的哦？
我不是连续跑完了 3km，跑 1km 我就会停下来走一走圈，我在想会不会是这个原因导致的～

**Page：**
![image](https://user-images.githubusercontent.com/29684201/114294910-48cbeb80-9ad4-11eb-9b88-e671e0470996.png)

**NRC iOS：**
<img src="https://user-images.githubusercontent.com/29684201/114294930-5ed9ac00-9ad4-11eb-9af8-889f865df120.png" width="300">

<img src="https://user-images.githubusercontent.com/29684201/114295092-9d239b00-9ad5-11eb-96de-7b60fd72e0c6.png" width="300">

**Comment by yihong0618** [comment]
是的，

因为 nrc 的数据最终是gpx生成的，你走路其实也算距离了哈哈。但这个是有办法解决的，我下周一或者周二改一下。直接从nrc拿数据。

**Comment by hishark** [comment]
> 是的，
> 
> 因为 nrc 的数据最终是gpx生成的，你走路其实也算距离了哈哈。但这个是有办法解决的，我下周一或者周二改一下。直接从nrc拿数据。

哈哈哈好的！破案了破案了，谢谢～🥳

**Comment by shaonianche** [comment]
> > 是的，
> > 因为 nrc 的数据最终是gpx生成的，你走路其实也算距离了哈哈。但这个是有办法解决的，我下周一或者周二改一下。直接从nrc拿数据。
> 
> 哈哈哈好的！破案了破案了，谢谢～🥳

我这几天有点小忙（主要是忘了Python怎么写了已经），所以需要慢慢改（言外之意就是该 Bug 随缘修好 ...

**Comment by hishark** [comment]
> > > 是的，
> > > 因为 nrc 的数据最终是gpx生成的，你走路其实也算距离了哈哈。但这个是有办法解决的，我下周一或者周二改一下。直接从nrc拿数据。
> > 
> > 
> > 哈哈哈好的！破案了破案了，谢谢～🥳
> 
> 我这几天有点小忙（主要是忘了Python怎么写了已经），所以需要慢慢改（言外之意就是该 Bug 随缘修好 ...

问题不大哈哈哈哈随缘吧朋友（现在这样或许还能激励我一次性跑完了别停 OTZ
