### ISSUE TITLE
求小白部署教程

### ISSUE THREAD

**Issue by zjD27** [yihong0618/running_page#117]
垃圾小白报道，配合Google还是看不到教程，求一个文科生能够看懂得部署教程，不胜感谢。

**Comment by yihong0618** [comment]
@zjD27 
不好意思，这个教程目前是没有的，我也不知道该写多细致。

你可以加 README 中的 telegram 群，遇到哪步卡住可以在群里问。
关于如何安装环境的问题，这些问题你可以尝试 google 是能搜的到的。

如果你不想本地安装，也是可以的，可以直接更改 GitHub Actions 中的 yml 文件，关于这个如何更改，应该也是可以查到的。

**Comment by zjD27** [comment]
> @ zjD27
> 不好意思，这个教程目前是没有的，我也不知道该写多细致。
> 
> 你可以加README中的电报群，遇到哪步卡住可以在群里问。
> 关于如何安装环境的问题，这些问题你可以尝试谷歌是能搜的到的。
> 
> 如果你不想本地安装，也是可以的，可以直接更改GitHub Actions中的yml文件，关于这个如何更改，应该也是可以查到的。

十分感谢
