### ISSUE TITLE
增加 favicon

### ISSUE THREAD

**Issue by MFYDev** [yihong0618/running_page#120]
Running Page似乎一直没有设置favicon，

这里我使用您自己设计的 LOGO 简单做了一个 favicon 放到了我自己的 Running Page 上：

![running_page_logo](https://user-images.githubusercontent.com/53750381/115108576-d65f7d80-9fa3-11eb-85fd-4cd466f0f3ca.png)

由于原图不是正方形所以稍微做了一些的裁剪，如果不满意可以暂时当作一个备选。

实际使用效果如下：（[点我预览](https://mfydev.run)）

![image](https://user-images.githubusercontent.com/53750381/115109062-4bcc4d80-9fa6-11eb-97f6-be9764a56368.png)

我也从 icons8 和 flaticon上面找到了几个不错的跑步icon，是免费的。

这几款感觉都可以作为 Running Page Logo 的设计参考，**当然目前的这个 LOGO 就已经很好看了（感谢 @shaonianche ）**，就是作为 favicon 的话好像有点不清晰，要是有个高清的 svg 图标就好了（小声bb）：

![running](https://user-images.githubusercontent.com/53750381/115108815-0b200480-9fa5-11eb-8fd4-9583ae4c2c2e.png)：个人觉得这个最好看

![icons8](https://img.icons8.com/color/48/000000/sports-mode.png)：这个配色好像和 Running Page还挺搭？哈哈

![icons8](https://img.icons8.com/color/48/000000/trainers.png)：跑鞋拟物风

![icons8](https://img.icons8.com/cotton/64/000000/trainers.png)：这个感觉有点少女风LOL

![icons8](https://img.icons8.com/cotton/64/000000/sneakers--v2.png)：另一款跑鞋拟物风，好像配色也有点搭

**Comment by yihong0618** [comment]
感谢～我们看一下哈哈。

**Comment by MFYDev** [comment]
抱歉，我忽视了 Running Page 的 您自己设计的 LOGO 了，也放到下面：

![running_page_logo](https://user-images.githubusercontent.com/53750381/115108576-d65f7d80-9fa3-11eb-85fd-4cd466f0f3ca.png)

由于原题不是正方形所以稍微做了一些的裁剪，也可以当作一个备选

**Comment by geekplux** [comment]
let me do this ASAP..

**Comment by shaonianche** [comment]
> let me do this ASAP..

I want to get familiar with react code, I did some of the work today but I ran into some problems, can I ask you some questions?

**Comment by geekplux** [comment]
sure, plz

**Comment by MFYDev** [comment]
超级感谢 @shaonianche ！辛苦了！

此issue已解决，所以关闭。
