### ISSUE TITLE
功能建议：加入月度统计数据展示

### ISSUE THREAD

**Issue by MFYDev** [yihong0618/running_page#121]
yihong 您好，

刚刚在看 @geekplux 的 running page 的时候发现 geekplus 在首页中加入了月统计柱状图，主要显示了 跑步，徒步，骑行的月度统计数据。

![image](https://user-images.githubusercontent.com/53750381/115110291-31e23900-9fad-11eb-808e-623700191fd2.png)

私以为相比于年度和每日统计数据来说，**月度统计能够在一个更加折中的频率上展示统计数据，也丰富了展示效果**。

所以就依照 geekplus 本人的仓库尝试将此柱状图进行迁移，但是由于我并不曾深入研究学习过react框架导致出现了很多的错误。

所以想问一下您是否有任何计划将此月度统计柱状图迁移到 Running Page 仓库中呢？

**Comment by yihong0618** [comment]
@MFYDev 

目前这个还在想，因为可能好多人不会像 geekplux 一样呈现漂亮的柱状图，因为很可能只有几个运动，那样的话不算漂亮。而且目前多运动支持还没做。如果大家想用这个图，可以暂时直接用 geekplux 的 repo~

目前是有月度数据的，可以把鼠标光标停留在年度数据上，会出现环形图
![image](https://user-images.githubusercontent.com/15976103/115167887-a7542380-a0eb-11eb-9dff-3d996a8d0312.png)

**Comment by MFYDev** [comment]
好嘞明白~感谢解答~

**Comment by geekplux** [comment]
@MFYDev 你可以把报错或不懂的地方发到我那边的issue，按理来说应该不会和这个项目差太多的
