### ISSUE TITLE
功能建议：点击空白区域取消跑步记录选中或点击原数据列返回点击前的状态

### ISSUE THREAD

**Issue by MFYDev** [yihong0618/running_page#122]
yihong 您好！

今天在跑完步之后查看running page时，发现只要点击其中一项跑步记录后就无法通过    再次点击   或者  点击任何返回键    来返回总记录（即显示所有跑步路线的原本首页）

唯一的返回方法就是刷新网页，感觉这样设计少了一个允许返回的过程。

所以强烈建议允许用户在查看特定跑步记录后，能够通过再次点击相同跑步记录能够返回总记录页。

这样感觉会好很多。

如果我没有表述清楚请告诉我，我将结合图片说得更清楚些。

**Comment by shaonianche** [comment]
点击空白区域取消选中或点击原数据列返回点击前的状态？

**Comment by MFYDev** [comment]
@shaonianche 对的，您理解的就是我想表达的意思。

**Comment by shaonianche** [comment]
> @shaonianche 对的，您理解的就是我想表达的意思。

好的，我稍后调一下

**Comment by MFYDev** [comment]
超级感谢友人A！辛苦了！
