### ISSUE TITLE
佳明同步的数据把骑行当成跑步数据处理了

### ISSUE THREAD

**Issue by feitxue** [yihong0618/running_page#125]
不知道佳明的数据能否注明是跑步还是骑行

**Comment by yihong0618** [comment]
@feitxue 

理论上可以，但需要花些功夫，因为佳明用的是 gpx, 我之后做一下。

**Comment by yihong0618** [comment]
@feitxue 只同步跑步可以么？

**Comment by feitxue** [comment]
@yihong0618 当然可以.感谢大佬.

**Comment by yihong0618** [comment]
@feitxue 增加了 only-run 但因为 garmin 机制问题（上传的不会归类）
我增加了参数 --only-run
例：
```python
python3(python) scripts/garmin_sync.py ${your email} ${your password} --only-run
```

**Comment by feitxue** [comment]
@yihong0618 感谢大佬.晚上我试一下.

**Comment by ustccuikai** [comment]
@yihong0618 之前发现strava骑行的数据也被同步过来了，是不是也可以加个参数？

**Comment by yihong0618** [comment]
@ustccuikai 可以，我有空看一下~

**Comment by yihong0618** [comment]
@ustccuikai 
修改了，请帮忙测试，请删除 `data.db` 重新生成。

**Comment by ustccuikai** [comment]
> @ustccuikai
> 修改了，请帮忙测试，请删除 `data.db` 重新生成。

测试了下，骑行的数据已经过滤掉了   👍~

**Comment by feitxue** [comment]
测试了.佳明新数据没有骑行数据展示了.
我把GPX_OUT目录清空了.再重新同步佳明数据.然后重新生成svg好像还不能清理掉本地历史的旧的骑行数据.
请问还需要删除哪个目录或者文件.
感谢大佬
@yihong0618

**Comment by yihong0618** [comment]
@feitxue 
删除 `data.db`

**Comment by MFYDev** [comment]
https://github.com/yihong0618/running_page/issues/131#issuecomment-849622240
