### ISSUE TITLE
建议在README中加入Nike同步失败403的可能情况

### ISSUE THREAD

**Issue by MFYDev** [yihong0618/running_page#126]
时间：2021年5月9日 凌晨1:00

确认 refresh_token 正确，所有依赖正确安装

https://github.com/yihong0618/running_page/pull/89#issuecomment-835425629 此pr中已有人遇到了相同情况。

测试 Strava 目前还可以用， 但是 Nike to Strava 也无法使用了。

返回错误如下：

```bash
httpx.HTTPStatusError: 403 Client Error: Forbidden for url: https://unite.nike.com/tokenRefresh
For more information check: https://httpstatuses.com/403
```

**Comment by yihong0618** [comment]
你重新的登陆的话，refresh token 在 secret 里的得 update 成新的。

**Comment by yihong0618** [comment]
我这块没问题，@shaonianche 帮我看看？
另外猜测可能是这个不自持大陆区域了？
改成其它例如 hk 试一下，在设置里。

**Comment by MFYDev** [comment]
试了一下在官网把自己的区域改成了US，并且再次更新自己的refresh token依然返回了相同的错误，很奇怪。。。

**Comment by MFYDev** [comment]
@yihong0618 

由于我最近新更换了服务器，所以刚刚突然想到有可能是nike封禁了一部分服务器的IP，在换了一台欧洲完全不同数据中心的服务器之后发现可以同步。

应该是nike禁止了部分idc的ip的原因。

看来我只能用github actions同步了。

感谢yihong！

**Comment by yihong0618** [comment]
好嘞，可以加上个说明^_^

**Comment by MFYDev** [comment]
感谢yihong，辛苦啦~

此问题已解决，issue关闭啦~
