### ISSUE TITLE
是否考虑增加 Github Sponsor 或者 Patreon 呢？

### ISSUE THREAD

**Issue by MFYDev** [yihong0618/running_page#128]
@yihong0618 @shaonianche 

两位晚上好，非常感谢你们开源并维护了此项目，不知道二位是否有任何打算增加 Github Sponsor, Patreon 亦或者其他类似于这种形式的赞助渠道呢？

由于时间有限和学业压力，我一直未曾学过 React，暂时无法为核心代码做出贡献，所以想通过赞助形式维持此项目的良性运转。

如果可以我将愿意献上自己的一份绵薄之力。

**Comment by yihong0618** [comment]
感谢～

最后我加上了，谢谢就够了哈哈。
如果想帮忙，多多提 issue 和代码，欢迎欢迎～

**Comment by MFYDev** [comment]
好嘞明白~感谢回复！
