### ISSUE TITLE
Garmin login is broken I will try to fix it  as soon as possible（Garmin 修改了登陆方式，我尽快尝试解决）

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#129]

**Comment by yihong0618** [comment]
尝试失败、

**Comment by MFYDev** [comment]
目前暂时先从Garmin切换到Strava了，Strava唯一不方便的地方就是还得开个会员才能显示心率，不过也暂时没有其他办法了。

这段时间用过来发现好像就Strava最稳

**Comment by yihong0618** [comment]
@MFYDev 
等等看吧，应该所有佳明的都 broke 了，看看其它人有解决的没。

如果没解决可以尝试 session

btw, 如果你用佳明，可以用 strava 同步佳明，然后 strava 做为数据出口。

**Comment by MFYDev** [comment]
嗯嗯是的，刚刚已经使用这种方法同步成功了~

**Comment by yihong0618** [comment]
暂时的思路是先用 Cookie, 但 Cookie 有过期时间。。。

**Comment by AnneWielis** [comment]
Wouldn't be a problem, if we dispose them daily, right?

**Comment by yihong0618** [comment]
@AnneWielis @MFYDev  Done

**Comment by MFYDev** [comment]
Bravo!

**Comment by yihong0618** [comment]
大家别忘了 pip 新的依赖。
