### ISSUE TITLE
清理repo

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#13]
把没用的都删掉

**Comment by aleung** [comment]
你自己的running page也是用这个repo生成的吗？应该将个人数据从这个repo里面分离，这里就是一个纯工具。要不其他人不方便参与进来开发，merge/rebase就带上一堆更新的个人数据。

**Comment by yihong0618** [comment]
@aleung 
自己的不是，但是一直在开发里面有些测试数据，也方便别人测试。之后会清理，谢谢反馈。

**Comment by aleung** [comment]
可以将测试/演示用的数据放在一个专门的example data目录

**Comment by yihong0618** [comment]
我研究一下，目前的想法是保留一个，因为空文件夹会困扰，然后git filter 把之前commit中的文件都删掉。

**Comment by yihong0618** [comment]
@aleung 

感觉还是全删了清理历史比较好。
因为国内的网络环境占用空间大一点，大家clone就难受一点儿。

想法：
1. 把大家分享出来的跑步记录放在项目头 #12  
2. 所有sync加上
```python 
if not os has dir:
    os.mkdir()...
```
类似的容错code.

**Comment by yihong0618** [comment]
@aleung 
增加了: 大家的展示
删掉了: 大部分测试数据
