### ISSUE TITLE
本地运行的时候，获取Nike run club的数据的时候，会夹杂着别的人的数据

### ISSUE THREAD

**Issue by wwwwwfp** [yihong0618/running_page#131]
大佬？本地运行的时候，获取Nike run club的数据的时候，会夹杂这别的人的数据，是哪个地方配置有问题吗？？ 感谢

**Comment by MFYDev** [comment]
删除 `/scripts/data.db` `/src/static/activities.json`

然后同步。

**Comment by wwwwwfp** [comment]
> 删除 `/scripts/data.db` `/src/static/activities.json`
> 
> 然后同步。

谢谢大佬，这个本地打包部署后，之后的数据会自动同步吗？自动同步要怎么设置呢

**Comment by yihong0618** [comment]
@wwwwwfp 需要了解下 GitHub Actions 按照你的 secrets 和参数配置好。

**Comment by wwwwwfp** [comment]
> 不会自动同步。
> 
> 自己把这些命令写个脚本，或者使用github actions或者vercel部署。

好的，非常感谢

**Comment by wwwwwfp** [comment]
> @wwwwwfp 需要了解下 GitHub Actions 按照你的 secrets 和参数配置好。

好的，非常感谢
