### ISSUE TITLE
为什么部署成功之后，本年数据是我自己，total里展示的数据是yihong的呢？我用的keep

### ISSUE THREAD

**Issue by Zoomtoo** [yihong0618/running_page#132]

**Comment by yihong0618** [comment]
需要跑这些，另外我的筛选是 > 10 km, 这个你可以按自己的情况更改。
![image](https://user-images.githubusercontent.com/15976103/119914955-0aab5e00-bf94-11eb-836b-e9b569418f3b.png)

**Comment by MFYDev** [comment]
![Screenshot_2021-05-28-09-08-00-940_com microsoft emmx](https://user-images.githubusercontent.com/53750381/119915064-3fb7b080-bf94-11eb-9f52-aff89234cc47.jpg)

![IMG_20210528_090852](https://user-images.githubusercontent.com/53750381/119915115-5827cb00-bf94-11eb-846a-3a0c61901545.jpg)

**Comment by Zoomtoo** [comment]
好的，知道了，多谢回复

**Comment by Zoomtoo** [comment]
> 需要跑这些，另外我的筛选是 > 10 km, 这个你可以按自己的情况更改。
> ![image](https://user-images.githubusercontent.com/15976103/119914955-0aab5e00-bf94-11eb-836b-e9b569418f3b.png)

好的，知道了，多谢回复

**Comment by MFYDev** [comment]
如果已经解决请及时关闭issue，非常感谢
