### ISSUE TITLE
你好，部署到 GitHub Pages的，有些配置的环境变量没有解析出来，是什么地方配置有问题吗？

### ISSUE THREAD

**Issue by wwwwwfp** [yihong0618/running_page#133]
![image](https://user-images.githubusercontent.com/43170703/119984717-4b3ac400-bff4-11eb-89c6-d1462004a95b.png)

**Comment by shaonianche** [comment]
![image](https://user-images.githubusercontent.com/16186646/119986783-dc129f00-bff6-11eb-9395-c78c1ec7a42c.png)
你的 Run data sync 这个 actions 似乎没有运行？你手动运行一下试试，这个 svg 的文件是从 Run data sync 里面生成的。

**Comment by MFYDev** [comment]
先Run Data Sync，再Publish to Github Pages。

数据都没有该如何显示正确？

你在这里 https://github.com/wwwwwfp/run/blob/16186492172b7bb3e39243dd504df43676fc95c9/.github/workflows/run_data_sync.yml#L20-L27 已经输入对了环境变量

可以看到 https://github.com/wwwwwfp/run/blob/16186492172b7bb3e39243dd504df43676fc95c9/.github/workflows/run_data_sync.yml#L94-L97 Running Page在这里引用了你输入的内容才能生成svg图片

README中对此也有了详细的说明：
https://github.com/yihong0618/running_page/blob/master/README.md#total-data-analysis

**Comment by wwwwwfp** [comment]
> ![image](https://user-images.githubusercontent.com/16186646/119986783-dc129f00-bff6-11eb-9395-c78c1ec7a42c.png)
> 你的 Run data sync 这个 actions 似乎没有运行？你手动运行一下试试，这个 svg 的文件是从 Run data sync 里面生成的。

谢谢，现在可以了

**Comment by wwwwwfp** [comment]
> **先Run Data Sync，再Publish to Github Pages**
> 
> **要先有数据才能显示正确。**
> 
> https://github.com/yihong0618/running_page/blob/d6a50bd5eab2660193ba019cdce0df66378f9205/.github/workflows/run_data_sync.yml#L20-L26
> 
> 你在这里已经输入对了环境变量
> 
> https://github.com/yihong0618/running_page/blob/d6a50bd5eab2660193ba019cdce0df66378f9205/.github/workflows/run_data_sync.yml#L91-L97
> 
> 可以看到 Github Actions 在这里引用了你输入的内容才能生成 svg 图片
> 
> README中对此也有了详细的说明：
> 
> https://github.com/yihong0618/running_page/blob/d6a50bd5eab2660193ba019cdce0df66378f9205/README.md#L302-L326
> 
> **请仔细阅读 README 和 Github Actions 的内容，了解大概的运行逻辑，这不需要任何代码基础。**
> 
> BTW：如果之前的issue已解决不要忘记close issue。

谢谢，现在可以了

**Comment by yihong0618** [comment]
> **先Run Data Sync，再Publish to Github Pages**
> 
> 
> 
> **要先有数据才能显示正确。**
> 
> 
> 
> https://github.com/yihong0618/running_page/blob/d6a50bd5eab2660193ba019cdce0df66378f9205/.github/workflows/run_data_sync.yml#L20-L26  
> 
> 
> 
> 你在这里已经输入对了环境变量
> 
> 
> 
> https://github.com/yihong0618/running_page/blob/d6a50bd5eab2660193ba019cdce0df66378f9205/.github/workflows/run_data_sync.yml#L91-L97 
> 
> 
> 
> 可以看到 Github Actions 在这里引用了你输入的内容才能生成 svg 图片
> 
> 
> 
> README中对此也有了详细的说明：
> 
> 
> 
> https://github.com/yihong0618/running_page/blob/d6a50bd5eab2660193ba019cdce0df66378f9205/README.md#L302-L326
> 
> 
> 
> **请仔细阅读 README 和 Github Actions 的内容，了解大概的运行逻辑，这不需要任何代码基础。**
> 
> 
> 
> BTW：如果之前的issue已解决不要忘记close issue。
> 
> 

感谢耐心解答，cool.
