### ISSUE TITLE
Several suggestions to make this repo more efficient and standardized

### ISSUE THREAD

**Issue by MFYDev** [yihong0618/running_page#139]
Good afternoon guys @yihong0618 @shaonianche ,

It just occurred to me that regardless of the codes, we may need to do some optimizations to this repo to make it more standardized and efficient.

Here are my ideas in the following:

1. README.md refactoring: Since now we have a homepage, and a comprehensive wiki, we may not need the installation guide in the README so detailed anymore. So last night, I did some research and found some good README.md that we can refer to their structure. I can assign this task to myself and I am sure it can be done quickly when I am free. I will send you emails with the new README as attachment.
2. Release Control: The reason why I propose this proposal is mainly because several days ago, when I just released the initial version of the Wiki site, there were some codes in some vital parts changed. I would not noticed that if I did not watch all activities of this repo. From my perspective, I think making it release after every essential changes will be good for no matter users or developers.
3. Changelog: Maybe we should also add change log to every release and wiki.
4. Projects: I just created one this morning, a kanban can help us mange bugs and feature requests better. But what columns should it have, and how to use it, we may need some discussion, after all it is not my own repo.
5. CONTRIBUTING.md: Maybe we should add some protocols to it? For instance: Standardized the codes by using black before making any PR.

Currently these are the thoughts I have. Any better ideas are welcomed. Just wanna Running Page be better.

Meliora!

---

下午好各位 @yihong0618 @shaonianche :

我突然想到，抛开代码不谈，我们可能需要对这个 repo 做一些优化，使其更加标准化和高效。

以下是我目前的想法：

1. README.md 重构：由于现在我们有一个主页和一个全面的 wiki，我们可能不再需要 README 中的安装指南那么详细了。 所以昨晚查了一下资料，找到了一些不错的README.md，我觉得可以参考他们的结构对其重构。 我可以将这个任务分配给自己，而且我相信当我有空的时候它可以很快完成。 完成之后，我会用新的自述文件作为附件向大家发送电子邮件。
2. 规律的Release：我之所以提出这个建议，主要是因为前几天，我刚刚发布了wiki站点的初始版本之后，一些关键部分的代码发生了变化。 如果我不watch这个 repo 的所有活动，我就不会注意到。 从我的角度来看，我认为在每次重要更改后发布它对用户或开发人员都是有益的。
3. 变更日志：也许我们也应该为每个版本添加变更日志，同步Wiki。
4. Projects：我今天早上刚创建了一个，看板可以帮助我们更好地管理错误和功能请求。 但是它应该有哪些栏目，该怎么用，我们可能需要讨论一下，毕竟它不是我自己的repo。
5. CONTRIBUTING.md：也许我们应该添加一些要求？ 例如：在做任何 PR 之前使用black来标准化代码之类的。

这些是我目前的想法。任何更好的想法都欢迎。只是想让 Running Page 更好。

Meliora！

**Comment by yihong0618** [comment]
Looks good.

I will do 2 and 3. About part 5, I think any `PR` welcome seems fine, and I will add some `CI` for the `black` format.

**Comment by yihong0618** [comment]
Ci part Done.
