### ISSUE TITLE
NRC如果同时使用NTC好像有问题

### ISSUE THREAD

**Issue by shuxiao9058** [yihong0618/running_page#141]
不知道是不是NTC的缘故，今天跑步前后都使用了NTC，NRC的记录看着 data 文件里面没有记录。

还有一个问题，我在mac下使用preview生成favicon.ico图片，好像有问题，报错。

```

20:03:07.032 | success Build manifest and related icons - 0.002s
-- | --
20:03:07.070 | error "gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle:
20:03:07.071 | Input file contains unsupported image format
20:03:07.071 | Error: Input file contains unsupported image format
20:03:07.071 | not finished onPostBootstrap - 0.020s
20:03:08.478 | error Command failed with exit code 1.
20:03:08.479 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
20:03:08.495 | Error: Command "yarn run build" exited with 1

```

**Comment by yihong0618** [comment]
@shuxiao9058 

删除 data.db 重新同步试一下？之前遇到过此类的问题。我做了处理，但可能不够。

**Comment by shuxiao9058** [comment]
data.db 里面昨天还同步了keep的历史数据。。。

另外，同时使用NTC和NRC会产生这种问题吗？还是其他原因啊。

**Comment by shuxiao9058** [comment]
有没有其他办法能解决呢？我看代码里面好像是会看last_id大小，然后根据最后的id大小来看是否有记录过？感觉这个是不是应该全量查询，然后通过全局map或者查询db之类的来判断呢？

**Comment by yihong0618** [comment]
> 有没有其他办法能解决呢？我看代码里面好像是会看last_id大小，然后根据最后的id大小来看是否有记录过？感觉这个是不是应该全量查询，然后通过全局map或者查询db之类的来判断呢？

是的, 全量查询更好一点。之前没太考虑 NTC 的情况。

**Comment by yihong0618** [comment]
@shuxiao9058 
想到了个相对好的方式，我们判断下，直接如果是 NTC 我们不存 json, 这样好一些。

**Comment by shuxiao9058** [comment]
这样可以的 ~

**Comment by yihong0618** [comment]
我之后改一下。

**Comment by shuxiao9058** [comment]
好的，多谢了 ~

**Comment by shuxiao9058** [comment]
根据时间来判断也是一个主意，不大可能同时开这两个 APP。

**Comment by shuxiao9058** [comment]
> @shuxiao9058
> 想到了个相对好的方式，我们判断下，直接如果是 NTC 我们不存 json, 这样好一些。

按照这个方法我提了一个合并请求。

**Comment by MFYDev** [comment]
@shuxiao9058 不好意思刚看到，非常感谢~

**Comment by shuxiao9058** [comment]
> 还有一个问题，我在mac下使用preview生成favicon.ico图片，好像有问题，报错。

这个问题有遇到的吗？ @MFYDev @yihong0618 请问如何解决呢，前端我不太熟。

**Comment by shaonianche** [comment]
@shuxiao9058 使用新的 favicon.ico 文件替换掉原来 src/images 下面的图片应该是可以的，你是如何替换的呢？

**Comment by shuxiao9058** [comment]
这是我的 favicon.ico 文件。 [favicon.ico](https://blog.jiya.net/favicon.ico)，方便的话你可以测试一下试试 ~

**Comment by shaonianche** [comment]
> 这是我的 favicon.ico 文件。 [favicon.ico](https://blog.jiya.net/favicon.ico)，方便的话你可以测试一下试试 ~

老哥，你的 ico 源文件貌似有问题，我把你的 ico 文件用设计工具导出为 png 之后就 OK 了 ...
![favicon](https://user-images.githubusercontent.com/16186646/121020526-07ee0b80-c7d3-11eb-8469-1ed19eaf6d3a.png)

![image](https://user-images.githubusercontent.com/16186646/121020547-0b819280-c7d3-11eb-9f5f-cda60a3a369d.png)

**Comment by shuxiao9058** [comment]
ico 又不是 png。怎么要导成png，扩展名改成ico？

**Comment by shaonianche** [comment]
> ico 又不是 png。怎么要导成png，扩展名改成ico？

有可能是你源文件是别的格式直接改扩展名改成的ico，我不知道重新做一下会不会好，我试试。

**Comment by MFYDev** [comment]
@shuxiao9058 我觉得没必要咱们这改，八成是直接png改ico了。。是不是找个ico生成器转换一下，然后替换掉`favicon.ico`就可以了。。。

**Comment by shuxiao9058** [comment]
应该不是，我后来用其他软件改了下还是不行，你是用什么工具转的。

**Comment by MFYDev** [comment]
@shuxiao9058 用bitbug试一下呢？

**Comment by shaonianche** [comment]
> 应该不是，我后来用其他软件改了下还是不行，你是用什么工具转的。

这个事情很诡异，我不知道因为啥，我用苹果自带的图片查看器把你的ico导出为png，然后贴进去 yarn build 就好了，但是 ico 文件直接放进去就提示格式不支持，但是我原来的 ico 文件又不报这个错  ...

**Comment by shuxiao9058** [comment]
我用这个在线工具转换的不行，https://tool.lu/favicon/

**Comment by MFYDev** [comment]
bitbug用了吗？

**Comment by shuxiao9058** [comment]
破案了，原来目录存的是png图片，不是ico。不能用ico格式文件，文件 magic head不一样。

这个图片是我转换后的图片
<img width="1779" alt="image" src="https://user-images.githubusercontent.com/3312525/121024815-29e98d00-c7d7-11eb-81ec-ee4577765001.png">

下面是项目里面的图片，格式实际上为png。
<img width="1775" alt="image" src="https://user-images.githubusercontent.com/3312525/121024688-0a526480-c7d7-11eb-8047-876369a37942.png">

**Comment by MFYDev** [comment]
刚刚看了一下仓库里的源文件，shaonianche直接把png改成ico了。。。。

**Comment by shaonianche** [comment]
> 刚刚看了一下仓库里的源文件，shaonianche直接把png改成ico了。。。。
这格式一般的设计工具都没法导 ... 
我刚找到个工具 https://github.com/ImageMagick/ImageMagick

**Comment by MFYDev** [comment]
没事，咱们直接用png也可以的，我把这个改了一下 d1dd43f9b984b5bd07aa20554c2bf0ca3d39729b

**Comment by MFYDev** [comment]
@shuxiao9058 多谢。。。不然我们还真发现不了这个小细节。。已修复。。

**Comment by shuxiao9058** [comment]
哈哈哈哈，这样也行，折腾了好久才发现这个问题。

**Comment by MFYDev** [comment]
确实，一直用着没问题还真没发现。。。刚刚win10下一看那个ico文件发现确实是损坏的。。。比较尴尬。。

**Comment by yihong0618** [comment]
谢谢大家。
