### ISSUE TITLE
请问mapbox不显示是什么问题

### ISSUE THREAD

**Issue by malinkang** [yihong0618/running_page#149]
https://malinkang.cn/running_page/
刚开始我换了自己的mapbox的token，发现不行，以为是token的问题，然后改回了原来的token但是还是一片黑？这个需要其他的设置吗？

**Comment by yihong0618** [comment]
请问是最近开始不显示的还是一直就没显示过？

**Comment by malinkang** [comment]
从来都没显示过。

**Comment by yihong0618** [comment]
我看一下。感谢反馈

**Comment by malinkang** [comment]
好的，多谢。

**Comment by yihong0618** [comment]
@malinkang 你可以本地起一下看一看有 map 么？
本地 `yarn develop`

**Comment by yihong0618** [comment]
@malinkang 没找到具体原因，建议尝试 vercvel 看看好用不

**Comment by malinkang** [comment]
本地没有问题。之前我本地没有没运行过，有影响吗？

**Comment by yihong0618** [comment]
没影响，我尝试了很多次，目前看很可能是 github pages 问题，建议试试 vercel

**Comment by malinkang** [comment]
好的，谢谢。

**Comment by yihong0618** [comment]
@malinkang 把你的这行改成 running_page 试试
![image](https://user-images.githubusercontent.com/15976103/123919778-df16fb80-d9b7-11eb-8633-6bd48451d222.png)

**Comment by malinkang** [comment]
这个改了，确实可以了，多谢。怪自己粗心，没注意到这个设置。
