### ISSUE TITLE
Keep最近看不到地图数据了

### ISSUE THREAD

**Issue by malinkang** [yihong0618/running_page#155]

**Comment by yihong0618** [comment]
很可能是他们改了加密或者结构，我找时间看一下。

**Comment by yihong0618** [comment]
@malinkang 其它数据还有么？我现在没有测试数据。

**Comment by malinkang** [comment]
其他数据还在。https://malinkang.cn/running_page/ 从7月份开始出现

**Comment by yihong0618** [comment]
@malinkang 
可能是你用其它软件或者 Apple Watch 传到 keep 的
那样也会没数据。

如果不是他们应该改了结构

**Comment by malinkang** [comment]
@yihong0618 没有使用其他App和Apple Watch导入。Keep应用里面可以看到路线。
![image](https://user-images.githubusercontent.com/3365208/125593537-c705aff5-c486-41aa-97ad-4da711afac7e.png)

**Comment by yihong0618** [comment]
@malinkang 我找时间看一看，你有兴趣帮看看么？
找路线解析在大概这个位置

![image](https://user-images.githubusercontent.com/15976103/125593978-0e92f83a-f129-46b3-97b6-935299763f44.png)

**Comment by malinkang** [comment]
嗯，看了下数据，Keep返回的rawDataURL是None
![image](https://user-images.githubusercontent.com/3365208/125718578-e87dfe14-6d4b-41e4-accd-3657943bdc07.png)

**Comment by yihong0618** [comment]
那应该是彻底封掉数据了。。。你能看看以前的么？

**Comment by malinkang** [comment]
之前的可以，我打印了几天的。中间也有几次时好时坏。
![image](https://user-images.githubusercontent.com/3365208/125719442-457eaaec-310b-43f1-9ba1-33477bb96a62.png)

**Comment by yihong0618** [comment]
那建议尽快导出 gpx....

**Comment by malinkang** [comment]
好吧

**Comment by jingchangshi** [comment]
彻底封掉是说KEEP的API在这个项目里不能用了吗？想继续用这个项目只能转投其它app？

**Comment by yihong0618** [comment]
@jingchangshi 能用，看起来是没有地图信息了（无法导出 gpx）

**Comment by cvvz** [comment]
这个问题找到根因或者有什么解决办法么？以后用keep都没法看到地图数据了么？

**Comment by yihong0618** [comment]
现在应该是在的吧？

**Comment by yihong0618** [comment]
如果没有建议地图数据，建议更换 app 了，没有太好的解决办法

**Comment by cvvz** [comment]
有什么比较推荐一直比较稳定的app推荐吗？🤣

**Comment by cvvz** [comment]
我用keep5次，今天这一次没数据，前面四次都有

**Comment by yihong0618** [comment]
是用其它 app 传的数据或者手表跑的么？

**Comment by yihong0618** [comment]
> 有什么比较推荐一直比较稳定的app推荐吗？🤣

目前是 strava 但是不保证之后就从国内没了
有条件可以 garmin-cn

**Comment by cvvz** [comment]
不是哦，就是keep

**Comment by cvvz** [comment]
Strava支持的app也有限哇，garmin手环1000多哈哈哈。之前用小米，结果strava也不支持小米

**Comment by cvvz** [comment]
感觉keep api使用起来最简单直接的，结果现在才发现也有坑🤣

**Comment by yihong0618** [comment]
有条件的话，美区 NRC 也行

**Comment by cvvz** [comment]
设备只能和apple watch 配合吗？

**Comment by yihong0618** [comment]
你用 apple watch 的话可以用strava 直接用 apple watch 跑步 strava 上传

**Comment by cvvz** [comment]
哦哦对，谢谢！我先看看keep这个api是不是有啥特殊限制。前几次都没问题说明这个api本身应该没啥问题才对。

**Comment by cvvz** [comment]
NRC 下下来不能用，停止服务了。

**Comment by cvvz** [comment]
等二代apple watch se吧。库克应该sponsor这个项目😄😄😄

**Comment by yihong0618** [comment]
> NRC 下下来不能用，停止服务了。 ![747646135748628294](https://user-images.githubusercontent.com/44308864/188191727-50b5332c-7982-4a64-9e81-c7ea2f68e97c.png)

手机地理位置改成大陆以外

**Comment by cvvz** [comment]
嗯，太繁琐了，iphone改地理位置不太方便，还是不折腾了

**Comment by iamjinlei0312** [comment]
> 嗯，看了下数据，Keep返回的rawDataURL是None ![image](https://user-images.githubusercontent.com/3365208/125718578-e87dfe14-6d4b-41e4-accd-3657943bdc07.png)

<img width="963" alt="image" src="https://user-images.githubusercontent.com/28210665/188308888-d7304a67-c695-4daa-8aba-8a590592a885.png">

我这确实是这样

**Comment by real-jiakai** [comment]
我这边keep显示正常啊。我拿手机跑的。
今天晚上刚搭的，感谢博主的项目，以后有了跑步的动力。:smile: :smile: :smile:
[demo](https://running.jiakai.page)

**Comment by lingdeyiyicifang** [comment]
今天整理keep数据时，发现一个规律
在2021.3.4日之后，导出的数据里地图数据时有时无（100条里大概40多条无）。但是2021.3.4日之前keep记录的数据，导出均含有地图数据（44/44）

**Comment by YeWeihong** [comment]
> 我这边keep显示正常啊。我拿手机跑的。 今天晚上刚搭的，感谢博主的项目，以后有了跑步的动力。😄 😄 😄 [demo](https://running.gujiakai.top/)

请问你是拿着手机跑步才有轨迹的吗，我是华为健康同步到keep，然后这些同步的数据就没有轨迹，应该是第三方同步就没有轨迹数据gpx

**Comment by yihong0618** [comment]
> > 我这边keep显示正常啊。我拿手机跑的。 今天晚上刚搭的，感谢博主的项目，以后有了跑步的动力。😄 😄 😄 [demo](https://running.gujiakai.top/)
> 
> 请问你是拿着手机跑步才有轨迹的吗，我是华为健康同步到keep，然后这些同步的数据就没有轨迹，应该是第三方同步就没有轨迹数据gpx

华为健康同步是没有的

**Comment by YeWeihong** [comment]
> > > 我这边keep显示正常啊。我拿手机跑的。 今天晚上刚搭的，感谢博主的项目，以后有了跑步的动力。😄 😄 😄 [demo](https://running.gujiakai.top/)
> > 
> > 
> > 请问你是拿着手机跑步才有轨迹的吗，我是华为健康同步到keep，然后这些同步的数据就没有轨迹，应该是第三方同步就没有轨迹数据gpx
> 
> 华为健康同步是没有的

好的，谢谢！我现在使用华为外区账号同步strava成功了，以后应该可以用这个方法🥳👍

**Comment by jujimeizuo** [comment]
keep确实有点怪，有一段时间就是显示不了，只能改换app。
