### ISSUE TITLE
咕咚导出的gpx文件时区不对，作者能否修复一下？

### ISSUE THREAD

**Issue by nnkn** [yihong0618/running_page#159]
我想把咕咚的记录导到佳明上去，结果导出的文件的时间戳是+8时区的，但是佳明是按标准的0时区导入，结果显示时间和实际的时间多了个8小时。

我觉得把时间戳减个8个小时应该就可以了，于是尝试修改一下codoon_sync.py文件，几个小时还搞不定，最后放弃，还望作者能修复一下，

**Comment by yihong0618** [comment]
我找时间看一下。
