### ISSUE TITLE
Garmin GPX has no track inside

### ISSUE THREAD

**Issue by aleung** [yihong0618/running_page#16]
I used `garmin_sync` to download all my activities and some of them are unable to load. Open the file which has error and I found that the track is empty (as below). Then I went to Garmin Connect website to download the TCX file of the same activity. The TCX file has all the data.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<gpx creator="Garmin Connect" version="1.1"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/11.xsd"
  xmlns:ns3="http://www.garmin.com/xmlschemas/TrackPointExtension/v1"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
  <metadata>
    <link href="connect.garmin.com">
      <text>Garmin Connect</text>
    </link>
    <time>2014-01-01T09:16:06.000Z</time>
  </metadata>
  <trk>
    <name>Run</name>
    <type>running</type>
    <trkseg/>
  </trk>
</gpx>
```

It must be the fault of Garmin. Perhaps the tool has to import data from TCX. I will investigate it further and let you know if I have more finding.

**Comment by yihong0618** [comment]
@aleung 
Can this be fixed?
