### ISSUE TITLE
华为健康支持

### ISSUE THREAD

**Issue by 0x11-dev** [yihong0618/running_page#167]
官方已经放出了相关示例文档，可以尝试支持

**Comment by yihong0618** [comment]
这个是无法自动化的，因为华为限制比较严格，所以没弄。

**Comment by 0x11-dev** [comment]
我看可以是一个rest接口，做成一个自动同步到Strava的工具是否可行？ 不知道华为审核应用是否严格。

**Comment by yihong0618** [comment]
> 我看可以是一个rest接口，做成一个自动同步到Strava的工具是否可行？ 不知道华为审核应用是否严格。

不太可行，因为我这个是模拟登陆的，显然华为不会给这样的机会，如果你有兴趣可以试一下，如果成功我直接加上~

**Comment by yihong0618** [comment]
@0x11-dev 

这个项目可能有帮助

https://github.com/CTHRU/Hitrava

**Comment by 0x11-dev** [comment]
找华为申请导出数据，测试下来目前2周了，尚未完成审核。可以作为一次性换平台转移，不适合日常使用。

**Comment by yihong0618** [comment]
是的，之前研究过，也是为什么我说无法自动化。

**Comment by kang8** [comment]
> 官方已经放出了相关示例文档，可以尝试支持

想问，从哪里可以看到官方示例文档？

**Comment by 0x11-dev** [comment]
https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides/read-sports-recording-scene-0000001050782026 FYI  @kang8

**Comment by yihong0618** [comment]
https://github.com/yihong0618/running_page/issues/600
