### ISSUE TITLE
running_page配置

### ISSUE THREAD

**Issue by phh95** [yihong0618/running_page#173]
昨天弄了好久，最开始很有挫败感，问了作者好几次问题，感谢作者的耐心解答，最后还是弄出来了，成就感满满   

我根据自己昨天一路弄下来的整个过程，写了一个配置说明，希望对后来者有帮助：   

https://www.penghh.fun/2021/09/28/2021-9-28-runningpage/

**Comment by yihong0618** [comment]
@phh95 Apple watch 的数据可以导入的，可以在健康中导出全部数据，而跑步数据是 gpx, running_page 支持gpx

**Comment by phh95** [comment]
Apple watch 的数据，是通过同步到其他运动 app 导出的吗
