### ISSUE TITLE
地图缩放后的小彩蛋里，城市显示不完整

### ISSUE THREAD

**Issue by superleeyom** [yihong0618/running_page#176]
@yihong0618 有个小问题，比如我现在已经换城市到长沙工作和生活，并且在该城市已经产生了一定的跑步数据，但是实际缩放的时候，里面的城市列表里面并没有长沙市这个城市的数据统计：
<img width="1453" alt="iShot2021-11-15 09 09 27" src="https://user-images.githubusercontent.com/22115219/141716295-d667e865-6921-4b30-92f6-e83097dd7992.png">

**Comment by superleeyom** [comment]
链接：https://running.leeyom.top/

**Comment by superleeyom** [comment]
仓库：https://github.com/superleeyom/running_page

**Comment by yihong0618** [comment]
@superleeyom 有可能是正则匹配或者没拿到数据，我看一下之后。

你可以看看正则那块。

正则
https://github.com/yihong0618/running_page/blob/79809ca374aa9d053042c65565d8f943ddcd9a70/src/utils/utils.js#L55

拿到城市的代码在这儿
https://github.com/yihong0618/running_page/blob/master/scripts/generator/db.py#L85

之后我也看一下。

**Comment by superleeyom** [comment]
@yihong0618 ok，我看看哈

**Comment by superleeyom** [comment]
看了下数据库的最近几天的数据，发现 location_country 这个字段原来存的数据是 China，没有到具体的城市
![image](https://user-images.githubusercontent.com/22115219/141717624-6f288573-3b31-416a-abdb-88a9e91ab726.png)
正则匹配的时候，就匹配不到

**Comment by yihong0618** [comment]
> 看了下数据库的最近几天的数据，发现 location_country 这个字段原来存的数据是 China，没有到具体的城市坐标 ![image](https://user-images.githubusercontent.com/22115219/141717624-6f288573-3b31-416a-abdb-88a9e91ab726.png) 正则匹配的时候，就匹配不到

原来如此，我想办法换个其他的库试试，之后

**Comment by superleeyom** [comment]
从代码上看，是从db中取出location_country字段，如果是经纬度坐标，然后将经纬度转换成实际的区域地址，但是我有两个个疑问：
1、为啥数据库里面，既有经纬度坐标数据，也有转换后的实际区域地址呢？（2020有部分的地址，2021好像都是China）
2、nrc的原始数据就是经纬度坐标吗？然后实际数据库里面存的是通过指定的python库进行经纬度转换后的数据？
![image](https://user-images.githubusercontent.com/22115219/141723324-18081b5c-e488-4a2a-888a-07b529889002.png)

**Comment by yihong0618** [comment]
> （2020有部分的地址，2021好像都是China）
> 2、nrc的原始数据就是经纬度坐标吗？然后实际数据库里面存的是通过指定的python库进行经纬度转换后的数据？

可能是 bug... 我看看

**Comment by yihong0618** [comment]
> 从代码上看，是从db中取出location_country字段，如果是经纬度坐标，然后将经纬度转换成实际的区域地址，但是我有两个个疑问： 1、为啥数据库里面，既有经纬度坐标数据，也有转换后的实际区域地址呢？（2020有部分的地址，2021好像都是China） 2、nrc的原始数据就是经纬度坐标吗？然后实际数据库里面存的是通过指定的python库进行经纬度转换后的数据？ ![image](https://user-images.githubusercontent.com/22115219/141723324-18081b5c-e488-4a2a-888a-07b529889002.png)

可能长沙返回的就是 ‘china’?

**Comment by superleeyom** [comment]
你的是正常的吗？

**Comment by yihong0618** [comment]
> 你的是正常的吗？

今天看下

**Comment by yihong0618** [comment]
@superleeyom 我的没问题。

**Comment by doodle1129** [comment]
@yihong0618 首次在本地同步拉取的strava数据，所有的活动location只精确china，没有精确到省市。最近通过action同步的两次数据都能精确到城市。可能是同样的问题么？
