### ISSUE TITLE
能不能弄个docker版本这样在群晖上部署方便好的啊

### ISSUE THREAD

**Issue by haibuhao** [yihong0618/running_page#181]

**Comment by yihong0618** [comment]
可以，我之后看看，目前我这块不太熟

**Comment by pityonline** [comment]
我今天用 Docker 构建镜像了，不过目前过程很慢，这两天完善后我发个 PR 供参考。

**Comment by yihong0618** [comment]
> 我今天用 Docker 构建镜像了，不过目前过程很慢，这两天完善后我发个 PR 供参考。

期待。

**Comment by pityonline** [comment]
经过无数次重试，居然成功了一次。可能是网络原因，我这里一直特别慢，伴出现各种报错。我先把我这里可用的 Dockerfile 发到这里，还没打磨，有兴趣的朋友可以先试一下。

```
FROM node:14 AS base

WORKDIR /root/running_page
COPY sources.list /etc/apt/sources.list
COPY ./ /root/running_page
RUN apt-get -yq update && apt-get -yq install python3-pip nasm
RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U
RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
RUN pip3 install -r requirements.txt

FROM base AS builder

RUN npm config set registry https://registry.npm.taobao.org
RUN yarn install

FROM builder AS data

RUN python3 scripts/nike_sync.py $NIKE_TOKEN
RUN python3 scripts/gen_svg.py --from-db --title "my running page" --type grid --athlete "$YOUR_NAME" --output assets/grid.svg --min-distance 10.0 --special-color yellow --special-color2 red --special-distance 20 --special-distance2 40 --use-localtime
RUN python3 scripts/gen_svg.py --from-db --title "my running page" --type github --athlete "$YOUR_NAME" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5
RUN python3 scripts/gen_svg.py --from-db --type circular --use-localtime
RUN yarn build

FROM nginx:alpine AS web
COPY --from=data /root/running_page/public /usr/share/nginx/html/
COPY --from=data /root/running_page/assets /usr/share/nginx/html/assets
```

构建镜像依次使用以下命令：

```
docker build --target base -t running_page:base .
docker build --target builder -t running_page:builder .
docker build --target data -t running_page:data .
docker build --target web -t running_page:web .
```

运行只需要  `docker run -d -p 80:80 running_page:web` 即可，访问 http://localhost 可以看到页面及自己的数据。

**Comment by yihong0618** [comment]
@pityonline 
感兴趣可以提个 pr

**Comment by haibuhao** [comment]
能不能挂载本地目录，这样数据就不会丢失了

**Comment by haibuhao** [comment]
> 经过无数次重试，居然成功了一次。可能是网络原因，我这里一直特别慢，伴随出现各种报错。我先把我这里可用的 Dockerfile 发到这里，还没打磨，有兴趣的朋友可以先试一下。
> 
> ```
> FROM node:14 AS base
> 
> WORKDIR /root/running_page
> COPY sources.list /etc/apt/sources.list
> COPY ./ /root/running_page
> RUN apt-get -yq update && apt-get -yq install python3-pip nasm
> RUN pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U
> RUN pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
> RUN pip3 install -r requirements.txt
> 
> FROM base AS builder
> 
> RUN npm config set registry https://registry.npm.taobao.org
> RUN yarn install
> 
> FROM builder AS data
> 
> RUN python3 scripts/nike_sync.py $NIKE_TOKEN
> RUN python3 scripts/gen_svg.py --from-db --title "my running page" --type grid --athlete "$YOUR_NAME" --output assets/grid.svg --min-distance 10.0 --special-color yellow --special-color2 red --special-distance 20 --special-distance2 40 --use-localtime
> RUN python3 scripts/gen_svg.py --from-db --title "my running page" --type github --athlete "$YOUR_NAME" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5
> RUN python3 scripts/gen_svg.py --from-db --type circular --use-localtime
> RUN yarn build
> 
> FROM nginx:alpine AS web
> COPY --from=data /root/running_page/public /usr/share/nginx/html/
> COPY --from=data /root/running_page/assets /usr/share/nginx/html/assets
> ```
> 
> 构建镜像依次使用以下命令：
> 
> ```
> docker build --target base -t running_page:base .
> docker build --target builder -t running_page:builder .
> docker build --target data -t running_page:data .
> docker build --target web -t running_page:web .
> ```
> 
> 运行只需要 `docker run -d -p 80:80 running_page:web` 即可，访问 http://localhost 可以看到页面及自己的数据。

大佬那我想把数据挂载本地磁盘 应该对应docker哪个目录

**Comment by pityonline** [comment]
> @pityonline 感兴趣可以提个 pr

稍缓一下吧，我怀疑是我这里或是中国大陆的网络问题导致安装依赖超时出现各种报错，但我目前还没有其它网络环境可以验证。希望有其他网友也协助验证一下。然后把 Dockerfile 打磨一下再提 PR。

**Comment by pityonline** [comment]
@haibuhao 如果你只是想把数据放在本地磁盘再挂进容器里操作，应该要挂载 `activities`、`GPX_OUT`、`Workouts` 这三个目数据目录和 `publi`c、`assets` 这两个制品目录。另外还有两个数据文件 `src/static/activities.json` 和 `scripts/data.db` 在数据操作也会有变化，可能也要挂载。如果这两个文件可以重新规划一下位置应该会好弄一些。cc @yihong0618

**Comment by yihong0618** [comment]
已经有了。

**Comment by arthurfsy2** [comment]
今天成功在群晖上部署了，链接：[这里](http://ddns.4a1801.life:8088/)。但是部署有一些坑需要注意，我说一下我的步骤：
1、SSH群晖后，查询python的版本需要满足yihong在首页的要求(node >= 14.15.0 python >= 3.7)，因此需要安装python3、Nodejs、GIT server套件。我是安装了spk7的python3.11，因此安装完套件后SSH运行：
`ln -s /volume1/@appstore/python311/bin/pip3 /usr/bin/pip3`
`ln -s /volume1/@appstore/python311/bin/python3 /usr/bin/python3`
2、`git clone https://github.com/yihong0618/running_page.git`下载下来，按照yihong的说明，修改`gatsby-config.js`对应的内容。
（我的是`https://github.com/ben-29/workouts_page.git`）
3、依赖文件requirements.txt中，其中的`git+https://github.com/alenrajsp/tcxreader.git`改成`git+https://ghproxy.com/https://github.com/alenrajsp/tcxreader.git`才能正常访问，@ben-29 `，如果是ben的版本，requirements.txt还需删除以下多余的（不过也我只遇到了pycrypto无法正常下载的问题）
`bs4
pycrypto
html.parser
aiofiles
# if you need to import kml file
#fastkml`
4、如果提示类似无法连接`http://deb.debian.org/`之类的，可以尝试把路由器的DNS改为‘8.8.8.8’或者‘114.114.114.114’试一下。
5、运行`docker build -t running_page:latest . --build-arg app=Garmin-CN --build-arg email="2XXXX.com"  --build-arg password="XXXXX"`
6、经过上面的步骤，终于艰难地把镜像给搞定了，然后最后启动容器：
`docker run -itd --restart=always --name workout_page -p 8088:80 running_page:latest` 这样可以把端口映射到8088（可更改）
7、我有公网IP，搭配ddns-go即可实现外网访问
