### ISSUE TITLE
github actions 的 push git pages 报错了

### ISSUE THREAD

**Issue by fengzhao** [yihong0618/running_page#182]
yihong，你好，很早就fork了你的项目并部署了，最近action中的schedule中的push gitpages老是报错， 怎么回事呢？

**Comment by yihong0618** [comment]
@fengzhao 已经解决，请更新最新版本

**Comment by fengzhao** [comment]
已fetch upstream，已解决

**Comment by yihong0618** [comment]
> 已fetch upstream，已解决

好滴。
