### ISSUE TITLE
悦跑圈登陆失败，返回“Your version of App is out of date. Please update to our latest version.”

### ISSUE THREAD

**Issue by gavinlichn** [yihong0618/running_page#185]
今天尝试登录悦跑圈，一直出错，把login_data打出来，是以下信息。
尝试修改APPVERSION 4.2.0 ->5.22.2无效，仍然报告一样的出错消息，5.22.2是官网最新版本

{
    "msg": "Your version of App is out of date. Please update to our latest version.",
    "ret": "102"
}

**Comment by yihong0618** [comment]
@ben-29 麻烦帮看一下是不是实效了~?

**Comment by yihong0618** [comment]
@gavinlichn 看报错信息应该是实效了。

**Comment by gavinlichn** [comment]
兄弟反应神速，感谢。 我怕是我网络问题，我的IP地址是国外地址，正在部署国内网络。一会再试一下。
按理说应该和网络出口无关。

另外：发现部署中小bug一枚，README说node<16，实际代码里已经修改为<15

**Comment by yihong0618** [comment]
@gavinlichn 好的我改一下，不建议悦跑圈和咕咚等，因为用的是逆向，而且加密比较严格随时可能会实效，我最近精力有限可能没时间继续搞这个~

如果能成功我比较推荐佳明和 strava。

**Comment by ben-29** [comment]
可能是服务端加限制了，晚上有空再看看

**Comment by ben-29** [comment]
试了下，应该可以修复

**Comment by yihong0618** [comment]
@ben-29 帅啊

**Comment by ben-29** [comment]
> 今天尝试登录悦跑圈，一直出错，把login_data打出来，是以下信息。 尝试修改APPVERSION 4.2.0 ->5.22.2无效，仍然报告一样的出错消息，5.22.2是官网最新版本
> 
> { "msg": "Your version of App is out of date. Please update to our latest version.", "ret": "102" }

@gavinlichn 我这边试着登录能成功呀，没出现这个错，你再试试能登不？所有的修改都撤销试试

**Comment by gavinlichn** [comment]
今天又试了两次，我国内IP地址的机器是好的（走的中移动热点）。国外IP地址（美国俄勒冈）还是失败。可能是悦跑圈对IP地址做了限制？

**Comment by gavinlichn** [comment]
看来不是代码的问题，这个issue我先close了

**Comment by yihong0618** [comment]
@gavinlichn 请问你是 +86 大陆的手机号么？

**Comment by gavinlichn** [comment]
> @gavinlichn 请问你是 +86 大陆的手机号么？

对的，是大陆手机号
