### ISSUE TITLE
运动暂停会计入运动总时间

### ISSUE THREAD

**Issue by Cu6esugar** [yihong0618/running_page#187]
我是同步的佳明数据，发现一些运动记录的配速和总时间与佳明记录不对应。

检查GPX文件后发现，一些运动暂停时间，被计入了总时间。导致总时间和平均配速计算不一致

观察gpx文件发现是每秒一条记录，不清楚GPX文件是不是能保证一直每秒一条记录，如果是的话，就可以通过两条记录的间隔判断出运动暂停时间了。或者不知道佳明有没有返回运动暂停的信息。

**Comment by yihong0618** [comment]
@Cu6esugar 有返回的。这个 bug 已知，因为是 gpx 计算的全部
佳明返回的是有运动时间和暂停时间的。但需要更改些代码，完全使用 garmin 返回的数据代替使用 gpx 同步，我抽空看一下。

**Comment by Cu6esugar** [comment]
也可以考虑分析gpx解决，分析gpx文件应该更通用一点，否则每个数据源都要分别修改。

一个题外话，我从苹果健康导入到佳明的数据（导入的是gpx），也丢失了暂停记录。在佳明里看到的运动时间比苹果里长。

**Comment by yihong0618** [comment]
> 

是的，这个也已知，大部分运动软件互相导入都有这个问题。

**Comment by Cu6esugar** [comment]
这个issue需要保留吗？还是先close掉

**Comment by yihong0618** [comment]
先保留就好。感谢。

**Comment by oysmile** [comment]
佳明GPX数据有跑步和散步tag吗？选择步行也会提示跑步，没有区分。

**Comment by yihong0618** [comment]
> 佳明GPX数据有跑步和散步tag吗？选择步行也会提示跑步，没有区分。

可以加上 only-run

https://github.com/yihong0618/running_page/blob/master/.github/workflows/run_data_sync.yml#L83-L85

**Comment by oysmile** [comment]
> > 佳明GPX数据有跑步和散步tag吗？选择步行也会提示跑步，没有区分。
> 
> 需要更新代码，加上 only-run
> 
> https://github.com/yihong0618/running_page/blob/master/.github/workflows/run_data_sync.yml#L83-L85

CN区也是后面加 --only-run？似乎没有用？还是跑步。

**Comment by oysmile** [comment]
> > > 佳明GPX数据有跑步和散步tag吗？选择步行也会提示跑步，没有区分。
> > 
> > 
> > 需要更新代码，加上 only-run
> > https://github.com/yihong0618/running_page/blob/master/.github/workflows/run_data_sync.yml#L83-L85
> 
> CN区也是后面加 --only-run？似乎没有用？还是跑步。

only-run是只同步跑步数据？手表操作是选择的散步，page页面的显示午间跑步,与实际不符。

**Comment by yihong0618** [comment]
可能需要删掉 data.db 和 gpx files 重新跑一遍
