### ISSUE TITLE
MapBoxGL error

### ISSUE THREAD

**Issue by irvingbennett** [yihong0618/running_page#193]
### Discussed in https://github.com/yihong0618/running_page/discussions/192

<div type='discussions-op-text'>

<sup>Originally posted by **irvingbennett** January  6, 2022</sup>
Hi yihong and company! I forked your running page and managed to get it running. It took me some work because it didn't want to build with Gatsby 2.x because some libraries were too old. I managed to get working with Gatsby 4.0 and its going great on my local machine! I really like your app.
I also managed to deploy the app on Vercel and Gatsby Cloud. Both those installations build and run (after some tweaks). Both of those installations fail to show the map and have MapBoxGL errors that can be seen in the developers console: 
`77e41395-87bb-4f6d-86fc-2386ddd3dbdd:1 An error occurred while parsing the WebWorker bundle. This is most likely due to improper transpilation by Babel; please see https://docs.mapbox.com/mapbox-gl-js/guides/install/#transpiling`

Have you seen this problem in your deployments?</div>

[My running page on Vercel: ](https://running-page-irving1.vercel.app/) https://running-page-irving1.vercel.app/
[Azure](https://agreeable-meadow-0809b4910.azurestaticapps.net/)
[Gatsby Cloud](https://runningpagemaster.gatsbyjs.io/)

**Comment by yihong0618** [comment]
Thanks you like it. Will take a look 
I think we should update the dependencies to latest.
@geekplux can you help me to see this error~

**Comment by yihong0618** [comment]
Btw, any PR always welcome.

**Comment by irvingbennett** [comment]
Thanks yihong! I can make a pull request if you wish. I updated all dependencies, most of them anyway, to be compatible with Gatsby 4.0. I also had to use NPM install instead of Yarn because it kept failing on the install. The Running Page loads beautifully on my local install. It just fails to show something in the map when its built on any of the services mentioned: Gatsby Cloud, Vercel and Azure.
![IrvingBennett-heatmap-animation](https://user-images.githubusercontent.com/3063697/148473923-000521b9-ef85-4b76-8a83-4a924bacaff4.gif)

**Comment by yihong0618** [comment]
Your world map is amazing
@irvingbennett @shaonianche 
I created a new branch  `version_fix` please `PR` here and let's fix the dependicies together.

**Comment by irvingbennett** [comment]
Thanks @yihong0618! Please outline the steps for me to create a pull request against version fix. I know github but I mostly use it for my own purposes.

**Comment by yihong0618** [comment]
> Thanks @yihong0618! Please outline the steps for me to create a pull request against version fix. I know github but I mostly use it for my own purposes.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

**Comment by yihong0618** [comment]
@irvingbennett  seems that is mapbox token problem can you use your own mapbox token and give a try?

**Comment by shaonianche** [comment]
> earlier in the day, I added the following code to solve this problem, can you try this?

[ Transpilation of V2.0.0+ #10565 ](https://github.com/mapbox/mapbox-gl-js/issues/10565)
https://github.com/shaonianche/running-data-sync/commit/4419135abdc4374e81787a0cd2a9f33431baa7a9

``` javascript

"browserslist": {
  "production": [
    ">0.2%",
    "not dead",
    "not op_mini all",
    "not chrome < 51",
    "not safari < 10"
  ],
  "development": [
    "last 1 chrome version",
    "last 1 firefox version",
    "last 1 safari version"
  ]
}

```

**Comment by yihong0618** [comment]
@irvingbennett we updade all the version can you give a test?
