### ISSUE TITLE
supporting world map

### ISSUE THREAD

**Issue by XuperX** [yihong0618/running_page#196]
您好，
非常感谢开发出这么有趣的repo。
我在使用的时候发现网站并不能展示国际地图的运动轨迹，不知道这个功能是否已经被支持，或者在开发计划里呢？
非常感谢！

**Comment by yihong0618** [comment]
没被制裁

> 您好， 非常感谢开发出这么有趣的repo。 我在使用的时候发现网站并不能展示国际地图的运动轨迹，不知道这个功能是否已经被支持，或者在开发计划里呢？ 非常感谢！

是支持的，我看你是用 GitHub page 可能你配置不对。

参考这个 issue
https://github.com/yihong0618/running_page/issues/149

**Comment by XuperX** [comment]
感谢及时回复！抱歉的确是这个粗心的问题！ 多谢你花时间帮忙解决

**Comment by yihong0618** [comment]
客气了，my pleasure
