### ISSUE TITLE
地图打点漂移了

### ISSUE THREAD

**Issue by xiaoheiAh** [yihong0618/running_page#198]
我都跑到黄浦江里了。😂
keep 的数据源。

![image](https://user-images.githubusercontent.com/27981726/149899987-1e7fb995-7ad2-485f-9c17-b426eb6cb822.png)

**Comment by yihong0618** [comment]
可以用这个方式解决

https://github.com/yihong0618/running_page/issues/92

**Comment by yihong0618** [comment]
@xiaoheiAh 我之后更新下，放在 config 里好一些。

**Comment by yihong0618** [comment]
@xiaoheiAh 
你可以更改这一行 false -> true 应该可以修正地图问题

https://github.com/yihong0618/running_page/blob/master/src/utils/const.js#L62

**Comment by ben-29** [comment]
也可以用python的 [eviltransform](https://github.com/googollee/eviltransform) 库，保存gpx前就转为 wgs-84坐标系，代码可以参考 https://github.com/ben-29/workouts_page/blob/17052d6a3e11085966fc32b3ca1b0f99b6e534c1/scripts/kml2polyline.py#L50
