### ISSUE TITLE
TODO : 3D 热力图

### ISSUE THREAD

**Issue by sun0225SUN** [yihong0618/running_page#208]
大佬，还有个小建议，就是这个统计图可以做成3D的么，就是根据自己每次跑步的距离长短来定义高度，像下面这样。

![QQ图片20220216202504](https://user-images.githubusercontent.com/79169717/154264238-4928c0f9-1c78-4ec6-8ac0-180cb6e040d3.png)

我是用的这个大佬的脚本生成的这种3D的统计图，当然我技术比较菜，不了解其中的原理，仅仅是一个小提议哈🙈

——————>  https://github.com/yoshi389111/yoshi389111 <————————

**Comment by yihong0618** [comment]
这个需要渲染的，风格可能不一致。
你想生成 3d 的可以用我这个项目

https://github.com/yihong0618/GitHubPoster

**Comment by sun0225SUN** [comment]
> 这个需要渲染的，风格可能不一致。 你想生成 3d 的可以用我这个项目
> 
> https://github.com/yihong0618/GitHubPoster

OK，已经用上过了，确实是风格不一样，哈哈哈，非常感谢大佬(❤️ ω ❤️)

**Comment by yihong0618** [comment]
@sun0225SUN 这个先关掉了哈，如果有更好的方式再 reopen.
