### ISSUE TITLE
生成Total Data Analysis时Python命令报错

### ISSUE THREAD

**Issue by TOBEACODER7** [yihong0618/running_page#209]

**Comment by TOBEACODER7** [comment]
您好，当我clone项目到我本地并修改相关数据以及上传我的运动数据然后生成svg的时候，使用相关的命令会报错：

$python3 scripts/gen_svg.py --from-db --title "${{ env.TITLE }}" --type github --athlete "${{ env.ATHLETE }}" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5 
zsh: bad substitutionpython3 scripts/gen_svg.py --from-db --title "${{ env.TITLE }}" --type github --athlete "$ env.ATHLETE ))" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5 
$zsh: bad substitution

第二条命令亦是如此，当我修改了命令中语法$({env.TITLE})以及$({env.ATHLETE})后，程序能够运行但是报错：
$zsh: command not found: env.TITLE
$zsh: command not found: env.ATHLETE

但是有相关的svg生成
使用yarn develop命令在本地localhost生成的网页中也能够正常显示我的运动数据以及轨迹图

切换bash输入命令问题仍存在

想请问是不是这两行命令有问题啊？还是我实操的问题？

**Comment by yihong0618** [comment]
"${{ env.TITLE }}"

这个是变量的意思，需要你改成自己的

**Comment by TOBEACODER7** [comment]
！明白了，感谢您的分享～
非常nice的项目和创意

**Comment by TOBEACODER7** [comment]
！明白了，感谢您的分享
非常nice的创意
