### ISSUE TITLE
Some runs don't have map data.

### ISSUE THREAD

**Issue by abinnz** [yihong0618/running_page#21]
I think that it's better to undisplay the empty block that has no map data in tracks.

![image](https://user-images.githubusercontent.com/13955662/97098652-50c8d800-16ba-11eb-95c3-e786c1625a8d.png)

**Comment by yihong0618** [comment]
I know this issue.～ and need a little time to solve. The better way is not show the grid.svg

**Comment by abinnz** [comment]
These missing tracks may have track in keep app, because there are a lot of missing tracks.

**Comment by yihong0618** [comment]
> These missing tracks may have track in keep app, because there are a lot of missing tracks.
> 
> Because I do not have a keep accout that has many runs, can you help me to get some luck to see if the missing tracks have map info（lat lon time）

**Comment by yihong0618** [comment]
@abinnz 
About keep api I wrote a blog https://github.com/yihong0618/gitblog/issues/191

**Comment by abinnz** [comment]
我的数据几乎都是keep app里原有的，大部分里的rawDataURL字段是空字符，所以也就没有轨迹数据。我也不知道为什么没有，但给我感觉应该是存了轨迹的数据，可能会有其它接口方式能获取到。

**Comment by superleeyom** [comment]
@abinnz 你是用其他设备上传到keep的吗？比如Apple Watch，我有很多的数据都没有地图，因为我是用手表上传的，后面我专门测试了下，只用手机记录跑步数据，就有地图数据。

**Comment by abinnz** [comment]
没有，所以很奇怪没有轨迹数据，详细接口里确实也是没返回的

**Comment by superleeyom** [comment]
@abinnz 难道地图数据需要单独的接口去获取？

**Comment by abinnz** [comment]
@superleeyom keep每个run记录，详细接口会返回rawDataURL字段（一个链接地址），然后根据这个链接地址去获取，然而有些run记录这个字段值是空的，所以就没法获取

**Comment by yihong0618** [comment]
@abinnz  我之后把没有地图数据的在生成grid svg时候过滤吧。

**Comment by yihong0618** [comment]
@abinnz  @superleeyom 
Fixed by filter empty map for `grid poster`

**Comment by superleeyom** [comment]
@yihong0618 nice👍

**Comment by yihong0618** [comment]
@abinnz @superleeyom 
Can you try it?

**Comment by superleeyom** [comment]
@yihong0618 ok,let me try

**Comment by superleeyom** [comment]
@yihong0618 生效了，但是如果地图比较少，比如我这只有一个地图，有点大
![image](https://user-images.githubusercontent.com/22115219/97107057-652fc380-1700-11eb-8d46-b21ccb287e98.png)

**Comment by yihong0618** [comment]
> @yihong0618 生效了，但是如果地图比较少，比如我这只有一个地图，有点大
> ![image](https://user-images.githubusercontent.com/22115219/97107057-652fc380-1700-11eb-8d46-b21ccb287e98.png)

我记得你又好多地图啊。就这一个？

**Comment by superleeyom** [comment]
@yihong0618 目前显示的好像只有一个

**Comment by yihong0618** [comment]
> > @yihong0618 生效了，但是如果地图比较少，比如我这只有一个地图，有点大
> > ![image](https://user-images.githubusercontent.com/22115219/97107057-652fc380-1700-11eb-8d46-b21ccb287e98.png)
> 
> 我记得你又好多地图啊。就这一个？

我知道了你需要改 --min-distance 的距离， 改小一点， 我有过滤。在 action中。

**Comment by yihong0618** [comment]
> > > @yihong0618 生效了，但是如果地图比较少，比如我这只有一个地图，有点大
> > > ![image](https://user-images.githubusercontent.com/22115219/97107057-652fc380-1700-11eb-8d46-b21ccb287e98.png)
> > 
> > 
> > 我记得你又好多地图啊。就这一个？
> 
> 我知道了你需要改 --min-distance 的距离， 改小一点， 我有过滤。在 action中。


![image](https://user-images.githubusercontent.com/15976103/97107155-facb5300-1700-11eb-84b1-c7398db206c0.png)

**Comment by superleeyom** [comment]
@yihong0618 比如超过5km的，也可以绘制地图

**Comment by superleeyom** [comment]
@yihong0618 这里设置是吧？
![image](https://user-images.githubusercontent.com/22115219/97107212-509ffb00-1701-11eb-88f2-43fda3619a6a.png)

**Comment by yihong0618** [comment]
@superleeyom 
只有这个grid 有过滤。map里面是没有的
![image](https://user-images.githubusercontent.com/15976103/97107201-4978ed00-1701-11eb-91b4-14df3a795e6a.png)

我感觉我应该在 readme里写个说明。

**Comment by superleeyom** [comment]
@yihong0618 thanks，我试试

**Comment by superleeyom** [comment]
@yihong0618 生效了，但是这里的标题不是动态的吗？应该改成 Over 5km Runs
![image](https://user-images.githubusercontent.com/22115219/97107478-cb1d4a80-1702-11eb-864f-3c055dce4544.png)

**Comment by abinnz** [comment]
The display is no problem, good.

![image](https://user-images.githubusercontent.com/13955662/97107458-a0cb8d00-1702-11eb-9399-0e0a3fbd5702.png)

**Comment by yihong0618** [comment]
> @yihong0618 生效了，但是这里的标题不是动态的吗？应该改成 Over 5km Runs
> ![image](https://user-images.githubusercontent.com/22115219/97107478-cb1d4a80-1702-11eb-864f-3c055dce4544.png)

你可以自己改的 --title 后面，env里也可以改

**Comment by yihong0618** [comment]
> The display is no problem, good.
> 
> ![image](https://user-images.githubusercontent.com/13955662/97107458-a0cb8d00-1702-11eb-9399-0e0a3fbd5702.png)

Are you sure 300km？

**Comment by superleeyom** [comment]
@yihong0618 ok，多谢了哈🥳

**Comment by yihong0618** [comment]
> > The display is no problem, good.
> > ![image](https://user-images.githubusercontent.com/13955662/97107458-a0cb8d00-1702-11eb-9399-0e0a3fbd5702.png)
> 
> Are you sure 300km over 10 km means select runs that more than 10km ~~？

**Comment by abinnz** [comment]
> @superleeyom
> 只有这个grid 有过滤。map里面是没有的
> ![image](https://user-images.githubusercontent.com/15976103/97107201-4978ed00-1701-11eb-91b4-14df3a795e6a.png)
> 
> 我感觉我应该在 readme 里写个说明。

第一次我也是迷糊，然后是看代码才知道的，有参数说明应该好一点

**Comment by superleeyom** [comment]
> > The display is no problem, good.
> > ![image](https://user-images.githubusercontent.com/13955662/97107458-a0cb8d00-1702-11eb-9399-0e0a3fbd5702.png)
> 
> Are you sure 300km？

300km，有点吓到我了，标题搞错了吧？

**Comment by yihong0618** [comment]
OK, 我在 Readme 里说明下。

**Comment by abinnz** [comment]
> > > The display is no problem, good.
> > > ![image](https://user-images.githubusercontent.com/13955662/97107458-a0cb8d00-1702-11eb-9399-0e0a3fbd5702.png)
> > 
> > 
> > Are you sure 300km, over 10 km means select runs that more than 10km ~~？

搞错了，我理解成了以为是累积的公里数
