### ISSUE TITLE
Keep App更新了，runninglog报错

### ISSUE THREAD

**Issue by Cadplanner** [yihong0618/running_page#214]
服务器返回账号有问题，请重新登录。有人有这个问题吗

**Comment by Cadplanner** [comment]
> 我找个时间看一下，感谢反馈。（这种如果是他们官方改了措施挺难搞定的，我尽量）

感觉是用户登录后的cookies不能用了，更新了请@一下我，感谢~

**Comment by yihong0618** [comment]
目前其它人来看没问题。
