### ISSUE TITLE
请问咕咚怎么导出非跑步数据，主要是骑行数据

### ISSUE THREAD

**Issue by jeffxjh** [yihong0618/running_page#215]
现在导出的数据不包含骑行数据，请问有这个功能吗？有的话应该如何配置？谢谢！

**Comment by yihong0618** [comment]
理论是可以的，需要你看下咕咚的代码，现在应该是限定死的 run.其余按照步骤来就行了

**Comment by yihong0618** [comment]
@jeffxjh 
可以 DIY 这块。把 only run 改成 false 试试
https://github.com/yihong0618/running_page/blob/master/scripts/codoon_sync.py#L34-L41

**Comment by sauchye** [comment]
Traceback (most recent call last):
  File "scripts/codoon_sync.py", line 385, in <module>
    tracks = j.get_old_tracks(old_tracks_ids, options.with_gpx)
  File "scripts/codoon_sync.py", line 348, in get_old_tracks
    track = self.parse_raw_data_to_namedtuple(run_data, old_gpx_ids, with_gpx)
  File "scripts/codoon_sync.py", line 332, in parse_raw_data_to_namedtuple
    "average_speed": run_data["total_length"] / run_data["total_time"],
ZeroDivisionError: division by zero
咕咚导出跑步gpx时出现这错误@yihong0618   大佬帮忙看看

**Comment by yihong0618** [comment]
我修一下，没判断 0

**Comment by yihong0618** [comment]
@sauchye 尝试修复了，麻烦看一下？

**Comment by sauchye** [comment]
@yihong0618 感谢老哥，正在导出中...

**Comment by yihong0618** [comment]
客气，别忘了加 --gpx

**Comment by yihong0618** [comment]
@sauchye 客气了，enjoy your data.
btw 这个项目支持上传 gpx/tcx 数据到 strava(gpx 需要些 trick) 你需要的话我可以加上。
上传到 garmin 的话你可以直接网页往 garmin-connect 拖

**Comment by yihong0618** [comment]
>  @yihong0618 感谢老哥，正在导出中...
> 
> 
> 
> 导出codoon 484次，joyrun 275次，跑步数据，承载着从13年底跑步数据，视觉化跑步数据项目很赞，感谢老哥！
> 
> 
> 
> 
> 
> 我注册了connet，刚手动拖文件同步到connect了，connect网页授权同步到strava，发现数据同步有些问题😂 

garmin 能同步，garmin-cn 是不能的
