### ISSUE TITLE
strava 的模糊处理如何使用？

### ISSUE THREAD

**Issue by Leibnizhu** [yihong0618/running_page#226]
文档中提及：  

> 如果你不想公开数据，可以选择 strava 的模糊处理

那么请问如何选择strava 的模糊处理呢？ 看了 `gatsby-config.js` 和 `const.js` 似乎没找到相关的配置

**Comment by yihong0618** [comment]
在 strava 中设置

**Comment by Leibnizhu** [comment]
@yihong0618 哦哦，其实是strava自己的特性啊…… Mapbox这一侧是不能配置的？我是佳明的数据。

**Comment by yihong0618** [comment]
嗯应该是，garmin 没试过但穿到 strava 理论上是能模糊的

**Comment by litianc** [comment]
最近在研究数据隐私问题，所以非常好奇 strava 的模糊处理如何使用。目前只看到对不同人群的可见性设置，请问老哥说的是隐藏部分地图功能吗？
https://support.strava.com/hc/en-us/articles/115000173384
![image](https://github.com/yihong0618/running_page/assets/25164879/bfe2b783-d61a-490e-b513-f11fac8360e9)

**Comment by yihong0618** [comment]
跟 starva 处理一样，我们就是用 starva 接口拿的地图数据。
