### ISSUE TITLE
keep 从第三方同步过来的跑步轨迹数据无法解码

### ISSUE THREAD

**Issue by wchen9** [yihong0618/running_page#230]
我现在是用华为手机配合华为手环，然后使用华为运动健康来记录数据，然后keep支持从华为运动健康同步数据，然后发现数据同步到 keep 后，使用 running_page来同步 keep 没有获取到轨迹数据，即 summary_polyline 字段。

调试后发现，从第三方同步的数据，vendor["source"] 字段为 `thirdParty`，并且rawDataURL 字段为空。同时返回数据中有两个加密字段 `stepPoints` 和 `geoPoints`，`stepPoints` 数据加密方式同为 zip + base64，但是这个字段中 dict 数据结构虽然与 vendor["source"] 为 keep 的一致，但是里面的字段数据基本为空，现在疑似轨迹数据在 `geoPoints` 中，但是加密方式未知，不知道如何解包，貌似用华为运动健康同步到 keep 就没法记录轨迹数据了。

尝试过使用 ciphey 来解码，运行了几次都是运行到 ciphey 自动终止，并且无返回数据，不知是电脑配置过低还是 ciphey 无法解码。

`geoPoints` 数据示例可见 https://gist.github.com/wchen9/4c6e185c85192ac26aced00084218f86
 
若需要 keep 账户来调试，可联系我，邮箱 base64：Y2hlbndhbmcwQGZveG1haWwuY29t

**Comment by yihong0618** [comment]
已知问题应该是，keep 刻意给去掉了

**Comment by wchen9** [comment]
> @wchen9 华为数据我不确定，可能是可以导出的。 例如：https://github.com/tommyblue/huawei-health-to-gpx https://github.com/CTHRU/Hitrava

感谢，第一个需要外置存储器，第二个导出数据需要绑定邮箱，并且7天后才能导，现在没法测。条件允许后再来更新。

**Comment by yihong0618** [comment]
好的

**Comment by yihong0618** [comment]
@wchen9 如果能解决 any PR welcome ~

**Comment by wchen9** [comment]
从华为导出数据太漫长了。。请求导出后，过了好多天数据还没有拿到。不过我发现可以用咕咚配置从华为运动健康同步，然后导出的activities有轨迹数据，我先使用一段时间看有没有什么其他问题。

**Comment by yihong0618** [comment]
fixed

**Comment by yihong0618** [comment]
@wchen9 you can try now

**Comment by yihong0618** [comment]
https://github.com/yihong0618/running_page/issues/600

**Comment by wchen9** [comment]
感谢po主还记得，我已经转苹果了: )

**Comment by yihong0618** [comment]
> 感谢po主还记得，我已经转苹果了: )

哈哈哈哈哈
