### ISSUE TITLE
vercel 报错

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#231]
如果遇到这个问题，可以更新到最新的代码。
vercel 可能有缓存，删了重新部署就好了

**Comment by yihong0618** [comment]
如果遇到 404 问题，更新下最新代码

**Comment by MQ-0707** [comment]
![123](https://user-images.githubusercontent.com/74593661/222966365-0a79e480-3bc3-471b-aa49-6c9931f52fb6.png)
这个错是语法错误吗？

**Comment by yihong0618** [comment]
不用在意，这个是因为 gh page 也会触发

**Comment by MQ-0707** [comment]
![1678107604141](https://user-images.githubusercontent.com/74593661/223117240-647b7e58-b5de-4285-a9e9-07d29af9f64a.png)这个一直报错，部署好像也是一直报错。
