### ISSUE TITLE
keep_syn 报错

### ISSUE THREAD

**Issue by ymyguang** [yihong0618/running_page#232]
按照指导方式进行，运行后出现以下错误：

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file

具体异常：
![image](https://user-images.githubusercontent.com/34205471/169831118-f78d918f-917d-447c-b2aa-e883ffc8d9e2.png)

**Comment by yihong0618** [comment]
因为是 windows 我这块没处理路径怀疑，我找时间 fix 一下。

**Comment by ben-29** [comment]
@ymyguang 你确认下脚本执行目录，要在项目根目录(keep_sync.py目录的上级目录)执行：
```
python .\scripts\keep_sync.py
```

**Comment by ymyguang** [comment]
已解决，谢谢作者

**Comment by yihong0618** [comment]
好的，路径问题我一会儿改一下。
