### ISSUE TITLE
佳明数据抓取问题

### ISSUE THREAD

**Issue by imjasondai** [yihong0618/running_page#237]
raise GarminConnectAuthenticationError("Authentication error")
__main__.GarminConnectAuthenticationError: Authentication error

抓取时最后报错，大佬帮忙看看呗

**Comment by yihong0618** [comment]
首先确认如果你是大陆 garmin 你需要用 garmin-cn

之后：
也可能是 garmin 改了安全方式
好久没试验 garmin 了。
这你先浏览器确定能登陆，然后再跑一遍试试。

**Comment by imjasondai** [comment]
> 

搞定了，是CN的问题，感谢大佬
