### ISSUE TITLE
建议中文readme更新一下

### ISSUE THREAD

**Issue by fengzhao** [yihong0618/running_page#239]
git action 中已经不能自定义名字为 GITHUB_TOKEN  的token了，我看你的action的文件已经更新了，readme的配图还没更新

**Comment by shaonianche** [comment]
感谢指正，目前已移除掉了`commit`这个`ci`,不需要手动添加`GITHUB_TOKEN`。稍后会同步更新readme

**Comment by fengzhao** [comment]
look good
