### ISSUE TITLE
AttributeError: module 'locale' has no attribute 'MON_1'

### ISSUE THREAD

**Issue by Rebel1111** [yihong0618/running_page#25]
![image](https://user-images.githubusercontent.com/73677625/97652352-1d5ec280-1a99-11eb-8afa-c90cb8673166.png)

**Comment by yihong0618** [comment]
@Rebel1111 

windows cmd doesn't support locale Month name, I will try to change the logic.

**Comment by yihong0618** [comment]
@Rebel1111  fixed you can  pull the latest and try again.

**Comment by Rebel1111** [comment]
> @Rebel1111 fixed you can pull the latest and try again.

![image](https://user-images.githubusercontent.com/73677625/97663025-78051800-1ab3-11eb-86d4-4f9ef815f4aa.png)
still cant work.

**Comment by yihong0618** [comment]
Did you pull the latest code?
