### ISSUE TITLE
NRC找不到refresh_token了？

### ISSUE THREAD

**Issue by sc13sees** [yihong0618/running_page#257]
在浏览器里找refresh_token值的时候没找到。
Storage -> https:unite.nike.com 没有 refresh_token
Storage -> https:www.nike.com 只有id_token
尝试使用id_token 提示httpx.HTTPStatusError: 401 Client Error: Unauthorized for url: https://unite.nike.com/tokenRefresh

**Comment by yihong0618** [comment]
有的，刷新下试试，参考这个图。
<img width="335" alt="image" src="https://user-images.githubusercontent.com/15976103/174317085-3c1a2320-c1ca-4b33-a54e-3f4adbfaaeaa.png">

**Comment by yihong0618** [comment]
客气了，先关了哈

**Comment by BarryThrill** [comment]
Hello! It looks like the cookie has been removed from nike, can anyone confirm that?

**Comment by yihong0618** [comment]
@BarryThrill 
Not removed, you can re-login it and call some api.
then check the cookie.

**Comment by BarryThrill** [comment]
> @BarryThrill Not removed, you can re-login it and call some api. then check the cookie.

Weirdly, im not able to get the cookie. Tried to re-login, accessing different urls through nike.com but nothing on Edge & Chrome. Not sure if its due to nike EU

**Comment by yihong0618** [comment]
not the cookie its the Storage
please check like the pic


![image](https://user-images.githubusercontent.com/15976103/188033546-a3bf800b-ecaf-423e-a3dd-b7b378498fcf.png)

**Comment by hadwinn** [comment]
您好，我已经尝试重新登陆，刷新等操作。没有找到token。
![image](https://user-images.githubusercontent.com/73227570/190074647-869493e6-aed5-44a2-9bb6-2c8e8c11d1b4.png)

**Comment by yihong0618** [comment]
@hadwinn 
1. 确保登陆的是 nike.com
2. 可以尝试抓取请求看看有没有
3. 随便 call 几个 api 再看看
4. 确保你的账号已经专区

**Comment by hadwinn** [comment]
1.登陆的是nike.com
点击页面中某些元素出现如图：
![image](https://user-images.githubusercontent.com/73227570/190078738-aaf3fa39-e858-4653-9204-b7c5fe7637f2.png)

4.如何才算转区？

**Comment by hadwinn** [comment]
还是没有，我是挂US代理访问，否则会重定向到.cn。但目前看网页似乎显示不全，不知道问题出在哪。
![image](https://user-images.githubusercontent.com/73227570/190084379-c021e041-9701-40cb-9ab5-338d3d14f535.png)

**Comment by hadwinn** [comment]
> 还是没有，我是挂US代理访问，否则会重定向到.cn。但目前看网页似乎显示不全，不知道问题出在哪。 ![image](https://user-images.githubusercontent.com/73227570/190084379-c021e041-9701-40cb-9ab5-338d3d14f535.png)

![image](https://user-images.githubusercontent.com/73227570/190094640-86b17dc5-dd07-487d-87cd-4c26b27be98d.png)

**Comment by hadwinn** [comment]
> @yihong0618 好了，谢谢！

@sc13sees 请问是如何解决的？

**Comment by BarryThrill** [comment]
Anyone managed to get bearer token? I still dont seem to see the cookie in local storage.

**Comment by hadwinn** [comment]
我在美国官网登录时，找不到token。在台湾官网登录时，可以找到。可以试试修改官网地址登录。

**Comment by BarryThrill** [comment]
> 我在美国官网登录时，找不到token。在台湾官网登录时，可以找到。可以试试修改官网地址登录。

After using the refresh token and using the new refresh token that being generated. Im getting this error:

```
> HTTP/2.0 403 Forbidden
> Cache-Control: private, max-age=0
> Expires: Sat, 08 Oct 2022 15:55:32 GMT
> Date: Sat, 08 Oct 2022 15:55:32 GMT
> Server: AkamaiGHost
> Mime-Version: 1.0
> Content-Type: text/html
> Content-Length: 289
> X-Reference-Error: 18.656e5668.1665244532.18def357
> 
<HTML><HEAD>
<TITLE>Access Denied</TITLE>
</HEAD><BODY>
<H1>Access Denied</H1>
 
You don't have permission to access "http&#58;&#47;&#47;api&#46;nike&#46;com&#47;snkrs&#47;hunts&#47;v1&#63;" on this server.<P>
Reference&#32;&#35;18&#46;656e5668&#46;1665244532&#46;18def357
</BODY>
</HTML>
```

What should I do?

**Comment by hadwinn** [comment]
sry, I didn't encounter this problem. :)

**Comment by BarryThrill** [comment]
> sry, I didn't encounter this problem. :)

Do you perhaps know how long a cookie is valid for? :)

**Comment by hadwinn** [comment]
> > sry, I didn't encounter this problem. :)
> 
> Do you perhaps know how long a cookie is valid for? :)

I don't know, currently I use cookies for more than 1 month

**Comment by shaonianche** [comment]
> After using the refresh token and using the new refresh token that being generated. Im getting this error:

Use your account to log in at [nike Taiwan](https://www.nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings) and see if you can find the token ?

**Comment by EINDEX** [comment]
@shaonianche this is working for me, thanks.

**Comment by BarryThrill** [comment]
Does this still work? I dont seem to get any tokens when logging in: 
![image](https://github.com/yihong0618/running_page/assets/15836342/c0beea82-6718-4ad8-8e2f-22530425ff06)

**Comment by yihong0618** [comment]
> Does this still work? I dont seem to get any tokens when logging in: 
> 
> ![image](https://github.com/yihong0618/running_page/assets/15836342/c0beea82-6718-4ad8-8e2f-22530425ff06)
> 
> 

use nike tw

**Comment by BarryThrill** [comment]
> > Does this still work? I dont seem to get any tokens when logging in:
> > ![image](https://github.com/yihong0618/running_page/assets/15836342/c0beea82-6718-4ad8-8e2f-22530425ff06)
> 
> use nike tw

I used this link: https://www.nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings - Can you please check from your side if its visible?

**Comment by shaonianche** [comment]
> I used this link: [nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings](https://www.nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings) - Can you please check from your side if its visible?

After testing, links in Taiwan cannot obtain tokens.

Please refer to the steps in the https://github.com/geidelguerra/nike-run-club-exporter?tab=readme-ov-file to obtain the token 

- [click here](https://unite.nike.com/s3/unite/mobile.html?androidSDKVersion=3.1.0&corsoverride=https://unite.nike.com&uxid=com.nike.sport.running.droid.3.8&locale=en_US&backendEnvironment=identity&view=login&clientId=WLr1eIG5JSNNcBJM3npVa6L76MK8OBTt&facebookAppId=84697719333&wechatAppId=wxde7d0246cfaf32f7#%7B%22user_id%22:%22b797ad7b-508d-4215-a7e1-964428bd6e20%22,%22access_token%22:%22eyJhbGciOiJSUzI1NiIsImtpZCI6ImVkZmY4YTAyLWIyZGEtNDhkZC1iOGVjLThhMmM1MGE2YTM0MnNpZyJ9.eyJ0cnVzdCI6MTAwLCJpYXQiOjE2NTMzMjE2NjAsImV4cCI6MTY1MzMyNTI2MCwiaXNzIjoib2F1dGgyYWNjIiwianRpIjoiMmU5YjAyNGMtMGIyNi00NGFiLWI2MzQtM2M0Y2Q2Zjk2OWE4IiwibGF0IjoxNjUzMzIxNjYwLCJhdWQiOiJjb20ubmlrZS5kaWdpdGFsIiwic3ViIjoiY29tLm5pa2Uuc3BvcnQucnVubmluZy5kcm9pZCIsInNidCI6Im5pa2U6YXBwIiwic2NwIjpbIm5pa2UuZGlnaXRhbCJdLCJwcm4iOiJiNzk3YWQ3Yi01MDhkLTQyMTUtYTdlMS05NjQ0MjhiZDZlMjAiLCJwcnQiOiJuaWtlOnBsdXMifQ.NpBsunJN9JNojm3TeFemnaT3v5R7qlX0BsSNSosIAXqELQXFcoVlrI0oWIWHhTiR_zBT3ddRXxu_eSuJvAGrCArjPCdsRSDdRg2R32J4dAjR-wO9sKfXydU9f2bIqXSId3aG8SasDjfSJCWsdQDiAjDDMWiOlmet80wEj6dzCLRj4egj8aKcLyZgfKDdEq6GO4lsI9REEIDHdlKWsISW3yuBXCoK8FEwWsx_TeLLgA07VpJWt797HndGIlYuEJCDs0P-j_7SvzgyEC407Z10MoBwXGLsBdxI31hotDbHIrFEpHq1rfJ1-1g4cJc8jS_fF0zuCWmk3HgUMmWeqXKwtA%22,%22refresh_token%22:%22eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YTIzYjUxLTIwNDEtNDBkNS05MjEyLTU5NGQxOTM3NzA2ZnNpZyJ9.eyJ0cnVzdCI6MTAwLCJpYXQiOjE2NTMzMjE2NjAsImV4cCI6MTY4NDg1NzY2MCwiaXNzIjoib2F1dGgyaWR0IiwianRpIjoiZDc3NThhNmItNDUxOC00ZDU2LTk0MGYtZGNlMWEwM2ZjMjlkIiwibGF0IjoxNjUzMzIxNjYwLCJhdWQiOiJvYXV0aDJpZHQiLCJjbGkiOiJXTHIxZUlHNUpTTk5jQkpNM25wVmE2TDc2TUs4T0JUdCIsInN1YiI6ImI3OTdhZDdiLTUwOGQtNDIxNS1hN2UxLTk2NDQyOGJkNmUyMCIsInNidCI6Im5pa2U6cGx1cyJ9.g9CKwwmwRgrCYhKc--ufmZfc6NO3mDzCgVxQEjKTg3yieREC-iTYY3N4DewsTXaYv5407W92B3t96IxRp3QbaV8IkqaF0uvUaaT7w8kmUQ4Tf3obVZ8qVNBZz3lwGqJx6QZKRR4X01jqwyjUK5A4rxMeFzl7y3xghQ4xB2reFPLitypX3EjML3m50Aiik-90kFzccBxSO4Snj6n59dJE2ZSNDvqhi516IdgpzBOJZu48KDDpUP0XBkfKaOCKHQhqjuPFoV3ZxcX9pRgLWCibLSjLjPHke0uwl_764XYTvy8Dp8BaFZLx3FwIHdf9eQaBBG7s8czcJ9iXc-CP8DFe_A%22,%22expires_in%22:%223600%22,%22token_type%22:%22bearer%22,%22user%22:%7B%22account%22:%7B%22registration%22:%7B%22date%22:1618019899356,%22siteId%22:%22nikedotcom%22,%22wasScreenNameAutoGenerated%22:%22true%22%7D%7D,%22dob%22:%7B%22date%22:561340800000,%22day%22:16,%22month%22:10,%22year%22:1987%7D,%22emails%22:%7B%22primary%22:%7B%22email%22:%22geidelguerra@protonmail.com%22,%22label%22:%22primary%22%7D%7D,%22gender%22:%22M%22,%22language%22:%22en%22,%22locale%22:%22en_US%22,%22location%22:%7B%22country%22:%22US%22,%22visibility%22:%22PRIVATE%22%7D,%22marketing%22:%7B%22datashare%22:%7B%2200001%22:%7B%22id%22:%2200001%22,%22active%22:false%7D%7D,%22email%22:false%7D,%22measurements%22:%7B%22height%22:178,%22weight%22:81%7D,%22name%22:%7B%22latin%22:%7B%22family%22:%22Guerra%22,%22given%22:%22Geidel%22%7D%7D,%22nuId%22:%22b0562088e759453683d8d7b76c78941e%22,%22preferences%22:%7B%22heightUnit%22:%22M/CM%22,%22weightUnit%22:%22KILOGRAMS%22,%22distanceUnit%22:%22KILOMETERS%22%7D,%22screenname%22:%22GeidelG58520900%22,%22social%22:%7B%22allowtagging%22:false,%22visibility%22:%22SOCIAL%22%7D,%22upmId%22:%22b797ad7b-508d-4215-a7e1-964428bd6e20%22,%22userType%22:%22MEMBER%22,%22username%22:%22geidelguerra@protonmail.com%22%7D,%22timestamp%22:%221653321661%22,%22clientId%22:%22WLr1eIG5JSNNcBJM3npVa6L76MK8OBTt%22,%22uxId%22:%22com.nike.sport.running.droid.3.8%22,%22lastLoginTime%22:%221653321661099%22,%22uuid%22:%22b797ad7b-508d-4215-a7e1-964428bd6e20%22,%22meta%22:%7B%22keepMeLoggedIn%22:true,%22language%22:%22en%22,%22country%22:%22US%22,%22experienceId%22:%22com.nike.sport.running.droid.3.8%22,%22mobile%22:false,%22host%22:%22unite.nike.com%22,%22pathname%22:%22/s3/unite/mobile.html%22%7D,%22event%22:%22success%22,%22view%22:%22login%22,%22ts%22:1653321661101%7D) 
- Open the network tab of the browser DevTool before login
- login
- Select the request with the URL starting with https://unite.nike.com/login

**Comment by BarryThrill** [comment]
> @BarryThrill
> 
> > I used this link: [nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings](https://www.nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings) - Can you please check from your side if its visible?
> 
> After testing, links in Taiwan cannot obtain tokens.
> 
> Please refer to the steps in the https://github.com/geidelguerra/nike-run-club-exporter?tab=readme-ov-file#usage to obtain the token:
> 
> * [click here](https://unite.nike.com/s3/unite/mobile.html?androidSDKVersion=3.1.0&corsoverride=https://unite.nike.com&uxid=com.nike.sport.running.droid.3.8&locale=en_US&backendEnvironment=identity&view=login&clientId=WLr1eIG5JSNNcBJM3npVa6L76MK8OBTt&facebookAppId=84697719333&wechatAppId=wxde7d0246cfaf32f7#%7B%22user_id%22:%22b797ad7b-508d-4215-a7e1-964428bd6e20%22,%22access_token%22:%22eyJhbGciOiJSUzI1NiIsImtpZCI6ImVkZmY4YTAyLWIyZGEtNDhkZC1iOGVjLThhMmM1MGE2YTM0MnNpZyJ9.eyJ0cnVzdCI6MTAwLCJpYXQiOjE2NTMzMjE2NjAsImV4cCI6MTY1MzMyNTI2MCwiaXNzIjoib2F1dGgyYWNjIiwianRpIjoiMmU5YjAyNGMtMGIyNi00NGFiLWI2MzQtM2M0Y2Q2Zjk2OWE4IiwibGF0IjoxNjUzMzIxNjYwLCJhdWQiOiJjb20ubmlrZS5kaWdpdGFsIiwic3ViIjoiY29tLm5pa2Uuc3BvcnQucnVubmluZy5kcm9pZCIsInNidCI6Im5pa2U6YXBwIiwic2NwIjpbIm5pa2UuZGlnaXRhbCJdLCJwcm4iOiJiNzk3YWQ3Yi01MDhkLTQyMTUtYTdlMS05NjQ0MjhiZDZlMjAiLCJwcnQiOiJuaWtlOnBsdXMifQ.NpBsunJN9JNojm3TeFemnaT3v5R7qlX0BsSNSosIAXqELQXFcoVlrI0oWIWHhTiR_zBT3ddRXxu_eSuJvAGrCArjPCdsRSDdRg2R32J4dAjR-wO9sKfXydU9f2bIqXSId3aG8SasDjfSJCWsdQDiAjDDMWiOlmet80wEj6dzCLRj4egj8aKcLyZgfKDdEq6GO4lsI9REEIDHdlKWsISW3yuBXCoK8FEwWsx_TeLLgA07VpJWt797HndGIlYuEJCDs0P-j_7SvzgyEC407Z10MoBwXGLsBdxI31hotDbHIrFEpHq1rfJ1-1g4cJc8jS_fF0zuCWmk3HgUMmWeqXKwtA%22,%22refresh_token%22:%22eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YTIzYjUxLTIwNDEtNDBkNS05MjEyLTU5NGQxOTM3NzA2ZnNpZyJ9.eyJ0cnVzdCI6MTAwLCJpYXQiOjE2NTMzMjE2NjAsImV4cCI6MTY4NDg1NzY2MCwiaXNzIjoib2F1dGgyaWR0IiwianRpIjoiZDc3NThhNmItNDUxOC00ZDU2LTk0MGYtZGNlMWEwM2ZjMjlkIiwibGF0IjoxNjUzMzIxNjYwLCJhdWQiOiJvYXV0aDJpZHQiLCJjbGkiOiJXTHIxZUlHNUpTTk5jQkpNM25wVmE2TDc2TUs4T0JUdCIsInN1YiI6ImI3OTdhZDdiLTUwOGQtNDIxNS1hN2UxLTk2NDQyOGJkNmUyMCIsInNidCI6Im5pa2U6cGx1cyJ9.g9CKwwmwRgrCYhKc--ufmZfc6NO3mDzCgVxQEjKTg3yieREC-iTYY3N4DewsTXaYv5407W92B3t96IxRp3QbaV8IkqaF0uvUaaT7w8kmUQ4Tf3obVZ8qVNBZz3lwGqJx6QZKRR4X01jqwyjUK5A4rxMeFzl7y3xghQ4xB2reFPLitypX3EjML3m50Aiik-90kFzccBxSO4Snj6n59dJE2ZSNDvqhi516IdgpzBOJZu48KDDpUP0XBkfKaOCKHQhqjuPFoV3ZxcX9pRgLWCibLSjLjPHke0uwl_764XYTvy8Dp8BaFZLx3FwIHdf9eQaBBG7s8czcJ9iXc-CP8DFe_A%22,%22expires_in%22:%223600%22,%22token_type%22:%22bearer%22,%22user%22:%7B%22account%22:%7B%22registration%22:%7B%22date%22:1618019899356,%22siteId%22:%22nikedotcom%22,%22wasScreenNameAutoGenerated%22:%22true%22%7D%7D,%22dob%22:%7B%22date%22:561340800000,%22day%22:16,%22month%22:10,%22year%22:1987%7D,%22emails%22:%7B%22primary%22:%7B%22email%22:%22geidelguerra@protonmail.com%22,%22label%22:%22primary%22%7D%7D,%22gender%22:%22M%22,%22language%22:%22en%22,%22locale%22:%22en_US%22,%22location%22:%7B%22country%22:%22US%22,%22visibility%22:%22PRIVATE%22%7D,%22marketing%22:%7B%22datashare%22:%7B%2200001%22:%7B%22id%22:%2200001%22,%22active%22:false%7D%7D,%22email%22:false%7D,%22measurements%22:%7B%22height%22:178,%22weight%22:81%7D,%22name%22:%7B%22latin%22:%7B%22family%22:%22Guerra%22,%22given%22:%22Geidel%22%7D%7D,%22nuId%22:%22b0562088e759453683d8d7b76c78941e%22,%22preferences%22:%7B%22heightUnit%22:%22M/CM%22,%22weightUnit%22:%22KILOGRAMS%22,%22distanceUnit%22:%22KILOMETERS%22%7D,%22screenname%22:%22GeidelG58520900%22,%22social%22:%7B%22allowtagging%22:false,%22visibility%22:%22SOCIAL%22%7D,%22upmId%22:%22b797ad7b-508d-4215-a7e1-964428bd6e20%22,%22userType%22:%22MEMBER%22,%22username%22:%22geidelguerra@protonmail.com%22%7D,%22timestamp%22:%221653321661%22,%22clientId%22:%22WLr1eIG5JSNNcBJM3npVa6L76MK8OBTt%22,%22uxId%22:%22com.nike.sport.running.droid.3.8%22,%22lastLoginTime%22:%221653321661099%22,%22uuid%22:%22b797ad7b-508d-4215-a7e1-964428bd6e20%22,%22meta%22:%7B%22keepMeLoggedIn%22:true,%22language%22:%22en%22,%22country%22:%22US%22,%22experienceId%22:%22com.nike.sport.running.droid.3.8%22,%22mobile%22:false,%22host%22:%22unite.nike.com%22,%22pathname%22:%22/s3/unite/mobile.html%22%7D,%22event%22:%22success%22,%22view%22:%22login%22,%22ts%22:1653321661101%7D)
> * Open the network tab of the browser DevTool before login
> * login
> * Select the request with the URL starting with https://unite.nike.com/login

Thank you! I can now find it here:
![image](https://github.com/yihong0618/running_page/assets/15836342/cc03f924-e939-44b4-bfb1-7c451ed02165)

However I still get an error when using both the refresh token and access token:

{"errors":[{"code":99001,"message":"Unauthorized Request - Failed Basic Authorization."}]}

**Comment by BarryThrill** [comment]
> @BarryThrill
> 
> > I used this link: [nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings](https://www.nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings) - Can you please check from your side if its visible?
> 
> After testing, links in Taiwan cannot obtain tokens.
> 
> Please refer to the steps in the https://github.com/geidelguerra/nike-run-club-exporter?tab=readme-ov-file#usage to obtain the token:
> 
> * [click here](https://unite.nike.com/s3/unite/mobile.html?androidSDKVersion=3.1.0&corsoverride=https://unite.nike.com&uxid=com.nike.sport.running.droid.3.8&locale=en_US&backendEnvironment=identity&view=login&clientId=WLr1eIG5JSNNcBJM3npVa6L76MK8OBTt&facebookAppId=84697719333&wechatAppId=wxde7d0246cfaf32f7#%7B%22user_id%22:%22b797ad7b-508d-4215-a7e1-964428bd6e20%22,%22access_token%22:%22eyJhbGciOiJSUzI1NiIsImtpZCI6ImVkZmY4YTAyLWIyZGEtNDhkZC1iOGVjLThhMmM1MGE2YTM0MnNpZyJ9.eyJ0cnVzdCI6MTAwLCJpYXQiOjE2NTMzMjE2NjAsImV4cCI6MTY1MzMyNTI2MCwiaXNzIjoib2F1dGgyYWNjIiwianRpIjoiMmU5YjAyNGMtMGIyNi00NGFiLWI2MzQtM2M0Y2Q2Zjk2OWE4IiwibGF0IjoxNjUzMzIxNjYwLCJhdWQiOiJjb20ubmlrZS5kaWdpdGFsIiwic3ViIjoiY29tLm5pa2Uuc3BvcnQucnVubmluZy5kcm9pZCIsInNidCI6Im5pa2U6YXBwIiwic2NwIjpbIm5pa2UuZGlnaXRhbCJdLCJwcm4iOiJiNzk3YWQ3Yi01MDhkLTQyMTUtYTdlMS05NjQ0MjhiZDZlMjAiLCJwcnQiOiJuaWtlOnBsdXMifQ.NpBsunJN9JNojm3TeFemnaT3v5R7qlX0BsSNSosIAXqELQXFcoVlrI0oWIWHhTiR_zBT3ddRXxu_eSuJvAGrCArjPCdsRSDdRg2R32J4dAjR-wO9sKfXydU9f2bIqXSId3aG8SasDjfSJCWsdQDiAjDDMWiOlmet80wEj6dzCLRj4egj8aKcLyZgfKDdEq6GO4lsI9REEIDHdlKWsISW3yuBXCoK8FEwWsx_TeLLgA07VpJWt797HndGIlYuEJCDs0P-j_7SvzgyEC407Z10MoBwXGLsBdxI31hotDbHIrFEpHq1rfJ1-1g4cJc8jS_fF0zuCWmk3HgUMmWeqXKwtA%22,%22refresh_token%22:%22eyJhbGciOiJSUzI1NiIsImtpZCI6ImU2YTIzYjUxLTIwNDEtNDBkNS05MjEyLTU5NGQxOTM3NzA2ZnNpZyJ9.eyJ0cnVzdCI6MTAwLCJpYXQiOjE2NTMzMjE2NjAsImV4cCI6MTY4NDg1NzY2MCwiaXNzIjoib2F1dGgyaWR0IiwianRpIjoiZDc3NThhNmItNDUxOC00ZDU2LTk0MGYtZGNlMWEwM2ZjMjlkIiwibGF0IjoxNjUzMzIxNjYwLCJhdWQiOiJvYXV0aDJpZHQiLCJjbGkiOiJXTHIxZUlHNUpTTk5jQkpNM25wVmE2TDc2TUs4T0JUdCIsInN1YiI6ImI3OTdhZDdiLTUwOGQtNDIxNS1hN2UxLTk2NDQyOGJkNmUyMCIsInNidCI6Im5pa2U6cGx1cyJ9.g9CKwwmwRgrCYhKc--ufmZfc6NO3mDzCgVxQEjKTg3yieREC-iTYY3N4DewsTXaYv5407W92B3t96IxRp3QbaV8IkqaF0uvUaaT7w8kmUQ4Tf3obVZ8qVNBZz3lwGqJx6QZKRR4X01jqwyjUK5A4rxMeFzl7y3xghQ4xB2reFPLitypX3EjML3m50Aiik-90kFzccBxSO4Snj6n59dJE2ZSNDvqhi516IdgpzBOJZu48KDDpUP0XBkfKaOCKHQhqjuPFoV3ZxcX9pRgLWCibLSjLjPHke0uwl_764XYTvy8Dp8BaFZLx3FwIHdf9eQaBBG7s8czcJ9iXc-CP8DFe_A%22,%22expires_in%22:%223600%22,%22token_type%22:%22bearer%22,%22user%22:%7B%22account%22:%7B%22registration%22:%7B%22date%22:1618019899356,%22siteId%22:%22nikedotcom%22,%22wasScreenNameAutoGenerated%22:%22true%22%7D%7D,%22dob%22:%7B%22date%22:561340800000,%22day%22:16,%22month%22:10,%22year%22:1987%7D,%22emails%22:%7B%22primary%22:%7B%22email%22:%22geidelguerra@protonmail.com%22,%22label%22:%22primary%22%7D%7D,%22gender%22:%22M%22,%22language%22:%22en%22,%22locale%22:%22en_US%22,%22location%22:%7B%22country%22:%22US%22,%22visibility%22:%22PRIVATE%22%7D,%22marketing%22:%7B%22datashare%22:%7B%2200001%22:%7B%22id%22:%2200001%22,%22active%22:false%7D%7D,%22email%22:false%7D,%22measurements%22:%7B%22height%22:178,%22weight%22:81%7D,%22name%22:%7B%22latin%22:%7B%22family%22:%22Guerra%22,%22given%22:%22Geidel%22%7D%7D,%22nuId%22:%22b0562088e759453683d8d7b76c78941e%22,%22preferences%22:%7B%22heightUnit%22:%22M/CM%22,%22weightUnit%22:%22KILOGRAMS%22,%22distanceUnit%22:%22KILOMETERS%22%7D,%22screenname%22:%22GeidelG58520900%22,%22social%22:%7B%22allowtagging%22:false,%22visibility%22:%22SOCIAL%22%7D,%22upmId%22:%22b797ad7b-508d-4215-a7e1-964428bd6e20%22,%22userType%22:%22MEMBER%22,%22username%22:%22geidelguerra@protonmail.com%22%7D,%22timestamp%22:%221653321661%22,%22clientId%22:%22WLr1eIG5JSNNcBJM3npVa6L76MK8OBTt%22,%22uxId%22:%22com.nike.sport.running.droid.3.8%22,%22lastLoginTime%22:%221653321661099%22,%22uuid%22:%22b797ad7b-508d-4215-a7e1-964428bd6e20%22,%22meta%22:%7B%22keepMeLoggedIn%22:true,%22language%22:%22en%22,%22country%22:%22US%22,%22experienceId%22:%22com.nike.sport.running.droid.3.8%22,%22mobile%22:false,%22host%22:%22unite.nike.com%22,%22pathname%22:%22/s3/unite/mobile.html%22%7D,%22event%22:%22success%22,%22view%22:%22login%22,%22ts%22:1653321661101%7D)
> * Open the network tab of the browser DevTool before login
> * login
> * Select the request with the URL starting with https://unite.nike.com/login

I followed the steps and I got the access_token when logging in and after testing here:

```py
refersh_token = "eyJhbGciOiJSUzI1NiIsImtpZCI6IjMwZTQ0MjE1LThjZTAtNDdiZi04Y2Y1LWQwNGViOGM4ZTI1N3NpZyJ9.eyJ0cnVzdCI6MTAwLCJpYXQiOjE2OTc4ODgyNzksImV4cCI6MTY5Nzg5MTg3OSwiaXNzIjoib2F1dGgyYWNjIiwianRpIjoiZTc4NDQ2MzctZTMyNi00NWVhLThmOWItYjMzNjk4NWVlZmIxIiwibGF0IjoxNjk3ODg4Mjc5LCJhdWQiOiJjb20ubmlrZS5kaWdpdGFsIiwic3ViIjoiY29tLm5pa2Uuc3BvcnQucnVubmluZy5kcm9pZCIsInNidCI6Im5pa2U6YXBwIiwic2NwIjpbIm5pa2UuZGlnaXRhbCJdLCJwcm4iOiIyMGRkZjI5YS0xNjFmLTRmZGQtOWY3OS04MjEwODQ2OGExODQiLCJwcnQiOiJuaWtlOnBsdXMifQ.y0T37PJyFULJgVIZFcG5Soabz1Mg_xQvsTt4Xu34rO5Ehq0jn_Ay1nOcIqJawjlSGxUwPGtXK3s3L7z3RcdT9HEMcgfSOjFr7FLlDzXNNi4Iw4YVodLCoMoCqscQoRR5tMCAs3VLTwEAIW_D2ZjoXa_F2gX0ZOis9fqGjUt4PwYngNizG0Fz8xgNewkegBqVprqdWWPhyyBaL9FImkjJDKDF48IRQpmtZ91yn_4zvNsEB4-DaGCElsDjTs-cixHYjZg0q4dDs24a1Yfwq86sKDbTACqjqV2_hp5yoggV7teesxgr11HbGZXR2qDmMMpzT3pMfvh5oRplUd7L05D5pQ"

response = session.post(
    'https://unite.nike.com/tokenRefresh',
    json={
        "refresh_token": refersh_token,
        "client_id": 'HlHa2Cje3ctlaOqnxvgZXNaAs7T9nAuH',
        "grant_type": "refresh_token",
    },
    timeout=60,
)

if response and response.status_code == 200:
    print(f'New bearer token from: {refersh_token}')
else:
    print(f'Failed to get new bearer token from: {refersh_token}')
```

It returns: `{"errors":[{"code":99001,"message":"Unauthorized Request - Failed Basic Authorization."}]}` - Do you have the same issue?

**Comment by yihong0618** [comment]
@BarryThrill the logic has changed, you should use token here.
the nike sync in GitHub Actions will never support in the future, we only support `one time` in the future, use the latest nike code, and the `token` you get not the refresh_token.

If you do not know how to, you can just wait here.

**Comment by yihong0618** [comment]
you can follow the setups in this repo and get the `GPX` copy them to GPX_OUT, and use gpx_sync.py

**Comment by BarryThrill** [comment]
> @BarryThrill the logic has changed, you should use token here. the nike sync in GitHub Actions will never support in the future, we only support `one time` in the future, use the latest nike code, and the `token` you get not the refresh_token.
> 
> If you do not know how to, you can just wait here.

Does it still require us to refresh it manually every hour as the token expires every hour?

**Comment by yihong0618** [comment]
> @

yes, so will be not GitHub Actions Auto any more./

**Comment by BarryThrill** [comment]
> > @
> 
> yes, so will be not GitHub Actions Auto any more./

Hi again, I saw that you added back the https://github.com/yihong0618/running_page/commit/34c859ea23ef202ec878fe512e0f7d570093a3ac again. How come? Something im missing? :)

**Comment by yihong0618** [comment]
@BarryThrill we fix it, can you take a try refer new READ about nike_sync?

**Comment by BarryThrill** [comment]
> @BarryThrill we fix it, can you take a try refer new READ about nike_sync?

It doesnt seem to work for me when using https://unite.nike.com/tokenRefresh with given access token or refresh token from your readme
