### ISSUE TITLE
执行install命令报错

### ISSUE THREAD

**Issue by JasonZhao2k08** [yihong0618/running_page#258]
将代码git到本地后，运行pip3 install -r requirements.txt，在downloading timezonefinder时总时超时报错。请问是什么问题呀？谢谢yihong老师。

**Comment by yihong0618** [comment]
可能需要全局梯子。

**Comment by JasonZhao2k08** [comment]
搞定了，是的，需要梯子。谢谢

**Comment by yihong0618** [comment]
客气
