### ISSUE TITLE
keep轨迹不全

### ISSUE THREAD

**Issue by pypeng28** [yihong0618/running_page#262]
您好。我是下载keep的gpx再上传使用的，发现有12个轨迹总也下载不下来。手动对照后发现这12个大部分是中间暂停过，所以轨迹间断可能影响它形成gpx？但其中也有几个是完整的，另外轨迹间断了的也有下载下来了的。所以也不知道是为什么。尝试了很多遍，总是缺这12个。求教~

**Comment by yihong0618** [comment]
是的，keep 数据不全的已知问题，你可以搜一下 issue

**Comment by pypeng28** [comment]
搜了，好像和大家情况都不一样……排除了来自其他设备和同一天多个条目的情况
![keep](https://user-images.githubusercontent.com/104598489/175813635-0b0a1714-5320-4dce-acac-ad15292afc3d.jpg)
也不是有跑步数据没有轨迹，这12条就直接跳过也不报错= =

**Comment by z-quan-tong** [comment]
感觉是keep机制的问题，17、18年79条用 app 跑出来的数据，rawdata字段有值的有41个，最后能计算出轨迹的只有24个，

**Comment by z-quan-tong** [comment]
> 感觉是keep机制的问题，17、18年79条用 app 跑出来的数据，rawdata字段有值的有41个，最后能计算出轨迹的只有24个，

如果不破解geopoints 字段的加密方式，估计只能这样了，烦~

**Comment by pypeng28** [comment]
找到了手动解决的方法：
https://www.gpsvisualizer.com/draw/ 画出路线
https://gotoes.org/gotoes/strava/Add_Timestamps_To_GPX.php 加时间戳

**Comment by yihong0618** [comment]
@Ym9i fixed
