### ISSUE TITLE
我又来麻烦大佬了，我的githubpage跑步界面没有地图

### ISSUE THREAD

**Issue by sc13sees** [yihong0618/running_page#264]
在我本地已经成功运行这个程序了，地图显示都正常。但是push到github上后地图直接黑了。GitHub Token改成自己的了，不知道还有哪设置有问题?下面是我的界面。
https://sc13sees.github.io/GordonRunning/

**Comment by sc13sees** [comment]
> 在我本地已经成功运行这个程序了，地图显示都正常。但是push到github上后地图直接黑了。GitHub Token改成自己的了，不知道还有哪设置有问题?下面是我的界面。 https://sc13sees.github.io/GordonRunning/

别人的我看都正常

**Comment by yihong0618** [comment]
这块可能需要是 running_page
https://github.com/yihong0618/running_page/blob/ace5de40cb307da263cb36f4d38bf3f9fe1918c9/gatsby-config.js#L2
