### ISSUE TITLE
Fitbit？

### ISSUE THREAD

**Issue by conge** [yihong0618/running_page#266]
今天花了点儿时间修了一个人的code，可以从fitbit批量下载所有activity的TCX file

有了这个，running page是不是有戏支持 Fitbit？

我提的pull request还没被merge，先给我的fork吧。
https://github.com/conge/fitbit-dump

用下面的code，就可以一步步的把Fitbit数据下载下来。

```
# create virtualenv
conda create -n fitbit python=3.8
conda activate fitbit 
# install fitbit-dump
pip3 install "fitbit-dump@git+https://github.com/conge/fitbit-dump"

fitbit-dump init
fitbit-dump dump-00-activity-log-list
fitbit-dump dump-01-activity-tcx
```

另外：谁知道怎么能批量把TCXfile导入到Strava？

**Comment by yihong0618** [comment]
- 应该可以支持，但是我记得 Fitbit 不维护了？
- 我比较倾向于 gpx
- 我没有 Fitbit 设备不太好测试
- 批量上传可以参考我 nike_to_strava 的 gpx 代码理论上 data_type = "tcx" 就行

https://github.com/yihong0618/running_page/blob/ace5de40cb307da263cb36f4d38bf3f9fe1918c9/scripts/nike_to_strava_sync.py#L45-L49

**Comment by yihong0618** [comment]
@conge 支持了 `tcx` 上传 strava. 
参考 scripts/tcx_to_strava_sync.py

**Comment by conge** [comment]
by the way, 我是用 https://github.com/u8sand/fitbit-dump 这个工具下载 fitbit 数据的。

**Comment by yihong0618** [comment]
先关了哈，暂时先不支持 fitbit
