### ISSUE TITLE
NCR下线后，可以支持NCR导出的tcx文件吗？

### ISSUE THREAD

**Issue by sealhuang** [yihong0618/running_page#267]
您好，NCR要下线了，现在可以导出tcx文件，running page是否可以支持这些导出文件的显示？

**Comment by yihong0618** [comment]
running page 目前支持 nike 
tcx 我之后看看，应该和 gpx 一样可以支持

**Comment by sealhuang** [comment]
> running page 目前支持 nike
> tcx 我之后看看，应该和 gpx 一样可以支持

好的，如果对于这个需求有比较系统地开发计划，我也可以参与

**Comment by yihong0618** [comment]
好的

**Comment by yihong0618** [comment]
思路

- [ ] 引入 `tcx` 包 https://github.com/vkurup/python-tcxparser 去解析 tcx
- [ ] 但简单看了下这个包好像没有路径的方法（like our gpx)，需要提 `PR` 去解决这个或者 fork 自己搞
- [ ] 增加 TCX_ FOLDER 像 GPX 一样处理过程也如 tcx
- [ ] --tcx 命令解析 --> data.db --> json --> front

@sealhuang @ben-29

**Comment by yihong0618** [comment]
@sealhuang 支持了

**Comment by sealhuang** [comment]
@yihong0618 👍
我试着使用tcx_to_strava的方法将tcx的内容上传到sträva，但发现读取出的数据和实际跑步的数据不太一样，貌似是读取tcx文件时出了问题，不知道是nrc给导出的tcx文件和标准不一致，还是啥其他问题

**Comment by yihong0618** [comment]
能看看具体哪些不一样么

**Comment by yihong0618** [comment]
我找时间看一下

**Comment by yihong0618** [comment]
@sealhuang 看了下基本是 nike 数据问题，因为 nrc 是记录暂停时间的，而 tcx 没有。
你可以用 running_page 导出 gpx 上传试试。
---

理论上你改完手机 location 和 nrc location 还可以用

**Comment by sealhuang** [comment]
> ## @sealhuang 看了下基本是 nike 数据问题，因为 nrc 是记录暂停时间的，而 tcx 没有。
> 你可以用 running_page 导出 gpx 上传试试。
> 理论上你改完手机 location 和 nrc location 还可以用

好的，我试试，感谢！
