### ISSUE TITLE
求助：push new runs时报错

### ISSUE THREAD

**Issue by jathon** [yihong0618/running_page#268]
报错内容如下：
Run github-actions-x/commit@v2.6
/usr/bin/docker run --name cd98f[1](https://github.com/jathon/running_page/runs/7153369804?check_suite_focus=true#step:17:1)7623fd6319f45f6a1747ef3763ef1c2_d3d914 --label 4cd98f --workdir /github/workspace --rm -e RUN_TYPE -e ATHLETE -e TITLE -e TITLE_GRID -e GITHUB_NAME -e GITHUB_EMAIL -e pythonLocation -e INPUT_GITHUB-TOKEN -e INPUT_COMMIT-MESSAGE -e INPUT_FILES -e INPUT_REBASE -e INPUT_NAME -e INPUT_EMAIL -e INPUT_PUSH-BRANCH -e INPUT_FORCE-ADD -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/running_page/running_page":"/github/workspace" 4cd98f:17623fd6319f45f6a1747ef3763ef1c2

Traceback (most recent call last):
  File "/entrypoint.py", line 53, in <module>
    run()
  File "/entrypoint.py", line 46, in run
    debug(git(['pull', '--rebase', '--autostash', 'origin', branch]))
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 99, in __call__
    return self.run(args, **kwargs)[1]
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 322, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/commands/processes.py", line 24, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/usr/local/lib/python3.7/site-packages/plumbum/machines/base.py", line 29, in verify
    getattr(self, "argv", None), self.returncode, stdout, stderr
plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1[28](https://github.com/jathon/running_page/runs/7153369804?check_suite_focus=true#step:17:29)
Command line: | /usr/bin/git pull --rebase --autostash origin master
Stderr:       | fatal: unsafe repository ('/github/workspace' is owned by someone else)
              | To add an exception for this directory, call:
              | 
              | 	git config --global --add safe.directory /github/workspace

**Comment by yihong0618** [comment]
你是之前 fork 的么？
需要更新到最新。

**Comment by jathon** [comment]
对，是很早之前fork的，大概要怎么操作？有点忘记了

**Comment by yihong0618** [comment]
重新走一遍流程

**Comment by jathon** [comment]
好的，我试试，感谢
