### ISSUE TITLE
Map zoom and jaggy line problems after dependencies upgraded

### ISSUE THREAD

**Issue by ben-29** [yihong0618/running_page#273]
After fetch from upstream, I'm facing 2 problems:
1. Map zoom in/out with a unbearable delay(1s+) using scroll key.
2. Map route become blur and jaggy as the left part of image below:
![image](https://user-images.githubusercontent.com/6956444/177737490-831e818c-bf18-48e9-a490-98bac8e36e7b.png)

Preview Links:
Before the upgrade: https://running-page-ll820s7my-ben-29.vercel.app
After the upgrade: https://running-page-8i2ubp7qk-ben-29.vercel.app

After some digging, I had ping down to the following depends:
* Problem 1: 
  * `react`: `17.0.2` -> `18.2.0`
  * `react-dom`: `17.0.2` -> `18.2.0`
* Problem 2: causing blur and jaggy with `line-opacity` option 
  * `react-map-gl`: `5.1.22` -> `6.1.16`

I'm not so familiar with React & Mapbox. I don't really sure if this is the root cause of the 2 problems. But to me, revert this 3 depends works like before.

I'll make a PR to revert the depends for now. Because the first Problem is really annoying.

@shaonianche @yihong0618 Can you guys check if there is a better solution? Thanks.

**Comment by yihong0618** [comment]
I am facing this problem too...
and its on my todo list...
Thanks a lot for the dig.
