### ISSUE TITLE
Garmin CN GPX heartrate解析问题

### ISSUE THREAD

**Issue by luyangk** [yihong0618/running_page#275]
在自己部署的页面上没看到bpm数据，后来看了gpx内容改了以下内容就显示了，请作者看看是不是该这么改哈
gpx中内容：
`<extensions>
<ns3:TrackPointExtension>
<ns3:atemp>34.0</ns3:atemp>
<ns3:hr>168</ns3:hr>
<ns3:cad>113</ns3:cad>
</ns3:TrackPointExtension>
</extensions>`
track.py文件修改
修改前：
`heart_rate_list.extend(
                        [
                            int(p.extensions[0].getchildren()[0].text)
                            for p in s.points
                            if p.extensions
                        ]
                    )`
修改后：
`heart_rate_list.extend(
                        [
                            int(p.extensions[0].getchildren()[1].text)
                            for p in s.points
                            if p.extensions
                        ]
                    )`

**Comment by yihong0618** [comment]
是的，造成的原因是，这个里面可以既有 heartrate 也可能有其它的，其它的就在第二个了。可能需要改下，你有兴趣试试么？

or 我来改？

**Comment by yihong0618** [comment]
@ben-29 我记得你之前遇到了这个问题。

**Comment by ben-29** [comment]
是的，需要改为解析 `hr` 标签, 我的fork有处理，一会同步过来~ @yihong0618 @luyangk

**Comment by yihong0618** [comment]
@luyangk merge 了你能实验一下么？
https://github.com/yihong0618/running_page/pull/276

**Comment by luyangk** [comment]
> 

测试完毕~完美解决~

**Comment by yihong0618** [comment]
感谢～
