### ISSUE TITLE
我跑过济州岛，但是显示只有一个

### ISSUE THREAD

**Issue by Clown12138** [yihong0618/running_page#292]
![image](https://user-images.githubusercontent.com/35648418/181877960-0417c285-548f-4d0e-894f-e7e6c0c7ca2c.png)
![image](https://user-images.githubusercontent.com/35648418/181878013-5212c373-7324-42ca-a300-a129c333adfe.png)

**Comment by yihong0618** [comment]
大概率这个没解析出来国家。

**Comment by yihong0618** [comment]
我有时间看看，这块解析一直有些问题。

**Comment by Clown12138** [comment]
原来如此，我看你的是显示三个国家，不知道是不是我跑步记录的原因

**Comment by efish2002** [comment]
我查到我的一个次记录，应该是在日本跑的，没有识别出来，国家识别是不是用邮编更准确一些？
"location_country": "\u30db\u30c6\u30eb\u65e5\u822a\u6210\u7530, 500, \u6210\u7530\u5c0f\u898b\u5ddd\u9e7f\u5cf6\u6e2f\u7dda, \u53d6\u9999, \u6210\u7530\u5e02, \u5343\u8449\u770c, 286-0106, \u65e5\u672c", 
![image](https://github.com/yihong0618/running_page/assets/10509616/ee4e311c-1704-494c-a2b4-fd71e69ae101)

**Comment by yihong0618** [comment]
@efish2002 可能是，但是这个识别出来的格式我不太确定是否有邮编，我有时间看一下。
PR welcome

**Comment by 2tu** [comment]
> 我查到我的一个次记录，应该是在日本跑的，没有识别出来，国家识别是不是用邮编更准确一些？ "location_country": "\u30db\u30c6\u30eb\u65e5\u822a\u6210\u7530, 500, \u6210\u7530\u5c0f\u898b\u5ddd\u9e7f\u5cf6\u6e2f\u7dda, \u53d6\u9999, \u6210\u7530\u5e02, \u5343\u8449\u770c, 286-0106, \u65e5\u672c", ![image](https://user-images.githubusercontent.com/10509616/246712571-ee4e311c-1704-494c-a2b4-fd71e69ae101.png)

是不是可以改用经纬度来调用逆地址解析，但是根据ISO_3166只有国家和地区，没有市
```
$ curl http://api.geonames.org/countrySubdivisionJSON?lat=28.875685\&lng=105.437581\&username=demo

{"codes":[{"code":"SC","level":"1","type":"ISO3166-2"}],"adminCode1":"32","distance":0,"countryCode":"CN","countryName":"China","adminName1":"Sichuan"}

```

**Comment by yihong0618** [comment]
> > 我查到我的一个次记录，应该是在日本跑的，没有识别出来，国家识别是不是用邮编更准确一些？ "location_country": "\u30db\u30c6\u30eb\u65e5\u822a\u6210\u7530, 500, \u6210\u7530\u5c0f\u898b\u5ddd\u9e7f\u5cf6\u6e2f\u7dda, \u53d6\u9999, \u6210\u7530\u5e02, \u5343\u8449\u770c, 286-0106, \u65e5\u672c", ![image](https://user-images.githubusercontent.com/10509616/246712571-ee4e311c-1704-494c-a2b4-fd71e69ae101.png)
> 
> 是不是可以改用经纬度来调用逆地址解析，但是根据ISO_3166只有国家和地区，没有市
> 
> ```
> $ curl http://api.geonames.org/countrySubdivisionJSON?lat=28.875685\&lng=105.437581\&username=demo
> 
> {"codes":[{"code":"SC","level":"1","type":"ISO3166-2"}],"adminCode1":"32","distance":0,"countryCode":"CN","countryName":"China","adminName1":"Sichuan"}
> ```

现在 gpx 解析就是(^-^)

**Comment by 2tu** [comment]
> > > 我查到我的一个次记录，应该是在日本跑的，没有识别出来，国家识别是不是用邮编更准确一些？ "location_country": "\u30db\u30c6\u30eb\u65e5\u822a\u6210\u7530, 500, \u6210\u7530\u5c0f\u898b\u5ddd\u9e7f\u5cf6\u6e2f\u7dda, \u53d6\u9999, \u6210\u7530\u5e02, \u5343\u8449\u770c, 286-0106, \u65e5\u672c", ![image](https://user-images.githubusercontent.com/10509616/246712571-ee4e311c-1704-494c-a2b4-fd71e69ae101.png)
> > 
> > 是不是可以改用经纬度来调用逆地址解析，但是根据ISO_3166只有国家和地区，没有市
> > 
> > ```
> > $ curl http://api.geonames.org/countrySubdivisionJSON?lat=28.875685\&lng=105.437581\&username=demo
> > 
> > {"codes":[{"code":"SC","level":"1","type":"ISO3166-2"}],"adminCode1":"32","distance":0,"countryCode":"CN","countryName":"China","adminName1":"Sichuan"}
> > ```
> 
> 现在 gpx 解析就是(^-^)

好吧

**Comment by 2tu** [comment]
Thanks for being in touch.I will respond as soon as possible!

**Comment by NaturezzZ** [comment]
@Clown12138 最新版本是否已经解决？
