### ISSUE TITLE
Local build bug: "This is a bug in `node-gyp`" 

### ISSUE THREAD

**Issue by gricn** [yihong0618/running_page#30]
It happen in the process of "**Yarn install**" on my local machine, but I don't know how to solve that. Run here for help.

Having test in :
- Python: 3.9 | 3.8 | 2.7
- Yarn: 1.22.5
- Node: 15.0.1
- Win10, AMD

## Logs

That's what happen when run in **Python3**:
[node-gyp_error_python3.log](https://github.com/yihong0618/running_page/files/5470327/node-gyp_error_python3.log)

When run in **Python2** (Use the dirty method: cd to C:\Python27\ and change "python.exe" to "python2.exe"):
[node-gyp_error-python2.log](https://github.com/yihong0618/running_page/files/5470328/node-gyp_error-python2.log)

**Comment by yihong0618** [comment]
Can you try Python3.8 or 3.6 or 3.7 it seems the version problems base on the log

**Comment by gricn** [comment]
I have tried Python **3.6.8** and **3.7.9** , **3.8.6** and **3.9.0**, all of them not work

**Comment by yihong0618** [comment]
Sorry I don't have this issue. And I just check my node version it is 12.
And I test mac ubuntu and wsl these version they are all work.
Can you try use node 12 and give a try?
