### ISSUE TITLE
[github action] Run Data Sync workflow 没有自动触发Publish GitHub Pages workflow

### ISSUE THREAD

**Issue by cvvz** [yihong0618/running_page#305]
看配置文件，理论上Run Data Sync workflow会push到master分支，就会触发Publish GitHub Pages workflow自动运行，但是实际上没有触发。还是得依赖手工或者周期性的触发。

**Comment by yihong0618** [comment]
把这几行删了试试？我研究一下。
https://github.com/yihong0618/running_page/blob/master/.github/workflows/gh-pages.yml#L8-L18

**Comment by yihong0618** [comment]
@cvvz 请问是不是去掉这几行就可以了？
我接下来更新下～

**Comment by cvvz** [comment]
我来试试~
