### ISSUE TITLE
请问为什么我的mapbox里的路线显示的是很浅色的虚线呢

### ISSUE THREAD

**Issue by cvvz** [yihong0618/running_page#307]
如图，是浅黄色的虚线，如何能调整为黄色实线呢？
![image](https://user-images.githubusercontent.com/44308864/187820644-bd12ce89-dcaa-4cda-b840-9920d9f2cef2.png)

**Comment by ben-29** [comment]
参考文档：https://github.com/yihong0618/running_page/blob/master/README-CN.md#%E4%B8%80%E4%BA%9B%E4%B8%AA%E6%80%A7%E5%8C%96%E9%80%89%E9%A1%B9

**Comment by yihong0618** [comment]
如果跑了很多的话，哪个地方跑的多，哪个地方跑的少，虚线清晰一些。
其它参考 @ben-29 的评论

**Comment by cvvz** [comment]
thanks 😊
