### ISSUE TITLE
[feature request] 之后会考虑支持高驰（COROS）的设备吗？

### ISSUE THREAD

**Issue by zxl19** [yihong0618/running_page#308]
您好，请问这个项目之后会考虑支持高驰（COROS）的设备吗？

**Comment by yihong0618** [comment]
短时间不会，精力有限。PR welcome(^-^)

**Comment by yihong0618** [comment]
搜索了一下似乎有研究过

你可以参考一下，我有精力试试
https://github.com/xballoy/coros-api

**Comment by zxl19** [comment]
好的，谢谢！

**Comment by yihong0618** [comment]
提供下思路

1. 根据上面 repo 的 api 拿到你的运动
2. 参考任何一个 sync 拿到需要存在 sqlite 的数据
3. 可能需要拿到坐标点，看看是否能解析成 gpx --> 参考 keep_sync or nike_sync
4. 存 gpx ->GPX_OUT
5. 想办法配置 Actions 每日自动化
6. 具体如何自动化可以参考 Actions 的 yml

**Comment by haowei93** [comment]
> 您好，请问这个项目之后会考虑支持高驰（COROS）的设备吗？

目前这个mr 支持 coros 设备自动生成， 可以试试(https://github.com/yihong0618/running_page/pull/623/)
