### ISSUE TITLE
vercel部署的网页似乎访问不了了？

### ISSUE THREAD

**Issue by lulu10922** [yihong0618/running_page#311]
我的地址：
https://running-page-lulu10922.vercel.app/
试了几个readme里的几个vercel地址，似乎也访问不了了。

**Comment by yihong0618** [comment]
@lulu10922 你的能访问。
现在可能需要梯子了。

**Comment by lulu10922** [comment]
还真的是需要梯子了。。。
我学习下其他的部署方式吧，谢谢啦
