### ISSUE TITLE
发布之后，地图就没有了。localhost打开是有地图的。

### ISSUE THREAD

**Issue by be-better-zky** [yihong0618/running_page#315]
发布之后控制台有这些报错。一模一样的代码localhost没有报错，地图是正常显示的。
![image](https://user-images.githubusercontent.com/77084553/189515388-ec1d9f32-bd2f-4f76-a442-260e33410f8b.png)

**Comment by yihong0618** [comment]
GitHub page 么？

**Comment by yihong0618** [comment]
看了下，你要设置 GitHub page 的 branch 目前你全用的 master

**Comment by be-better-zky** [comment]
是这个吗，这个我改过了。我代码里面也改成了这个分支gh-pages。还有哪里是master啊，我没找到。😁😁
![image](https://user-images.githubusercontent.com/77084553/189519456-1f5e5798-05ba-4baa-985c-eca670ceb044.png)

**Comment by yihong0618** [comment]
sorry 不是 master 是 main
@be-better-zky 我看了下你的 repo 
你的默认 branch 是 gh-page 
而 main  branch 啥也没有。
这样是不对的。。。

gh-page 的生成逻辑是 main 跑生成新的数据，然后运行 gh-page 这样才能生成数据。


![image](https://user-images.githubusercontent.com/15976103/189520325-c1714304-c68c-4c2c-afc8-51650ffed8ca.png)

**Comment by yihong0618** [comment]
可以参考 README 一步一步来。

1. main 的代码跑或者 actions 来生成数据
2. push
3. trigger GitHub page 的 Actions 来试验。

**Comment by yihong0618** [comment]
@shaonianche @ben-29 麻烦有空帮忙也看看～～

**Comment by ben-29** [comment]
https://github.com/yihong0618/running_page/blob/99c2816418075b8e99083613356c586deb4f02dd/gatsby-config.js#L2
@be-better-zky  你fork后repo名称改了，把`pathPrefix` 改为repo名 '/running' 试试

**Comment by be-better-zky** [comment]
谢谢各位大佬！！🐱‍🏍🐱‍🏍问题解决了。ヾ(≧▽≦*)oヾ(≧▽≦*)o
