### ISSUE TITLE
悦跑圈提取问题

### ISSUE THREAD

**Issue by wxlznsb** [yihong0618/running_page#316]
大佬，我想问下是悦跑圈记录只能爬取一次吗，在u盘里不小心删了，第二次爬取说没有记录了，还有救吗

**Comment by yihong0618** [comment]
删除data.db 和 gpx_out 里的文件再试试

**Comment by wxlznsb** [comment]
> 删除data.db 和 gpx_out 里的文件再试试

好了好了 感谢大佬
