### ISSUE TITLE
keep 接口用不了了，但是历史的GPX数据还在，但是历史数据打点漂移，请问有办法转换GPX数据吗

### ISSUE THREAD

**Issue by cvvz** [yihong0618/running_page#318]

**Comment by cvvz** [comment]
GPX导入到strava仍然是漂移的

**Comment by yihong0618** [comment]
keep 目前用不了了？

**Comment by cvvz** [comment]
python3 scripts/keep_sync.py xxx xxx--with-gpx

pares keep ids data since 1970-01-01 00:00:00
0 new keep runs to generate
No tracks found.

**Comment by cvvz** [comment]
但是好在有之前的gpx数据，可是打点是便宜的，所以没法用一些issue里提到的解决办法。。

**Comment by yihong0618** [comment]
1. 备份这个 repo
2. 弄一个新的，重新执行试试？

**Comment by yihong0618** [comment]
没找到的原因是因为 data.db 里没法找到下一个，很可能。防止意外，你可以新建一个 repo 重新执行 keep 的步骤试试

**Comment by cvvz** [comment]
从新clone一个repo执行这个脚本吗？

**Comment by cvvz** [comment]
解决了，太棒了 ！@yihong0618 🚀🚀

**Comment by yihong0618** [comment]
你可以试试用新的 gpx 是否偏移。

**Comment by cvvz** [comment]
> 你可以试试用新的 gpx 是否偏移。

修正后的gpx数据是准确的😄
