### ISSUE TITLE
nike refresh token不见了

### ISSUE THREAD

**Issue by schenxia** [yihong0618/running_page#320]
请教您一下，我之前是可以找到Nike refresh token的，最近几个礼拜突然没有了，能麻烦您看一下是什么情况吗？谢谢了！
![Capture](https://user-images.githubusercontent.com/45961727/195738326-affb56e3-a894-4546-80be-8a4bba195675.JPG)

**Comment by shaonianche** [comment]
> 请教您一下，我之前是可以找到Nike refresh token的，最近几个礼拜突然没有了，能麻烦您看一下是什么情况吗？谢谢了！ ![Capture](https://user-images.githubusercontent.com/45961727/195738326-affb56e3-a894-4546-80be-8a4bba195675.JPG)

试试使用[nike台湾](https://www.nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings) 来登录找找。

**Comment by schenxia** [comment]
> > 请教您一下，我之前是可以找到Nike refresh token的，最近几个礼拜突然没有了，能麻烦您看一下是什么情况吗？谢谢了！ ![Capture](https://user-images.githubusercontent.com/45961727/195738326-affb56e3-a894-4546-80be-8a4bba195675.JPG)
> 
> 试试使用[nike台湾](https://www.nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings) 来登录找找。

在nike 台湾上找到了，非常感谢！

**Comment by arthurfsy2** [comment]
> > > 请教您一下，我之前是可以找到Nike refresh token的，最近几个礼拜突然没有了，能麻烦您看一下是什么情况吗？谢谢了！ ![Capture](https://user-images.githubusercontent.com/45961727/195738326-affb56e3-a894-4546-80be-8a4bba195675.JPG)
> > 
> > 
> > 试试使用[nike台湾](https://www.nike.com/tw/member/profile/login?continueUrl=https://www.nike.com/tw/member/settings) 来登录找找。
> 
> 在nike 台湾上找到了，非常感谢！

请问现在nike台湾还可以获取吗？2023/4/3尝试登录，但是无法获取refresh token

**Comment by yihong0618** [comment]
@arthurfsy2 可以的

**Comment by arthurfsy2** [comment]
> @arthurfsy2 可以的

那可能是我账号问题，14年注册了账号，已经不记得有没有跑步记录了

**Comment by has-ctrl** [comment]
Hi @yihong0618, thank you so much for creating this repo. It is really helpful. Sadly, I have the same problem as mentioned above. Is there any other way to get the NRC refresh token? Via Nike Taiwan seems to be locked. Thank you!

![image](https://github.com/yihong0618/running_page/assets/57541155/3a4183c0-26f2-4f72-a1dd-3bd1a7f53f0f)

**Comment by yihong0618** [comment]
> Hi @yihong0618, thank you so much for creating this repo. It is really helpful. Sadly, I have the same problem as mentioned above. Is there any other way to get the NRC refresh token? Via Nike Taiwan seems to be locked. Thank you!
> 
> 
> 
> ![image](https://github.com/yihong0618/running_page/assets/57541155/3a4183c0-26f2-4f72-a1dd-3bd1a7f53f0f)
> 
> 

maybe you can use mobile like iOS to login and capture the api using somethkng like proxyman？

**Comment by has-ctrl** [comment]
Seems like the Taiwan website is working again. No trouble getting the refresh token today! Thank you.

**Comment by yihong0618** [comment]
> Seems like the Taiwan website is working again. No trouble getting the refresh token today! Thank you.

my pleasure and do you know Chinese? Since you can search this issue. 😄

**Comment by has-ctrl** [comment]
> > Seems like the Taiwan website is working again. No trouble getting the refresh token today! Thank you.
> 
> my pleasure and do you know Chinese? Since you can search this issue. 😄

Haha I do not, but Google Translate helps a lot. Thanks again for this repo!

**Comment by yihong0618** [comment]
copy that
