### ISSUE TITLE
Strava API 配置问题

### ISSUE THREAD

**Issue by i-abc** [yihong0618/running_page#326]
老哥请问网站这里填什么？

![image](https://user-images.githubusercontent.com/104631897/196603001-47c0bed9-c4bb-409e-8be0-acf205b573d7.png)

我看教程里没：

![](https://raw.githubusercontent.com/shaonianche/gallery/master/running_page/strava_settings_api.png)

**Comment by yihong0618** [comment]
添 localhost 就行

**Comment by i-abc** [comment]
> 添 localhost 就行

填 localhost 提示不行

![image](https://user-images.githubusercontent.com/104631897/196607984-65dab747-add3-4aa8-84a4-e9a24142486e.png)

**Comment by yihong0618** [comment]
http://localhost 也可能需要加个端口

**Comment by i-abc** [comment]
> http://localhost

加了也提示不行

![image](https://user-images.githubusercontent.com/104631897/196609661-b62be56b-4fed-4a1f-9e9d-ef36c260fb38.png)

**Comment by yihong0618** [comment]
@i-abc 参考我的长这样
<img width="626" alt="image" src="https://user-images.githubusercontent.com/15976103/196612721-0cddb706-6793-40c2-992e-68cd185d39d9.png">

**Comment by yihong0618** [comment]
by the way, strava 的 api 需要获取权限，需要按照 readme 步骤

**Comment by i-abc** [comment]
@yihong0618 谢谢老哥提醒，成功了，赞一个

**Comment by yihong0618** [comment]
@i-abc 另外你需要把 username 和 email 改了。。。要不我能收到通知。

**Comment by i-abc** [comment]
@yihong0618 抱歉抱歉，还没注意这个，这就去改

**Comment by yihong0618** [comment]
没关系哈哈，enjoy it
