### ISSUE TITLE
腾讯云主机部署，本地机器能 curl 通，通过 IP+端口就不行了

### ISSUE THREAD

**Issue by zhuyaguang** [yihong0618/running_page#327]
运行成功
![image](https://user-images.githubusercontent.com/8857976/196668906-6a3b45e4-a87e-4229-9147-b2a43ce16794.png)

本地能 curl 通 

![image](https://user-images.githubusercontent.com/8857976/196668998-23ed0651-74cc-4c7a-8fe2-ba6a532964fa.png)

但是访问 IP+ 端口有问题

![image](https://user-images.githubusercontent.com/8857976/196669587-3562039e-e7f2-4e82-a6dd-d10d83ed148d.png)

所以哪里可以设置默认的8000端口

**Comment by shaonianche** [comment]
telnet 端口可以通吗？

**Comment by yihong0618** [comment]
外面访问的话，你起 0.0.0.0:8000 而不是 localhost 试试

**Comment by zhuyaguang** [comment]
> 试

这个在代码哪里设置呢 我全局搜索代码 除了 README 里面 没找到 localhost

![image](https://user-images.githubusercontent.com/8857976/196674358-a047d030-1ff9-4109-b495-35f9f676c0b6.png)

**Comment by zhuyaguang** [comment]
> 

我部署了一个服务 用的是 默认是 80 端口，访问没问题

**Comment by yihong0618** [comment]
是 gatsby 搜索 gatsby run 0.0.0.0 然后改 package.json

**Comment by zhuyaguang** [comment]
> 0.0.0.0

原来是我的腾讯云 没有开放端口访问  谢谢 @yihong0618 @shaonianche   解答 
![Uploading image.png…]()

**Comment by yihong0618** [comment]
客气了

**Comment by yihong0618** [comment]
enjoy it 😄
