### ISSUE TITLE
求Keep数据更新接口

### ISSUE THREAD

**Issue by EugeneLau0** [yihong0618/running_page#328]
因个人的Keep步行数据存在很多现在看来没有意义的自动记录，这样的数据大约有三千来条，手工删除实在费劲。我fork了作者的工具，实现可以查询到每一条步行记录，但是没有删除接口可用。看看作者这边有没有了解Keep的删除接口，或者给提供一种思路

**Comment by yihong0618** [comment]
running_page 里没有删除接口，抱歉。

**Comment by EugeneLau0** [comment]
> running_page 里没有删除接口，抱歉。

有没有什么思路可以去模拟呢？我通过IOS抓包，现在的接口、参数都加密了

**Comment by yihong0618** [comment]
提供些思路
1. 利用安卓去找老版本抓包
2. 想办法解密，有些是可以猜出来的。

**Comment by EugeneLau0** [comment]
> 提供些思路
> 
> 1. 利用安卓去找老版本抓包
> 2. 想办法解密，有些是可以猜出来的。

好的，我去试试。谢谢

**Comment by yihong0618** [comment]
先关了哈。
