### ISSUE TITLE
悦跑圈导出数据问题

### ISSUE THREAD

**Issue by w749** [yihong0618/running_page#334]
你好，我按照文档方法成功导出悦跑圈数据并记录了uid和sid，但是在我登录悦跑圈app（尝试了验证码和微信登录）后sid就失效了，无法再次获取数据
所以现在的问题是手机app在线和每天定时导出悦跑圈数据这两件事情只能实现一个。是我操作的方式有问题还是其他什么原因

![截图_16674564929804](https://user-images.githubusercontent.com/39213602/199658529-821cb234-f20f-4810-98f2-72fdb0aa3999.png)

**Comment by yihong0618** [comment]
操作没问题，因为悦跑圈和微信是一样的，只能一个设备登入，所以无法自动化的

**Comment by w749** [comment]
好吧，感谢

**Comment by yihong0618** [comment]
@w749 
悦跑圈和咕咚是无法做到自动化的。如果想自动化需要使用其它 app
