### ISSUE TITLE
v2.0 TODO

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#336]
- [ ] refactor python code
- [ ] TUI
- [ ] PyPI
- [ ] next.js
- [ ] another theme
- [x] fast
- [ ] tailwind

**Comment by yihong0618** [comment]
https://github.com/yihong0618/running_page/issues/458

**Comment by shaonianche** [comment]
v2 : https://www.figma.com/file/YqanLWbDXAbSXS7tDnRlEU/running_page?type=design&node-id=0%3A1&mode=design&t=utK2Ir0IFrIflhYV-1

**Comment by yihong0618** [comment]
@shaonianche you can paste the png in the issue content

**Comment by yihong0618** [comment]
@VintLin @frostming 
I think @shaonianche's v2 design is great, maybe we can also make some color change to make v2 different !
