### ISSUE TITLE
仅能导出部分数据

### ISSUE THREAD

**Issue by Luodimaizi** [yihong0618/running_page#338]
试验了悦跑圈 keep和咕咚，都只能导出很小一部分记录，悦跑圈20条，Keep21条，咕咚约50条，其中悦跑圈多次试验，均只能导出20条，且不是最新的20条，而是随机分布的20条，每个月都有一两条的样子，其他两个APP没有进一步测试，深感疑惑，不知道有解没有？

**Comment by yihong0618** [comment]
是这样的，你删掉 data.db 然后专门倒一个试试。
因为可能你每个 app 都用切时间有重叠，你删掉之后重新专门倒一个试一试

**Comment by Luodimaizi** [comment]
- [ ] 删掉data.db后重试，问题复现，重复操作，没有变化；更换电脑重新配置，并重试，问题复现，重复操作，没有变化，对比发现导出数据的代码完全一致，能导出的条数一致。

- [ ] 贴一下代码
- [ ] D:\running_page-master>python scripts/joyrun_sync.py 17702726997 936516 --with-gpx
your uid and sid are 163914577 85722d113fc03bdbacf453bab617a1d8
downloading joyrun_id 739681537 gpx
downloading joyrun_id 751726598 gpx
downloading joyrun_id 732975118 gpx
downloading joyrun_id 732975123 gpx
downloading joyrun_id 731932954 gpx
downloading joyrun_id 749131346 gpx
downloading joyrun_id 745640025 gpx
downloading joyrun_id 725488232 gpx
downloading joyrun_id 742123903 gpx
downloading joyrun_id 677017490 gpx
downloading joyrun_id 706138297 gpx
downloading joyrun_id 729099588 gpx
downloading joyrun_id 750508741 gpx
downloading joyrun_id 741250503 gpx
downloading joyrun_id 737062091 gpx
downloading joyrun_id 749063657 gpx
downloading joyrun_id 681339370 gpx
downloading joyrun_id 747822572 gpx
downloading joyrun_id 749063660 gpx
downloading joyrun_id 744562673 gpx
Syncing tracks '+' means new track '.' means update tracks
++++++++limit+++++++
++++++++++limit+++++++
++++++++++limit+++++++
++++++++++limit+++++++
+++++++++limit+++++++
++++++++++++++++++++++++++++++++++++++++++limit+++++++
++++++++limit+++++++
+++++++++++limit+++++++
++++++++++++limit+++++++
++++++++++++++limit+++++++
+++++++++++++++++++++++++limit+++++++
+++++++++limit+++++++
+++++++++++limit+++++++
++++++++++limit+++++++
++++++++++limit+++++++
+++++++++++++++++limit+++++++
+++++++++limit+++++++
+++++++++limit+++++++
++++++++limit+++++++
++++++++limit+++++++
+++++++++
[D:\running_page-master>[]

**Comment by yihong0618** [comment]
@Luodimaizi 我明天看一下。
@ben-29 能帮忙看一下么～

**Comment by Luodimaizi** [comment]
辛苦作者啦，我是个门外汉，只会照葫芦画瓢，没有能力贡献力量，真的很感谢作者为跑友解决这种难搞的问题。

**Comment by ben-29** [comment]
@Luodimaizi 感谢测试，你给的数据很详细，有帮助到问题的定位。
不过有泄露隐私的风险，我把你的隐私信息删掉了。
我用你的uid和sid测试了下悦跑圈的，重复跑都能获取到相同的109条数据，但是其中只有20条数据有轨迹，你看看app内是否也是大部分看不到轨迹？
> * [ ]  删掉data.db后重试，问题复现，重复操作，没有变化；更换电脑重新配置，并重试，问题复现，重复操作，没有变化，对比发现导出数据的代码完全一致，能导出的条数一致。

**Comment by yihong0618** [comment]
@Luodimaizi 好的，我们试验一下，但我印象中你不加 --gpx 这些数据都是能出来的，只是没有轨迹图。
我们确定下。

**Comment by Luodimaizi** [comment]
> @Luodimaizi 好的，我们试验一下，但我印象中你不加 --gpx 这些数据都是能出来的，只是没有轨迹图。 我们确定下。

我也试了下，不加 --gpx，从运行的代码来看是出来了，但是没有生成文件，是存储在data.db文件里了吗？怎么才能把数据提取出来呢？

**Comment by Luodimaizi** [comment]
> @Luodimaizi 好的，我们试验一下，但我印象中你不加 --gpx 这些数据都是能出来的，只是没有轨迹图。 我们确定下。

我也试了下，不加 --gpx，从运行的代码来看是出来了，但是没有生成文件，是存储在data.db文件里了吗？怎么才能把数据提取出来呢？

**Comment by yihong0618** [comment]
你想提取什么样的数据呢？这里仅仅是一些字段了，因为没有轨迹，无法生成 gpx 之类的上传到其它地方。

--> 是 data.db

--> 你可以导出 csv 利用 pandas 之类的 read -> to_csv 就行

**Comment by Luodimaizi** [comment]
> 你想提取什么样的数据呢？这里仅仅是一些字段了，因为没有轨迹，无法生成 gpx 之类的上传到其它地方。
> 
> --> 是 data.db
> 
> --> 你可以导出 csv 利用 pandas 之类的 read -> to_csv 就行

懂了，我的本意自然是这些没有轨迹的数据也能生成某种格式的文件上传到其他地方，虽然没有轨迹，也算有纪念意义，不过程序上实现不了那就只能如此了。话说回来，能研究到这方面的跑友水平应该不差，大约没啥人会跑室内，像我这样的需求应该比较少见了，非常感谢作者答疑解惑^^

**Comment by yihong0618** [comment]
写完了，拉去最新代码执行以下步骤。

1. git pull
2. pip install pandas
3. 执行 running_page 你需要同步的之前的步骤
4. python3 scripts/data_to_csv.py

数据存在 data.csv 里，你可以用 Excel 打开

**Comment by yihong0618** [comment]
```python

import sqlite3
try:
    import pandas as pd
except:
    raise Exception("please install pandas run: pip3 install pandas")
from math import floor
data = sqlite3.connect("scripts/data.db")
df = pd.read_sql_query("SELECT * FROM activities", data)

def apply_duration_time(d):
    try:
        return d.split()[1].split(".")[0]
    except:
        return ''

# we do not need polyline in csv
df = df.drop('summary_polyline', axis=1)
df['elapsed_time'] = df['elapsed_time'].apply(apply_duration_time)
df['moving_time'] = df['moving_time'].apply(apply_duration_time)

def format_pace(d):
  if not d:
    return '0';
  pace = (1000.0 / 60.0) * (1.0 / d);
  minutes = floor(pace);
  seconds = floor((pace - minutes) * 60.0);
  return f"{minutes}''{seconds}"

df['average_speed'] = df['average_speed'].apply(format_pace)
df = df.sort_values(by=['start_date'])

df.to_csv("data.csv")
```

**Comment by yihong0618** [comment]
先关了哈

**Comment by yihong0618** [comment]
@Luodimaizi fixed
