### ISSUE TITLE
时间识别问题 

### ISSUE THREAD

**Issue by Cui1994** [yihong0618/running_page#34]
「午后」和「傍晚」是如何区分的呢，没有确定的时间界限。
![image](https://user-images.githubusercontent.com/20189661/97839321-f284a080-1d1c-11eb-9ae7-b0a3f5256a0a.png)

**Comment by yihong0618** [comment]
@Cui1994 

我在 utils.js 中自己定义的，你可以根据自己需要更改~
![image](https://user-images.githubusercontent.com/15976103/97839993-37f59d80-1d1e-11eb-8f39-32b9a6a42f9b.png)

**Comment by Cui1994** [comment]
get~
