### ISSUE TITLE
gpx to tcx

### ISSUE THREAD

**Issue by anChaOs** [yihong0618/running_page#340]
请问，咕咚导出的gpx数据，能否转换为tcx数据？

tcx数据，用于导入到高驰平台

**Comment by yihong0618** [comment]
我们之后研究一下，应该可以支持。

**Comment by yihong0618** [comment]
我们之后研究一下，应该可以支持。

**Comment by k29913x** [comment]
> 我们之后研究一下，应该可以支持。

您好，请问这个支持了吗？谢谢

**Comment by k29913x** [comment]
> 应该



> > 我们之后研究一下，应该可以支持。
> 
> 您好，请问这个支持了吗？谢谢

发现已经支持直接导出.tcx了，赞！

**Comment by DAVPanda** [comment]
> > 应该
> 
> > > 我们之后研究一下，应该可以支持。
> > 
> > 
> > 您好，请问这个支持了吗？谢谢
> 
> 发现已经支持直接导出.tcx了，赞！

请问是直接在咕咚软件内导出的吗？现在需要收费，而且只能一条一条导出。是否有更高效的方法

**Comment by yihong0618** [comment]
不收费啊，参考 README 自行尝试
