### ISSUE TITLE
运行之后，Github上的链接没有地图，部署到Vercel里的倒是正常的

### ISSUE THREAD

**Issue by Zhigang26** [yihong0618/running_page#343]
Hi Yihong,

如题，我运行running_page之后，从Garmin_Cn 里成功抓取了数据。但是发现在Github上的链接：https://zhigang26.github.io/Running-Page/  没地图。我后来按着说明，部署到Vercel上了，这个倒可以的https://zhigang-running-page.vercel.app，我又倒回来重新运行了Run Data Sync和Public Github Pages，都运行成功。然后刷新上面的链接，第一个还是没有地图。请问这是什么原因？

**Comment by yihong0618** [comment]
参考：
https://github.com/yihong0618/running_page/issues/315

**Comment by Zhigang26** [comment]
> 

地图问题已经解决了。我试了在你基础上修改的支持骑车的，只导出了18条数据就停掉了，有错误，但我自己不懂咋弄，完全不会代码。

我是在一个跑友群里看到你这个的。期待你这个代码可以尽快支持世界地图，支持多种运动。我自己的记录里有徒步、骑车、皮划艇，当然，绝大部分是跑步。之前购买过Gyroscope这个App，我觉得你这个完全有前途往那个方向做！即便收取一些费用，我个人也愿意的。再次感谢，并期待早日更新，谢谢。

**Comment by yihong0618** [comment]
> > 
> 
> 
> 
> 地图问题已经解决了。我试了在你基础上修改的支持骑车的，只导出了18条数据就停掉了，有错误，但我自己不懂咋弄，完全不会代码。
> 
> 
> 
> 我是在一个跑友群里看到你这个的。期待你这个代码可以尽快支持世界地图，支持多种运动。我自己的记录里有徒步、骑车、皮划艇，当然，绝大部分是跑步。之前购买过Gyroscope这个App，我觉得你这个完全有前途往那个方向做！即便收取一些费用，我个人也愿意的。再次感谢，并期待早日更新，谢谢。

1. 只支持跑步，骑行 fork 有推荐
2. 目前没精力做这个方向
3. 保持开源我觉得挺好的
