### ISSUE TITLE
KEEP导出数据偶尔不含GPX

### ISSUE THREAD

**Issue by lingdeyiyicifang** [yihong0618/running_page#351]
应该是KEEP的问题
如果把华为运动的数据同步到KEEP，且恰好那天你也用了KEEP来记录数据，那么同一天会有两条数据（KEEP APP上显示华为的为无效数据）
但是同步数据时，如果那天有这样子两条，那么就不会同步GPX数据，只会有跑步的里程等记录

**Comment by lingdeyiyicifang** [comment]
更新，刚又复查了一下数据，跟华为的没有关系，找到了反例：有一天我KEEP APP里，KEEP自己的轨迹和华为的轨迹都记录了，但是那天GPX数据是有导出的

**Comment by yihong0618** [comment]
已知问题。
https://github.com/yihong0618/running_page/issues/262

**Comment by yihong0618** [comment]
fixed
