### ISSUE TITLE
data.db数据更新后，网页显示内容没变化

### ISSUE THREAD

**Issue by lingdeyiyicifang** [yihong0618/running_page#352]
如题，删除data.db的运动记录后，重新执行yarn develop后，网页显示内容无变化（已清缓存）
后来，我把data.db和GPX_OUT文件夹都删去，重新执行yarn develop后，网页显示内容还是无变化

不知道是bug，还是我使用方法不对，需要执行什么命令才能更新网页内容显示吗

**Comment by lingdeyiyicifang** [comment]
但是执行完strava_sync.py或者keep_sync.py后，再执行yarn develop，网页内容是会更新的

**Comment by lingdeyiyicifang** [comment]
看明白了，通过data.db生成actitities.json，再呈现到web上。
所以现在问题变成了，该怎么手动更新actitities.json……

**Comment by yihong0618** [comment]
@lingdeyiyicifang 点一下这个按钮
![image](https://user-images.githubusercontent.com/15976103/207196513-fc49f180-506c-490b-9664-56d69764fe97.png)
