### ISSUE TITLE
佳明的同步好像失效了

### ISSUE THREAD

**Issue by liuxindtc** [yihong0618/running_page#355]
如下报错：Exception: 402 Client Error: Payment Required for url: https://connect.garmin.com/proxy/activitylist-service/activities/search/activities?start=0&limit=100
感谢帮忙看看吧

**Comment by yihong0618** [comment]
我找时间看看

**Comment by yihong0618** [comment]
新的 PR 解决了，你拉取下最新代码试试？

**Comment by liuxindtc** [comment]
感谢，原来就缺少个头参数啊~~~
