### ISSUE TITLE
【求助】garmin获取天气失败

### ISSUE THREAD

**Issue by liuxindtc** [yihong0618/running_page#358]
目前garmin的同步数据中没有气温，想通过其他接口获取。
找到一个接口有weather信息，代码如下
```
        url = f"{self.modern_url}/activity-service/activity/{activity_id}/weather"
        response = await self.req.get(url, headers=self.headers)
        response.raise_for_status()
        return response.read()
```
可是，这个运行结果是404。
增加自定义头headers["di-backend"] = "connectapi.garmin.com"后也不行，返回403
我看页面请求是是有auther头的，怀疑是缺少这个信息。但是为什么脚本中其他的请求不需要这个头也行。
搞不懂了，求助大佬们，看看如何能正确访问。

**Comment by yihong0618** [comment]
这个问题不属于这个项目～
我有精力帮你看看哈，最近可能没那么多精力。

---

hint:
拿到天气不难，你现在有时间戳，和 gpx -> gpx 能导出地点 -> 地点+ 时间 -> 去找个接口，拿到天气应该不难。

**Comment by liuxindtc** [comment]
感谢。我先用3方接口试试看
