### ISSUE TITLE
有支持google analytics的计划么? 有支持运动类型的计划么？

### ISSUE THREAD

**Issue by lmmsoft** [yihong0618/running_page#362]
yihong你好，fork你的项目很快就搭建起个人跑步页面，很开心，对你的工作表示感谢:) 
有两个问题
- google analytics4 应该是在 header 里注入一段script即可
- 多项运动现在是什么状态，有时间表，还是等待PR呀？

还发现一个bug:
热力图里面漂移挺多的，strava的heatmap就把漂移给去掉了，应该是有优化在里面~

**Comment by yihong0618** [comment]
多运动类型可以直接用 README 的 fork
google 欢迎 pr(^-^)

**Comment by yihong0618** [comment]
飘逸问题可以搜索 issue 里面有解决方法

**Comment by lmmsoft** [comment]
> 

漂移问题你指的是地球坐标系和火星坐标系的问题吧？

我的意思的跑步轨迹的大幅移动，这种一般是暂停和重启的点间隔太远导致的，如下图三个红线，这种轨迹有办法排除么？strava的个人热力图是没有的~

![image](https://user-images.githubusercontent.com/1109198/211970130-e13b2bbb-d47e-4e3c-a8ed-f15c5e973a46.png)

**Comment by yihong0618** [comment]
@lmmsoft 明白了，我试试，有可能可以

**Comment by shaonianche** [comment]
> google analytics4 应该是在 header 里注入一段script即可

参考gatsby文档：https://www.gatsbyjs.com/plugins/gatsby-plugin-google-analytics/，添加插件试试
