### ISSUE TITLE
大家好，我是80后非科班小白，喜欢捣腾网站啥的，最近摸索学习github，看到了running这个项目，真的很惊艳，我16-18年，也跑步了3年，马拉松，半马跑了10来个，跑的比较狠，犯了足底筋膜炎，到20年好了，又偶尔一年跑了几次，最近这几年体重又上来了，想再继续跑步，但是动力明显不足了。看到running的这个项目，我感觉自己又行了😂，我自己捣鼓了一下代码，按照描述的本地没有做成，就在腾讯整了一个轻量应用，按照步骤安装系统，文件，但还是没有搞定😓，现在寻求帮助。我的个人网站www.wangbin.org，我是一个非科班小白，见笑了，寻求你们的帮助，请不吝赐教，感谢！感谢！


### ISSUE THREAD

**Issue by zuqiuxie** [yihong0618/running_page#364]

**Comment by yihong0618** [comment]
readme 里有 tg 群的链接，在那里问可能有人能帮到你

**Comment by zuqiuxie** [comment]
> readme 里有 tg 群的链接，在那里问可能有人能帮到你

好的好的，新年快乐，感谢，我晚上再继续研究，

**Comment by zHElEARN** [comment]
其实很容易的 从[README.md#下载](https://github.com/yihong0618/running_page/blob/master/README-CN.md#%E4%B8%8B%E8%BD%BD) 开始 一步一步来就好了

**Comment by zuqiuxie** [comment]
谢谢大神们，看了youtube的讲解视频，结合百度，装了python，pip3，node，yarn等等，配置各种环境，本地终于整好了。
![IMG_20230124_182627.jpg](https://user-images.githubusercontent.com/50693793/214269053-97186bc3-2a5b-4268-a839-a9a41464fc82.jpg)
![IMG_20230124_182633.jpg](https://user-images.githubusercontent.com/50693793/214269080-0dc99d49-2078-45c8-8d71-ebb900314b05.jpg)
![IMG_20230124_183206.jpg](https://user-images.githubusercontent.com/50693793/214269258-db69643c-31f0-431a-a2b8-b9ccd0c27a5c.jpg)

**Comment by yihong0618** [comment]
@zuqiuxie cool 可以参考 README 换成自己数据试试了

**Comment by yihong0618** [comment]
Issue 我先关了哈，如果有问题我再打开。
