### ISSUE TITLE
next.js !!!!

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#369]
gatsby 突然不好用了，妈的

**Comment by Brightpan** [comment]
最近两天自动发布后，访问404，我看了是找不到根目录。是这个问题吗

**Comment by yihong0618** [comment]
@Brightpan 是的看我最新的 commit, 只需要改一行代码。
现在 vercel 默认行为改了。

**Comment by Brightpan** [comment]
@yihong0618 修改后站点访问正常了❤️
