### ISSUE TITLE
Deployment Tutorial

### ISSUE THREAD

**Issue by ChangxinBai** [yihong0618/running_page#37]
The deployment part is not friendly, especially a novice using the Github Action.

**Comment by shaonianche** [comment]
Thanks for your feedback , Do you have specific suggestions for improvement?

**Comment by ChangxinBai** [comment]
Maybe it is better to have a processing steps, where people can follow each one.

**Comment by yihong0618** [comment]
@ChangxinBai 
Did you change your "runing app` in GitHub actions [file](https://github.com/yihong0618/running_page/blob/master/.github/workflows/run_data_sync.yml) 

And add the secret in it too (the secrets are based with your running app)

**Comment by ChangxinBai** [comment]
@yihong0618  Yes, I did it.
