### ISSUE TITLE
Data fetched from Nike seems incorrect

### ISSUE THREAD

**Issue by gricn** [yihong0618/running_page#38]
First of all, thanks for your lovely project. It really encourages me to run. But I find the data fetched from Nike seems incorrect.

## Data Lost
The data from my Vercel-build website is as below, which presents that I have total run only **14 times and 24.4KM**. 
![蜂蜜浏览器_Snipaste_2020-11-04_15-54-09](https://user-images.githubusercontent.com/34237589/98084254-8178f080-1eb6-11eb-8cb8-167100e0a2a6.png)

When I launch my Nike Running Club, however, it presents that I have total run **34 times and 41.72KM**.
![蜂蜜浏览器_6fc6a509e54ea9fb701527fd83dd6ad](https://user-images.githubusercontent.com/34237589/98084256-8342b400-1eb6-11eb-9d4c-6fb6431e1dfa.jpg)

After checking my data, I find 20 of them are lost. It has nothing to do with running time and distance. 

## Remained data's problem
As for those remained data, the distance and pace are also different from Nike's. Is the distance recalculated by Mapbox?

**Comment by yihong0618** [comment]
@gricn 
Because some of your Runs has no gpxs.
Nike_sync is based on gpx
Maybe you added them manually or something wrong with the workout(I don't know).

**Comment by yihong0618** [comment]
@gricn 

Or you can try 
```shell
rm scripts/data.db GPX_OUT/* activities/*
```
then
```python
python3 scripts/nike_sync.py  eeeee ppp
```
to regenerate the data, to see if the data is corrent.

**Comment by gricn** [comment]
I have also tried in WSL2 today, however, the data is still incorrect, just as shown in Vercel.
No matter how, thanks.
