### ISSUE TITLE
【keep】为啥会存在轨迹缺失的问题

### ISSUE THREAD

**Issue by sun0225SUN** [yihong0618/running_page#380]
`actions` 倒没报错，但好像没获取`gpx`到数据，不太清楚原因，今天晚上再跑个步测试一下看看是不是脚本的问题。

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/79169717/221772616-3a2623d8-65ff-4bb8-9729-02eb15ee04e5.png">

还有这个彩蛋，左边的样式是不是有点问题。

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/79169717/221772688-f081a074-973f-4a43-851c-70d79e48eb59.png">

**Comment by yihong0618** [comment]
1. 没有数据是因为 keep 没有放轨迹数据，你搜一下 issue 这个无法解决
2. 样式问题应该是屏幕小拉伸的。

**Comment by sun0225SUN** [comment]
> 1. 没有数据是因为 keep 没有放轨迹数据，你搜一下 issue 这个无法解决

啊这，我第一条就是用 `keep` 跑的

**Comment by yihong0618** [comment]
对，keep 有时会没有轨迹

**Comment by sun0225SUN** [comment]
> 对，keep 有时会没有轨迹

哦哦，好哒，有时有有时没还挺玄学的，哈哈

**Comment by yihong0618** [comment]
fixed
