### ISSUE TITLE
yarn develop 之后报错：error Command failed with exit code 1.

### ISSUE THREAD

**Issue by hi-nikola** [yihong0618/running_page#382]
你好，请问按照命令安装 但是报错如下，搜索原因仍无法解决 （不太懂yarn）：请问一下怎么回事
![image](https://user-images.githubusercontent.com/52887883/224023935-f199165a-a6da-404c-941c-3190112b5332.png)

**Comment by hi-nikola** [comment]
哦  对了  我是听了播客过来的  。我觉得很酷！！我也是做数据、可视化的。~~

**Comment by yihong0618** [comment]
需要梯子。。。yarn install 那步～

**Comment by shaonianche** [comment]
> ![image](https://user-images.githubusercontent.com/52887883/224027625-1d5fb8e2-f5c1-4ec1-b737-fad5cd64badb.png)
> 
> 
> 
> 
> 
> 第二步骤 我检查了 安装的是成功  但是还是如此。

yarn build 试试能成功吗

**Comment by yihong0618** [comment]
先关了
