### ISSUE TITLE
GitHUb Actions执行的时候permission denied，请问有遇到的吗

### ISSUE THREAD

**Issue by shensl4499** [yihong0618/running_page#383]
百度后没有解决，大佬帮忙分析一下哪里出问题的。![image](https://user-images.githubusercontent.com/41412753/224526646-9e63caec-a948-468c-9c2d-dc86fa9b2213.png)

**Comment by shensl4499** [comment]
本地push到github没有这个问题，github action执行的时候遇到此问题

**Comment by yihong0618** [comment]
在 setting 里把 actions 的 write 权限打开

**Comment by shensl4499** [comment]
可以了，感谢支持。
![image](https://user-images.githubusercontent.com/41412753/224527312-e1dcd417-ca52-4192-81b2-94a39f042766.png)

**Comment by yihong0618** [comment]
不客气，GitHub 刚改不久的。
有兴趣提个 PR 把这个 note 加上 readme 和 readme-cn 里么？

**Comment by shensl4499** [comment]
放弃了，一提交pr就把我的数据传上去了，issue关闭了吧...

**Comment by yihong0618** [comment]
没关系～我帮你添加到 runner 里

waner ***@***.***> 于2023年3月13日周一 22:23写道：

**Comment by shensl4499** [comment]
谢谢，我会继续学习
