### ISSUE TITLE
小白不会折腾

### ISSUE THREAD

**Issue by woodanemone** [yihong0618/running_page#386]
请问想导出悦跑圈该怎么操作呀，不会这些东西

**Comment by Loongphy** [comment]
README里面写得很清楚了，见[悦跑圈](https://github.com/yihong0618/running_page/blob/master/README-CN.md#joyrun%E6%82%A6%E8%B7%91%E5%9C%88)
前提是你需要了解一点Python知识，知道怎么安装依赖，如何解决报错

**Comment by tiny656** [comment]
@woodanemone, 我也是用悦跑圈(JoyRun)，你可以参考下我仓库的[run_data_sync.yml](https://github.com/tiny656/running_page/blob/master/.github/workflows/run_data_sync.yml)，悦跑圈现在没法自动同步，所以配成了输入手机验证码，主动触发同步。

**Comment by 2tu** [comment]
以前我也一直用悦跑圈，导出一次数据后，现在改用郁金香了。他有开放平台，申请后，以后就直接通过 token 自动拉取了。大家一起支持开放数据的公司啊

**Comment by YangxyZut** [comment]
> @woodanemone, 我也是用悦跑圈(JoyRun)，你可以参考下我仓库的[run_data_sync.yml](https://github.com/tiny656/running_page/blob/master/.github/workflows/run_data_sync.yml)，悦跑圈现在没法自动同步，所以配成了输入手机验证码，主动触发同步。


您好，输完验证码显示这样 Exception: 102: Your version of App is out of date. Please update to our latest version.  怎么办呢

**Comment by 2tu** [comment]
Thanks for being in touch.I will respond as soon as possible!
