### ISSUE TITLE
Keep sync for North American users? 

### ISSUE THREAD

**Issue by yvetterowe** [yihong0618/running_page#39]
Super cool project! 

I was trying syncing my Keep data with the script but my mobile number is based in North American (area code +1), the LOGIN_API keeps returning 400 for my account...any chance you know if there's a different endpoint for North American accounts? Thanks！

**Comment by yihong0618** [comment]
you need to change your phone number to +86, to login, another user has found the problem too. You can find someone to help you change your login phone number  in China  than login. If you have WeChant you can add me, I can do some help with this, My WeChat  account is ‘zouzou19890208’
