### ISSUE TITLE
地图彩蛋版面有问题

### ISSUE THREAD

**Issue by jimrory** [yihong0618/running_page#396]
缩放地图显示城市汇总版面出错了。之前的版本好像没问题。
<img width="1566" alt="image" src="https://user-images.githubusercontent.com/13883429/230908955-522e6516-a315-4cdd-aabc-285b0ff116f4.png">

**Comment by yihong0618** [comment]
具体是什么问题呢？

**Comment by yihong0618** [comment]
@jimrory 

谢谢，我们稍后修复一下
