### ISSUE TITLE
通过github action + vercel部署完页面不会自动刷新

### ISSUE THREAD

**Issue by yvetterowe** [yihong0618/running_page#403]
* 试了多个浏览器都存在这个问题，应该不是浏览器缓存的问题...
* 手动control+r后会刷新
* 收到了很多vercel node version出错的部署错误 “Error: Node.js Version "12.x" is discontinued and must be upgraded. Please set Node.js Version to 18.x in your Project Settings to use Node.js 18.”

https://github.com/yvetterowe/running_page 这个是我fork的版本。不知道是不是gatsby还是github action那里config错了？求指点，谢谢 🙏

**Comment by yihong0618** [comment]
@yvetterowe 目前初步猜想出错原因是因为同时跑了 GitHub Page 分支（这个的 actions 同样会触发 vercel) 把这个 yml 删掉应该就好了

**Comment by yihong0618** [comment]
尝试加了 vercel.json

**Comment by yvetterowe** [comment]
Actually this is fixed in my vercel's setting - updating node.js from 12.x to 18.x re-enables vercel auto deployment and fixes the refresh issue. 
<img width="1393" alt="Screenshot 2023-06-18 at 10 55 17 PM" src="https://github.com/yihong0618/running_page/assets/5595281/3cd7ae9d-a86a-4a9c-9dc0-2f8f54f77108">

**Comment by yihong0618** [comment]
@yvetterowe cool~
