### ISSUE TITLE
跑步机上的没有GPS轨迹的记录有办法同步吗？

### ISSUE THREAD

**Issue by cuikai2015** [yihong0618/running_page#42]
`<?xml version="1.0" encoding="UTF-8"?>
<gpx creator="Garmin Connect" version="1.1"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/11.xsd"
  xmlns:ns3="http://www.garmin.com/xmlschemas/TrackPointExtension/v1"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
  <metadata>
    <link href="connect.garmin.com">
      <text>Garmin Connect</text>
    </link>
    <time>2020-09-02T12:09:40.000Z</time>
  </metadata>
  <trk>
    <name>跑步机上跑步</name>
    <type>treadmill_running</type>
    <trkseg/>
  </trk>
</gpx>
`

**Comment by yihong0618** [comment]
@cuikai2015 这个不行。gpx 是根据轨迹同步的。

**Comment by yihong0618** [comment]
@cuikai2015 理论上可以，但是没地图。如果 Garmin 有数据的话，但是比较麻烦，我之后看看吧。

**Comment by yihong0618** [comment]
@cuikai2015 
目前支持了 nike, 但我没有 garmin 在跑步机上的设备进行测试。不知道你能提供帮助么？可以私信我。
