### ISSUE TITLE
缩小地图后显示0个国家

### ISSUE THREAD

**Issue by efish2002** [yihong0618/running_page#420]
![image](https://github.com/yihong0618/running_page/assets/10509616/59c7ebfd-afec-44f1-987f-d70655a8d0e3)
我看到大家分享的一些网站，有的存在同样的问题，有的显示正常

**Comment by yihong0618** [comment]
@efish2002 你用的 app 是？

**Comment by yihong0618** [comment]
garmin-cn 么？
这块他们可能把地理位置去掉了，你可以删除 data.db
rm scripts/data.db
然后跑 python3 scripts/gpx_sync.py （可能一直需要梯子）来看看是否有这个

**Comment by efish2002** [comment]
![image](https://github.com/yihong0618/running_page/assets/10509616/e0ebd130-3bd7-4b08-9721-b523746fdf43)
感谢您的回复，跑的Action时候出现这个错误，请问如何处理

**Comment by yihong0618** [comment]
![image](https://github.com/yihong0618/running_page/assets/15976103/3d8c4c91-db93-45eb-80e5-35ffe8b2324d)
那个 sync 点开里面有报错信息。

**Comment by efish2002** [comment]
确实是账号密码在 secret设置不对 ，非常感谢

**Comment by efish2002** [comment]
![image](https://github.com/yihong0618/running_page/assets/10509616/75489b4f-e27e-4227-991e-fe4828c5e5db)
在运行Publish GitHub Pages 时出现上面的错误。
在Vercel中building时同样出现这样的错误。
![image](https://github.com/yihong0618/running_page/assets/10509616/6e77d82d-0c2c-4fba-a193-45299873fbf3)
昨天运行时没有问题，请问这是什么原因呢？

**Comment by yihong0618** [comment]
@efish2002 可以忽略，是因为 GitHub page 和 vercel 共存时候，触发 GitHub page 的 branch 更新也会再 call 一次 vercel 而这个没有太好的办法解决。

**Comment by efish2002** [comment]
这个错误影响部署吗？ 我Github page和vercel都没部署成功，我看数据都是更新了，但https://efish2002.github.io/running_page/ 仍然还是您的数据

**Comment by yihong0618** [comment]
不影响，但你需要都改成你的重新跑，或者本地跑完 push

**Comment by efish2002** [comment]
成功了，谢谢指导
