### ISSUE TITLE
对比了一下佳明的活动记录和runningpage的结果，发现几个问题

### ISSUE THREAD

**Issue by efish2002** [yihong0618/running_page#422]
1、把骑行识别成跑步
2、把多次运行合并成一次
3、把合并后的轨迹画在一起
![image](https://github.com/yihong0618/running_page/assets/10509616/fa0a2dae-ccb8-445c-a36d-103398674b84)
![image](https://github.com/yihong0618/running_page/assets/10509616/b2500cb1-6451-46a3-831b-202833533840)
![image](https://github.com/yihong0618/running_page/assets/10509616/44cb2887-40be-425e-85e3-830651ce3e5e)

**Comment by yihong0618** [comment]
1. 有命令参数 --only-run 只导出跑步数据
2. 这个可以改代码
3. 没有，只是重合了。你可以看我的主页其实不是在一起，你可以放大看

**Comment by efish2002** [comment]
使用了 --only-run ，删除了data.db，重新跑了一遍，现在好了。

**Comment by yihong0618** [comment]
好的。我先关了哈。别忘了你要自动化 actions yml 里也需要家 --only-run
