### ISSUE TITLE
你好，咕咚同步提示错误，能帮忙看下吗

### ISSUE THREAD

**Issue by vtku** [yihong0618/running_page#426]
Error: Can not execute strptime
Error: Can not execute strptime
Error: Can not execute strptime
Error: Can not execute strptime
Error: Can not execute strptime
Error: Can not execute strptime
Error: Can not execute strptime
Error: Can not execute strptime
downloading codoon 25918833 gpx
Get single run for codoon id b14d4ac4-b674-11e3-b28d-00163e0012d9
downloading codoon 20066653 gpx
Get single run for codoon id 140afc02-b5b1-11e3-acdb-00163e020001
Traceback (most recent call last):
  File "scripts/codoon_sync.py", line 607, in <module>
    tracks = j.get_old_tracks(old_tracks_ids, options.with_gpx, options.with_tcx)
  File "scripts/codoon_sync.py", line 563, in get_old_tracks
    run_data, old_gpx_ids, with_gpx, with_tcx
  File "scripts/codoon_sync.py", line 502, in parse_raw_data_to_namedtuple
    for i, p in enumerate(run_points_data):
TypeError: 'NoneType' object is not iterable
Error: Process completed with exit code 1.

**Comment by yihong0618** [comment]
python 版本？

**Comment by yihong0618** [comment]
@vtku 我们看一下。

**Comment by yihong0618** [comment]
@vtku 尝试修复了，你可以用最新代码试一试

**Comment by vtku** [comment]
您好
已重试，正常运行了。
谢谢作者更新。

继续快乐跑步ing
________________________________
发件人: yihong ***@***.***>
发送时间: 2023年6月20日 22:10
收件人: yihong0618/running_page ***@***.***>
抄送: vtku ***@***.***>; Mention ***@***.***>
主题: Re: [yihong0618/running_page] 你好，咕咚同步提示错误，能帮忙看下吗 (Issue #426)


@vtku<https://github.com/vtku> 尝试修复了，你可以用最新代码试一试

―

**Comment by yihong0618** [comment]
不客气，enjoy it

但是咕咚仅支持单设备登陆，不太友好，跑 actions 的话

**Comment by vtku** [comment]
我是华为运动运动健康，同步到咕咚，然后从咕咚里面同步出来。我平时不登录咕咚，只是想把华为的数据导出来。
您那有其他办法读取华为运动数据不？

________________________________
发件人: yihong ***@***.***>
发送时间: 2023年6月21日 14:29
收件人: yihong0618/running_page ***@***.***>
抄送: vtku ***@***.***>; Mention ***@***.***>
主题: Re: [yihong0618/running_page] 你好，咕咚同步提示错误，能帮忙看下吗 (Issue #426)


不客气，enjoy it

但是咕咚仅支持单设备登陆，不太友好，跑 actions 的话

―

**Comment by yihong0618** [comment]
没有。。。

**Comment by vtku** [comment]
谢谢回复，最后请教您个问题，地图的颜色有调整开关吗，想调整成正常颜色应该怎么处理？
[cid:6264ed38-6a84-466c-8290-f663fe2aa1d6]
________________________________
发件人: yihong ***@***.***>
发送时间: 2023年6月21日 14:36
收件人: yihong0618/running_page ***@***.***>
抄送: vtku ***@***.***>; Mention ***@***.***>
主题: Re: [yihong0618/running_page] 你好，咕咚同步提示错误，能帮忙看下吗 (Issue #426)


没有。。。

―
