### ISSUE TITLE
KEEP 导出数据不包含轨迹图

### ISSUE THREAD

**Issue by Kilerd** [yihong0618/running_page#427]
在APP上面看得到轨迹图的，但是用脚本同步到running page的时候。地图就显示 no map data for this run.

REF LINK:
Sync task: https://github.com/Kilerd/running_page/actions/runs/5324115043/jobs/9642943711
Commit data: https://github.com/Kilerd/running_page/commit/67634935339ba192a18d74ea96647ec7fd5d2c6e
website: https://kilerd.github.io/running_page/

**Comment by Kilerd** [comment]
但是在数据中却包含了城市信息 
```json
"location_country": "{'latitude': 22.57311539544229, 'longitude': 113.87190763614187, 'country': '\u4e2d\u56fd', 'nationCode': '156', 'province': '\u5e7f\u4e1c\u7701', 'city': '\u6df1\u5733\u5e02', 'cityCode': '0755', 'district': '\u5b9d\u5b89\u533a', 'districtCode': '440306'}"
```

**Comment by yihong0618** [comment]
如果是 apple watch 跑的话 keep 把轨迹图去掉了，可以搜一下 issue 这个是已知问题。
（也可能是其它原因部分 keep 的 track 没有轨迹图）

**Comment by yihong0618** [comment]
@Kilerd #155 #380

**Comment by Kilerd** [comment]
谢谢，我也搜到了相关的issue

**Comment by Kilerd** [comment]
看起来是keep自身接口的问题

**Comment by yihong0618** [comment]
cool 这个无法解决，

你可以打开那个 txt 如果没有的话它其实就是张图片。

**Comment by yihong0618** [comment]
@Kilerd 现在应该可以了，可以重新实验下，但请低调使用。

**Comment by yihong0618** [comment]
> > @Kilerd 现在应该可以了，可以重新实验下，但请低调使用。
> 
> 我已经是strava的形状了。 apple watch + strava 很好用

嗯嗯，以前的数据可以重新导出
