### ISSUE TITLE
自定义修改：前端显示问题

### ISSUE THREAD

**Issue by zpengcom** [yihong0618/running_page#436]
我已经把跑步的数据换成骑行的数据，但是部分的文字及颜色（如图）不知道在哪里可以修改，向各位大佬请教🫡
![image](https://github.com/yihong0618/running_page/assets/8217132/42612512-b78b-46bc-9331-4ff5261c3d91)

**Comment by vlin** [comment]
1. 可以考虑在以下代码处进行修改：
    1. for "Runs"
        文字：[line 62 in `<YearStat>`](https://github.com/yihong0618/running_page/blob/master/src/components/YearStat/index.jsx#L62)
        样式：[line 13 in `<Stat>`](https://github.com/yihong0618/running_page/blob/master/src/components/Stat/index.jsx#L13)

    2. for "Running"
        文字：[line 46 in `index.js`](https://github.com/yihong0618/running_page/blob/master/src/pages/index.jsx#L46)
        样式：[line 121 in `<RunMap>`](https://github.com/yihong0618/running_page/blob/master/src/components/RunMap/index.jsx#L121)

2. 自定义颜色可先添加在对应组件的 `style.module.css` 中，再加到对应标签声明的 `className` 中。
或者先在 [`variables.scss`](https://github.com/yihong0618/running_page/blob/master/src/styles/variables.scss) 中定义你所想要的颜色，并全局使用。
