### ISSUE TITLE
Keep同步到Strava里程数不一致

### ISSUE THREAD

**Issue by malinkang** [yihong0618/running_page#437]
Strava展示的里程数会比Keep少，而且不止一条数据。
![IMG_4459](https://github.com/yihong0618/running_page/assets/3365208/77b0e214-1b7a-48ef-a4ff-f907b1fb0e6b)
![IMG_63BA4EFA2EE1-1](https://github.com/yihong0618/running_page/assets/3365208/41152883-abaf-4f55-ab44-cffd803d3389)

**Comment by yihong0618** [comment]
已知问题
1. 可能会有便宜
2. keep 数据点记录不全导致的。
3. 可以搜下 issue 目前无太好的解决方案

先关了哈
