### ISSUE TITLE
[TODO] 写一个简要的介绍, 方便开发者快速理解项目, 开发或提 pr.

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#44]
用 draw.io 画一个简要的图。

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/99025531-fa0d3a80-25a3-11eb-92d0-6176fdf2746a.png)

**Comment by KermitLee** [comment]
您好，我对前端的了解不是很多，看了一下没运行起来的😂。是用Gatsbyjs来构建的吗？
![image](https://user-images.githubusercontent.com/17827496/99190685-fc89b300-27a2-11eb-83e0-5047809039bd.png)
安装测试这一块，第一行很容易理解。第二三行，是安装你的程序？和运行吗？我的环境是Windows下的wsl，Ubuntu18.04。
希望能得到解答，或者请教一下该看那些框架?十分感谢。

**Comment by yihong0618** [comment]
> 您好，我对前端的了解不是很多，看了一下没运行起来的😂。是用Gatsbyjs来构建的吗？
> ![image](https://user-images.githubusercontent.com/17827496/99190685-fc89b300-27a2-11eb-83e0-5047809039bd.png)
> 安装测试这一块，第一行很容易理解。第二三行，是安装你的程序？和运行吗？我的环境是Windows下的wsl，Ubuntu18.04。
> 希望能得到解答，或者请教一下该看那些框架?十分感谢。

@KermitLee 你能贴一下报错信息么？
第二行是安装前端需要的赖，前提得有 node 环境和装好 yarn
第三行是启动测试。

**Comment by KermitLee** [comment]
> > 您好，我对前端的了解不是很多，看了一下没运行起来的😂。是用Gatsbyjs来构建的吗？
> > ![image](https://user-images.githubusercontent.com/17827496/99190685-fc89b300-27a2-11eb-83e0-5047809039bd.png)
> > 安装测试这一块，第一行很容易理解。第二三行，是安装你的程序？和运行吗？我的环境是Windows下的wsl，Ubuntu18.04。
> > 希望能得到解答，或者请教一下该看那些框架?十分感谢。
> 
> 是 Gatsbyjs.
> @KermitLee 你能贴一下报错信息么？
> 第二行是安装前端需要的赖，前提得有 node 环境和装好 yarn
> 第三行是启动测试。

谢谢，是环境的问题，我装好node和yarn就可以了。项目本地正常运行了，很酷，感谢！😁

**Comment by yihong0618** [comment]
@KermitLee 不客气。

**Comment by OrdinarySK** [comment]
yarn install的时候 一直 会报错 imagemin-pngquant这个包的安装有问题
running_page\node_modules\imagemin-pngquant\node_modules\pngquant-bin: Command failed.
Exit code: 1
Command: node lib/install.js
Output:
‼ getaddrinfo ENOENT raw.githubusercontent.com raw.githubusercontent.com:443
  ‼ pngquant pre-build test failed
  i compiling from source

**Comment by yihong0618** [comment]
@OrdinarySK 
可能需要科学上网。

**Comment by OrdinarySK** [comment]
已经科学上网了  可以用 npm  代替  yarn的安装嘛

**Comment by yihong0618** [comment]
> 已经科学上网了 可以用 npm 代替 yarn的安装嘛

可以，但是好像会冲突，建议新建一个文件夹 clone,  然后再 npm i

**Comment by OrdinarySK** [comment]
好的  我先试试。谢谢大佬。

**Comment by OrdinarySK** [comment]
@yihong0618 我试了以下  npm 安装依赖  也是这个包有问题pngquant-bin

**Comment by yihong0618** [comment]
@OrdinarySK 
https://learnku.com/laravel/t/14957/solve-error-homevagrantcodesamplenode-modulespngquant-bin-command-failed
https://learnku.com/laravel/t/14957/solve-error-homevagrantcodesamplenode-modulespngquant-bin-command-failed
https://github.com/papandreou/node-pngquant/issues/14

试试这几个？

**Comment by yihong0618** [comment]
@OrdinarySK 或者你可以换个环境，再或者全部用 Actions 完成

**Comment by OrdinarySK** [comment]
@yihong0618 按照你给的 那几个 还是没有解决 你说的换个环境是指什么意思啊，我没有太明白

**Comment by yihong0618** [comment]
@OrdinarySK  比如说你用 windows 可以用 linux 试试。

**Comment by OrdinarySK** [comment]
@yihong0618 我这里的linux环境  不能上网

**Comment by OrdinarySK** [comment]
@yihong0618 我觉得或者找成功下载的  拷贝以下依赖包

**Comment by OrdinarySK** [comment]
想问以下  利用 vercel  部署的话  是把代码复制一份到自己的新建的库，然后导入到vercel里面  让他部署是吗。

**Comment by yihong0618** [comment]
> 想问以下 利用 vercel 部署的话 是把代码复制一份到自己的新建的库，然后导入到vercel里面 让他部署是吗。

导入之后就什么都不用管了。

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/100429929-0ed3ed00-30d1-11eb-8c3d-89063624cf9e.png)

**Comment by AlexHaijiaZhu** [comment]
希望有一天能做成hexo插件～

**Comment by yihong0618** [comment]
@AlexHaijiaZhu 
我不太会，不过理论可以子域名 link 进去

**Comment by code-moritz** [comment]
能做成docker image吗？ 这样部署方便很多。

**Comment by yihong0618** [comment]
@code-moritz 倒是可以，不过这个本质流程还是 GitHub Actions, 用 vercel 直接部署。
你有兴趣可以直接提一个 docker file~ 
Always welcome.

**Comment by youxiaodao** [comment]
科学上网的问题，可以通过下面的方式解决
1. 安装cnpm；2. 删除目录下的node_modules；3. 运行cnpm install； 4. yarn develop

**Comment by yihong0618** [comment]
@youxiaodao Thanks

**Comment by yihong0618** [comment]
![image](https://user-images.githubusercontent.com/15976103/102441412-2f9ebb00-405d-11eb-9dc7-1a8951748895.png)

**Comment by yihong0618** [comment]
Change js -> json
![image](https://user-images.githubusercontent.com/15976103/103496454-4294f600-4e79-11eb-9bd6-8eea7a07ddff.png)
