### ISSUE TITLE
python3 scripts/strava_sync.py 同步不了strava数据

### ISSUE THREAD

**Issue by leosj** [yihong0618/running_page#443]
日志是这样的

Access ok
Start syncing

**Comment by yihong0618** [comment]
@leosj 这个日志说明同步了

我们是用上一个日期找下一个日期的，所以可能不对

你可以删掉 scripts/data.db 或者备份，再重新跑一下。

**Comment by leosj** [comment]
@yihong0618 删掉又再执行一次，还是这个日志，然后运行 yarn develop， 页面是空的，没有数据，大佬求指导，好人一生平安

**Comment by yihong0618** [comment]
你strava里有跑步数据么？确认下如果是qixing，需要改 type

**Comment by leosj** [comment]
@yihong0618 是的，大佬，只有骑行数据，type没在文档上看到在哪里改

**Comment by yihong0618** [comment]
@leosj 拉一下最新代码，然后删除 srcipts/data.db 再跑一遍试试

**Comment by leosj** [comment]
@yihong0618 最新代码日志显示

Access ok
Start syncing
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++%

数据库中感觉也有数据了，接下来执行
python3 scripts/gen_svg.py --from-db --title "${{ env.TITLE }}" --type github --athlete "${{ env.ATHLETE }}" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5

提示
zsh: bad substitution

**Comment by yihong0618** [comment]
> @yihong0618 最新代码日志显示
> 
> Access ok Start syncing +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++%
> 
> 数据库中感觉也有数据了，接下来执行 python3 scripts/gen_svg.py --from-db --title "${{ env.TITLE }}" --type github --athlete "${{ env.ATHLETE }}" --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5
> 
> 提示 zsh: bad substitution

格式不对，应该有多余的符号。手敲试试

**Comment by leosj** [comment]
@yihong0618 把双引号改成单引号，感觉可以了，日志显示

All tracks: 137
After filter tracks: 133

但是访问 http://localhost:8000/，还是没有数据，怎么弄呢，感恩大佬

**Comment by yihong0618** [comment]
没有数据显示的是什么？

**Comment by leosj** [comment]
@yihong0618 我用 App 记录自己跑步 0 年了，下面列表展示的是 undefined 的数据

**Comment by yihong0618** [comment]
查看 activities.json 看看里面的内容，贴一下

**Comment by leosj** [comment]
@yihong0618 是空的 []

**Comment by yihong0618** [comment]
@leosj 试着修复了，拉下最新代码再跑一遍

**Comment by leosj** [comment]
@yihong0618 我试试

**Comment by yihong0618** [comment]
@leosj 没问题我先关了，欢迎随时打开。
