### ISSUE TITLE
strava 导出的 json 里不包含地图轨迹信息

### ISSUE THREAD

**Issue by Moolan-d** [yihong0618/running_page#445]
[
  {
      "run_id":9392177451,
      "name":"\u508d\u665a\u8dd1\u6b65",
      "distance":403.7,
      "moving_time":"0:03:16",
      "type":"Run",
      "start_date":"2023-07-05 10:47:31+00:00",
      "start_date_local":"2023-07-05 18:47:31",
      "location_country":null,
      "summary_polyline":"",
      "average_heartrate":144.7,
      "average_speed":2.06,
      "streak":1
  }
]

大佬你好，我昨天使用 Starve （ Apple Watch ）尝试跑了一下  ， 执行脚本命令发现除了地图信息其他信息都跑通了，请问是因为试用版的 strava 所以导出数据不包含   "location_country":null, "summary_polyline":"", 信息嘛

**Comment by yihong0618** [comment]
不会，理论上是有的，你的 starva 里能看到信息么？

**Comment by Moolan-d** [comment]
<img width="587" alt="Screenshot 2023-07-06 at 11 18 58" src="https://github.com/yihong0618/running_page/assets/20973831/95e6238a-5f4f-41f9-a56d-ba5919df995d">

我看是有的

**Comment by yihong0618** [comment]
可能跑的比较短被 strava 隐藏了，去strava 设置里把隐私隐藏取消，然后再重新跑一遍

**Comment by Moolan-d** [comment]
好的 我后面再试试 感谢！
