### ISSUE TITLE
拿掉 gatsby

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#458]
开始我们考虑的是换成 next.js 但 @frostming 提过既然我们是单页应用，何以完全不用这么重的框架

需要考虑的问题：

- 拿掉后对 vercel 友好么？
- 如果需要选个小框架的话选什么好呢？
- 我们目前 svg 读取的问题。

好处是：

- 更易用
- 性能应该会提高一些
- 不用考虑 gatsby 版本的问题

@vlin @ben-29 @agassiyzh @shaonianche 你们觉得呢？

**Comment by vlin** [comment]
> * 拿掉后对 vercel 友好么？
> * 如果需要选个小框架的话选什么好呢？

A: 看到现有版本并不需要考虑 SEO ，那么 NEXT.js 也可以不用，毕竟现有版本中已生成了 json 文件，可以从浏览器端直接请求 json。除了数据的采集使用 python，理论上将可以是个只需要 React 的纯前端 web 站点，vercel 对此天生友好😁

> * 我们目前 svg 读取的问题。

A: 如果在此项目 2.0 版本考虑使用 create-react-app 初始化应用，它便支持将 svg 直接导入为组件（[文档](https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs)）。或者可以考虑使用 react-svg 渲染 svg。不知我对这点问题有没理解错，还请纠正。

性能方面：由于 activities.json 文件的大小随着运动次数增加而增加，从浏览器端加载 json 文件将会变越来越慢。
1. 当前 Total 视图中地图上渲染出所有的运动轨迹，不知 2.0 版本对这个功能是否做一定的取舍？这样有机会避免一次性把个人完整运动数据都加载到浏览器端而影响性能。
2. 可否考虑 python 从设备同步完数据后，直接生成各年份的统计数据、运动明细？减少 react 端每次打开页面都要重复计算，同时有利于浏览器端渲染速度的提升。
    例如：summary.json、2012.json、2013.json .... 2023.json

以上请指正~

**Comment by yihong0618** [comment]
> > * 拿掉后对 vercel 友好么？
> > * 如果需要选个小框架的话选什么好呢？
> 
> A: 看到现有版本并不需要考虑 SEO ，那么 NEXT.js 也可以不用，毕竟现有版本中已生成了 json 文件，可以从浏览器端直接请求 json。除了数据的采集使用 python，理论上将可以是个只需要 React 的纯前端 web 站点，vercel 对此天生友好😁
> 
> > * 我们目前 svg 读取的问题。
> 
> A: 如果在此项目 2.0 版本考虑使用 create-react-app 初始化应用，它便支持将 svg 直接导入为组件（[文档](https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs)）。或者可以考虑使用 react-svg 渲染 svg。不知我对这点问题有没理解错，还请纠正。
> 
> 性能方面：由于 activities.json 文件的大小随着运动次数增加而增加，从浏览器端加载 json 文件将会变越来越慢。
> 
> 1. 当前 Total 视图中地图上渲染出所有的运动轨迹，不知 2.0 版本对这个功能是否做一定的取舍？这样有机会避免一次性把个人完整运动数据都加载到浏览器端而影响性能。
> 2. 可否考虑 python 从设备同步完数据后，直接生成各年份的统计数据、运动明细？减少 react 端每次打开页面都要重复计算，同时有利于浏览器端渲染速度的提升。
>    例如：summary.json、2012.json、2013.json .... 2023.json
> 
> 以上请指正~

学习了，同意前辈的方式，我研究下～

**Comment by agassiyzh** [comment]
> > * 拿掉后对 vercel 友好么？
> > * 如果需要选个小框架的话选什么好呢？
> 
> A: 看到现有版本并不需要考虑 SEO ，那么 NEXT.js 也可以不用，毕竟现有版本中已生成了 json 文件，可以从浏览器端直接请求 json。除了数据的采集使用 python，理论上将可以是个只需要 React 的纯前端 web 站点，vercel 对此天生友好😁
> 
> > * 我们目前 svg 读取的问题。
> 
> A: 如果在此项目 2.0 版本考虑使用 create-react-app 初始化应用，它便支持将 svg 直接导入为组件（[文档](https://create-react-app.dev/docs/adding-images-fonts-and-files/#adding-svgs)）。或者可以考虑使用 react-svg 渲染 svg。不知我对这点问题有没理解错，还请纠正。
> 
> 性能方面：由于 activities.json 文件的大小随着运动次数增加而增加，从浏览器端加载 json 文件将会变越来越慢。
> 
> 1. 当前 Total 视图中地图上渲染出所有的运动轨迹，不知 2.0 版本对这个功能是否做一定的取舍？这样有机会避免一次性把个人完整运动数据都加载到浏览器端而影响性能。
> 2. 可否考虑 python 从设备同步完数据后，直接生成各年份的统计数据、运动明细？减少 react 端每次打开页面都要重复计算，同时有利于浏览器端渲染速度的提升。
>    例如：summary.json、2012.json、2013.json .... 2023.json
> 
> 以上请指正~

棒，也觉得`activities.json`需要拆分

**Comment by ben-29** [comment]
@yihong0618 我不熟前端，你们决定吧 :)

**Comment by frostming** [comment]
我也是个业余，原则是把重的操作放到build time去执行，那么是不是可以上RSC?

**Comment by shaonianche** [comment]
> 我也是个业余，原则是把重的操作放到build time去执行，那么是不是可以上RSC?

https://github.com/reactjs/rfcs/blob/main/text/0188-server-components.md RSC是指的这个吗？

**Comment by yihong0618** [comment]
Done will merge to master this week
