### ISSUE TITLE
Keep's Data missing gps if it was create by Apple watch

### ISSUE THREAD

**Issue by zhaohongxuan** [yihong0618/running_page#46]
As the image blow
![image](https://user-images.githubusercontent.com/8613196/99878813-fbdd9a80-2c42-11eb-8faf-d715c1ef98e3.png)

**Comment by yihong0618** [comment]
Yes keep drop the geo data...

**Comment by zhaohongxuan** [comment]
I use keep app in Apple watch.
After update from upstream code,But It still does't work😭
![image](https://user-images.githubusercontent.com/8613196/99880261-672c6a00-2c4d-11eb-9afd-4e84ee0ef698.png)

**Comment by zhaohongxuan** [comment]
![image](https://user-images.githubusercontent.com/8613196/99880579-436a2380-2c4f-11eb-8d91-65ac819de30e.png)

**Comment by zhaohongxuan** [comment]
I try to  clean gpx_out folder and clean data.db, After regenerate still can't work 
![image](https://user-images.githubusercontent.com/8613196/99881868-40733100-2c57-11eb-9727-b18a66698b82.png)

**Comment by yihong0618** [comment]
@zhaohongxuan I will use Apple watch app keep to run for testing tonight～
@yvetterowe can you help me with this issue？

**Comment by yvetterowe** [comment]
> @zhaohongxuan I will use Apple watch app keep to run for testing tonight～
> @yvetterowe can you help me with this issue？

@zhaohongxuan could you patch this https://github.com/yvetterowe/running_page/pull/2/commits/da88f51314119dba5681c515f081313aa48b4687 to keep_sync.py script and see what are the `genre` and `source` for your keep record? For my case all my records have `source = Keep` while `genre = KeepApp` or `genre = AppleWatch`. I could be missing some edge cases!

**Comment by zhaohongxuan** [comment]
@yvetterowe 
![image](https://user-images.githubusercontent.com/8613196/99892067-bc976400-2cab-11eb-9bf5-a6011d2f4b16.png)
vendor info is correct ,but the rawDataURL is None and I don't know why

**Comment by yvetterowe** [comment]
> @yvetterowe
> ![image](https://user-images.githubusercontent.com/8613196/99892067-bc976400-2cab-11eb-9bf5-a6011d2f4b16.png)
> vendor info is correct ,but the rawDataURL is None and I don't know why

That seems to be a Keep API issue to me...I've also lost a lot of runs from Keep and that's why I started using Strava as source of truth 😂

**Comment by zhaohongxuan** [comment]
so sad 😭

**Comment by yihong0618** [comment]
@zhaohongxuan 解决了，请低调使用

**Comment by zhaohongxuan** [comment]
> @zhaohongxuan 解决了，请低调使用

yihong哥牛逼（破音）🍻
