### ISSUE TITLE
garmin-sync脚本一直在刷这个

### ISSUE THREAD

**Issue by naosense** [yihong0618/running_page#467]
<img width="721" alt="image" src="https://github.com/yihong0618/running_page/assets/2225426/ead56674-410e-4984-9136-34d77e1cf9ec">

这是啥意思？

**Comment by yihong0618** [comment]
去掉 proxy 重新跑试试

**Comment by naosense** [comment]
没啥改观，我又看了下报错，还有一些这种提示

<img width="811" alt="image" src="https://github.com/yihong0618/running_page/assets/2225426/1bb18e47-d6cf-4ffe-8dff-b920726ce6af">

**Comment by yihong0618** [comment]
这个报错是网络问题。后面的报错是跑步机就是没有路径信息的

**Comment by naosense** [comment]
了解，那gpx是下载完了吗？我看已经下载了200多个，里面有些是正常的有些是空的，那为啥不能生成svg呢？

**Comment by yihong0618** [comment]
理论上可以，有容错，没生成 svg 是因为没走到那一步，你停掉之后参考 README 手动跑 gen_svg 可以，如果没生成可以删掉 data.db 用 gpx_sync 生成

**Comment by naosense** [comment]
好像不行，运行gpx_sync，报错信息如下，倒是也生成data.db了

<img width="819" alt="image" src="https://github.com/yihong0618/running_page/assets/2225426/258a328e-cd70-4f6a-bd7b-05c072c0d894">

但是，运行gen_svg没有生成svg，提示这个

<img width="1497" alt="image" src="https://github.com/yihong0618/running_page/assets/2225426/42aca8cf-67b1-4db4-bc6e-6d3e19d4eaac">

但是gpx里有正常的，如下

<img width="730" alt="image" src="https://github.com/yihong0618/running_page/assets/2225426/0ae75e31-1761-4753-ba68-ad2a968f418a">

**Comment by yihong0618** [comment]
我晚上帮你看看

**Comment by ttkltll** [comment]
我今天也碰到这样的问题

**Comment by yihong0618** [comment]
> 我今天也碰到这样的问题

是 garmin 还是 garmin-cn

**Comment by naosense** [comment]
Cn

**Comment by ttkltll** [comment]
> > 我今天也碰到这样的问题
> 
> 是 garmin 还是 garmin-cn

cn

**Comment by yihong0618** [comment]
看起来是风控加强了。。。

**Comment by yihong0618** [comment]
@ben-29 我们有空一起看一下

**Comment by ben-29** [comment]
@naosense 可以提供一个报错的gpx吗？

**Comment by naosense** [comment]
> @naosense 可以提供一个报错的gpx吗？

```
<?xml version="1.0" encoding="UTF-8"?>
<gpx creator="Garmin Connect" version="1.1"
  xsi:schemaLocation="http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/11.xsd"
  xmlns:ns3="http://www.garmin.com/xmlschemas/TrackPointExtension/v1"
  xmlns="http://www.topografix.com/GPX/1/1"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns2="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
  <metadata>
    <link href="connect.garmin.com">
      <text>Garmin Connect</text>
    </link>
    <time>2023-03-29T11:31:01.000Z</time>
  </metadata>
  <trk>
    <name>跑步机上跑步</name>
    <type>treadmill_running</type>
    <trkseg/>
  </trk>
</gpx>
```

**Comment by ben-29** [comment]
@naosense 这个不行，要非跑步机有轨迹的

**Comment by naosense** [comment]
[56185598.gpx.zip](https://github.com/yihong0618/running_page/files/12268415/56185598.gpx.zip)
试试这个

**Comment by ben-29** [comment]
gpx没问题，我试了能导入，

> 但是，运行gen_svg没有生成svg，提示这个
> 
> <img alt="image" width="1497" src="https://user-images.githubusercontent.com/2225426/258557029-42aca8cf-67b1-4db4-bc6e-6d3e19d4eaac.png">
你运行 gen_svg 的完整命令发一下，怀疑是 min-distance 没有改，改成 3 应该就能生成了

**Comment by naosense** [comment]
完整命令应该是这个

```
python3 scripts/gen_svg.py --from-db  --type github  --special-distance 10 --special-distance2 20 --special-
color yellow --special-color2 red --output assets/github.svg --use-localtime
```

**Comment by ben-29** [comment]
尝试一下步骤：
1. 删除 
   - workouts_page/imporedt.json
   - workouts_page/scripts/data.db
1. 运行 gpx_sync
2. 运行 gen_svg

**Comment by naosense** [comment]
> 尝试一下步骤：
> 1. 删除 
>    - workouts_page/imporedt.json
>    - workouts_page/scripts/data.db
> 1. 运行 gpx_sync
> 2. 运行 gen_svg

好的多谢，我试一下

**Comment by naosense** [comment]
@ben-29 还是不行，报错和之前差不多，上面的解决步骤每一步的现象：

1. workouts_page压根没有
2. 运行 gpx_sync
     <img width="808" alt="image" src="https://github.com/yihong0618/running_page/assets/2225426/f3ea4009-f2ae-40d1-bb23-aff8fa90e77e">
3. 运行 gen_svg
    <img width="1534" alt="image" src="https://github.com/yihong0618/running_page/assets/2225426/b31a70fc-dabe-4f02-98f2-4633dd3349be">

**Comment by ben-29** [comment]
@naosense 不好意思，写错了


1. 删除改为running_page, 也就是项目目录

    - running_page/imported.json
    - running_page/scripts/data.db
1. 运行 gpx_sync
1. 运行 gen_svg

**Comment by naosense** [comment]
不行，报错和上面一样，我将gpx全部打包了，你可以试试。

[GPX_OUT.zip](https://github.com/yihong0618/running_page/files/12292006/GPX_OUT.zip)

**Comment by ben-29** [comment]
我这边跑没问题。
1. 你确定 gpx_sync 运行完了，正常结束了吗？
2. 试下把 GPX_OUT 里体积小于1KB的文件删掉再运行 gpx_sync 呢
3. 确认 data.db 存在，用软件打开来看看是否有记录，或者把  scripts/data.db 传上来看看
![image](https://github.com/yihong0618/running_page/assets/6956444/a7c9f12c-2a5c-45b8-9ae1-54831b267b54)

**Comment by naosense** [comment]
> 我这边跑没问题。
> 1. 你确定 gpx_sync 运行完了，正常结束了吗？
> 2. 试下把 GPX_OUT 里体积小于1KB的文件删掉再运行 gpx_sync 呢
> 3. 确认 data.db 存在，用软件打开来看看是否有记录，或者把  scripts/data.db 传上来看看
> ![image](https://github.com/yihong0618/running_page/assets/6956444/a7c9f12c-2a5c-45b8-9ae1-54831b267b54)
> 

1. 第一步没运行完，它一直报limit…那个错我就把它终结了，你是运行多久第一步结束的

**Comment by naosense** [comment]
> 😓 你得等它运行完。。。得十几分钟吧

可以了，太不容易了，感谢感谢🙏。顺便问下，为啥gen_svg的type不支持heatmap和calendar呀？

**Comment by yihong0618** [comment]
支持啊。。。（参考 README 和 Actions 里的 yml
+++++ limit +++++ 这个是你懂的网络问题。

**Comment by naosense** [comment]
> 支持啊。。。（参考 README 和 Actions 里的 yml
> +++++ limit +++++ 这个是你懂的网络问题。

昨天我是用的gen_svg，我试了下heatmap类型，命令行提示我只支持github、grid、circular三种类型，莫非我哪里操作的不对？

**Comment by yihong0618** [comment]
heatmap 目前不支持。。。

**Comment by naosense** [comment]
噢，我看[GpxTrackPoster](https://github.com/flopp/GpxTrackPoster)支持，我运行了下他这个软件，报错，running_page不支持heatmap的愿意是啥呢？

**Comment by yihong0618** [comment]
因为没用上啊。。。我们地图里不是用 mapbox 做 heatmap 么

**Comment by naosense** [comment]
感谢🙏
