### ISSUE TITLE
现在 strava 会把骑行数据当成跑步数据

### ISSUE THREAD

**Issue by Bpazy** [yihong0618/running_page#470]
看到一个类似的，不过是佳明: https://github.com/yihong0618/running_page/issues/125

之前是不会有这种情况的，昨天 sync upstream 之后就有问题了，请问是新增了什么配置吗？

**Comment by yihong0618** [comment]
现在 strava 包含骑行了。。。我今天加个参数。。。

**Comment by yihong0618** [comment]
@Bpazy 你有兴趣修复一下么？接口和 garmin 一致就行 --only-run

**Comment by Bpazy** [comment]
> @Bpazy 你有兴趣修复一下么？接口和 garmin 一致就行 --only-run

没问题，我今天搞一下

**Comment by Bpazy** [comment]
@yihong0618 我看脚本已经支持了呀😂  24563b80

**Comment by yihong0618** [comment]
惊了！敬仰下我自己！我都忘了！

**Comment by Bpazy** [comment]
加了个注释，方便你我他: https://github.com/yihong0618/running_page/pull/471
