### ISSUE TITLE
生成数据展示 SVG 设置语言不生效

### ISSUE THREAD

**Issue by Keystion** [yihong0618/running_page#473]
## 问题描述

基础环境：
- macOS Ventura 13.4.1（M1 Pro）
- Python 3.11.3

尝试通过命令，添加 `--language` 参数生成中文的展示图：

```bash
python3 scripts/gen_svg.py --from-db --title Key --type github --athlete Keystion --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5 --language Chinese
```

命令没有报错，但是生成的图片还是英文的。查看代码：

https://github.com/yihong0618/running_page/blob/6f718af3ca2a4bf29f68be7dfcbfcf02d22a8d2d/scripts/gpxtrackposter/poster.py#L60C32-L60C32

找到这行，应该可以设置语言：

![CleanShot 2023-08-22 at 20 50 02](https://github.com/yihong0618/running_page/assets/2408287/eead5241-acc0-4cc4-b329-497a5f7018fa)

重新执行命令，进入异常代码逻，报错：

```bash
Cannot set locale to "zh-CN": unsupported locale setting
```

## 解决问题

搜索了一波，找到这个问题：https://stackoverflow.com/questions/14547631/python-locale-error-unsupported-locale-setting

通过修改 scripts/gpxtrackposter/poster.py 文件的，第 66 行代码即可修复。

```python
63.   def set_language(self, language):
64.        if language:
65.            try:
66.                locale.setlocale(locale.LC_ALL, f"{language}.utf8") # utf8 -> UTF-8
67.            except locale.Error as e:
68.                print(f'Cannot set locale to "{language}": {e}')
69.                language = None
70.                pass
```

`locale.setlocale(locale.LC_ALL, f"{language}.UTF-8")`

由于不懂Python，不确定是否跟平台有关系，就不提PR了。

**Comment by yihong0618** [comment]
好的

**Comment by arthurfsy2** [comment]
```PYTHON
python run_page/gen_svg.py --from-db --title "超过100公里的活动" --type grid --athlete "Feng Siyuan" --output assets/grid_100.svg --special-color yellow --special-color2 red --special-distance 120 --special-distance2 140 --use-localtime --min-distance 100 --language zh-CN 
```
我在本地单独运行，似乎生成的grid_100.svg还是英文
