### ISSUE TITLE
無法更改Site Metadata資料

### ISSUE THREAD

**Issue by QWERT1984** [yihong0618/running_page#479]
你好，我在Ubuntu 上Git clone相關的git之後 安裝了該running page的docker

配置完後運行成功進入

但是修改gatsby-config.js 裏面的Site Metadata後無法更新網頁

網頁上的超連結依然是yihong的網站

網站標題/圖標等也無法更改

已經嘗試整個image 和container remove後再次用新的gatsby-config.js develop

也是同樣的結果

**Comment by QWERT1984** [comment]
無意中發現需要移除相關的images和container 

然後再重新build 一個就解決了

謝謝

**Comment by yihong0618** [comment]
好的，我先关了哈
