### ISSUE TITLE
关于悦跑圈的支持

### ISSUE THREAD

**Issue by faithbro** [yihong0618/running_page#48]
之前看TODO还有悦跑圈，现在作者是不打算支持了吗？

**Comment by yihong0618** [comment]
@faithbro 
Sorry，悦跑圈一些机制改了，我之前研究的不太好用了。我在努力，但是不保证了。
抱歉。

**Comment by faithbro** [comment]
> @faithbro
> Sorry，悦跑圈一些机制改了，我之前研究的不太好用了。我在努力，但是不保证了。
> 抱歉。

理解，谢谢解答。
也就是现在没有途径可以导出个人数据吗？想打算换个APP

**Comment by yihong0618** [comment]
@faithbro 目前没有特别好的办法。国内软件数据这块特别蛋疼。。。

**Comment by faithbro** [comment]
> @faithbro 目前没有特别好的办法。国内软件数据这块特别蛋疼。。。

好的，谢谢~

**Comment by yihong0618** [comment]
@faithbro 悦跑圈支持了。

**Comment by faithbro** [comment]
> @faithbro 悦跑圈支持了。

看到了，谢谢~
这就部署看看效果

**Comment by yihong0618** [comment]
> > @faithbro 悦跑圈支持了。
> 
> 看到了，谢谢~
> 这就部署看看效果

好的，有问题或者建议可以在这个 issue 下留言。
