### ISSUE TITLE
获取keep数据错误

### ISSUE THREAD

**Issue by Epiphany-git** [yihong0618/running_page#484]
yihong你好！
部署这个项目快两年了，一直运行正常。但这周突然发现，最近两次跑步的keep数据没有更新上来。
本地执行python scripts/keep_sync.py **** ***--with-gpx命令后，报出下面的错误：

2 new keep runs to generate
parsing keep id 59d47317e666861941f1cf50_9223370343116489210_rn
Something wrong paring keep id 59d47317e666861941f1cf50_9223370343116489210_rnInvalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4
parsing keep id 59d47317e666861941f1cf50_9223370343501096357_rn
Something wrong paring keep id 59d47317e666861941f1cf50_9223370343501096357_rnInvalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4
No tracks found.

请问这是怎么回事呢？

**Comment by yihong0618** [comment]
你好
能从新拉一个目录，然后本地试试以前的能不能跑么？
---
我想确认下是都不好用还是只有这两次不好用

**Comment by Epiphany-git** [comment]
拉过新的代码，本地运行能load以前的keep数据，也能正常展示以前的数据，但缺失最近两次的数据，且会报上面的错误

**Comment by malinkang** [comment]
看了下是拉rawDataURL的时候报错了，{"error":"permission denied"}，卧槽，赶紧换软件了，不能用keep了，越来越恶心。

**Comment by malinkang** [comment]
试了下用session来拉也会报错。

**Comment by malinkang** [comment]
提供个链接https://ot-sport-log.keepcdn.com/ot-sport-log/ot/9VPdohFqV94ULxbnE8B08IdNm_85tefS6bHpi7gmyws3sBLujNdFE2Oz2tGArfKn.txt

**Comment by yihong0618** [comment]
@malinkang 我试了下之前的数据还好用啊，新的不可以了？

**Comment by yihong0618** [comment]
@malinkang @Epiphany-git 你们是否选择了隐藏路径这类的。

**Comment by malinkang** [comment]
嗯 最近的数据才这样，我没做任何设置的操作，换软件了。越来越坑了。

**Comment by malinkang** [comment]
#155 感觉跟这个差不多

**Comment by malinkang** [comment]
准备用strava了，keep不能生成gpx的直接调用stravalib.client.Client.create_activity来传了。

**Comment by yihong0618** [comment]
@malinkang 直接可以用代码里的 xxx_to_strava

**Comment by yihong0618** [comment]
@malinkang @Epiphany-git 

我下午改了一下，这块用 session 下了，如果还是不行就无能为力了

**Comment by malinkang** [comment]
> @malinkang 直接可以用代码里的 xxx_to_strava

嗯，我用的是gpx_to_strava，但是有问题的keep数据无法生成gpx，所以直接调用这个传了，不过会不显示轨迹。

**Comment by jujimeizuo** [comment]
> > @malinkang 直接可以用代码里的 xxx_to_strava
> 
> 嗯，我用的是gpx_to_strava，但是有问题的keep数据无法生成gpx，所以直接调用这个传了，不过会不显示轨迹。

直接调用的话，有问题的keep数据不还是没有生成gpx吗，还是不管这些数据，换strava了

**Comment by malinkang** [comment]
> > > @malinkang 直接可以用代码里的 xxx_to_strava
> > 
> > 
> > 嗯，我用的是gpx_to_strava，但是有问题的keep数据无法生成gpx，所以直接调用这个传了，不过会不显示轨迹。
> 
> 直接调用的话，有问题的keep数据不还是没有生成gpx吗，还是不管这些数据，换strava了

嗯这些数据我是直接拿开始时间 距离直接传strava了，不要gpx数据了。

**Comment by Epiphany-git** [comment]
换成codoon app了，但codoon的数据产生了整体偏移。

将const.js里的NEED_FIX_MAP改为false后，codoon的数据被纠正，但之前的keep数据又产生了偏移。

如何同时纠正codoon和keep的数据？

**Comment by yihong0618** [comment]
。。。换成 garmin 或者 郁金香或者 strava...

**Comment by bobwng** [comment]
我这里有同样的问题。最新10几条数据parse不了。不会真要换软件了吧：

> 13 new keep runs to generate
parsing keep id 5fdf6be0952174268eda0db7_9223370341568638407_rn
Something wrong paring keep id 5fdf6be0952174268eda0db7_9223370341568638407_rnInvalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4
parsing keep id 5fdf6be0952174268eda0db7_9223370341809839007_rn
Something wrong paring keep id 5fdf6be0952174268eda0db7_9223370341809839007_rnInvalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4
parsing keep id 5fdf6be0952174268eda0db7_9223370341981541507_rn

**Comment by yihong0618** [comment]
> 我这里有同样的问题。最新10几条数据parse不了。不会真要换软件了吧：
> 
> > 13 new keep runs to generate
> > parsing keep id 5fdf6be0952174268eda0db7_9223370341568638407_rn
> > Something wrong paring keep id 5fdf6be0952174268eda0db7_9223370341568638407_rnInvalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4
> > parsing keep id 5fdf6be0952174268eda0db7_9223370341809839007_rn
> > Something wrong paring keep id 5fdf6be0952174268eda0db7_9223370341809839007_rnInvalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4
> > parsing keep id 5fdf6be0952174268eda0db7_9223370341981541507_rn

可能是设置隐私之类的问题？我不确实。这俩月才开始出现这问题。

可以 tg 私信我们我看看

**Comment by liyiming1** [comment]
我这里整个8月份的数据都导不出来，decode_runmap_data的数据是{"error":"permission denied"}

**Comment by yihong0618** [comment]
看起来是 keep 给封了

**Comment by bobwng** [comment]
> 我这里整个8月份的数据都导不出来，decode_runmap_data的数据是{"error":"permission denied"}

一样的错误信息。仔细看了一下我的数据，8.17和之前的数据还可以导出来，8.17后的就不行了。但是，从8月份开始，就没有地图（轨迹）数据了。

**Comment by yihong0618** [comment]
> > 我这里整个8月份的数据都导不出来，decode_runmap_data的数据是{"error":"permission denied"}
> 
> 一样的错误信息。仔细看了一下我的数据，8.17和之前的数据还可以导出来，8.17后的就不行了。但是，从8月份开始，就没有地图（轨迹）数据了。

8.17 keep 有什么特别的更新么

**Comment by F4ria** [comment]
Android版本（7.59.0），8月4号及之前的跑步记录可以正常导出，5、6号没跑，7号跑了但是不能导出了

抓包看了下，请求接口是：
```
GET /pd/v3/runninglog/aaaa_9223370346129309063_rn?source=DETAIL_PAGE HTTP/1.1
Host: api.gotokeep.com
```
8月4号及之前的跑步记录返回的`rawDataURL`长这样：
```
"rawDataURL":"https://static1.keepcdn.com/txt/2023/08/04/22/13/832beb6db53410b2aaaa.txt"
```
这个接口没有鉴权；

8月4号之后返回的`rawDataURL`长这样：
```
"rawDataURL":"https://ot-sport-log.keepcdn.com/ot-sport-log/ot/fdf43b2a9d8d90d24e802ca49356df21_-1x-1.txt"
```
接口变了，新的接口需要鉴权才可以访问。

**Comment by yihong0618** [comment]
> port-log.keepcdn.com/ot-sport-l

能给我一个鉴权后的 curl 么？

**Comment by F4ria** [comment]
> > port-log.keepcdn.com/ot-sport-l
> 
> 能给我一个鉴权后的 curl 么？

可以，已发邮件。

**Comment by yihong0618** [comment]
研究了一个小时，结论是应该堵死了。很难获取到数据

**Comment by F4ria** [comment]
#496 

跑步记录导出了，不过没有gpx数据。

放弃keep了。

**Comment by bobwng** [comment]
打算换哪个软件啊？我还买了它的硬件，换了就不能用了😂

**Comment by F4ria** [comment]
> 打算换哪个软件啊？我还买了它的硬件，换了就不能用了😂
> 

还在试，用Strava跑了两次，第1次跑马路8公里相比悦跑圈和keep少了600米，第2次在小区跑5公里相比悦跑圈和keep少了1公里。

昨晚刚安装了郁金香运动，还没试，不过就注册然后进去随便点点，程序已经奔溃两次了。

不关心跑步地图的话，keep凑合着还能用。

**Comment by bobwng** [comment]
你是已经修改好代码可以导出了吗？麻烦共享一下patch或者发一下PR？

关于地图，我发现很不稳定，有的记录有地图，有的记录没有，还不知道规律是啥。

**Comment by yihong0618** [comment]
不可以。。。更改了权限。现在新的无法下载地图了

**Comment by yihong0618** [comment]
又研究了一下午，无论从 geoPoints 和 rawDataURL 目前都无法突破

**Comment by yihong0618** [comment]
@malinkang @F4ria @Epiphany-git 
@ben-29 解决了，但是因为用了 key 不会有更新说明，请低调使用

**Comment by QHQIII** [comment]
keep再次出现了这个问题，至少11月12日后的数据导出报错Invalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4

**Comment by yihong0618** [comment]
。。。。。
@ben-29 惊了。

**Comment by ben-29** [comment]
@QHQIII 试了下，不管是老数据，还是今天的新轨迹。都没有遇到这个这个错误。
试下更新代码，再跑试试

> keep再次出现了这个问题，至少11月12日后的数据导出报错Invalid base64-encoded string: number of data characters (21) cannot be 1 more than a multiple of 4

**Comment by QHQIII** [comment]
> @QHQIII 试了下，不管是老数据，还是今天的新轨迹。都没有遇到这个这个错误。 试下更新代码，再跑试试
> 
> > keep再次出现了这个问题，至少11月12日后的数据导出报错Invalid base64-encoded string: number of data characters(字符) (21) cannot be 1 more than a multiple(倍数) of 4
感谢说明

**Comment by arthurfsy2** [comment]
每次灵机一动上yihong的项目看都有惊喜！去年我也是遇到了这个问题，有一次当时没带手表，只能用keep记录跑步，然后好死不死这一次记录无法同步，今天完美解决了！已成功导出GPX，然后把GPX导入到佳明

**Comment by yihong0618** [comment]
> 每次灵机一动上yihong的项目看都有惊喜！去年我也是遇到了这个问题，有一次当时没带手表，只能用keep记录跑步，然后好死不死这一次记录无法同步，今天完美解决了！已成功导出GPX，然后把GPX导入到佳明

哈哈
enjoy it
