### ISSUE TITLE
GarminCN -> Strava时区问题

### ISSUE THREAD

**Issue by donghao526** [yihong0618/running_page#485]
同步GraminCN到Strava目前遇到了时区问题，同步到的时间-8小时，貌似不是北京时区
<img width="368" alt="image" src="https://github.com/yihong0618/running_page/assets/1930500/7cbd8bd7-c52a-4ab8-bda2-2077d08f8cc5">
<img width="1007" alt="image" src="https://github.com/yihong0618/running_page/assets/1930500/632009a8-b9ba-443b-a790-257863f1cebc">

**Comment by donghao526** [comment]
对了，用的是tcx格式同步的

**Comment by yihong0618** [comment]
@donghao526 
用跑步机跑的是不没有路线？

**Comment by donghao526** [comment]
@yihong0618

**Comment by donghao526** [comment]
@yihong0618 
对的，用跑步机跑的没有坐标，是符合预期，这个时区问题，路跑和跑步机均有，我这边抽空看看解决办法

**Comment by yihong0618** [comment]
我们也看一下

**Comment by ben-29** [comment]
大致看了一下，Garmin 导出的 tcx/gpx 都是 UTC 不带时区
而 strava 的上传接口无法指定时区， strava 应该是以账户设置的地区来解析时间，把 Garmin UTC 的时间认成当地时间
这么看来解决办法就是把 Garmin 导出的 tcx/gpx/fit 里的时间戳都改成当地时间(UTC+8), 再上传到 strava

**Comment by ben-29** [comment]
那么其实strava也是按 UTC 来读取，只是展示时，默认用了 0时区。
至于 gpx/tcx 的问题，如果能复现，猜测可能是 gpx 处理机制有差异，可能 gpx 读取了轨迹坐标来确认时区了

**Comment by yihong0618** [comment]
> 

是的，他们会用轨迹点来确认时区（我们代码里也是）
所以我开始觉得可能是因为跑步机无法确认到。。。

**Comment by donghao526** [comment]
<img width="1025" alt="image" src="https://github.com/yihong0618/running_page/assets/1930500/9036d85d-46a6-47f2-8aed-2cc2c4edcf03">
<img width="353" alt="image" src="https://github.com/yihong0618/running_page/assets/1930500/c0c7aa93-8ffe-40c2-9d2a-1d2e3550d81d">
<img width="961" alt="image" src="https://github.com/yihong0618/running_page/assets/1930500/c438599d-8588-4602-91f1-ee65973e4495">

1. 我这边设置了伦敦的时区

2. TCX同步
2.1 对于跑步机数据

**Comment by donghao526** [comment]
今天又充分测了下，说下结论

**Comment by donghao526** [comment]
@yihong0618 @ben-29 今天又充分测了下，说下结论
1. strava对gpx和tcx都是根据分析轨迹坐标来确认时区（我调整了时区后，无论TCX和GPX都是可以正确显示北京时间的）
2. strava对TCX格式的跑步机记录是因为没有轨迹，无法识别时区，用了UTC
3. strava对GPX格式的跑步机记录是无法导入的，同样我在佳明国际版导入GPX的跑步机记录也是失败，可能因为GPX格式本来就是基于位置信息的，缺乏位置信息会被判定为文件格式之类的问题

由于昨天是看了GPX格式的室外记录同步是没问题的，没有考虑到轨迹记录，给出了【也确实之前用GPX传是能识别时区的】的结论，确实不太严谨，耽误两位的一些时间。

跑步机这个坑目前看来是解决了，要想跑步机数据正确，必须用TCX格式同步，且在strava设置正确的时区。

**Comment by yihong0618** [comment]
@donghao526 谢谢解答～
