### ISSUE TITLE
Text customize

### ISSUE THREAD

**Issue by geekplux** [yihong0618/running_page#5]
There is some text on the page, but it is hard coding in your index.js.
The better way is to make it customizable by parsing markdown or reading from the config file.

But, I think Gatsby is not as convenient as next.js in terms of reading data.... so do you consider changing the page framework? 😳

**Comment by yihong0618** [comment]
Let me have a try.

**Comment by yihong0618** [comment]
@geekplux 
I will not change framework, i18n is a good idea? #10

**Comment by geekplux** [comment]
different points, I think
