### ISSUE TITLE
升到2.0之后 deploy to github pages 似乎不能正确工作

### ISSUE THREAD

**Issue by conge** [yihong0618/running_page#502]
按照 readme里面的步骤，运行"Publish GitHub Pages" ，
整个过程没有报错，但并没有生成 `gh-pages` branch 

我的github_pages https://conge.livingwithfcs.org/running_page/ 也没有更新。另外，用vercrel deploy则没有问题 对比一下 https://run-4sp9991r5-conge.vercel.app/。

我也尝试了其它的workflow，所有的workflow都可以无错运转，我看了一下 ./src/static/activities.json，数据也都同步下来了。 build 也没有报错，但就是deploy之后网页没有变化。

**Comment by yihong0618** [comment]
page 得在设置里改成 actions

**Comment by conge** [comment]
> page 得在设置里改成 actions

我当然做了这个。

**Comment by yihong0618** [comment]
可能有缓存，换个浏览器试试？

**Comment by frostming** [comment]
重现不了，介意把 `dist/` 打包附上吗？

**Comment by conge** [comment]
> 可能有缓存，换个浏览器试试？

果然是Chrome缓存的问题。
换Brave和Safari，就行了！

那额外问一句，为什么，为什么Chrome刷新页面不行呢？

谢谢！

**Comment by yihong0618** [comment]
可能是 GitHub 自身的 cdn 我们研究下强制刷新

**Comment by frostming** [comment]
> 为什么Chrome刷新页面不行呢？

刷新页面不清缓存，要强制刷新才行（<kbd>Cmd</kbd><kbd>F5</kbd>)

**Comment by conge** [comment]
> > 为什么Chrome刷新页面不行呢？
> 
> 刷新页面不清缓存，要强制刷新才行（CmdF5)

谢谢，不过
似乎应该是 shift+cmd+r :)

**Comment by frostming** [comment]
> 似乎应该是 shift+cmd+r :)

两个都是，因为有的键盘没有F键

**Comment by yihong0618** [comment]
先关了哈

**Comment by conge** [comment]
我觉得这个值得在readme里面加上一句。
因为我记得，之前的老版本，每次数据/页面更新后，如果数据不对，只要f5刷新就行了。
升2.0之后，就得强制清缓存才行了。

而且2.0之后，如果用Github Actions来deploy到github pages环境，似乎也不会生成 `gh-pages` branch了。

**Comment by yihong0618** [comment]
> 我觉得这个值得在readme里面加上一句。 因为我记得，之前的老版本，每次数据/页面更新后，如果数据不对，只要f5刷新就行了。 升2.0之后，就得强制清缓存才行了。
> 
> 而且2.0之后，如果用Github Actions来deploy到github pages环境，似乎也不会生成 `gh-pages` branch了。

同意，来个 PR？
