### ISSUE TITLE
在 cloudflare 上部署报错：ERROR: Could not find a version that satisfies the requirement garth 

### ISSUE THREAD

**Issue by raywangsy** [yihong0618/running_page#511]
<img width="1117" alt="image" src="https://github.com/yihong0618/running_page/assets/56377217/5c98d2b3-c652-4a16-aace-fa9df3e29837">

<img width="1130" alt="image" src="https://github.com/yihong0618/running_page/assets/56377217/041457d6-5a0c-4332-9556-95adf7db8ffd">

在 cloudflare 上部署时找不到 garth 的相关版本号，本人试着添加了版本号 0.4.38 依然是报同样的错（如上图所示），谢谢！

**Comment by yihong0618** [comment]
python 版本？

**Comment by raywangsy** [comment]
> python 版本？

3.7 

![image](https://github.com/yihong0618/running_page/assets/56377217/a3a37226-5040-41b0-9f37-0d3d97c18735)

**Comment by raywangsy** [comment]
解决了，有设置中将构建版本改成2，然后将 Python 版本改成 3.11.5 就可以了

![image](https://github.com/yihong0618/running_page/assets/56377217/560711e3-402b-4aa0-8623-2aaa54ec40ba)
