### ISSUE TITLE
Fail to get data on strava using "python3 run_page/strava_sync.py"

### ISSUE THREAD

**Issue by misaka9981** [yihong0618/running_page#518]
I'm using this command for fetch my running data on strava, the data access is fine, however it always fails in gpx file process.
Following is the output of command:
`Access ok
Start syncing
+++++++++++++++++++++++++2023-10-12 08:56:39,061 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=35.011122124269605&lon=135.95425385981798&format=json&addressdetails=1
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++2023-10-12 08:58:15,100 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /reverse?lat=30.03566&lon=122.103856&format=json&addressdetails=1
++++++++++++++++++++%`
I tried to download my Strava data using both WiFi and mobile data, but both failed. However, I can see my run data in the generated activities.json file.

**Comment by yihong0618** [comment]
this is for get locations, we can ignore but may fail sometimes, we are trying a new way, but it needs token, so you for ignore this for now.

**Comment by misaka9981** [comment]
> this is for get locations, we can ignore but may fail sometimes, we are trying a new way, but it needs token, so you for ignore this for now.

Thanks for your work!
waiting for the upgrade.

**Comment by yihong0618** [comment]
closing now
