### ISSUE TITLE
如何支持香港、澳门作为一个省级行政区和城市显示，台湾省已解决

### ISSUE THREAD

**Issue by Jeffggmm** [yihong0618/running_page#520]
感谢@Ben-29的指点，用sqlbrowser修改data.db在位置信息后添加  ，美国  之类就能显示国家数量 。

台湾也是通过添加简体字的 台湾省， 中国 正确显示，但是 香港和澳门遇到了点问题，不知道如何解决

用 香港， 中国  和 香港特别行政区， 中国  都不行，加上香港的邮编 999077也不行

![333](https://github.com/yihong0618/running_page/assets/118322305/dbc16e21-e720-4039-9da4-023e8f9261ac)

大家可以缩放中国地图后看我的效果：https://jeffggmm.github.io/workouts_page/

**Comment by yihong0618** [comment]
跑了 25 个国家太牛逼了，我们看一下（另外请到 workouts 里留 issue
然后 cherry-pick 到这里好一些
@ben-29

**Comment by Jeffggmm** [comment]
我去@ben-29那里留了，可能他最近忙没顾得上，没好意思打扰他，所以我到这里也碰碰运气

**Comment by yihong0618** [comment]
我们有时间看看

**Comment by ben-29** [comment]
@Jeffggmm 看我在 issue 里的回复，更新最新代码，地址最后改为: 
`香港特别行政区, 中国 `
测试没问题后会同步到 running_page

**Comment by Jeffggmm** [comment]
测试通过，香港特别行政区和澳门特别行政区完美显示，感谢 @ben-29
