### ISSUE TITLE
strava请求refresh_token时候auth显示code 错误

### ISSUE THREAD

**Issue by zerone0x** [yihong0618/running_page#523]
`HTTP/2 400
content-type: application/json; charset=utf-8
date: Tue, 17 Oct 2023 13:47:23 GMT
via: 1.1 linkerd, 1.1 linkerd, 1.1 95e030d195f2fd02b9dd1216a944c770.cloudfront.net (CloudFront)
vary: Origin
server: nginx/1.23.4
status: 400 Bad Request
x-request-id: b25de31a-cbe5-4b34-9e79-2b8b47857f2b
cache-control: no-cache
referrer-policy: strict-origin-when-cross-origin
x-frame-options: DENY
x-xss-protection: 1; mode=block
x-download-options: noopen
x-content-type-options: nosniff
x-permitted-cross-domain-policies: none
x-cache: Error from cloudfront
x-amz-cf-pop: LAX50-P4
x-amz-cf-id: qPWmOOde1lThg5u-qFDkiev1yc1KsOFUyFAirULsQlZlhSKjzbbXaA==

{
    "message": "Bad Request",
    "errors": [
        {
            "resource": "AuthorizationCode",
            "field": "code",
            "code": "invalid"
        }
    ]
}`

**Comment by zerone0x** [comment]
check了几次varible，没有填写错，用strava auth的link生成了两次code，都是一样的auth问题，不清楚是如何更改code值才能拿到refresh token.可以帮忙看下吗？谢谢！

**Comment by yihong0618** [comment]
@shaonianche

**Comment by shaonianche** [comment]
> check了几次varible，没有填写错，用strava auth的link生成了两次code，都是一样的auth问题，不清楚是如何更改code值才能拿到refresh token.可以帮忙看下吗？谢谢！
看报错似乎提示的是你的code过期了，重新走一遍授权流程使用新的code请求一下试试？

**Comment by zerone0x** [comment]
有效期大概多久？我已经试过三次了

**Comment by shaonianche** [comment]
> cloudfront 是啥？
> 
> 

https://en.wikipedia.org/wiki/Amazon_CloudFront amazon 的 cdn服务吧

**Comment by yihong0618** [comment]
猜测是这个导致的

**Comment by zerone0x** [comment]
@yihong0618 应该怎么解决啊？

**Comment by yihong0618** [comment]
关掉 proxy 然后重新按照 readme 跑一下，如果还不行可以去 tg link 里，那里人多能帮忙看看

**Comment by zerone0x** [comment]
fixed by wrong client id
