### ISSUE TITLE
keep导入到佳明国际区运动类型问题

### ISSUE THREAD

**Issue by SlippyJimmy** [yihong0618/running_page#525]
keep生成gpx文件并导入到佳明国际区时，运动类型问题默认为其他，需要手动更改为跑步，比较麻烦，有更好的办法吗？
<img width="312" alt="image" src="https://github.com/yihong0618/running_page/assets/45062658/4befd0fe-75d1-44e1-9ee3-5eef7f498816">

**Comment by yihong0618** [comment]
多少个呀，理论可以强制改成 run..但是你别的运动也会改成 run 了

**Comment by SlippyJimmy** [comment]
我看了，默认导出的都是run类型的gpx文件，就算有非run类型的噪声条目，也可以手动删除，毕竟删除比更改来的方便。ps：我目前已经手动改完了，作者可以考虑更新一下这个功能，方便其他有需要的人。

**Comment by yihong0618** [comment]
不太可以，run 的话我们可以强制，但是有些人不光是跑步

**Comment by SlippyJimmy** [comment]
keep导出可以识别运动类型吗？如跑步、骑行、健身等，如果可以的话，可以对其分别进行类型设置

**Comment by NaturezzZ** [comment]
目前本项目可以支持Garmin中国区直接同步到Garmin国际区，不知道能不能解决你的需求。

**Comment by yihong0618** [comment]
可以的
