### ISSUE TITLE
实在搞不定

### ISSUE THREAD

**Issue by skynco** [yihong0618/running_page#526]
![QQ截图20231020162903](https://github.com/yihong0618/running_page/assets/556705/6cce8983-57ad-444c-a136-77b1fe04a0d3)
小白一个，搞不下去了，这是什么意思啊

**Comment by yihong0618** [comment]
你好，README 里有个 YouTube 的视频教程链接你可以参考
你这个错误是没有 git 请搜索 wsl 如何装 git
