### ISSUE TITLE
缩放彩蛋显示0个国家、省份、城市

### ISSUE THREAD

**Issue by qigeloveit** [yihong0618/running_page#531]
![微信截图_20231026130153](https://github.com/yihong0618/running_page/assets/20183613/758fc255-b6f6-492d-b79d-9d96731de5d4)

**Comment by qigeloveit** [comment]
求助，是缺少哪个配置步骤吗？其他功能都正常

**Comment by yihong0618** [comment]
需要在全局梯子下跑脚本

**Comment by qigeloveit** [comment]
> 需要在全局梯子下跑脚本

我fork代码没有在本地运行，也就是说需要clone到本地运行再上传代码？

**Comment by yihong0618** [comment]
我们看一下。理论上 actions 跑会有地理位置的

**Comment by yihong0618** [comment]
@qigeloveit 你的项目地址贴一下可以么？

**Comment by qigeloveit** [comment]
> @qigeloveit 你的项目地址贴一下可以么？

感谢回复！
https://github.com/qigeloveit/running_page

**Comment by vlin** [comment]
![image](https://github.com/yihong0618/running_page/assets/239585/dd43c26a-eaad-4666-be92-49a2398f9e84)

发现 @qigeloveit 同学的所有 `291` 条运动记录中 `location_country` 全是 `United States` 😂
原始运动数据可能在采集时有误，同时 `src/utils/utils.ts` 的 `locationForRun` 方法当前仅对中文国家名称进行解析。

猜测会不会因为运动设备上有某些设置导致记录下来的地理信息有误？

**Comment by qigeloveit** [comment]
> ![image](https://user-images.githubusercontent.com/239585/279340796-dd43c26a-eaad-4666-be92-49a2398f9e84.png)
> 
> 发现 @qigeloveit 同学的所有 `291` 条运动记录中 `location_country` 全是 `United States` 😂 原始运动数据可能在采集时有误，同时 `src/utils/utils.ts` 的 `locationForRun` 方法当前仅对中文国家名称进行解析。
> 
> 猜测会不会因为运动设备上有某些设置导致记录下来的地理信息有误？

我之前都是用的华为gtr，这个月才换的佳明255，不太可能都设置成了美国，那更可能是因为佳明中国的账号设置问题？但我也没找到地方修改，这个location_country是从fit文件中解析出来的吗？

**Comment by qigeloveit** [comment]
我发现是我strava个人资料的位置填的United States，估计是这个原因，现在修改了

**Comment by vlin** [comment]
![image](https://github.com/yihong0618/running_page/assets/239585/af0a97b4-9ed0-424f-8031-a278bcf69fcc)
@qigeloveit 
看到已生成非0的国家省份信息了。

但由于你的运动数据中昨天以前的运动数据中 `location` 仍是 `United State`，这历史数据可能`Strava` 应用就不会因为你更新了个人资料而主动更新。
![image](https://github.com/yihong0618/running_page/assets/239585/2582c21b-89e8-4d9e-9c0b-4116fa5e21c6)
所以统计到的1个国家信息实际上是2023-11-01的最新中文地址信息。

**Comment by yihong0618** [comment]
@vlin @qigeloveit 如果数据不多可以删掉 data.db 重写跑

**Comment by qigeloveit** [comment]
以前的记录没办法了，我打算换源从garmin来获取了

**Comment by vlin** [comment]
> @vlin @qigeloveit 如果数据不多可以删掉 data.db 重写跑

@qigeloveit 
已试过 @yihong0618 同学说的方法也不行吗？

**Comment by qigeloveit** [comment]
> > @vlin @qigeloveit 如果数据不多可以删掉 data.db 重写跑
> 
> @qigeloveit 已试过 @yihong0618 同学说的方法也不行吗？

Action运行生成的running_page/data.db在哪呢？我已经试过删除cache了

**Comment by yihong0618** [comment]
我看你成功了，我先关了哈

**Comment by qigeloveit** [comment]
谢谢大佬

**Comment by whyyyPan** [comment]
> 谢谢大佬

Hi 我遇到了和你一样的问题 能分享下如何解决的吗 谢谢

**Comment by yihong0618** [comment]
这个目前解决了请用最新代码实验下

**Comment by Vensent** [comment]
> 这个目前解决了请用最新代码实验下

这个的提交是哪一笔啊，可以发一下么？我cherry-pick到我的项目中，我不知道是不是因为我从 @ben-29 的项目fork过来的，strava上面都是0

**Comment by yihong0618** [comment]
> > 这个目前解决了请用最新代码实验下
> 
> 这个的提交是哪一笔啊，可以发一下么？我cherry-pick到我的项目中，我不知道是不是因为我从 @ben-29 的项目fork过来的，strava上面都是0

0 的话可以重新生成，因为需要梯子，我先把这个打开，后续我加一个重写生成 location 的脚本

**Comment by Vensent** [comment]
自己本地跑了一下，我的这个现象和上面 @qigeloveit 的问题很像，我的strava的数据是重新从Garmin全部导入过来的，activities.json中我发现现在的location_country写的“Hong Kong”，全部都是。

所以这种有办法解决么？

**Comment by Vensent** [comment]
> 自己本地跑了一下，我的这个现象和上面 @qigeloveit 的问题很像，我的strava的数据是重新从Garmin全部导入过来的，activities.json中我发现现在的location_country写的“Hong Kong”，全部都是。
> 
> 所以这种有办法解决么？

找了个解决办法，自己在db.py里面加了一行可以根据我自己的情况完成解决。
![image](https://github.com/yihong0618/running_page/assets/7401921/31e42b24-eb9e-41bb-a8f9-a154cee8f2d2)

有需要的朋友可以参考这个方法

**Comment by yihong0618** [comment]
啊倒是可以。。。（你是在香港跑的？

**Comment by Vensent** [comment]
> 啊倒是可以。。。（你是在香港跑的？

说来话长。。

我这边想把跑步机啊、游泳这些数据都留着，就用的strava，Garmin要丢不少的数据，支持没有那么好。
但是Strava我这边是从2018年才开始和Garmin同步的，丢了不少之前的数据。所以我新开了一个号，用的RunGap这个app同步了一下佳明的数据到我的这个新的Strava的号。

因为申请新的这个Strava的号是在公司的网里面，所以定位到了香港。。

**Comment by yihong0618** [comment]
啊我后面写个脚本可以重新生成

**Comment by Leerol** [comment]
> 我们看一下。理论上 actions 跑会有地理位置的

大佬，你好，请教一个问题，我也遇到了和楼主一样的问题，我是用佳明中国和coros拉取完本地数据以后，同样缩放地图也是显示0个国家、省份、城市。自行查看activity.json文件，发现里面的location_country 字段的值是空的，所以想问一下这个情况是fit和gpx源数据有问题是嘛？我又自己手动导了其他格式的文件，同步过去以后，发现也是location_country 字段的值是空的。所以，想请教一下各位大佬，是需要额外的配置啥的吗，我的这种情况要怎么排查啊？谢谢啦

**Comment by yihong0618** [comment]
> > 我们看一下。理论上 actions 跑会有地理位置的
> 
> 大佬，你好，请教一个问题，我也遇到了和楼主一样的问题，我是用佳明中国和coros拉取完本地数据以后，同样缩放地图也是显示0个国家、省份、城市。自行查看activity.json文件，发现里面的location_country 字段的值是空的，所以想问一下这个情况是fit和gpx源数据有问题是嘛？我又自己手动导了其他格式的文件，同步过去以后，发现也是location_country 字段的值是空的。所以，想请教一下各位大佬，是需要额外的配置啥的吗，我的这种情况要怎么排查啊？谢谢啦 @yihong0618 @vlin 

可能你需要重新跑一遍（注意需要全局梯子）

**Comment by shaonianche** [comment]
该提交尝试修复 strava location_country 的问题，请使用 Strava 的朋友帮忙测试。

在 generator/__init__.py 文件中将 activity location_country  强制替换为经纬度查询后的数据。
https://github.com/shaonianche/running-data-sync/commit/d7db2ec0260dbd054e17c486e201b14e70c876a0#diff-02a17b4a00f43e7e49df26b84d2ae78a033766bbeb7a3a91e06c7ea0b10176bd
