### ISSUE TITLE
merge 2.0后 页面文件缺失

### ISSUE THREAD

**Issue by coolp4n** [yihong0618/running_page#533]
Halo yihong 我fetch到2.0版本了  
但是不知部署完之后的页面缺少一些文件

这是我部署后的页面
希望能够得到你的解答 谢谢！
[coolp4n.github.io/running_page/](https://coolp4n.github.io/running_page/)

**Comment by yihong0618** [comment]
没问题的，你需要强制刷新或者换个浏览器访问
（参考 README
