### ISSUE TITLE
strava sync running page页面地图无轨迹

### ISSUE THREAD

**Issue by whyyyPan** [yihong0618/running_page#539]
Hi yihong  这个项目很酷 ，我也成功用捷径触发同步workflow了
但是running page 地图无轨迹  左边栏也没有每一个年份的数据 
我把db删除了几次 重新同步 但是还是一样
不知是什么原因呢 ？希望得到你的解答 Thanks
这是我的页面 
仓库
![image](https://github.com/yihong0618/running_page/assets/149458618/f504f9b1-92b4-4545-b93b-974cad135a54)

**Comment by yihong0618** [comment]
比较奇怪，理论上不会，你可以这么检查
1. strava 里面有设置隐私不分享轨迹么？
2. strava 里面有运动轨迹么？
3. 在 strava 网页版里面看看有轨迹么

**Comment by haowei93** [comment]
不知道原始数据是从哪个平台拿的， 用原始数据download的gpx生成试试， 对比排查下是不是strava 的问题

**Comment by yihong0618** [comment]
不对啊，你 total 页面里的轨迹生成了，而且你这里面有好多 gpx, 按理 strava 是没用 gpx 的，我们看一下

**Comment by whyyyPan** [comment]
> 比较奇怪，理论上不会，你可以这么检查
> 
> 1. strava 里面有设置隐私不分享轨迹么？
> 2. strava 里面有运动轨迹么？
> 3. 在 strava 网页版里面看看有轨迹么

噢 可能是我之前设置了活动仅本人可见 但是现在权限改为所有人之后，打开我的活动 还是每一个都是带了锁头图标
不能全选 都放开权限吗？？？

**Comment by whyyyPan** [comment]
> 不对啊，你 total 页面里的轨迹生成了，而且你这里面有好多 gpx, 按理 strava 是没用 gpx 的，我们看一下


我最近才开始用strava， 我是用你项目的脚本把悦跑圈的gpx同步到strava的
（悦跑圈的数据是高驰同步的）

**Comment by whyyyPan** [comment]
ok 现在用了gpx数据同步 是可以的 
我试试strava 隐私打开后没问题的话 我会把issue close的
Thank you！

**Comment by yihong0618** [comment]
不客气

**Comment by whyyyPan** [comment]
谢谢 打开过去活动的权限后可以了

**Comment by yihong0618** [comment]
不客气，btw 跑的很厉害，敬仰！

**Comment by whyyyPan** [comment]
> 不客气，btw 跑的很厉害，敬仰！

菜鸡路过   只是非常瘦小而已  占了体型的优势  :- D
