### ISSUE TITLE
Feat: multiple activities type

### ISSUE THREAD

**Issue by geekplux** [yihong0618/running_page#54]
of course, running is the main activity for users, but it would be better to support more sports types.
As you can see, I've tried to get all my activities including the hike, ride, etc. displayed on the page, and I assign them different colors by the type. 

***This is not a necessary function, more discussion is needed.***

<img width="1552" alt="Screen Shot 2020-12-03 at 11 57 06 AM" src="https://user-images.githubusercontent.com/3816105/100962137-b84a3100-355e-11eb-88b5-32af1fb56d98.png">

**Comment by ange20** [comment]
Hello
Yes, please, its a very good idea because I need to separate biking and running.
How can I have this version ?

**Comment by geekplux** [comment]
I have implemented it on my own project and it will be migrated later.

**Comment by yihong0618** [comment]
@ange20 @geekplux 
I think its a little complicated, because it can only support strava and garmin for now.
Gpx may not be have the  activate `type`, we can default it as `Run`?

**Comment by geekplux** [comment]
@ange20 so what device or app you are using

**Comment by ange20** [comment]
Hi
I m using Runtastic app, and my data are incorrect due to my biking trips.
Thanks for your dev and help :)

**Comment by yihong0618** [comment]
> Hi
> I m using Runtastic app, and my data are incorrect due to my biking trips.
> Thanks for your dev and help :)

can you offer more details about the incorrect data?

**Comment by ange20** [comment]
It's not really incorrect, but I would like only my running sessions, and not biking sessions
For exemple currently, this activity isn't a run, but a bike trip, and I don't want to have it on my map, and generated svg.

![2020-12-09_21h27_37](https://user-images.githubusercontent.com/47721188/101683697-991f3800-3a65-11eb-86e0-8a085b1308c3.png)

is it possible in the runtastic script to specify only running activities?

Thanks

**Comment by yihong0618** [comment]
@ange20 

Done with this commit https://github.com/yihong0618/running_page/commit/c85e8b74aa781d5cd4ed61db9e048477c9e6063a
You can generate new data by deleting the previous data using the following steps
1. rm GPX_OUT/*
2. rm scripts/data.db
3. python3(python) scripts/runtastic_sync.py ${your email} ${your password}

**Comment by ange20** [comment]
Thanks a lot, it's perfect for me, and with your comments in file, I know where I can change the values.
Have a nice day

**Comment by yihong0618** [comment]
> Thanks a lot, it's perfect for me, and with your comments in file, I know where I can change the values.
> Have a nice day

My pleasure have nice day and a nice run~

**Comment by geekplux** [comment]
Could we drop this condition: https://github.com/yihong0618/running_page/blob/master/scripts/generator/__init__.py#L107

And bring the activity type filter to front-end, which could make user select if shows their other activities than just 'Run' type. what do you think? @yihong0618

**Comment by yihong0618** [comment]
> Could we drop this condition: https://github.com/yihong0618/running_page/blob/master/scripts/generator/__init__.py#L107
> 
> And bring the activity type filter to front-end, which could make user select if shows their other activities than just 'Run' type. what do you think? @yihong0618

Yes～.  And we should mention it, because some fox do not have type, default run?

**Comment by geekplux** [comment]
If we support multiple types of sports, we can achieve statistics like https://github.com/yihong0618/running_page/issues/55. But I don’t know whether our project is to focus only on 'running'. If you only want to focus on 'running', I think it might be simple, a bar graph and a line graph will enough.

**Comment by pshwu** [comment]
This would be a really good feature. I'm a user of https://veloviewer.com/ which has some similar ideas.
