### ISSUE TITLE
NRC down refresh_token we use can not use anymore

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#542]

**Comment by zlog-in** [comment]
is it possible to fetch the running data out of NRC if one already has the refresh_token?

**Comment by zlog-in** [comment]
NRC users can use [rungap app](http://www.rungap.com/) to link the RNC account and import workout data, but to export the workout data as GPX fils, a 3-month subscription must be enabled with fee 3.99$.
Maybe Running_page can also enable the account link with NRC email address and password to import the data file.

**Comment by yihong0618** [comment]
> is it possible to fetch the running data out of NRC if one already has the refresh_token?

yes we have a way but seems we can not use actions for daily job will update today

**Comment by zlog-in** [comment]
> > is it possible to fetch the running data out of NRC if one already has the refresh_token?
> 
> yes we have a way but seems we can not use actions for daily job will update today

Thanks you! Quite helpful to these who want to fetch their data out of RNC, and I do recommand you to try RunGap, which can import workout data from almost fitness app

**Comment by yihong0618** [comment]
@zlog-in yes I know this great app, also used to use it, thanks, and will try to fix nike_sync this weekend, when we are done, can you help us test?

**Comment by zlog-in** [comment]
Glad to help your work.

**Comment by yihong0618** [comment]
> Glad to help your work.

can you help try the latest code?

**Comment by zlog-in** [comment]
Tested on Firefox and it works perfect! And I this this screenshot could be useful to help others get refresh token from Nike webiste
![NikeRefreshToken](https://github.com/yihong0618/running_page/assets/67903793/d7367246-23db-4cd5-bcf0-86acd2ace726)

**Comment by yihong0618** [comment]
@zlog-in can you open a PR to support it? IMO use this png is ok(link in issue)

**Comment by zlog-in** [comment]
Sent a PR to your repo, thanks for your work XD

**Comment by yihong0618** [comment]
@zlog-in merged thanks a lot
