### ISSUE TITLE
能够导出骑行gpx数据吗

### ISSUE THREAD

**Issue by Justbecause0210** [yihong0618/running_page#543]
想要将keep的骑行数据导出，查到知乎的文章了解到该工具，跟着操作教程进行导出后发现只能导出跑步数据

**Comment by yihong0618** [comment]
能的，搜索骑行，在这个项目 issue 和 disscuss 里有过讨论

**Comment by yihong0618** [comment]
> > 能的，搜索骑行，在这个项目 issue 和 disscuss 里有过讨论
> 
> 真的十分感谢，刚才没有仔细的看完所有讨论，现在发现有相关内容了，真是麻烦您了

不是是我们的问题，我们之后会列个常见的问题合集 @shaonianche 现在我们做的不太好，如果有疑问随时打开这个 issue
