### ISSUE TITLE
keep能否导出行走数据

### ISSUE THREAD

**Issue by QHQIII** [yihong0618/running_page#549]
很多跑步和骑行图方便都塞在行走中了，可以指定导出这一部分数据吗？

**Comment by yihong0618** [comment]
可以的，在 issue 里搜索 keep 骑行，里面有导出方式

**Comment by QHQIII** [comment]
刚刚翻了下apk文件，记录一下
行走 hiking/hikinglog
骑行 cycling/cyclinglog
跑步 running/runninglog

**Comment by yihong0618** [comment]
谢谢

**Comment by QHQIII** [comment]
不对嘛，非常感谢你的工具，能够把数据拿回到自己的手里，只可惜20年之前都在坑爹动动计步器里面😂

**Comment by yihong0618** [comment]
> 不对嘛，非常感谢你的工具，能够把数据拿回到自己的手里，只可惜20年之前都在坑爹动动计步器里面😂

运动计步器是啥？

**Comment by QHQIII** [comment]
那个运动app他就叫_动动_ 
![image](https://github.com/yihong0618/running_page/assets/49380606/232aba2a-3178-48d9-8b5f-8603eac9b6d2)

**Comment by yihong0618** [comment]
查了下 动动 应该没人研究过，我先 close 这个 issue 了哈
