### ISSUE TITLE
请问GPX中心率记录的颗粒度是？

### ISSUE THREAD

**Issue by wuSaberMaster** [yihong0618/running_page#556]
您好，非常感谢您的runpage开源项目。在复刻之前有个小问题想咨询您，请问从keep提取下来的gpx文件里面有包含实时的心率记录吗，就是每分钟的心率都包含的，我想对详细的心率记录做数据分析，只是一个平均心率的话不太能满足我的需求。期待您的回复，非常感谢！

**Comment by yihong0618** [comment]
不客气。
