### ISSUE TITLE
页面空白，麻烦大佬看看问题出在哪了

### ISSUE THREAD

**Issue by DanileLxp** [yihong0618/running_page#557]
https://github.com/DanileLxp/running_page/

**Comment by DanileLxp** [comment]
https://running.danilelxp.com/

**Comment by DanileLxp** [comment]
> https://github.com/DanileLxp/running_page/blob/master/.github/workflows/gh-pages.yml#L100C14-L100C63
> 
> 把这句改成 run: PATH_PREFIX=/${{ github.event.repository.name }} pnpm build
> 
> ```
>     pnpm build
> ```

感谢大佬，已修改密码。
不过好奇怪，total显示的还是大佬的数据，还在找问题出在哪了

**Comment by yihong0618** [comment]
total 是用 data.db 生成的，你没有传 data.db
