### ISSUE TITLE
设置`IGNORE_BEFORE_SAVING=1`后`gen_svg.py`报错

### ISSUE THREAD

**Issue by conanyangqun** [yihong0618/running_page#558]
看了下代码，应该是 `run_page/gpxtrackposter/track.py`中`load_from_db`函数的问题。blame下，是在这个[commit](https://github.com/yihong0618/running_page/commit/f17a3e694a2ba102a218efc16e21a8cf83f0053b#diff-ea1ab7ec71fbeb34ad5d08163ac064c11b28e4ccbe97f75b1a876015aac51a8e)引入的。

未设置该环境变量时，不会触发bug。设置该变量，则导致`summary_polyline`发生未定义先引用错误。

按照我的理解，代码应该改成这个样子：

```python
if IGNORE_BEFORE_SAVING:
        summary_polyline = filter_out(activity.summary_polyline)
else:
        summary_polyline = activity.summary_polyline
```

**Comment by yihong0618** [comment]
@conanyangqun 感谢，能提个 PR 么把你的修改？

**Comment by conanyangqun** [comment]
> @conanyangqun 感谢，能提个 PR 么把你的修改？

一会提一个，专门做个分支。稍后哦。

**Comment by yihong0618** [comment]
谢谢

**Comment by conanyangqun** [comment]
> 谢谢

客气了。很有趣的项目，我不懂前端，对python有了解。感谢付出！我关这个issue了。
