### ISSUE TITLE
请问KEEP可以导出其他类型的运动数据吗？

### ISSUE THREAD

**Issue by wuSaberMaster** [yihong0618/running_page#561]
作者您好，我用keep进行了三次跑步运动用来测试，其中前两次跑步是正常的户外跑，第三段跑步是开启跑步运动然后进行室内有氧训练。我本是想通过这种方式来获取其他运动的心率数据，后来发现获取不到第三段跑步的数据。请问有其他方式可以获取其他运动的数据吗？（opp、xiaomi、vivo等运动手表）
![image](https://github.com/yihong0618/running_page/assets/95974421/d3c191d8-dd73-43cc-8f61-719411daabc6)

**Comment by wuSaberMaster** [comment]
> 1. 只能跑步，如果是其它类型请在 issue 中搜索，有办法。
> 2. 不支持其它运功手表

感谢您的回复。
1、我的目的是获取国产智能手表的心率数据，所以就将这些设备的数据同步到keep、悦跑圈这类第三方软件，然后通过runningpage来导出。
2、然后在其他issue里面看到可以通过strava来获取到其他类型的运动数据
3、 但是strava不支持部分国产设备的数据同步(huawei、oppo)

**Comment by GeuojMr** [comment]
keep导出的跑步数据再导入其他app里，如strava、Garmin都是显示其他活动，不是跑步，这个有办法解决吗，多谢啦

**Comment by yihong0618** [comment]
> keep导出的跑步数据再导入其他app里，如strava、Garmin都是显示其他活动，不是跑步，这个有办法解决吗，多谢啦

strava 可以，可以强行指定 type

**Comment by GeuojMr** [comment]
> keep导出的跑步数据再导入其他app里，如strava、Garmin都是显示其他活动，不是跑步，这个有办法解决吗，多谢啦

另外一个评论里看到一样的问题了，我的数据都是run，能改吗😂

**Comment by yihong0618** [comment]
> > keep导出的跑步数据再导入其他app里，如strava、Garmin都是显示其他活动，不是跑步，这个有办法解决吗，多谢啦
> 
> 另外一个评论里看到一样的问题了，我的数据都是run，能改吗😂

参考这个改
https://github.com/yihong0618/run/blob/master/run_page/utils.py#L109C3-L113C18

**Comment by yihong0618** [comment]
> > > > keep导出的跑步数据再导入其他app里，如strava、Garmin都是显示其他活动，不是跑步，这个有办法解决吗，多谢啦
> > > 
> > > 
> > > 另外一个评论里看到一样的问题了，我的数据都是run，能改吗😂
> > 
> > 
> > 参考这个改 https://github.com/yihong0618/run/blob/master/run_page/utils.py#L109C3-L113C18
> 
> 你好，我使用的是佳明的手表，以前在keep有很多跑步的数据，能帮我导出keep的数据吗？ 有偿，谢谢。

具体需求可以给我发邮件，我有时间和精力会帮你看看
