### ISSUE TITLE
Docker build error

### ISSUE THREAD

**Issue by ICYMYM** [yihong0618/running_page#566]
docker build -t running_page:latest . --build-arg app=Garmin-CN --build-arg secret_string="{my_secret}"

![image](https://github.com/yihong0618/running_page/assets/3919539/33157149-bbcb-41e1-aefc-5e5f237858f8)

**Comment by yihong0618** [comment]
fixed @ICYMYM can you take a try ?

**Comment by ICYMYM** [comment]
There still seems to be a problem

![image](https://github.com/yihong0618/running_page/assets/3919539/bf484113-0489-4737-944d-c3af0e0b83b4)

**Comment by ICYMYM** [comment]
不用docker可以运行，但是在同步数据时出现了问题：

python3 run_page/garmin_sync.py {my_secret} --is-cn --only-run

![image](https://github.com/yihong0618/running_page/assets/3919539/a882ba66-ed2c-47d0-bcd7-0ebabfcf8b58)

我用的python@3.12.0， 难道是版本问题？
