### ISSUE TITLE
支持高驰手表吗？

### ISSUE THREAD

**Issue by Forrest-Tao** [yihong0618/running_page#569]

**Comment by yihong0618** [comment]
可以支持。
#TODO

**Comment by zhaohongxuan** [comment]
我记得coros可以同步到strava的，可以使用strava实现自动化

**Comment by Forrest-Tao** [comment]
感谢作者回复，期待作者的完成~ 
btw，我也在大连跑步

**Comment by Forrest-Tao** [comment]
学生暂时还能cover strava的费用

**Comment by yihong0618** [comment]
> 感谢作者回复，期待作者的完成~ btw，我也在大连跑步

starva 同步coros 需要付费呀？

**Comment by Forrest-Tao** [comment]
> > 感谢作者回复，期待作者的完成~ btw，我也在大连跑步
> 
> starva 同步coros 需要付费呀？

仅同步数据是免费的。

我使用 win 安装出现了好多问题，等我有空了用虚拟机试试。
感谢作者的回复~~~

**Comment by Forrest-Tao** [comment]
我还是没太搞清楚 coros 如何获取client_id 和token？

<img width="1167" alt="1f45d29bd9f7ff707620c382968ff43" src="https://github.com/yihong0618/running_page/assets/112991218/367ba3bf-3b38-47dc-b8e1-3e10f69269a7">

<img width="562" alt="88d6340f72085da90531d2512178e95" src="https://github.com/yihong0618/running_page/assets/112991218/903d3e24-e5c7-4abb-927b-0d1906318477">

**Comment by yihong0618** [comment]
https://github.com/yihong0618/running_page/pull/623#pullrequestreview-1919606867

@Forrest-Tao 有兴趣帮我测试和 review 一下这个 PR 么？

**Comment by yihong0618** [comment]
支持了
