### ISSUE TITLE
Bug: garmin_sync crash with --fit

### ISSUE THREAD

**Issue by NaturezzZ** [yihong0618/running_page#584]
When synchronizing FIT from Garmin, it sucessfully downloads FIT activities but crashes when generating track info. FYI, some activities are treadmill running / trail running. There are also a lot of errors when loading FIT with fit-tool. I suggest to load .fit with garmin-fit-sdk instead. ref: https://developer.garmin.com/fit/example-projects/python/

Error log snippet:
```
Something went wrong when loading FIT. for file 270504327.fit, we just ignore this file and continue
'utf-8' codec can't decode byte 0xc9 in position 49: invalid continuation byte
Something went wrong when loading FIT. for file 244180517.fit, we just ignore this file and continue
list index out of range
Something went wrong when loading FIT. for file 270033973.fit, we just ignore this file and continue
'utf-8' codec can't decode byte 0xc9 in position 49: invalid continuation byte
Something went wrong when loading FIT. for file 280518961.fit, we just ignore this file and continue
list index out of range
Something went wrong when loading FIT. for file 269049239.fit, we just ignore this file and continue
'utf-8' codec can't decode byte 0xc9 in position 49: invalid continuation byte
Something went wrong when loading FIT. for file 261396599.fit, we just ignore this file and continue
54 is not a valid Sport
```

**Comment by ben-29** [comment]
Can the corresponding GPX file be synced properly? If so, perhaps we should consider switching to the `garmin-fit-sdk`.

**Comment by NaturezzZ** [comment]
GPX is okay. Can you reproduce this bug?

**Comment by ben-29** [comment]
@NaturezzZ Can you assist me in testing the PR #590 to check if it resolved the issue?

**Comment by NaturezzZ** [comment]
Yes, let me take a look.
