### ISSUE TITLE
deploy page报错

### ISSUE THREAD

**Issue by donghao526** [yihong0618/running_page#587]
今天merge了最新的一些commit，然后depoly就报如下的错了
<img width="861" alt="image" src="https://github.com/yihong0618/running_page/assets/1930500/7807d24a-ddbe-4414-baa0-5647f496e7c0">
我看assets/index.ts文件也正常

```
export const yearStats = import.meta.glob('./year_*.svg', { import: 'ReactComponent' })
export const totalStat = import.meta.glob(['./github.svg', './grid.svg'], { import: 'ReactComponent' })
```
很抱歉，我对前端不是很熟悉，好像看也没人提过这个问题，求空了给看看

**Comment by NaturezzZ** [comment]
将GitHub Pages的所有cache清空试试

**Comment by donghao526** [comment]
> 将GitHub Pages的所有cache清空试试

确实是缓存的问题，把这个地方漏掉了，多谢大兄弟

**Comment by ZhengHe-MD** [comment]
> 将GitHub Pages的所有cache清空试试

that saves my day!

**Comment by yihong0618** [comment]
> > 将GitHub Pages的所有cache清空试试
> 
> that saves my day!

我们之后加在 README 里一下
