### ISSUE TITLE
没有生成新的svg, 越500kb？

### ISSUE THREAD

**Issue by zpengcom** [yihong0618/running_page#588]
你好，我是在windows本地运行
在项目目录中执行生成svg图形：
`python3 run_page/gen_svg.py --from-db --title Running --type github --athlete peng --special-distance 10 --special-distance2 20 --special-color yellow --special-color2 red --output assets/github.svg --use-localtime --min-distance 0.5`

没有生成新的svg

多次尝试有过一条通知
 [BABEL] Note: The code generator has deoptimised the styling of F:\ABC\workouts_page\assets\grid.svg as it exceeds the max of 500KB.

 我用的是https://github.com/ben-29/workouts_page 的项目，但似乎应该把问题提在这里

**Comment by yihong0618** [comment]
>[BABEL] Note: The code generator has deoptimised the styling of F:\ABC\workouts_page\assets\grid.svg as it exceeds the max of 500KB.
忽略这条。他告诉你 500k 会影响性能不是没生成

**Comment by zpengcom** [comment]
> [BABEL] Note: The code generator has deoptimised the styling of F:\ABC\workouts_page\assets\grid.svg as it exceeds the max of 500KB.
> > 忽略这条。他告诉你 500k 会影响性能不是没生成

不好意思 浪费你时间了，我知道问题是怎么产生的了：这项目是我从另一台电脑上直接拷贝过来的，所有的脚本都不能运行  我看看怎么解决吧

**Comment by yihong0618** [comment]
好的有问题随时打开
