### ISSUE TITLE
Your version of App is out of date. Please update to our latest version

### ISSUE THREAD

**Issue by Vincent1976** [yihong0618/running_page#589]
今天使用，突然报错了
![image](https://github.com/yihong0618/running_page/assets/14182554/d1e12869-3233-4fac-b473-6d37f1d4785a)

**Comment by Vincent1976** [comment]
我是同步悦跑圈数据，今天拉了最新版的程序，也同样报这个错误

**Comment by yihong0618** [comment]
@ben-29 可能不行了？

**Comment by ben-29** [comment]
刚试了，能正常登录。把代理关了，或者换个网络试试

**Comment by Vincent1976** [comment]
还是不行哦，我没有代理，电脑也重启过。还是out of date

**Comment by ben-29** [comment]
应该是你本地网络环境的问题。试试切换其他网络，比如手机开热点？我也试了能正常登录

https://github.com/yihong0618/running_page/issues/185#issuecomment-1004453484

**Comment by Vincent1976** [comment]
确实，换了台电脑就好了，但实在弄不清楚自己电脑是什么问题

**Comment by ben-29** [comment]
两台电脑是连同一个网络吗？python版本一样吗？

**Comment by yihong0618** [comment]
x先关了哈。应该是网络问题
