### ISSUE TITLE
获取数据一直停在Syncing tracks '+' means new track '.' means update tracks

### ISSUE THREAD

**Issue by linyinian** [yihong0618/running_page#595]
导出的是咕咚，试了几次一直停在Syncing tracks '+' means new track '.' means update tracks，看视频里这一步都很快，不知道哪里出了问题

![WX20240111-104853](https://github.com/yihong0618/running_page/assets/39898791/dc460110-6ea0-428a-87cc-6415e310758c)

**Comment by yihong0618** [comment]
挂梯子了么？

**Comment by linyinian** [comment]
> 挂梯子了么？

是的，我把梯子关了重新运行又出现别的问题，好像能解析到但数据导不出来
![WX20240111-110631](https://github.com/yihong0618/running_page/assets/39898791/fad3b113-f654-4ecb-a1a5-1cef54690953)

**Comment by yihong0618** [comment]
rm imported.json 
rm data.db

然后重新跑，别忘了加 --with-gpx

**Comment by linyinian** [comment]
> rm imported.json rm data.db
> 
> 然后重新跑，别忘了加 --with-gpx

命令返回没找到文件，我直接在目录里找到data.db手动删了。然后用token模式跑还是一样，最后用账号密码模式--with-gpx成功了。虽然看起来还是报了很多warning（正常？），但gpx_out有文件输出来了。

总之还是还是感谢大佬提供这么好的工具。咕咚广告太恶心又舍不得跑了8年的数据，终于能导出来了。
![WX20240111-140402](https://github.com/yihong0618/running_page/assets/39898791/0c6938d2-5650-466e-92c9-dd61c7133d5f)

**Comment by yihong0618** [comment]
> > rm imported.json rm data.db
> > 然后重新跑，别忘了加 --with-gpx
> 
> 命令返回没找到文件，我直接在目录里找到data.db手动删了。然后用token模式跑还是一样，最后用账号密码模式--with-gpx成功了。虽然看起来还是报了很多warning（正常？），但gpx_out有文件输出来了。
> 
> 总之还是还是感谢大佬提供这么好的工具。咕咚广告太恶心又舍不得跑了8年的数据，终于能导出来了。 ![WX20240111-140402](https://private-user-images.githubusercontent.com/39898791/295807212-0c6938d2-5650-466e-92c9-dd61c7133d5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NTQzODksIm5iZiI6MTcwNDk1NDA4OSwicGF0aCI6Ii8zOTg5ODc5MS8yOTU4MDcyMTItMGM2OTM4ZDItNTY1MC00NjZlLTkyYzktZGQ2MWM3MTMzZDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA2MjEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2Y2NkODA1OWQzMTY2YzFiNTJkOWVhZDBjNWRkZWM4MzIzYzg0OTZhNzI0YzRkOGVlY2EzYmUxOGMyNDA3YTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lGTnI22DlLJkvnyqeLkAEnbKhD6a_mu-BGIEyTpbRYg)

不客气

**Comment by yihong0618** [comment]
@linyinian  没有 gpx 的数据应该也在，但没有路径了。

**Comment by yihong0618** [comment]
先关了哈
