### ISSUE TITLE
Country parsing bug

### ISSUE THREAD

**Issue by NaturezzZ** [yihong0618/running_page#597]
This is my running page https://run.zhengnq.com. I have an activity in 2023-10-25 at Germany, but the running page shows that I have only run in one country. Is it the same bug as #292?
![run](https://github.com/yihong0618/running_page/assets/46887061/8a3821b1-e1a9-4da7-94a4-f533e802a875)
![runningpage](https://github.com/yihong0618/running_page/assets/46887061/44de1702-5db6-4de1-ab43-1e422c3332d2)

**Comment by yihong0618** [comment]
yes will take a look
