### ISSUE TITLE
About running stats

### ISSUE THREAD

**Issue by geekplux** [yihong0618/running_page#6]
I found the stats code in the scripts folder is from [GpxTrackPoster](https://github.com/flopp/GpxTrackPoster), is it possible to set it as a git submodule?

And the SVG produced by this module may set it as a page. There will be 2 or 3 links in navbar, and embed the SVG into the corresponding page. The best way, of course, is to visualize the stats data by front-end directly so that we could add some interaction, and SVG download would be just a feature then.

**Comment by yihong0618** [comment]
I changed some code of gpxtrackposter, and svg is interactive with map in “Total” so I think it is not a good way I will change it maybe later.
