### ISSUE TITLE
地图缩放的时候 LocationStat 和 YearsStat 文字会稍微跳动一下

### ISSUE THREAD

**Issue by sayidhe** [yihong0618/running_page#603]
看了一下是 `src/components/LocationStat/index.tsx` 里

```
 <div className="w-100-l pb5 pr5-l">
```

`src/components/YearsStat/index.tsx` 里

```
<div className="fl w-100-l pb5 pr5-l">
```

两个 className 不一致导致，**LocationStat** 少了一个 `fl` 这个 className

**Comment by yihong0618** [comment]
@sayidhe 如果测试没问题来个 PR?
