### ISSUE TITLE
高驰手表如何自动同步

### ISSUE THREAD

**Issue by Maiziii** [yihong0618/running_page#616]
你好，我部署了一套running_page在自己的阿里云服务器上。感谢作者，现在系统运行得挺好的。
想请教一下，如何实现高驰pace3数据自动同步到自己部署的running_page上呢？现在每次跑完步都需要在COROS APP导出GPX文件然后上传到服务器上，有点繁琐。

**Comment by ustccuikai** [comment]
高驰可以自动同步到strava，再通过strava同步到running_page就可以

**Comment by yihong0618** [comment]
@ustccuikai thanks

**Comment by haowei93** [comment]
> 你好，我部署了一套running_page在自己的阿里云服务器上。感谢作者，现在系统运行得挺好的。 想请教一下，如何实现高驰pace3数据自动同步到自己部署的running_page上呢？现在每次跑完步都需要在COROS APP导出GPX文件然后上传到服务器上，有点繁琐。

https://github.com/yihong0618/running_page/pull/623/  目前这个mr 支持 coros 设备自动生成， 可以试试
