### ISSUE TITLE
2.0版本的workflow里的git报错，可不可以提供一下解决方案。谢谢啦。

### ISSUE THREAD

**Issue by ohmykevin** [yihong0618/running_page#617]
![image](https://github.com/yihong0618/running_page/assets/160414940/01f2ed44-a3c8-408b-819b-5f03c741233f)

**Comment by yihong0618** [comment]
能提供下你项目的链接么？

**Comment by ohmykevin** [comment]
> 能提供下你项目的链接么？

抱歉 我换成了 另一个 fork 项目，目前正常。原来的暂时无法复现了。我先 close
