### ISSUE TITLE
求大佬考虑接入华为手环 华为运动

### ISSUE THREAD

**Issue by baixf-xyz** [yihong0618/running_page#62]

**Comment by yihong0618** [comment]
@baixf-xyz 不好意思，目前可能没太多精力研究华为数据，因为加密比较复杂。
但你可以用这个项目导出数据 https://github.com/CTHRU/Hitrava
可以生成你需要的数据 然后用 only gpx 生成你的网站。

如果我有精力和能力能搞定华为，我在这个 issue @ 你~

**Comment by baixf-xyz** [comment]
好的 蟹蟹




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yihong"<notifications@github.com&gt;; 
发送时间: 2020年12月14日(星期一) 晚上10:09
收件人: "yihong0618/running_page"<running_page@noreply.github.com&gt;; 
抄送: "707401057"<707401057@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [yihong0618/running_page] 求大佬考虑接入华为手环 华为运动 (#62)





 
@baixf-xyz 不好意思，目前可能没太多精力研究华为数据，因为加密比较复杂。
 但你可以用这个项目导出数据 https://github.com/CTHRU/Hitrava
 可以生成你需要的数据 然后用 only gpx 生成你的网站。
 
如果我有精力和能力能搞定华为，我在这个 issue @ 你~

**Comment by yihong0618** [comment]
@baixf-xyz https://github.com/yihong0618/running_page/issues/600
