### ISSUE TITLE
vercel部署失败 Error: spawn pip3 ENOENT 

### ISSUE THREAD

**Issue by Brightpan** [yihong0618/running_page#627]
Error: spawn pip3 ENOENT

**Comment by yihong0618** [comment]
有截图么

**Comment by jimrory** [comment]
![v](https://github.com/yihong0618/running_page/assets/13883429/b7faadd7-ff61-4ca9-9fb0-1c2c5eafc9e0)

**Comment by yihong0618** [comment]
升级 vercel 的 node 版本到 20

**Comment by yihong0618** [comment]
@all

merge 到最新代码，然后重新部署，选 vercel 中选 vite, node 版本大于 18

**Comment by yvetterowe** [comment]
Did upgrading node to 20.x fix this issue for anyone? Redeployment still failed but hit another gatsby error this time 
<img width="1194" alt="Screenshot 2024-03-24 at 5 31 09 PM" src="https://github.com/yihong0618/running_page/assets/5595281/ed9bbe5b-c2bf-4cab-9a96-6055abfb0ecc">

**Comment by yvetterowe** [comment]
Did upgrading node to 20.x fix this issue for anyone? Redeployment still failed on this error

**Comment by yihong0618** [comment]
> Did upgrading node to 20.x fix this issue for anyone? Redeployment still failed on this error

no, 
need backup data.db and merge the latest code maybe also need to reimport vercel gatsby never supported for vercel seems will do some dig this week

**Comment by yihong0618** [comment]
@all merge the latest commit maybe fix this
