### ISSUE TITLE
pnpm install 提示错误

### ISSUE THREAD

**Issue by gavenwan** [yihong0618/running_page#636]
在部署的时候第一步pip install 没有报错，第二步 nom install -g 这里会 提示报错，分解这条命令，实际是最后一句 pnpm install 报错，提示 this project  is configured by yarn

**Comment by yihong0618** [comment]
yarn install

**Comment by yihong0618** [comment]
我改下 readme

**Comment by yihong0618** [comment]
这个该怎么改好一些。
改成 yarn 的原因是 vercel @orionna319

**Comment by gavenwan** [comment]
我也尝试了yarn install，提示 fatal:unable to access "https://GitHub.com/tachyons-css/achyons-sass.git",，尝试多次也是如此，手动打开上述地址，是404的

**Comment by gavenwan** [comment]
手动忽略错误，继续yarn run build ，会提示vite不是内部程序；
如果用pnpm develop  会提示，this project is configured by yarn

**Comment by gavenwan** [comment]
pack里去掉tachyons-sass，然后yarn run build ,在文件夹里手动添加css后，成功build运行

**Comment by yihong0618** [comment]
我今晚看看

**Comment by yihong0618** [comment]
谢谢反馈

**Comment by orionna319** [comment]
有ci错误链接地址吗，我本地`yarn install && yarn build`，都是成功执行的。
<img width="534" alt="image" src="https://github.com/yihong0618/running_page/assets/85230052/cf406fad-e565-462a-b268-69abc6bdaa3d">

**Comment by orionna319** [comment]
是不是同步下最新的代码就好了

**Comment by yihong0618** [comment]
> 是不是同步下最新的代码就好了

我更新了下代码，https://github.com/yihong0618/running_page/pull/632 这个是因为 vercel 的问题。不知道是不是这个导致的

**Comment by gavenwan** [comment]
可能是，我手动改了package解决了问题就没有截图了。有空时我再试试重新下载最新包build一下。目前还在解决keep数据没能把我iphone 健身上的跑步同步完整的问题。

**Comment by yihong0618** [comment]
> 可能是，我手动改了package解决了问题就没有截图了。有空时我再试试重新下载最新包build一下。目前还在解决keep数据没能把我iphone 健身上的跑步同步完整的问题。

在issue里搜索，keep默认只有跑步。

**Comment by tianheg** [comment]
![image](https://github.com/yihong0618/running_page/assets/52186032/e743cf3d-ba09-4282-9ea1-a55dbcdcd5e5)

其实主要问题在于 tachyons 这个样式库，在 package.json 中不是通过版本号安装的，所以在 Vercel 上找不到。把 tachyons 相关代码删掉就行。

可以考虑换个样式库，比如 tailwind，但这是个大工程，短期内不太容易做到

**Comment by yihong0618** [comment]
> ![image](https://private-user-images.githubusercontent.com/52186032/319561181-e743cf3d-ba09-4282-9ea1-a55dbcdcd5e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzExOTAsIm5iZiI6MTcxMjIzMDg5MCwicGF0aCI6Ii81MjE4NjAzMi8zMTk1NjExODEtZTc0M2NmM2QtYmEwOS00MjgyLTllYTEtYTU1ZGJjZGNkNWU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDExNDEzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmZGUyMGFlYzNkNmE3NzQ2MWY4NWZkOGQ4MzZhMzQyNjYyZDU3ZmJmNTJhY2YyYWU5YzBmMmViMzk1MGYyZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cwtdIg-XLceKc0Z0aA83EzjMeKEkqtYMn91upPcyg28)
> 
> 其实主要问题在于 tachyons 这个样式库，在 package.json 中不是通过版本号安装的，所以在 Vercel 上找不到。把 tachyons 相关代码删掉就行。
> 
> ```json
> "tachyons-sass": "git+https://github.com/tachyons-css/tachyons-sass.git",
> ```
> 
> 可以考虑换个样式库，比如 tailwind，但这是个大工程，短期内不太容易做到

我们先删代码吧，有兴趣来个 PR 么？

**Comment by yihong0618** [comment]
> > 我们先删代码吧，有兴趣来个 PR 么？
> 
> 因为很多 CSS 样式是基于 tachyons 的，所以只删除 tachyons 会导致页面没有样式，就像下面这样 :) ![image](https://private-user-images.githubusercontent.com/52186032/319592638-e2040564-3f7e-4328-941d-cfb39f410838.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzYxNDksIm5iZiI6MTcxMjIzNTg0OSwicGF0aCI6Ii81MjE4NjAzMi8zMTk1OTI2MzgtZTIwNDA1NjQtM2Y3ZS00MzI4LTk0MWQtY2ZiMzlmNDEwODM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDEzMDQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwNWRiMGY4ZmEwMzcxMDM4NWNhYmQ2YWQ1MjJiZjQwMjU1M2JlYWI0OTE4YjgwYmE5ZmQ0NjMwZWVmYzIzN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TGMjn_y6l9OS5TonUTQ9kXCLYBx6M8CJ1QBR-l_0bdQ)
> 
> 需要重写样式代码才能完成这个工作

OK 我找找有 fork 没

**Comment by yihong0618** [comment]
> ```json
> https://github.com/tachyons-css/tachyons-sass.git
> ```

我们可以 fork 一个自己发 npm 对吧？

**Comment by tianheg** [comment]
可以，这样只需要换这个包就行了

**Comment by yihong0618** [comment]
好的。你有兴趣搞一个么？

- fork tachyons-css to tachyons-css-fork
- new package tachyons-css-fork-${version}
- push to npm
- change the running_page tachyons-css package

**Comment by tianheg** [comment]
> 好的。你有兴趣搞一个么？

好呀，我现在就可以做

**Comment by tianheg** [comment]
yihong 哥，还有个问题不太明白。Pnpm 用着不是挺好的吗，怎么就改用 Yarn 了。这个包管理器改来改去的，其实也没必要。

**Comment by yihong0618** [comment]
> yihong 哥，还有个问题不太明白。Pnpm 用着不是挺好的吗，怎么就改用 Yarn 了。这个包管理器改来改去的，其实也没必要。

因为 vercel 报错。。。它自动用的 yarn

**Comment by tianheg** [comment]
那现在是用 Yarn 还是 Pnpm 呢，tachyons-sass 的问题解决了，Vercel 部署就没问题了吧，我自己测试过了没有错误

**Comment by yihong0618** [comment]
> 那现在是用 Yarn 还是 Pnpm 呢，tachyons-sass 的问题解决了，Vercel 部署就没问题了吧，我自己测试过了没有错误 ![image](https://private-user-images.githubusercontent.com/52186032/319626902-e4e091f7-3554-4b8c-b98d-3530af282054.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNjg1ODcsIm5iZiI6MTcxMjI2ODI4NywicGF0aCI6Ii81MjE4NjAzMi8zMTk2MjY5MDItZTRlMDkxZjctMzU1NC00YjhjLWI5OGQtMzUzMGFmMjgyMDU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDIyMDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyYzJhN2M1NjgzMzk4YmI3MTkxMjcwZmE5YTEzOWQ5MTYyNDlhYmVjYmUxZDE5N2QyYjFiNzk2YzlkZWFhMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7A08SPwTl-IDI9-MkBvDlVxiQG2n6fciDCVm6_qbTzw)

我研究研究能一起用不。。
