### ISSUE TITLE
请教为什么国家解析不对

### ISSUE THREAD

**Issue by gavenwan** [yihong0618/running_page#637]
地图上显示确实有其他国家的路线，但是统计里仍然显示“1个国家”，是不是在src/static/run_countries 添加这个国家的地理围栏数据才可以？

**Comment by yihong0618** [comment]
项目开源么？链接发一下？

**Comment by gavenwan** [comment]
> 项目开源么？链接发一下？

https://wenxiaowan.com

**Comment by gavenwan** [comment]
> 项目开源么？链接发一下？

https://wenxiaowan.com 
比如2024/2/17 的记录，是在新加坡，但是并没有解析为国家

**Comment by yihong0618** [comment]
我看看。

**Comment by SongJgit** [comment]
我也遇到了这个问题。
strava同步下来的好多数据location_country都仅仅显示了China，而没有详细的省份之类的信息。
但是实际上在strava中是正常的，

两条信息都是strava中同步下来的，但是一条是keep传到strava(act.json中有详细位置)，一条是garmin传到strava(act.json中没有详细位置)
对应有的
```
"distance": 9993.1,
"moving_time": "0:52:51",
"type": "Run",
"start_date": "2024-03-30 23:47:56+00:00",
"start_date_local": "2024-03-31 07:47:56",
"location_country": "*******************(代替相信信息)",
```
strava标题显示2024年3月31日 星期日 上午7:47 中山街道, 河北省
石家庄马拉松十公里

对应没的
```
"distance": 35823.7,
"moving_time": "1:10:30",
"type": "Ride",
"start_date": "2023-08-06 12:29:01+00:00",
"start_date_local": "2023-08-06 20:29:01",
"location_country": "China",
```
2023年8月6日 星期日 下午8:29 柳青街道, 山东省
傍晚骑行

**Comment by SongJgit** [comment]
两条数据在网页的地图中都是有正常的轨迹并且正确的，仅仅只是缺失了location_country.

**Comment by yihong0618** [comment]
> 我也遇到了这个问题。 strava同步下来的好多数据location_country都仅仅显示了China，而没有详细的省份之类的信息。 但是实际上在strava中是正常的，
> 
> 两条信息都是strava中同步下来的，但是一条是keep传到strava(act.json中有详细位置)，一条是garmin传到strava(act.json中没有详细位置) 对应有的
> 
> ```
> "distance": 9993.1,
> "moving_time": "0:52:51",
> "type": "Run",
> "start_date": "2024-03-30 23:47:56+00:00",
> "start_date_local": "2024-03-31 07:47:56",
> "location_country": "*******************(代替相信信息)",
> ```
> 
> strava标题显示2024年3月31日 星期日 上午7:47 中山街道, 河北省 石家庄马拉松十公里
> 
> 对应没的
> 
> ```
> "distance": 35823.7,
> "moving_time": "1:10:30",
> "type": "Ride",
> "start_date": "2023-08-06 12:29:01+00:00",
> "start_date_local": "2023-08-06 20:29:01",
> "location_country": "China",
> ```
> 
> 2023年8月6日 星期日 下午8:29 柳青街道, 山东省 傍晚骑行

这个应该可以手动更改？

**Comment by yihong0618** [comment]
我可以写个脚本把没国家的都加上国家。。。

**Comment by SongJgit** [comment]
我似乎已经找到了问题。
似乎是因为在墙内？
因为我自己手动试了一下。
geopy会直接超时，然后我回想了一下，没有地理信息的那些是我本地同步的，所以解析出了问题。

**Comment by yihong0618** [comment]
> 我似乎已经找到了问题。 似乎是因为在墙内？ 因为我自己手动试了一下。 geopy会直接超时，然后我回想了一下，没有地理信息的那些是我本地同步的，所以解析出了问题。

是的。。这个需要梯子

**Comment by andyoung009** [comment]
您好，我跑步的数据是从 joyrun 中导出的，全局梯子情况下拉取的数据并生成相关的svg文件，最终的页码中国家解析和城市数量有误差，请教可能存在其他的原因吗？
我后续做了检查和验证，发现悦跑圈在数据导出时形成的 activities.json 中的定位的信息似乎有些问题，\u547c\u548c\u6d69\u7279:\u5185\u8499\u53e4\u81ea\u6cbb\u533a 似乎直接被当作了国家，然后就显示跑过8个国家，同时也缺少经纬度的定位信息（我用keep跑了下发现其对应的 json文件中有这些），这些貌似共同导致了国家和省份城市数量的问题，另外我想请教下地图渲染是和经纬度相关的吗？
