### ISSUE TITLE
gpx文件未生成

### ISSUE THREAD

**Issue by netyjq** [yihong0618/running_page#640]
您好，非常感谢您这个项目对我的帮助。

我在阅读文档和issue后，依然无法解决这个问题。

运行的脚本参考的文档，测试能正常抓取记录，界面上也有数据，问题 出在GPX_OUT目录下  无数据，删除db测试多次依然不生效，不知道是不是操作不当，还是有其他需要配置，恳请答复，谢谢！

python3 run_page/keep_sync.py ${your mobile} ${your password} --with-gpx

**Comment by yihong0618** [comment]
这个只有跑步数据，如果不是跑步请在 issue 中搜索骑行

**Comment by netyjq** [comment]
> 这个只有跑步数据，如果不是跑步请在 issue 中搜索骑行

没错，我确实想导出的骑行的数据，api地址 已经修改为骑行了，请问下还有其他配置项需要修改吗？

# need to test
LOGIN_API = "https://api.gotokeep.com/v1.1/users/login"
RUN_DATA_API = "https://api.gotokeep.com/pd/v3/stats/detail?dateUnit=all&type=cycling&lastDate={last_date}"
RUN_LOG_API = "https://api.gotokeep.com/pd/v3/cyclinglog/{run_id}"

**Comment by yihong0618** [comment]
应该可以用了

**Comment by netyjq** [comment]
貌似这样还不行，我之前就是在已经配置了api地址的情况下，导出不了 gpx 文件，所以在才这里寻求帮助

**Comment by netyjq** [comment]
<img width="819" alt="image" src="https://github.com/yihong0618/running_page/assets/13848223/06b1ba1f-3d48-4589-9aec-0d923e00a88c">

没有看到有帮助的提示

**Comment by netyjq** [comment]
<img width="864" alt="image" src="https://github.com/yihong0618/running_page/assets/13848223/8445091a-dd55-43b2-b91b-cc7dfe0eb868">

image
没有看到有帮助的提示

**Comment by yihong0618** [comment]
rm imported.json
rm run_page/data.db

之后重新跑

**Comment by netyjq** [comment]
imported.json 这个文件不存在，run_page/data.db 这个文件已经删除了，重新执行了一遍 python3 run_page/keep_sync.py ${your mobile} ${your password} --with-gpx   依然没看到 GPX_OUT目录下 产生 gpx文件

**Comment by yihong0618** [comment]
搜索这句，然后把这句删了，重复上面步骤试试
and run_data["dataType"] == "outdoorRunning"

**Comment by netyjq** [comment]
感谢，成功了！！
