### ISSUE TITLE
localhost拒绝访问

### ISSUE THREAD

**Issue by yyniao** [yihong0618/running_page#641]
你好，我是一个小白。请问在使用 Strava 授权是遇到 localhost 拒绝连接的错误该如何处理。尝试换了localhost
![截屏2024-04-08 00 29 09](https://github.com/yihong0618/running_page/assets/35762396/55aac785-6570-4a6d-9492-21b437330159)
![截屏2024-04-08 00 30 17](https://github.com/yihong0618/running_page/assets/35762396/082ff814-fbd0-40bb-9591-a934adc3acde)

**Comment by yihong0618** [comment]
仔细阅读 readme 这里是正常的，浏览器网址里有你要的东西

**Comment by yyniao** [comment]
> 仔细阅读 readme 这里是正常的，浏览器网址里有你要的东西

抱歉，没有看清楚。谢谢你的回复。我解决了疑惑。
