### ISSUE TITLE
資安疑慮：Mapbox token 只能明碼寫在`const.ts`中？

### ISSUE THREAD

**Issue by changchiyou** [yihong0618/running_page#643]
https://github.com/yihong0618/running_page/blob/e05b665865af61071eab78d042cf9257b38fef9f/src/utils/const.ts#L3

**Comment by yihong0618** [comment]
嗯，对

**Comment by changchiyou** [comment]
@yihong0618 我隨意問了下 ChatGPT https://chat.openai.com/share/1db41f61-a363-44fb-a63a-a5701e922bf4 ，請問這是可行的嗎？

如果並非架構問題 / 以前有踩過無法處理的坑，那我會想試試看發 PR 來處理這個問題。

**Comment by yihong0618** [comment]
> @yihong0618 我隨意問了下 ChatGPT https://chat.openai.com/share/1db41f61-a363-44fb-a63a-a5701e922bf4 ，請問這是可行的嗎？
> 
> 如果並非架構問題 / 以前有踩過無法處理的坑，那我會想試試看發 PR 來處理這個問題。

抱歉哈我忘了，这个 mapbox 怎么处理的了（这块两年没改了），理论上不需要改，我晚上研究研究。

PR welcome

**Comment by orionna319** [comment]
如果觉得有安全问题的话，可以放在[settings/secrets/actions](https://docs.github.com/en/actions/learn-github-actions/variables)。然后在`const.ts`文件中读取`secrets`，欢迎PR。

**Comment by orionna319** [comment]
如果读取不到尽量给一个默认值，向前兼容。

**Comment by changchiyou** [comment]
@yihong0618 @orionna319 感謝回復，我晚點處理看看

**Comment by changchiyou** [comment]
- https://stackoverflow.com/a/21941683
- https://stackoverflow.com/a/61857467

好像不管如何都避不開

**Comment by changchiyou** [comment]
1. 參考

    1. https://docs.mapbox.com/help/getting-started/access-tokens/#url-restrictions
       
       <img width="680" alt="image" src="https://github.com/yihong0618/running_page/assets/46549482/52403a62-bcfe-41e8-9e07-234614ef7beb">
    
    2. https://docs.mapbox.com/accounts/guides/tokens/#url-restrictions
    
       <img width="680" alt="image" src="https://github.com/yihong0618/running_page/assets/46549482/8df18571-f90d-47d8-b726-2d1dc3122c53">
  
    到 [Account | Mapbox - Tokens ](https://account.mapbox.com/access-tokens/) 新增一個 token:
    
    <img width="680" alt="image" src="https://github.com/yihong0618/running_page/assets/46549482/38c372c4-726b-4b1f-ae70-764d3647b812">

2. 並參考

    <img width="634" alt="image" src="https://github.com/yihong0618/running_page/assets/46549482/c831b4ee-4899-4f21-8ff1-8b1711da9b3b">

   中的`Origin:
https://changchiyou.github.io`設置`URLs`

    <img width="680" alt="image" src="https://github.com/yihong0618/running_page/assets/46549482/510dae6a-3d5a-4209-a8d2-ab32211d4d51">
    <img width="680" alt="image" src="https://github.com/yihong0618/running_page/assets/46549482/f72893a5-456b-4f29-a0ee-aeb1f03d58cd">

3. push commit 更新 Mapbox token https://github.com/changchiyou/running_page/commit/c33d7f56641f4fe77cfa585183ce79bf3a67acb8
4. 手動執行 [Run Data Sync](https://github.com/changchiyou/running_page/actions/runs/8599836186) Github Action:
   <img width="1086" alt="image" src="https://github.com/yihong0618/running_page/assets/46549482/577bf1e0-abca-4a96-b83b-dae052682e02">
5. （✅ 成功）shift+command+R 重整頁面 https://changchiyou.github.io/running_page/
6. （✅ 成功: 理應失敗，因為沒有從指定的 origin URL 發 request）curl `2.`中的 request:

    ```
    curl https://api.mapbox.com/v4/mapbox.mapbox-streets-v8,mapbox.mapbox-terrain-v2.json\?secure\&access_token\=pk.eyJ1IjoiY2hhbmdjaGl5b3UiLCJhIjoiY2x1cXd2MWRxMDExZzJqcXJyNTVjbnVwOSJ9.hOsDM-tbwwCAAsDHWHYkFQ
    ```

   <img width="804" alt="image" src="https://github.com/yihong0618/running_page/assets/46549482/f5c668ce-0f27-4254-a6a6-86ebcb87b6bc">

**Comment by changchiyou** [comment]
@yihong0618 @orionna319 看起來確實如 https://github.com/yihong0618/running_page/issues/643#issuecomment-2041976662 所說不用重構專案，但需要根據 https://github.com/yihong0618/running_page/issues/643#issuecomment-2042668580 更新`README.md` / 於`src/utils/const.ts`對應位置上新添加提示 command

**Comment by orionna319** [comment]
好像是的，就算存储在`settings/secrets`中，在web端也会显示调用`MAPBOX_TOKEN`
> 如果想藉由改動專案結構來處理這問題，好像不管如何都避不開

**Comment by orionna319** [comment]
当然最好的方案我理解是，`MAPBOX_TOKEN`放在`settings/secrets`下，然后再设置`Mapbox-URLs`。

**Comment by changchiyou** [comment]
> 当然比较好的处理方式是，`MAPBOX_TOKEN`放在`settings/secrets`下，然后再设置`Mapbox-URLs`。

確實，資安不求完美但也不嫌多，這樣的做法雖說不能避免從瀏覽器開發者工具看到 Mapbox token，但確實能避免明碼將 token 寫在 repo 中（滿足包含我在內一部分對資安比較敏感開發者的強迫症 🤣）。
