### ISSUE TITLE
使用--with-tcx参数获取咕咚数据，导出来的TCX文件导入Garmin还是会提示报错无法导入

### ISSUE THREAD

**Issue by Sunnyone2three** [yihong0618/running_page#645]
如题

**Comment by Vensent** [comment]
亲测了一下咕咚导出的tcx文件存在一些异常哈，后续我发一个pr应该可以解决，tcx必须指定你的device，并且正确，才可以。
![image](https://github.com/yihong0618/running_page/assets/7401921/5cd0bdb0-4c41-4720-a94c-da6571689263)
