### ISSUE TITLE
我发现 Run Data Sync.yaml 在跑的时候-Garmin_cn 执行就死循环了

### ISSUE THREAD

**Issue by cigar** [yihong0618/running_page#648]
![Uploading CleanShot 2024-04-11 at 21.22.29@2x.png…]()

**Comment by yihong0618** [comment]
图挂了

**Comment by yihong0618** [comment]
> ![CleanShot 2024-04-11 at 21 22 29@2x](https://private-user-images.githubusercontent.com/389157/321912735-41044c71-6a31-4372-9932-b473e255308e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5MTA2OTcsIm5iZiI6MTcxMjkxMDM5NywicGF0aCI6Ii8zODkxNTcvMzIxOTEyNzM1LTQxMDQ0YzcxLTZhMzEtNDM3Mi05OTMyLWI0NzNlMjU1MzA4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMlQwODI2MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYmRlNjMyMWU3ZTFmNjc4MjhmMjkwZTc3MDA3MTk0NWM2Zjg0MWQyZGY0M2Y5ZDA4NDhiODFkZjM0YmU5YzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T89RrZPqHCVCP_opQfqnoQBm6QAfS8GUmT1GT0h_j_g)

will check that did you merge the latest code?

**Comment by cigar** [comment]
Yes, i did clone a new repo from you, and it failed again while **Install dependencies**
![CleanShot 2024-04-12 at 21 09 33@2x](https://github.com/yihong0618/running_page/assets/389157/81ed97e0-4023-4309-b6f0-5fe460d72260)

**Comment by cigar** [comment]
[logs_22700153147.zip](https://github.com/yihong0618/running_page/files/14959167/logs_22700153147.zip)
Please find attached the log for your reference so that you can audit the issues.
thank you!

**Comment by tianheg** [comment]
I know what's going on, when install packages use `pnpm install`, need add `--no-frozen-lockfile`

**Comment by cigar** [comment]
Thanks, @tianheg, offered the help. After that, there is a new issue happens the next process like the below:
![Run Data Sync · cigarrunning@5efd80f](https://github.com/yihong0618/running_page/assets/389157/33ec1dce-da07-4645-918c-cc48555586f7)
[logs_22724478853.zip](https://github.com/yihong0618/running_page/files/14965681/logs_22724478853.zip)

**Comment by yihong0618** [comment]
> Thanks, @tianheg, offered the help. After that, there is a new issue happens the next process like the below: ![Run Data Sync · cigarrunning@5efd80f](https://private-user-images.githubusercontent.com/389157/322186423-33ec1dce-da07-4645-918c-cc48555586f7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTQ2MTQsIm5iZiI6MTcxMjk5NDMxNCwicGF0aCI6Ii8zODkxNTcvMzIyMTg2NDIzLTMzZWMxZGNlLWRhMDctNDY0NS05MThjLWNjNDg1NTU1ODZmNy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QwNzQ1MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYWRmMDZiNzMwMTVhNjdhMGM2M2E5YWNkZDJkMGIyMTljOTAxMzg4ZjIwNzE0ZTVhZGZmMGE1YTU0ZmE4NGQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.EqvWTCzTorI22Y_F2Hd-1rMFn-B7X9_uAQYV_CcOTCc) [logs_22724478853.zip](https://github.com/yihong0618/running_page/files/14965681/logs_22724478853.zip)

you need open write in setting

**Comment by cigar** [comment]
That's great. It worked!
Thanks to all of you!
