### ISSUE TITLE
可以提供一个部署的步骤吗

### ISSUE THREAD

**Issue by youxiaodao** [yihong0618/running_page#65]
1. 我将代码拉倒服务器，执行了yarn build ，执行了同步佳明数据，使用nginx做了代理，但是访问到的还是作者的数据

**Comment by yihong0618** [comment]
> 1. 我将代码拉倒服务器，执行了yarn build ，执行了同步佳明数据，使用nginx做了代理，但是访问到的还是作者的数据

GPX 数据都同步成功了么？

你需要在本地同步完之后执行 佳明的命令，然后传到服务器。
本地可以用 gatsby develop 进行测试。
然后访问 127.0.0.1:8000 看是否成功。

部署的话可以选择 vercel.

**Comment by youxiaodao** [comment]
> 
> 
> > 1. 我将代码拉倒服务器，执行了yarn build ，执行了同步佳明数据，使用nginx做了代理，但是访问到的还是作者的数据
> 
> GPX 数据都同步成功了么？
> 
> 你需要在本地同步完之后执行 佳明的命令，然后传到服务器。
> 本地可以用 gatsby develop 进行测试。
> 然后访问 127.0.0.1:8000 看是否成功。
> 
> 部署的话可以选择 vercel.
我执行garmin同步数据的脚本后显示如此
Syncing Activity IDs
Syncing Activity IDs
Syncing Activity IDs
Syncing Activity IDs
0 new activities to be downloaded
Download finished. Elapsed 4.7206878662109375e-05 seconds
355
Something went wrong when loading GPX. for file 115382114.gpx
Something went wrong when loading GPX. for file 93858615.gpx

**Comment by yihong0618** [comment]
> 步完之后执行 佳明的命令，

yarn install 
gatsby develop 试试

**Comment by geekplux** [comment]
@youxiaodao 数据部分用python获取好之后，部署到自己到服务器可参考 https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/ 官方文档

**Comment by youxiaodao** [comment]
> 
> 
> @youxiaodao 数据部分用python获取好之后，部署到自己到服务器可参考 https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/ 官方文档

谢谢指导，我做一下

**Comment by youxiaodao** [comment]
> 
> 
> > 步完之后执行 佳明的命令，
> 
> yarn install
> gatsby develop 试试

按照您说的，我在本地运行成功了，再请问
1. scripts/garmin_sync.py 如何拉取佳明所有的数据，或者指定时间的数据
2. 如果我用vercel进行部署，我是不是可以直接用我本地已经成功运行的代码pull到我的仓库，然后进行vercel的操作，这中间需不要要我删除或者添加某些原作者的历史数据

**Comment by yihong0618** [comment]
> > > 步完之后执行 佳明的命令，
> > 
> > 
> > yarn install
> > gatsby develop 试试
> 
> 按照您说的，我在本地运行成功了，再请问
> 
> 1. scripts/garmin_sync.py 如何拉取佳明所有的数据，或者指定时间的数据
> 2. 如果我用vercel进行部署，我是不是可以直接用我本地已经成功运行的代码pull到我的仓库，然后进行vercel的操作，这中间需不要要我删除或者添加某些原作者的历史数据


1. 你拉取的就是所有数据，指定时间暂时不支持，也不在支持计划，因为和自动化冲突不好意思
2. 这里没有历史数据了，只只需要改一些 config 的信息，可 GitHub Actions yml 中的信息，当然你还得参考 readme 改一下 secrets 如果你想自动化的话。

**Comment by youxiaodao** [comment]
>     2\. ，只只需要改一些 config 的信息，可 GitHub Actions yml 中的信息

1. 我建立了自己的config.yaml文件
2. 我创建了自己Gamin账号的secret
3. 然后在vercel导入，成功后还是原来的数据
4. 下面是我的截图
![图片](https://user-images.githubusercontent.com/40420602/102471754-8e315c80-4090-11eb-8e2c-c370adfe5eaf.png)
![图片](https://user-images.githubusercontent.com/40420602/102471822-a0ab9600-4090-11eb-99d2-1ad2c6b52cca.png)
![图片](https://user-images.githubusercontent.com/40420602/102471918-b8831a00-4090-11eb-9070-67c0f1c1bc0c.png)
![图片](https://user-images.githubusercontent.com/40420602/102472315-27607300-4091-11eb-8494-7809bd21ba47.png)

请教，我是否有操作错误或者遗漏的地方

**Comment by yihong0618** [comment]
@youxiaodao 
先生成所有数据然后 push 到你的repo里

**Comment by yihong0618** [comment]
Close now.

**Comment by shog86** [comment]
> @youxiaodao 先生成所有数据然后 push 到你的repo里

请问vercel部署了，也获取了refersh token，在哪里操作才能首次同步数据到我fork的git项目里呢？

**Comment by yihong0618** [comment]
> > @youxiaodao 先生成所有数据然后 push 到你的repo里
> 
> 请问vercel部署了，也获取了refersh token，在哪里操作才能首次同步数据到我fork的git项目里呢？

设置 secret 到 GitHub Actions 里跑（参考 README 设置 Github Actions

**Comment by shog86** [comment]
> > > > 步完之后执行 佳明的命令，
> > > 
> > > 
> > > yarn install
> > > gatsby develop 试试
> > 
> > 
> > 按照您说的，我在本地运行成功了，再请问
> > 
> > 1. scripts/garmin_sync.py 如何拉取佳明所有的数据，或者指定时间的数据
> > 2. 如果我用vercel进行部署，我是不是可以直接用我本地已经成功运行的代码pull到我的仓库，然后进行vercel的操作，这中间需不要要我删除或者添加某些原作者的历史数据
> 
> 1. 你拉取的就是所有数据，指定时间暂时不支持，也不在支持计划，因为和自动化冲突不好意思
> 2. 这里没有历史数据了，只只需要改一些 config 的信息，可 GitHub Actions yml 中的信息，当然你还得参考 readme 改一下 secrets 如果你想自动化的话。

是说把${{ secrets.STRAVA_CLIENT_ID }} 替换成 1xxxx的数字吗，还是说${{ secrets.1xxxx}}？这儿说得不太明白

**Comment by shog86** [comment]
哦，明白了，是在action参数那儿加这些！

**Comment by shog86** [comment]
不过设置的位置好像有变化，在Security下面

**Comment by shog86** [comment]
我好像没看懂在哪里改Action的Github token。。。

**Comment by shog86** [comment]
<img width="331" alt="image" src="https://github.com/yihong0618/running_page/assets/19712631/9c4ae720-4f72-497f-b6d8-03eab8fb89b5">
看来各种secrets要放到repo下面，而不是env
