### ISSUE TITLE
为什么数据库删除的数据前端还是有

### ISSUE THREAD

**Issue by gavenwan** [yihong0618/running_page#657]
通过数据库浏览工具删除了data.db中的一些记录；
然后yarn vite build  以及生成3个图标，生成图标时提示的track记录数量是我删除后的数量；

但是，最后生成的前端页面，选择年份，仍然有这条记录。

开始以为是我浏览器的缓存问题，但是清空浏览器，用本地调试浏览和部署到cloudflare浏览，都还是有这条记录；
查看生成的asset的activate里面，也确实有这条数据。
实在不能理解这个数据怎么来的？

是因为数据库删除了也有缓存吗？我打开数据库，尝试压缩数据库再生成也并没有变化

**Comment by yihong0618** [comment]
再跑一次 run_data_sync
