### ISSUE TITLE
Cloudflare 部署的是作者演示画面

### ISSUE THREAD

**Issue by gavenwan** [yihong0618/running_page#658]
我按教程操作
1、github repo
2、cloudflare 新建pages 关联到github repo
3、pages里 设置环境变量python3.8和构建命令 npm run build
4、构建，提示成功
5、打开page，显示的是作者的演示画面。
6、修改了sitemeta文件，cloudflare重新构建并显示了修改
重点：在github上修改了run_data_sync.yml ，github action执行后github画面更新为我的数据了；但是cloudflare构建后仍然是演示数据。重复多次构建，仍然是演示数据。
请问一下cloudflare这样部署是没办法和github数据同步吗？怎样让cloudflare部署的数据不是演示数据尼

**Comment by yihong0618** [comment]
1. 是同步的
2. 理论上应该跟 GitHub 一样是你的数据。

**Comment by gavenwan** [comment]
> 1. 是同步的
> 2. 理论上应该跟 GitHub 一样是你的数据。

感谢，那肯定是我哪步操作有问题，我再去琢磨

**Comment by gavenwan** [comment]
> 是不是因为这里 https://github.com/gavenwan/running_page/actions/runs/8705624172/job/23876414423#step:8:25 ，没有新的跑步数据加入
> 
> 我看这个 GitHub pages 上有页面，这个的数据是准确的吗 https://gavenwan.github.io/running_page/

是的，GitHub这个页面数据是准确的

**Comment by gavenwan** [comment]
> 是不是因为这里 https://github.com/gavenwan/running_page/actions/runs/8705624172/job/23876414423#step:8:25 ，没有新的跑步数据加入
> 
> 我看这个 GitHub pages 上有页面，这个的数据是准确的吗 https://gavenwan.github.io/running_page/

你的意思是，因为我的keep同步数据没有更新，所以没能触发cloudflare与github同步前端页面，是这样理解吗？
因为我没搞清楚github action生成的前端页面去哪儿了以及怎么和cloudflare同步的（设置里是dist文件夹，但是这个项目的文件夹里没找到dist文件夹）

**Comment by tianheg** [comment]
> 你的意思是，因为我的keep同步数据没有更新，所以没能触发cloudflare与github同步前端页面，是这样理解吗？

是的

我发现可能是这里出现了问题：

```yml
  SAVE_DATA_IN_GITHUB_CACHE: true # if you deploy in the vercal, check the README
  DATA_CACHE_PREFIX: 'track_data'
  BUILD_GH_PAGES: true # If you do not need GitHub Page please set it to `false`
```

你应该把 `SAVE_DATA_IN_GITHUB_CACHE` 和 `BUILD_GH_PAGES`，都设为 false。这样你就会触发这个 job step：

```yml
      - name: Push new runs
        if: env.SAVE_DATA_IN_GITHUB_CACHE != 'true'
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git add .
          git commit -m 'update new runs' || echo "nothing to commit"
          git push || echo "nothing to push"
```

它会更新你的 src/static/activities.json 文件，这样你的 Cloudflare Pages 上的网页就可以自动更新了

**Comment by gavenwan** [comment]
> > 你的意思是，因为我的keep同步数据没有更新，所以没能触发cloudflare与github同步前端页面，是这样理解吗？
> 
> 是的
> 
> 我发现可能是这里出现了问题：
> 
> ```yaml
>   SAVE_DATA_IN_GITHUB_CACHE: true # if you deploy in the vercal, check the README
>   DATA_CACHE_PREFIX: 'track_data'
>   BUILD_GH_PAGES: true # If you do not need GitHub Page please set it to `false`
> ```
> 
> 你应该把 `SAVE_DATA_IN_GITHUB_CACHE` 和 `BUILD_GH_PAGES`，都设为 false。这样你就会触发这个 job step：
> 
> ```yaml
>       - name: Push new runs
>         if: env.SAVE_DATA_IN_GITHUB_CACHE != 'true'
>         run: |
>           git config --local user.email "${{ env.GITHUB_EMAIL }}"
>           git config --local user.name "${{ env.GITHUB_NAME }}"
>           git add .
>           git commit -m 'update new runs' || echo "nothing to commit"
>           git push || echo "nothing to push"
> ```
> 
> 它会更新你的 src/static/activities.json 文件，这样你的 Cloudflare Pages 上的网页就可以自动更新了

感谢，实测了一下，将两个参数都设置为false，然后action运行一次，会自动下载keep所有数据，触发sync任务，未触发building github page任务，但是cloudflare那边没有触发重建任务，前端页面也并未发生变化。泪水

**Comment by gavenwan** [comment]
可能是data_sync的设置原因，目前已解决
