### ISSUE TITLE
Can't get  nike refresh_token

### ISSUE THREAD

**Issue by fengzhao** [yihong0618/running_page#660]
I have an new nike account in US， and the network is  already outside GFW , But can't Login this [website](https://unite.nike.com/s3/unite/mobile.html?androidSDKVersion=3.1.0&corsoverride=https%3A%2F%2Funite.nike.com&uxid=com.nike.sport.running.droid.3.8&backendEnvironment=identity&view=login&clientId=VhAeafEGJ6G8e9DxRUz8iE50CZ9MiJMG), 
the response like this 

```
Access Denied
You don't have permission to access "http://unite.nike.com/login?" on this server.
Reference #18.8c6ad117.1713341016.1c912fc

https://errors.edgesuite.net/18.8c6ad117.1713341016.1c912fc

```

**Comment by fengzhao** [comment]
It seems  Nike has blocked My  proxy IDC's IP band ?  So I need to find a pure united stats IP ?

**Comment by yihong0618** [comment]
nike may be in the pass config if you are using clash config(for some)
you can check that.
I will take a look this weekend

**Comment by yihong0618** [comment]
> It seems Nike has blocked My proxy IDC's IP band ? So I need to find a pure united stats IP ?

yes
