### ISSUE TITLE
数据库的地区格式不统一影响吗

### ISSUE THREAD

**Issue by gavenwan** [yihong0618/running_page#661]
我因为有部分数据是gpx，部分是keep
解析完成后，看db数据库里

gpx解析后的location_country 字段是纯文本，例如
`莫平山镇, 德清县, 湖州市, 浙江省, 中国`

keep解析后的location_country字段是对象json，例如
`{'latitude': 40.083184, 'longitude': 113.373578, 'country': '中国', 'nationCode': '156', 'province': '山西省', 'city': '大同市', 'cityCode': '0352', 'district': None, 'districtCode': None}`

这个会影响最后前台页面的显示吗？是不是gpx_sync的location_country解析后数据格式与keep解析后的格式统一比较好？

**Comment by yihong0618** [comment]
> 这个完全没有必要担心，写入数据库的时候是统一的。 大部分的流程都是： 数据(无论来自哪里) -> data.db -> activities.json -> display

谢谢，是的有一步是利用 GPX 强行统一
但现在有一点不好，那个接口被墙了
