### ISSUE TITLE
咨询下docker的工作原理

### ISSUE THREAD

**Issue by QQ-War** [yihong0618/running_page#665]
我是用的opentracks记录的，然后直接导出的GPX文件。

想问一下 ：
1. build的时候，是要先git clone下来，然后把GPX文件放到GPX_OUT目录，然后再进行build?
----应该是这样：build的下面这个地方，应该要加上RUN python3 run_page/gpx_sync.py，才行：
https://github.com/yihong0618/running_page/blob/5d84bd4a8aeb52babef8beefec6a825946b4ff2b/Dockerfile#L56

2. 容器已经running了，后续如果再往GPX_OUT目录更新文件，这个页面会相应更新吗？如果不会，有办法让它更新吗？

看了一下这个已经起来的container，这里面的内容都是静态的吗？

```
# docker exec  -it running_page ls -la /usr/share/nginx/html
total 32
drwxr-xr-x    1 root     root          4096 Apr 22 00:13 .
drwxr-xr-x    1 root     root          4096 Apr 17 16:52 ..
-rw-r--r--    1 root     root           497 Apr 16 15:47 50x.html
drwxr-xr-x    1 root     root          4096 Apr 22 00:13 assets
drwxr-xr-x    2 root     root          4096 Apr 22 00:13 images
-rw-r--r--    1 root     root           617 Apr 22 00:13 index.html
-rw-r--r--    1 root     root          4927 Apr 22 00:13 manifest.json
```

**Comment by yihong0618** [comment]
你可以查詢下如何映射 docker 文件夾。如果映射了就可以
