### ISSUE TITLE
请教， 开始从咕咚拉数据的时，没有带 --with-gpx，后续怎么得到GPX数据

### ISSUE THREAD

**Issue by sztuxp** [yihong0618/running_page#671]
重新带 --with-gpx 跑， 会提示如下信息：
your refresh_token and user_id are 485xxxxx 40xxxxxxxxx
120 runs to parse
No tracks found

**Comment by sztuxp** [comment]
非常感谢！这么快回复，没想到

**Comment by yihong0618** [comment]
哈哈哈 enjoy it
