### ISSUE TITLE
如何把国家涂上色

### ISSUE THREAD

**Issue by gavenwan** [yihong0618/running_page#673]
请教大家如何给国家也像省份一样涂上色。
如图，数据显示3个国家，但是最大缩放下只有省份涂色了，有没有办法把跑过的国家涂上色，我查看了原始代码，地图部分都是mapbox集成了，没找到怎么渲染涂色的
![1716283032001](https://github.com/yihong0618/running_page/assets/37296420/f00cc6c8-6908-4f8d-ad7d-aad1b79d82da)

**Comment by yihong0618** [comment]
你那日本不是涂颜色了么

**Comment by gavenwan** [comment]
> 你那日本不是涂颜色了么

原来那个是涂色后的效果呀，那个颜色是在哪里修改呀，想改成更明亮点的颜色

**Comment by yihong0618** [comment]
COUNTRY_FILL_COLOR 搜索这个
