### ISSUE TITLE
源自华米的GPX导入轨迹漂移，且心率为空

### ISSUE THREAD

**Issue by zc0616** [yihong0618/running_page#674]
小白第一次部署跑步网页，尝试记录：
1.两部分数据源：
（1）较早使用小米手环记录，从zepp life中导出GPX文件，用gpx_sync.py脚本上传数据；
（2）现在使用华为手表记录，数据同步到keep、悦跑圈，用keep_sync.py脚本上传并同步数据；
2.结果:
数据全部上传成功，[网页](https://zc0616.github.io/running)也成功显示。但是来自小米手环，即使用GPX文件（示例
[ZeppLife20230618220119.txt](https://github.com/user-attachments/files/15510719/ZeppLife20230618220119.txt)）上传的轨迹存在偏移，如下图，同时没有记录到心率。
![image](https://github.com/yihong0618/running_page/assets/104877616/51c9d96f-7c6f-45bd-91f2-5f9147b22082)
![image](https://github.com/yihong0618/running_page/assets/104877616/700de2ef-23c4-4196-87f6-263ac92de578)
之前使用悦跑圈同步过小米手环的这部分数据，轨迹显示一样也漂移，但是有心率存在，想问问前辈们有没有方法解决这个漂移？

**Comment by yihong0618** [comment]
有办法，issue 里搜索漂移

**Comment by zc0616** [comment]
> 有办法，issue 里搜索漂移

我看了下，好像是用keep的那个轨迹修正，但是我这个keep数据是正常的，只是通过zepp life导出的GPX文件上传到地图存在漂移

**Comment by yihong0618** [comment]
这些你得单独修正

**Comment by zc0616** [comment]
> 这些你得单独修正

明白了，谢谢大佬，我还有个问题，就是如果先不想在网页上展示这些轨迹，只能在data.db中删除吗，还是有其他接口可以更改显示状态

**Comment by web-L** [comment]
请问，问题解决了吗？我也出现同样情况，求解决办法

**Comment by web-L** [comment]
> 请问，问题解决了吗？我也出现同样情况，求解决办法

已解决！在以下修改配置
src/utils/const.ts#L106

**Comment by zc0616** [comment]
> > 请问，问题解决了吗？我也出现同样情况，求解决办法
> 
> 已解决！在以下修改配置 src/utils/const.ts#L106

我的解决方法：通过脚本使用[eviltransform](https://github.com/googollee/eviltransform)对华米导出的轨迹坐标进行转换，原因是MapBox使用坐标系为WGS-84，而华米导出的轨迹坐标系为GCJ-02
