### ISSUE TITLE
[Function enhancement] SVG info source error caused by the inability to automate JoyRun

### ISSUE THREAD

**Issue by wayichao** [yihong0618/running_page#675]
## Background：

After 
```
python3(python) run_page/joyrun_sync.py ${your mobile} ${your 验证码}
pip3 install -r requirements.txt
npm install -g corepack && corepack enable && pnpm install
pnpm develop
``` 
running activities data can be seen in the web. But when clicking `Total` in years, the GithubSvg and GridSvg will show yihong0618's info but not mine.

### option 1[I prefer and what I did manually to resolve it]:

Update `joyrun_sync.py` to support `Make svg GitHub profile` action in Run Data Sync. 
After sync data from joyRun, the SVG will also be generated.

Cons:
- Need more parameters when running `joyrun_sync.py` 
- Need further discussion about how to integrate these script to one
  - By command invoking a new process?
  - By Module import?

### option 2[I think fine]:
 
Update readme to indicate it.

**Comment by twyc** [comment]
我觉得悦跑圈封闭系统 占用户数据私有 不进一步支持也是有道理的。。只是怎样把数据导出之后再导入其他app这个事挺棘手。。

**Comment by yihong0618** [comment]
@twyc both ok for me 
If you would like to open a PR to support, just do it ~

**Comment by twyc** [comment]
I need some time to go through `Poster` and `*_drawer` and then integrate them directly into `joyrun_sync.py`.

It will be completed by end of June.

**Comment by ben-29** [comment]
I think you missed [this part](https://github.com/yihong0618/running_page?tab=readme-ov-file#total-data-analysis)

**Comment by twyc** [comment]
@ben-29 [JoyRun can't be automatic](https://github.com/yihong0618/running_page/blob/master/README-CN.md#joyrun%E6%82%A6%E8%B7%91%E5%9C%88). As a JoyRun user, I don't see any value to configure Github action..
Correspondingly, it is necessary to trigger the update of SVG after manually exporting JoyRun data each time.

**Comment by ben-29** [comment]
@twyc For option 1, the quick way to generate the total svg is changing the [RUN_TYPE](https://github.com/yihong0618/running_page/blob/38ad7a3129ced7026bcade2621d6cd349e88107d/.github/workflows/run_data_sync.yml#L28C3-L28C11) in `run_data_sync` to `only_gpx`, or even `joyrun`, so the workflow would trigger [`Make svg GitHub profile`](https://github.com/yihong0618/running_page/blob/38ad7a3129ced7026bcade2621d6cd349e88107d/.github/workflows/run_data_sync.yml#L206)

For option 2 which is to generate the total svg locally, just kindly run the [`Make svg GitHub profile`](https://github.com/yihong0618/running_page/blob/38ad7a3129ced7026bcade2621d6cd349e88107d/.github/workflows/run_data_sync.yml#L206) scripts locally.
To improve the readme, it would be great to add the commands as examples to the [total-data-analysis](https://github.com/yihong0618/running_page?tab=readme-ov-file#total-data-analysis)  section.



> 我觉得悦跑圈封闭系统 占用户数据私有 不进一步支持也是有道理的。。只是怎样把数据导出之后再导入其他app这个事挺棘手。。

Strava and [郁金香运动](http://www.tulipsport.com/#app-features) may be good alternatives. Strava allows users to [upload activities through GPX files](https://www.strava.com/upload/select), you can export Joyrun's data using `--with-gpx` option
