### ISSUE TITLE
同步Keep数据报错index out of range

### ISSUE THREAD

**Issue by GuoxinL** [yihong0618/running_page#677]
如果需要数据，我上传一下
![image](https://github.com/yihong0618/running_page/assets/19989609/a26f7239-16db-4036-ba29-247b291aa8e9)

**Comment by yihong0618** [comment]
需要。

**Comment by GuoxinL** [comment]
![image](https://github.com/yihong0618/running_page/assets/19989609/6fe6f777-7a23-4267-a11c-14034b96bdd5)
报错的数据在哪里

**Comment by yihong0618** [comment]
理论上你可以忽略这几个错误，这几个可能没路线
