### ISSUE TITLE
github action 执行报错

### ISSUE THREAD

**Issue by GuoxinL** [yihong0618/running_page#678]
![image](https://github.com/yihong0618/running_page/assets/19989609/9156c4ac-41c9-416c-bd60-1471719f1756)
有一个疑问，`STRAVA_CLIENT_REFRESH_TOKEN`是根据README中的链接STRAVA，通过curl获得最新的`REFRESH_TOKEN`，过一段时间就会过期，程序内部会更新`REFRESH_TOKEN`吗
![image](https://github.com/yihong0618/running_page/assets/19989609/6e455a96-b15f-4c76-a210-722e8ebe31e3)

**Comment by yihong0618** [comment]
refresh_token 不会变。。

这个可能是 bug 我们看看

**Comment by yihong0618** [comment]
你本地跑有报错么？

**Comment by GuoxinL** [comment]
本地跑读的是db，没有报错，同步数据脚本也没有报错

**Comment by GuoxinL** [comment]
您可以看下我fork的仓库，现状是报错的

**Comment by GuoxinL** [comment]
感谢大佬们做出这么好的东西！😄

**Comment by yihong0618** [comment]
不客气。看起来是你 IGNORE_BEFORE_SAVING 你搜索下这个，设成 False 试试

**Comment by GuoxinL** [comment]
已解决👍🏻

**Comment by GuoxinL** [comment]
<img width="1714" alt="image" src="https://github.com/yihong0618/running_page/assets/19989609/8adbac85-66f0-4afa-a51e-3fb01c077b6f">
今天记得看到成功了，刚刚执行还是失败，上图是执行workflow的文件信息，可以看到`IGNORE_BEFORE_SAVING`属性已经设置为False

**Comment by GuoxinL** [comment]
<img width="1716" alt="image" src="https://github.com/yihong0618/running_page/assets/19989609/6bf79fad-1a34-4b49-8f07-4d12eae1f0b0">
我fa发现这个包应该是没有被加载到
