### ISSUE TITLE
[TODO] change joyrun code to async

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#68]
But I don't know if it is wroth.

**Comment by lusuzi** [comment]
大佬，悦跑圈第一次尝试一直显示+++++
![image](https://user-images.githubusercontent.com/68739721/102712377-d56f5580-42fb-11eb-9a57-e64a6640e591.png)
第二次尝试显示 No tracks found.
![image](https://user-images.githubusercontent.com/68739721/102712440-4dd61680-42fc-11eb-9df5-6e5c509b8e7f.png)
是不是be被限制了？

**Comment by yihong0618** [comment]
> 大佬，悦跑圈第一次尝试一直显示+++++
> ![image](https://user-images.githubusercontent.com/68739721/102712377-d56f5580-42fb-11eb-9a57-e64a6640e591.png)
> 第二次尝试显示 No tracks found.
> ![image](https://user-images.githubusercontent.com/68739721/102712440-4dd61680-42fc-11eb-9df5-6e5c509b8e7f.png)
> 是不是be被限制了？

不是，是你的网络获取地理位置有点问题（gfw）.没有新的track是因为你已经获取完了。直接 gatsby develop 就能看到。如果想重新弄可以删除data.db 重新来。

**Comment by yihong0618** [comment]
limit 是有个获取跑步地点的方法，有时候会因为我们的特色网络获取不到。

**Comment by lusuzi** [comment]
> limit 是有个获取跑步地点的方法，有时候会因为我们的特色网络获取不到。

我尝试了多次（也换了正常网络）发现获取的数据都是一样的，然后比对了跑步数据，发现数据都是完整的，**获取不到跑步地点出现limit的原因是少部分跑步本身没开定位没有地点数据**，没毛病，完美！

哈哈哈，已经成功了，两年多的悦跑圈记录拿到手了，而且可视化非常漂亮！Genius，十分感谢大佬的帮助！！！

**Comment by yihong0618** [comment]
> > limit 是有个获取跑步地点的方法，有时候会因为我们的特色网络获取不到。
> 
> 我尝试了多次（也换了正常网络）发现获取的数据都是一样的，然后比对了跑步数据，发现数据都是完整的，**获取不到跑步地点出现limit的原因是少部分跑步本身没开定位没有地点数据**，没毛病，完美！
> 
> 哈哈哈，已经成功了，两年多的悦跑圈记录拿到手了，而且可视化非常漂亮！Genius，十分感谢大佬的帮助！！！

好的，很高兴能帮到你。但是悦跑圈是无法像其它的一样自动化的。

**Comment by lusuzi** [comment]
> > > limit 是有个获取跑步地点的方法，有时候会因为我们的特色网络获取不到。
> > 
> > 
> > 我尝试了多次（也换了正常网络）发现获取的数据都是一样的，然后比对了跑步数据，发现数据都是完整的，**获取不到跑步地点出现limit的原因是少部分跑步本身没开定位没有地点数据**，没毛病，完美！
> > 哈哈哈，已经成功了，两年多的悦跑圈记录拿到手了，而且可视化非常漂亮！Genius，十分感谢大佬的帮助！！！
> 
> 好的，很高兴能帮到你。但是悦跑圈是无法像其它的一样自动化的。

嗯嗯，之后就打算换软件啦，之前一直想要导出数据，实现数据的自我拥有、不依赖于平台，但悦跑圈不支持才不得不一直使用它，现在成了！

**Comment by yihong0618** [comment]
No need/
