### ISSUE TITLE
running_page v1.x 版本 Vercel 部署失败

### ISSUE THREAD

**Issue by phh95** [yihong0618/running_page#688]
我还在用 1.0 的版本，Vercel 部署失败，抛出好多错误，是不是要拉到本地更新一下依赖的版本呢？

![error](https://github.com/yihong0618/running_page/assets/29042617/f9f74f85-a522-44b2-bc77-9e0811b21b79)

**Comment by yihong0618** [comment]
不是需要升级 2.0

**Comment by yihong0618** [comment]
1.0 现在已经在 vercel 上用不了了。。
