### ISSUE TITLE
同步失败是什么问题呢

### ISSUE THREAD

**Issue by helloo2020** [yihong0618/running_page#689]
提示这个 
1 error and 2 warnings
[Build and publish Github Pages / build_and_deploy](https://github.com/helloo2020/Running-Tim/actions/runs/9801816305/job/27065677851#step:5:14)
Something went wrong, self-installer exits with code 1
[Sync](https://github.com/helloo2020/Running-Tim/actions/runs/9801816305/job/27065661144)
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3, actions/setup-python@v4. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
[Build and publish Github Pages / build_and_deploy](https://github.com/helloo2020/Running-Tim/actions/runs/9801816305/job/27065677851)
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/checkout@v3, actions/setup-node@v3, pnpm/action-setup@v2. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default

**Comment by Yer1k** [comment]
https://github.com/yihong0618/running_page/commit/78b2a1c66454d041650e749e6615770566047042
根据这个更新一下 [.github/workflows/gh-pages.yml](https://github.com/yihong0618/running_page/commit/78b2a1c66454d041650e749e6615770566047042#diff-c04119feaeffc2c216f069aec66797f2f839a2074287060698e3a2440dec8d45) 版本就好了。

**Comment by yihong0618** [comment]
@Yer1k 
嗯我也发现了。有兴趣来个 PR 么？
或者一会儿我来修。。。

**Comment by yihong0618** [comment]
啊。。。我们已经修完了，抱歉，我自己的没修。
