### ISSUE TITLE
NCR同步了数据后出现了错误

### ISSUE THREAD

**Issue by finallyeva** [yihong0618/running_page#69]
HI,我用NCR同步了数据后出现了错误.
![image.png](https://i.loli.net/2020/12/18/NiX8y16kojOqaFe.png)
是不是我以前用NIKE的手表记录,后来又用佳明手表同步到NCR的缘故??

**Comment by yihong0618** [comment]
> HI,我用NCR同步了数据后出现了错误.
> ![image.png](https://camo.githubusercontent.com/4d34c2232d5b5ddff7f452e4ac5ece90a22ad4d72bcea313e704592cb6cf8a41/68747470733a2f2f692e6c6f6c692e6e65742f323032302f31322f31382f4e6958387931366b6f6a4f716146652e706e67)
> 是不是我以前用NIKE的手表记录,后来又用佳明手表同步到NCR的缘故??

update to the latest code

**Comment by yihong0618** [comment]
@finallyeva 
暂时关了，如果还有问题，请留言，我会重新打开~
