### ISSUE TITLE
Strava同步数据 第6步报错

### ISSUE THREAD

**Issue by hy4015** [yihong0618/running_page#697]
curl -X POST https://www.strava.com/oauth/token \
-F client_id=${Your Client ID} \
-F client_secret=${Your Client Secret} \
-F code=${Your Code} \
-F grant_type=authorization_code

这步输完之后报错：
{"message":"Bad Request","errors":[{"resource":"Application","field":"client_id","code":"invalid"}]}curl: (7) Failed to connect to 0.1.253.115 port 80 after 0 ms: Couldn't connect to server

**Comment by yihong0618** [comment]
你的 client_id 大概率不对，在网址上那个
