### ISSUE TITLE
悦跑圈无法导出gpx

### ISSUE THREAD

**Issue by christianchan** [yihong0618/running_page#711]
运行python run_page/joyrun_sync.py ${your mobile} ${your 验证码}后，在网页上可以显示轨迹，加“ --with-gpx”运行后，在 GPX_OUT 目录里没有导出任何的gpx文件，keep可以导出gpx，是悦跑圈的接口问题吗？

**Comment by yihong0618** [comment]
你在一个新的文件夹 clone running_page 然后跑 --with-gpx 试试。因为你先用了正常的（也可能和 keep 冲突）

**Comment by christianchan** [comment]
我是先跑的joyrun，没有输出任何gpx，然后又跑的keep，GPX_OUT就导出了Keep的gpx，不过我先按你说的再试下，感谢。

**Comment by christianchan** [comment]
> 你在一个新的文件夹 clone running_page 然后跑 --with-gpx 试试。因为你先用了正常的（也可能和 keep 冲突）

按您的提示，新文件夹重新跑一遍就出来gpx了，感谢感谢。

**Comment by yihong0618** [comment]
这块有点复杂，我感觉可以做的更好点，我研究下

**Comment by DAVPanda** [comment]
我也遇到，感觉是检测到之前已同步过一次（不加--with-gpx ），再执行--with-gpx 时发现没有新增轨迹，就不再同步gpx文件

**Comment by yihong0618** [comment]
这个是因为我们是用 gpx last time 和 data.db 检测的，你可以把把 data.db 和 gpx 都删除再同步就可以了
