### ISSUE TITLE
悦跑圈时间问题

### ISSUE THREAD

**Issue by uiolee** [yihong0618/running_page#721]
![joyrun](https://github.com/user-attachments/assets/4920283d-ee6a-403a-bab5-8d27791aa783)

如图，悦跑圈部分gpx中的数据的时间会跳到后一天。

用gpx.studio查看，总时长数据异常。后面这部分数据的速度变为-0.01km/h。

![gpx.studio](https://github.com/user-attachments/assets/31d29e41-a8dc-4776-9248-282723564d4d)

**Comment by yihong0618** [comment]
这个应该是悦跑圈的问题
