### ISSUE TITLE
支持苹果自带运动一点想法

### ISSUE THREAD

**Issue by jaychoubaby** [yihong0618/running_page#722]
> 1.通过快捷指令获取数据并同步
  经过测试快捷指令似乎无法获到健康数据
> 2.通过开发app来获取健康数据
  成本太高
> 3.试图寻找苹果网页版健康数据抓取
  暂未找到
> 4.做一个轻量app来获取健康数据
  轻量app开发快速，但是不一定能获取健康数据
> 5.通过代理app抓取请求数据
  某些抓包软件可以抓取http请求，时候可以抓取健康数据还待测试

**Comment by yihong0618** [comment]
strava 就可以啊，不需要自己开发 app

**Comment by jaychoubaby** [comment]
> @jaychoubaby 你可以参考这篇文章
> 
> [superleeyom/blog#54](https://github.com/superleeyom/blog/issues/54)

感谢，我研究研究
