### ISSUE TITLE
Github Action Run Data Sync Error: Version 3.7 with arch x64 not found 

### ISSUE THREAD

**Issue by wyn04** [yihong0618/running_page#723]
Sync
Version 3.7 with arch x64 not found Available versions: 3.10.15 (x64) 3.11.10 (x64) 3.12.7 (x64) 3.9.20 (x64)

**Comment by yihong0618** [comment]
can you provide more details, like logs

**Comment by wyn04** [comment]
Run actions/setup-python@v1
Error: Version 3.7 with arch x64 not found
Available versions:

3.10.15 (x64)
3.11.10 (x64)
3.12.7 (x64)
3.9.20 (x64)

**Comment by wyn04** [comment]
Run actions/setup-python@v1
  with:
    python-version: 3.7
    architecture: x64
  env:
    RUN_TYPE: codoon
    ATHLETE: yinan
    TITLE: yinan Running
    MIN_GRID_DISTANCE: 10
    TITLE_GRID: Over 10km Runs
    GITHUB_NAME: wyn04
    GITHUB_EMAIL: wyn04@qq.com
Error: Version 3.7 with arch x64 not found
Available versions:

3.10.15 (x64)
3.11.10 (x64)
3.12.7 (x64)
3.9.20 (x64)

**Comment by yihong0618** [comment]
options
1. update to latest code
2. actions/setup-python@v1 -> actions/setup-python@v4 and drop python3.7 to python3.9
