### ISSUE TITLE
Total 统计图 格子颜色不对

### ISSUE THREAD

**Issue by MikuSugar** [yihong0618/running_page#725]
你好
没有超过20公里也变成红色了，预期应该显示黄色
https://mikusugar.me/running_page/
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/abc47e09-47e0-4b90-9f91-85435928cc8b">

**Comment by MikuSugar** [comment]
https://github.com/MikuSugar/running_page

**Comment by yihong0618** [comment]
因为计算 diff 的问题。。。
跑一次 20 就对了。或者你改下距离。
（我之后找时间修一下）

**Comment by MikuSugar** [comment]
好的，哪天有空我试试跑20
> 因为计算 diff 的问题。。。 跑一次 20 就对了。或者你改下距离。 （我之后找时间修一下）

**Comment by yihong0618** [comment]
（PR welcome~

**Comment by yihong0618** [comment]
原因是需要两个不同 special 之间计算色差，只有一个 special 就造成了这个问题

**Comment by MikuSugar** [comment]
大佬，还有两个问题想请教一下你。
1，有的跑步数据会出现定位漂移到其他市，我手动删除gpx中漂移的数据后如何触发更新？
2，我用的是apple watch跑步 同步到keep，然后running_page通过keep同步数据，keep没法同步90天前的历史数据，我通过苹果健康导出历史的数据如何导入到running_page里和keep的数据合并

**Comment by MikuSugar** [comment]
> 大佬，还有两个问题想请教一下你。 1，有的跑步数据会出现定位漂移到其他市，我手动删除gpx中漂移的数据后如何触发更新？ 2，我用的是apple watch跑步 同步到keep，然后running_page通过keep同步数据，keep没法同步90天前的历史数据，我通过苹果健康导出历史的数据如何导入到running_page里和keep的数据合并

@yihong0618

**Comment by yihong0618** [comment]
稍微有点麻烦，但是能做，我晚些回你，你先理解一下 running_page 的原理（首页原理图）和代码。

**Comment by yihong0618** [comment]
> 大佬，还有两个问题想请教一下你。 1，有的跑步数据会出现定位漂移到其他市，我手动删除gpx中漂移的数据后如何触发更新？ 2，我用的是apple watch跑步 同步到keep，然后running_page通过keep同步数据，keep没法同步90天前的历史数据，我通过苹果健康导出历史的数据如何导入到running_page里和keep的数据合并

1. 删除 run_page/data.db
2. 拿到所有 apple 的 gpx 放到一个文件夹（不要在 running_page 内操作
3. keep 拿到所有 gpx 使用 with-gpx 命令，放到一个文件夹（在 running_page 内操作）
4. 再一次删除 run_page/data.db
5. 把所有 apple watch 的 gpx 扔到 GPX_OUT 里（这里应该有你刚刚拿到的 keep 的 gpx
6. 使用 gpx_sync
7. 再使用 keep_sync
8. actions 配置 keep

**Comment by yihong0618** [comment]
> > 大佬，还有两个问题想请教一下你。 1，有的跑步数据会出现定位漂移到其他市，我手动删除gpx中漂移的数据后如何触发更新？ 2，我用的是apple watch跑步 同步到keep，然后running_page通过keep同步数据，keep没法同步90天前的历史数据，我通过苹果健康导出历史的数据如何导入到running_page里和keep的数据合并
> 
> 1. 删除 run_page/data.db
> 2. 拿到所有 apple 的 gpx 放到一个文件夹（不要在 running_page 内操作
> 3. keep 拿到所有 gpx 使用 with-gpx 命令，放到一个文件夹（在 running_page 内操作）
> 4. 再一次删除 run_page/data.db
> 5. 把所有 apple watch 的 gpx 扔到 GPX_OUT 里（这里应该有你刚刚拿到的 keep 的 gpx
> 6. 使用 gpx_sync
> 7. 再使用 keep_sync
> 8. actions 配置 keep

@MikuSugar 你可以理解下为啥这么做哈哈，后面你就可以自己随便改了

**Comment by yihong0618** [comment]
fixed

**Comment by MikuSugar** [comment]
> > > 大佬，还有两个问题想请教一下你。 1，有的跑步数据会出现定位漂移到其他市，我手动删除gpx中漂移的数据后如何触发更新？ 2，我用的是apple watch跑步 同步到keep，然后running_page通过keep同步数据，keep没法同步90天前的历史数据，我通过苹果健康导出历史的数据如何导入到running_page里和keep的数据合并
> > 
> > 
> > 
> > 1. 删除 run_page/data.db
> > 2. 拿到所有 apple 的 gpx 放到一个文件夹（不要在 running_page 内操作
> > 3. keep 拿到所有 gpx 使用 with-gpx 命令，放到一个文件夹（在 running_page 内操作）
> > 4. 再一次删除 run_page/data.db
> > 5. 把所有 apple watch 的 gpx 扔到 GPX_OUT 里（这里应该有你刚刚拿到的 keep 的 gpx
> > 6. 使用 gpx_sync
> > 7. 再使用 keep_sync
> > 8. actions 配置 keep 配置 keep
> 
> @MikuSugar 你可以理解下为啥这么做哈哈，后面你就可以自己随便改了

谢谢大佬
