### ISSUE TITLE
[BUG] json parser

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#73]
10:42:20.331 | error "gatsby-transformer-json" threw an error while running the onCreateNode lifecycle:
-- | --
10:42:20.331 | Unable to parse JSON: file /vercel/workpath0/src/static/activities.json
10:42:20.331 | 75 \|   } catch {
10:42:20.331 | 76 \|     const hint = node.absolutePath ? `file ${node.absolutePath}` : `in node ${node.id}`;
10:42:20.331 | > 77 \|     throw new Error(`Unable to parse JSON: ${hint}`);
10:42:20.331 | \|           ^
10:42:20.331 | 78 \|   }
10:42:20.331 | 79 \|
10:42:20.331 | 80 \|   if (_.isArray(parsedContent)) {
10:42:20.343 |  
10:42:20.343 | Error: Unable to parse JSON: file /vercel/workpath0/src/static/activities.json
10:42:20.343 | - gatsby-node.js:77 Object.onCreateNode
10:42:20.343 | [workpath0]/[gatsby-transformer-json]/gatsby-node.js:77:11
10:42:20.343 |  
10:42:20.343 | - api-runner-node.js:460 runAPI
10:42:20.343 | [workpath0]/[gatsby]/src/utils/api-runner-node.js:460:16
10:42:20.343 |  
10:42:20.343 |  
10:42:20.344 | not finished source and transform nodes - 0.124s
10:42:21.351 | error Command failed with exit code 1.
10:42:21.351 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:42:21.363 | Error: Command "yarn run build" exited with 1

**Comment by geekplux** [comment]
Cannot reproduce it on my local env, we need to see the format and content of the `activities.json` file.

**Comment by yihong0618** [comment]
@Lax
更新了，麻烦能再试验一下么？

**Comment by Lax** [comment]
确认修复了。
