### ISSUE TITLE
一个疑惑

### ISSUE THREAD

**Issue by coutureone** [yihong0618/running_page#732]
大佬就是我已经用按照你的文档，能导出了gpx文件，但是我这个文件手动导入其他文件，我发现不显示心率，记录手表是keep自带的手表，是因为某些方面进行加密了吗？

**Comment by yihong0618** [comment]
没太懂，手动导入其它文件是指？

**Comment by coutureone** [comment]
手动导入，我发现用其他软件打开，这个好像应该不算导入，只能说咕咚悦跑圈这种软件打开
---- 回复的原邮件 ----
发件人 ***@***.***> 日期 2024年11月09日 08:22 收件人 ***@***.***> 抄送至 ***@***.***>***@***.***> 主题 Re: [yihong0618/running_page] 一个疑惑 (Issue #732) 
没太懂，手动导入其它文件是指？

**Comment by coutureone** [comment]
> 没太懂，手动导入其它文件是指？

就是我想脱离keep，给数据导入其他运动软件，手动导入，这个数据只有跑步数据，距离，配速定位，其他的数据没有，我在怀疑是不是keep自己的手表出来的数据加密了

**Comment by yihong0618** [comment]
你用 gpx 导入到其它的呀

**Comment by coutureone** [comment]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
Upload faild error [{'resource': 'AccessToken', 'field': 'activity:write_permission', 'code': 'missing'}]
大佬，这个是我的权限不够吗，在从keep同步到strava 遇到的问题，看样是没有push的权限

**Comment by yihong0618** [comment]
你需要 3 个 token 参考readme 而且建议在本地运行

**Comment by coutureone** [comment]
<img width="1078" alt="image" src="https://github.com/user-attachments/assets/5453d72c-e5ad-474f-a401-6a6573decbfd">
我看readme中的三个参数不是这个吗？我用的这三个参数提示就是上面的内容，我是在本地运行的

**Comment by yihong0618** [comment]
啊，你没申请 write 的权限，请严格按照 readme 的 url

**Comment by coutureone** [comment]
> 啊，你没申请 write 的权限，请严格按照 readme 的 url

好的，谢谢大佬，已经解决，没看到二维码在那里想请大佬喝杯水，还有一个问题就是如果我给strava的活动全部删除了，想要全部重新上传，那个token好像不刷新的，命令执行了，显示已经是最新了，无法再全部重新上传

**Comment by yihong0618** [comment]
> > 啊，你没申请 write 的权限，请严格按照 readme 的 url
> 
> 好的，谢谢大佬，已经解决，没看到二维码在那里想请大佬喝杯水，还有一个问题就是如果我给strava的活动全部删除了，想要全部重新上传，那个token好像不刷新的，命令执行了，显示已经是最新了，无法再全部重新上传
z
能重新上传的，需要你把 strava 里面的都删了，原理是找 strava 的最后一个时间，上传超过这个时间的。

**Comment by coutureone** [comment]
> > > 啊，你没有申请 write 的权限，请严格按照 readme 的 url
> > 
> > 
> > 好的，谢谢大佬，已经解决了，没看到二维码就想请大佬喝杯水，还有一个问题就是如果我把strava的活动全部删除了，想要全部重新上传，那个token希望不刷新的，命令执行了，显示已经是最新的了，无法再全部重新上传
> > z
> > 能重新上传的，需要你把strava里面的都删掉了，原理是找strava的最后一个时间，上传超过这个时间的。

我现在是全部都删除了，但是执行脚本都是提示最新了，如图所示
<img width="954" alt="image" src="https://github.com/user-attachments/assets/ed133d5f-e78c-415c-8bf8-feb73e569090">

**Comment by yihong0618** [comment]
rm -rf run_page/data.db
重新跑

**Comment by coutureone** [comment]
不行，我试过，不管是命令删除还是手动都试了，结果还是不能更新数据
<img width="1491" alt="image" src="https://github.com/user-attachments/assets/2ba43213-b50a-4f45-a542-b29953ec4f37">

**Comment by yihong0618** [comment]
1. 你确定下 strava 是真正的删除了不
2. 可能是 strava 那边的问题
3. 你找一个干净的文件夹重新走一遍流程（还是用这些 token
4. 如果还是不行就新注册个 strava 账号

**Comment by coutureone** [comment]
我发现问题就是如果你先从keep上面获取gpx，数据库里面能看见心率的，如果从keep直接上传到strava数据库里面很多是没有心率的，我不知道这是不是一个bug

**Comment by yihong0618** [comment]
应该不是。没有的原因是那些只有一个平均心率

**Comment by coutureone** [comment]
是的，我keep导出来的，要不就是没有心率的，要不就是平均心率的，上传到strava心率都是没有的😂😂😂

**Comment by coutureone** [comment]
> 应该不是。没有的原因是那些只有一个平均心率

非常感谢大佬，问题解决，我也部署好了 https://couture.run/,感谢感谢  🙏 ~

**Comment by yihong0618** [comment]
不客气，enjoy it.
