### ISSUE TITLE
do not have type subtype

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#742]
![telegram-cloud-photo-size-5-6206426475607999485-y](https://github.com/user-attachments/assets/d7bb41e3-7bb2-497c-8b33-952b0f0d4499)

@NaturezzZ @ben-29

**Comment by NaturezzZ** [comment]
Plz upload the related gpx or fit for further check.

**Comment by yihong0618** [comment]
link https://t.me/c/2147761260/6360

**Comment by x19920903** [comment]
[GPX_OUT.zip](https://github.com/user-attachments/files/17899943/GPX_OUT.zip)
我上传了三个gpx文件，我导出的有400多个gpx文件

**Comment by x19920903** [comment]
.something wrong with 243379763
'x' object has no attribute 'subtype'
.something wrong with 235818501
'x' object has no attribute 'subtype'
.something wrong with 232202117
'x' object has no attribute 'subtype'

**Comment by x19920903** [comment]
![269a59e3614a2574e319f7ec5d938ef](https://github.com/user-attachments/assets/c18da047-9a2d-44f3-af32-c4d5dd2ad996)
![d56d1840477c288a1164ca85b977229](https://github.com/user-attachments/assets/78d8aa79-b0a1-483a-a090-4d2e51c7ac03)
还麻烦大佬看下导不出gpx，昨天运行命令有gpx导出了，现在数据导出OK，http://localhost:5173/可以查看导出的数据

**Comment by x19920903** [comment]
@yihong0618 @NaturezzZ

**Comment by x19920903** [comment]
![图片](https://github.com/user-attachments/assets/05e14a15-1c1d-4c3b-b875-e518f4fd94fa)
![图片](https://github.com/user-attachments/assets/4f32f7fb-4042-499a-a8a2-84c582084d8e)
![图片](https://github.com/user-attachments/assets/9f3d0bae-e6c2-4de5-bb72-ec5fa514c341)

无法导出GPX信息，跑步数据导出正常了，也可以本地查看

**Comment by yihong0618** [comment]
> ![图片](https://private-user-images.githubusercontent.com/172000250/389747362-05e14a15-1c1d-4c3b-b875-e518f4fd94fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODU4NTcsIm5iZiI6MTczMjU4NTU1NywicGF0aCI6Ii8xNzIwMDAyNTAvMzg5NzQ3MzYyLTA1ZTE0YTE1LTFjMWQtNGMzYi1iODc1LWU1MThmNGZkOTRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTQ1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmU2NTk3ZGI5OTE4N2I3YjBhOTY0YzFmODAxYmRmNDRjMDk1YTkzMWQ1ZmMyMTMzM2RkYWMzODMwYzA5YzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-dCuG8W1LtHLBwuWupi4R-hDnu3EJz_YVhcFSEidirQ) ![图片](https://private-user-images.githubusercontent.com/172000250/389747585-4f32f7fb-4042-499a-a8a2-84c582084d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODU4NTcsIm5iZiI6MTczMjU4NTU1NywicGF0aCI6Ii8xNzIwMDAyNTAvMzg5NzQ3NTg1LTRmMzJmN2ZiLTQwNDItNDk5YS1hOGEyLTg0YzU4MjA4NGQ4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTQ1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDQ3NmNmMTIzMDcxMWI2MGYzMDZiMzc3NDViNTA5NmIzMTJiYjMxYmI1NzFkYTM2YzI0MmE5MDNiNmZiNDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4-RrEuYZVXqNy41r7GxGdNZHeXKuE1wFxHsmj9JA8ss) ![图片](https://private-user-images.githubusercontent.com/172000250/389747734-9f3d0bae-e6c2-4de5-bb72-ec5fa514c341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODU4NTcsIm5iZiI6MTczMjU4NTU1NywicGF0aCI6Ii8xNzIwMDAyNTAvMzg5NzQ3NzM0LTlmM2QwYmFlLWU2YzItNGRlNS1iYjcyLWVjNWZhNTE0YzM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTQ1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzhiZGJlOTUzYjQ5MjFlMWQ4YTQ2MGU2NTNhZTY5ZTFiY2JhZjEyZjAwOWZiNWYxZGI0MGI4NWJhNDRmOGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EtsLtJY_e92AzijPb66tylCNtr1oth-tvDpzTrkyrCE)
> 
> 无法导出GPX信息，跑步数据导出正常了，也可以本地查看

你已经都导出了啊

**Comment by yihong0618** [comment]
> ![图片](https://private-user-images.githubusercontent.com/172000250/389747362-05e14a15-1c1d-4c3b-b875-e518f4fd94fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODU4NTcsIm5iZiI6MTczMjU4NTU1NywicGF0aCI6Ii8xNzIwMDAyNTAvMzg5NzQ3MzYyLTA1ZTE0YTE1LTFjMWQtNGMzYi1iODc1LWU1MThmNGZkOTRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTQ1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmU2NTk3ZGI5OTE4N2I3YjBhOTY0YzFmODAxYmRmNDRjMDk1YTkzMWQ1ZmMyMTMzM2RkYWMzODMwYzA5YzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-dCuG8W1LtHLBwuWupi4R-hDnu3EJz_YVhcFSEidirQ) ![图片](https://private-user-images.githubusercontent.com/172000250/389747585-4f32f7fb-4042-499a-a8a2-84c582084d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODU4NTcsIm5iZiI6MTczMjU4NTU1NywicGF0aCI6Ii8xNzIwMDAyNTAvMzg5NzQ3NTg1LTRmMzJmN2ZiLTQwNDItNDk5YS1hOGEyLTg0YzU4MjA4NGQ4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTQ1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDQ3NmNmMTIzMDcxMWI2MGYzMDZiMzc3NDViNTA5NmIzMTJiYjMxYmI1NzFkYTM2YzI0MmE5MDNiNmZiNDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4-RrEuYZVXqNy41r7GxGdNZHeXKuE1wFxHsmj9JA8ss) ![图片](https://private-user-images.githubusercontent.com/172000250/389747734-9f3d0bae-e6c2-4de5-bb72-ec5fa514c341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODU4NTcsIm5iZiI6MTczMjU4NTU1NywicGF0aCI6Ii8xNzIwMDAyNTAvMzg5NzQ3NzM0LTlmM2QwYmFlLWU2YzItNGRlNS1iYjcyLWVjNWZhNTE0YzM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTQ1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzhiZGJlOTUzYjQ5MjFlMWQ4YTQ2MGU2NTNhZTY5ZTFiY2JhZjEyZjAwOWZiNWYxZGI0MGI4NWJhNDRmOGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EtsLtJY_e92AzijPb66tylCNtr1oth-tvDpzTrkyrCE)
> 
> 无法导出GPX信息，跑步数据导出正常了，也可以本地查看

btw, 跑的好快，牛逼

**Comment by x19920903** [comment]
> > ![图片](https://private-user-images.githubusercontent.com/172000250/389747362-05e14a15-1c1d-4c3b-b875-e518f4fd94fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODU4NTcsIm5iZiI6MTczMjU4NTU1NywicGF0aCI6Ii8xNzIwMDAyNTAvMzg5NzQ3MzYyLTA1ZTE0YTE1LTFjMWQtNGMzYi1iODc1LWU1MThmNGZkOTRmYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTQ1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YmU2NTk3ZGI5OTE4N2I3YjBhOTY0YzFmODAxYmRmNDRjMDk1YTkzMWQ1ZmMyMTMzM2RkYWMzODMwYzA5YzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-dCuG8W1LtHLBwuWupi4R-hDnu3EJz_YVhcFSEidirQ) ![图片](https://private-user-images.githubusercontent.com/172000250/389747585-4f32f7fb-4042-499a-a8a2-84c582084d8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODU4NTcsIm5iZiI6MTczMjU4NTU1NywicGF0aCI6Ii8xNzIwMDAyNTAvMzg5NzQ3NTg1LTRmMzJmN2ZiLTQwNDItNDk5YS1hOGEyLTg0YzU4MjA4NGQ4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTQ1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMDQ3NmNmMTIzMDcxMWI2MGYzMDZiMzc3NDViNTA5NmIzMTJiYjMxYmI1NzFkYTM2YzI0MmE5MDNiNmZiNDBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4-RrEuYZVXqNy41r7GxGdNZHeXKuE1wFxHsmj9JA8ss) ![图片](https://private-user-images.githubusercontent.com/172000250/389747734-9f3d0bae-e6c2-4de5-bb72-ec5fa514c341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1ODU4NTcsIm5iZiI6MTczMjU4NTU1NywicGF0aCI6Ii8xNzIwMDAyNTAvMzg5NzQ3NzM0LTlmM2QwYmFlLWU2YzItNGRlNS1iYjcyLWVjNWZhNTE0YzM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyNlQwMTQ1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzhiZGJlOTUzYjQ5MjFlMWQ4YTQ2MGU2NTNhZTY5ZTFiY2JhZjEyZjAwOWZiNWYxZGI0MGI4NWJhNDRmOGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.EtsLtJY_e92AzijPb66tylCNtr1oth-tvDpzTrkyrCE)
> > 无法导出GPX信息，跑步数据导出正常了，也可以本地查看
> 
> btw, 跑的好快，牛逼

好的好的，谢谢大佬。中间两年没怎么跑，现在6分配健康跑了。

**Comment by x19920903** [comment]
@yihong0618 大佬，还是麻烦看一下获取佳明密匙的错误,密码我用XXXXX替换了，
$ python run_page/get_garmin_secret.py ${240443013@qq.com} ${XXXXXXXX} --is-cn
Traceback (most recent call last):
  File "D:\Program Files\Lib\site-packages\garth\http.py", line 139, in request
    self.last_resp.raise_for_status()
  File "D:\Program Files\Lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://sso.garmin.cn/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\running\test2\running_page-master\run_page\get_garmin_secret.py", line 18, in <module>
    garth.login(options.email, options.password)
  File "D:\Program Files\Lib\site-packages\garth\http.py", line 160, in login
    self.oauth1_token, self.oauth2_token = sso.login(
                                           ^^^^^^^^^^
  File "D:\Program Files\Lib\site-packages\garth\sso.py", line 84, in login
    client.post(
  File "D:\Program Files\Lib\site-packages\garth\http.py", line 151, in post
    return self.request("POST", *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\Lib\site-packages\garth\http.py", line 141, in request
    raise GarthHTTPError(
garth.exc.GarthHTTPError: Error in request: 401 Client Error: Unauthorized for url: https://sso.garmin.cn/sso/signin?id=gauth-widget&embedWidget=true&gauthHost=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&service=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&source=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&redirectAfterAccountLoginUrl=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed&redirectAfterAccountCreationUrl=https%3A%2F%2Fsso.garmin.cn%2Fsso%2Fembed

**Comment by yihong0618** [comment]
${} 把这个去掉，这个是变量的意思

**Comment by x19920903** [comment]
> ${} 把这个去掉，这个是变量的意思
好的好的，我只试了去掉{}的方法，谢谢。你可以也在下面加个示例，可能对小白好些，给添麻烦了。
