### ISSUE TITLE
strava隐藏起点和终点

### ISSUE THREAD

**Issue by JiNanPiWang** [yihong0618/running_page#743]
大佬，我的一些strava活动隐藏了起点和终点，地图上就显示不了，这个是否有想法解决呢，比如增加一个strava to gpx功能。strava先下载gpx，这个是完整的，再到data.db。

**Comment by yihong0618** [comment]
这个是 strava 那边 api 的问题，你隐藏就拿不到了。
可以这样，先打开隐藏 -> 导出 data.db -> 备份 -> 再打开隐藏 -> 重新跑

**Comment by JiNanPiWang** [comment]
> 这个是 strava 那边 api 的问题，你隐藏就拿不到了。 可以这样，先打开隐藏 -> 导出 data.db -> 备份 -> 再打开隐藏 -> 重新跑

好的谢谢，如果想strava导出gpx，是否使用strava到佳明里面的方法就行

**Comment by yihong0618** [comment]
是

**Comment by JiNanPiWang** [comment]
> 是

明白了，谢谢大佬
