### ISSUE TITLE
第一次同步运行strava_sync时候，提示Activity' object has no attribute 'subtype'

### ISSUE THREAD

**Issue by doodle1129** [yihong0618/running_page#745]
![subtype](https://github.com/user-attachments/assets/fd42eb9a-2526-4718-82cd-dbed5b663728)
可能是哪一步操作出问题呢？

**Comment by yihong0618** [comment]
可能是我们问题。我去查一下，看看

**Comment by yihong0618** [comment]
你是用的 strava 并且第一次用么？

**Comment by yihong0618** [comment]
@NaturezzZ

**Comment by doodle1129** [comment]
> 你是用的 strava 并且第一次用么？

是的，第一次同步数据

**Comment by yihong0618** [comment]
好的谢谢。

**Comment by NaturezzZ** [comment]
可能因为strava下载的时候没有设置subtype，和https://github.com/yihong0618/running_page/issues/742 类似

**Comment by yihong0618** [comment]
我在查。。。但是好像是下载了，我去查下我的 token 试试

**Comment by NaturezzZ** [comment]
在 `run_page/generator/__init__.py:71` 添加`activity.subtype='generic'`应该就可以解决了。这个bug是因为strava同步和其他平台同步的逻辑不同，没有显式的将activity转换成named_tuple的一步。

**Comment by yihong0618** [comment]
@NaturezzZ 哈哈改完了。。我直接等于 type 了，等有时间改好一点，谢谢。

**Comment by yihong0618** [comment]
> @yihong0618 在 `run_page/generator/__init__.py:71` 添加`activity.subtype='generic'`应该可以解决。这个bug是因为strava同步和其他平台同步的逻辑不同，没有显式的将activity转换成named_tuple的一步。

我也查到了！握手

**Comment by yihong0618** [comment]
@doodle1129 修复了，麻烦用最新代码试试

**Comment by NaturezzZ** [comment]
OK 没想到增加subtype引发的影响这么大，之后系统性查一下还有没有遗漏的地方。

**Comment by yihong0618** [comment]
@ben-29 workouts 可能也得更新下

**Comment by NaturezzZ** [comment]
BTW, running_page支持的平台好多，开发的时候考虑到自己不用的平台的正确性还挺难的。。。

**Comment by yihong0618** [comment]
> BTW, running_page支持的平台好多，开发的时候考虑到自己不用的平台的正确性还挺难的。。。

是的哈哈哈我之前都找 ben-29 帮忙测试

**Comment by ben-29** [comment]
> @ben-29 workouts 可能也得更新下

Just merged :)

**Comment by doodle1129** [comment]
@yihong0618 请教一下，在跑action的时候，卡在了第二步一直下不去。可能是什么原因导致呢
<img width="942" alt="截屏2024-11-29 00 55 25" src="https://github.com/user-attachments/assets/61373ae8-631e-46d2-9cbb-8b780e0d0c6e">

**Comment by yihong0618** [comment]
没把 page 改成 action请参考readme

**Comment by doodle1129** [comment]
> 没把 page 改成 action请参考readme

谢谢，原来是分支名称错了，从默认的main改成master就可以运行了。小白第一次部署github还没琢磨透🤣

**Comment by doodle1129** [comment]
> 没把 page 改成 action请参考readme

再次请教，首次在本地同步拉取的strava数据，所有的活动location只精确china，没有精确到省市。通过action同步的数据可以精确到城市，以至缩放地图里统计的省市和距离只统计了action获取的部分。是什么原因呢？

**Comment by yihong0618** [comment]
> > 没把 page 改成 action请参考readme
> 
> 再次请教，首次在本地同步拉取的strava数据，所有的活动location只精确china，没有精确到省市。通过action同步的数据可以精确到城市，以至缩放地图里统计的省市和距离只统计了action获取的部分。是什么原因呢？

因为你 strava 里面的地点获取不对，没办法。。。
这个需要 diy

**Comment by doodle1129** [comment]
> > > 没把 page 改成 action请参考readme
> > 
> > 再次请教，首次在本地同步拉取的strava数据，所有的活动location只精确china，没有精确到省市。通过action同步的数据可以精确到城市，以至缩放地图里统计的省市和距离只统计了action获取的部分。是什么原因呢？
> 
> 因为你 strava 里面的地点获取不对，没办法。。。
> 这个需要 diy

可以直接手动把db里的location改成具体位置么😂

**Comment by yihong0618** [comment]
> > > > 没把 page 改成 action请参考readme
> > > 
> > > 
> > > 再次请教，首次在本地同步拉取的strava数据，所有的活动location只精确china，没有精确到省市。通过action同步的数据可以精确到城市，以至缩放地图里统计的省市和距离只统计了action获取的部分。是什么原因呢？
> > 
> > 
> > 因为你 strava 里面的地点获取不对，没办法。。。
> > 这个需要 diy
> 
> 可以直接手动把db里的location改成具体位置么😂

可以，但我应该没精力帮你，你自己来

**Comment by ben-29** [comment]
> > 没把 page 改成 action请参考readme
> 
> 再次请教，首次在本地同步拉取的strava数据，所有的活动location只精确china，没有精确到省市。通过action同步的数据可以精确到城市，以至缩放地图里统计的省市和距离只统计了action获取的部分。是什么原因呢？

你试试把data.db删除(记得先备份到本地)，直接让action跑呢。也可以本地用全局梯子重跑

**Comment by doodle1129** [comment]
> > > > > 没把 page 改成 action请参考readme
> 
> > > > 
> 
> > > > 
> 
> > > > 再次请教，首次在本地同步拉取的strava数据，所有的活动location只精确china，没有精确到省市。通过action同步的数据可以精确到城市，以至缩放地图里统计的省市和距离只统计了action获取的部分。是什么原因呢？
> 
> > > 
> 
> > > 
> 
> > > 因为你 strava 里面的地点获取不对，没办法。。。
> 
> > > 这个需要 diy
> 
> > 
> 
> > 可以直接手动把db里的location改成具体位置么😂
> 
> 
> 
> 可以，但我应该没精力帮你，你自己来

谢谢，这必须得由我自己来，活动数量不多，手动应该半天可以调整完。

**Comment by doodle1129** [comment]
> > > 没把 page 改成 action请参考readme
> > 
> > 再次请教，首次在本地同步拉取的strava数据，所有的活动location只精确china，没有精确到省市。通过action同步的数据可以精确到城市，以至缩放地图里统计的省市和距离只统计了action获取的部分。是什么原因呢？
> 
> 你试试把data.db删除(记得先备份到本地)，直接让action跑呢。也可以本地用全局梯子重跑

谢谢，我尝试一下。
