### ISSUE TITLE
strava跑步数据读取不完整

### ISSUE THREAD

**Issue by jaychoubaby** [yihong0618/running_page#746]
strava中有96条跑步数据，共2年的跑步数据，部署完成之后只能显示24年的20条，我尝试过调整一些配置，将最小单位改为1km，也没有变化，找了半天没找到哪里能配置显示完整的数据

`MIN_GRID_DISTANCE: 1 # change min distance here`

`const CHINESE_INFO_MESSAGE = (yearLength: number, year: string): string => {
  const yearStr = year === 'Total' ? '所有' : ` ${year} `;
  return `我用 App 记录自己跑步 ${yearLength} 年了，下面列表展示的是${yearStr}的数据`;
};`

我看到这里有一个配置，但是不知道这里从哪里配置才能生效，文档中也没有找到。

**Comment by yihong0618** [comment]
rm run_page/data.db 
重新跑一遍试试？

**Comment by jaychoubaby** [comment]
> rm run_page/data.db 重新跑一遍试试？

可以了，非常感谢，另外请问一下  我在out_gpx 文件夹下备份我的 gpx文件，里面的数据和strava是一样的，这俩在一起会冲突吗？因为我上传了gpx文件之后我看到action执行了，但是并没有产生新数据，是过滤掉重复数据了吗

**Comment by yihong0618** [comment]
不是，用 strava 的话不会走 gpx_out

**Comment by jaychoubaby** [comment]
> 不是，用 strava 的话不会走 gpx_out

明白了，再次感谢

**Comment by yihong0618** [comment]
好的，先关了哈
