### ISSUE TITLE
部署后默认是楼主的数据，如何修改成导入GPX文件夹里的跑步数据？

### ISSUE THREAD

**Issue by chester-zhou** [yihong0618/running_page#751]
抱歉，纯小白，靠ChatGPT终于搭起来了，搞定了啥是node.js, pnpm镜像啥的，现在也从华为手表里导出了跑步的GPX文件放到对应文件夹，请问如何只显示文件夹中的数据。谢谢。

**Comment by yihong0618** [comment]
跑一次 gpx_sync

**Comment by chester-zhou** [comment]
好的，解决了。
