### ISSUE TITLE
「小米运动健康」运动记录导出文件时间偏移问题

### ISSUE THREAD

**Issue by viazure** [yihong0618/running_page#753]
我在将 「小米运动健康」 的运动记录导出为 `.tcx ` 和 `.gpx` 文件时遇到了一个问题。这些文件在同步到项目后，时间会自动增加 8 个小时。我尝试过直接将这些文件导入 Strava，也遇到了相同的时间偏移问题。
![runpage](https://github.com/user-attachments/assets/dccea538-9a58-48a2-bdd0-d94c229785f0)
![strava](https://github.com/user-attachments/assets/fb635abe-027f-4b04-94c0-8c635977489d)

通过查看运动记录文件，我发现文件中记录的时间实际上是当前的北京时间，但文件中的时间格式却是以 UTC 时间表示的。我猜测是这个原因导致了在同步和导入过程中出现时间的偏差。

![tcx](https://github.com/user-attachments/assets/29fcd16e-e432-4157-a4d0-d840a1dfc30e)

请问有什么好的解决方案吗？

**Comment by viazure** [comment]
看到 #337 有提到「行者」软件导出的 GPX 时间不规范，和我这里提到的问题应该是相同的。我尝试将 `Z` 替换为 `+08:00` 后导入 Strava 时间显示正常了，但使用  `run_page/gpx_sync.py` 处理后 Running Page 上的时间仍然是 +8 小时。目前想到的的方案是：将文件中的时间统一处理 -> 同步到 Strava -> 从 Strava 获取数据到 Running Page 。🤔

**Comment by yihong0618** [comment]
理论上我们再代码里修复里这个问题（我有时间这周看一下

**Comment by yihong0618** [comment]
@viazure 我知道了，你用xiaomi 的话 running_page 应该是正常的我们做处理了，但是传到 strava 应该是不对的，他们没处理，我门也没处理相关的 gpx

**Comment by viazure** [comment]
> @viazure 我知道了，你用xiaomi 的话 running_page 应该是正常的我们做处理了，但是传到 strava 应该是不对的，他们没处理，我门也没处理相关的 gpx

running_page 也不正常，你看下我发的第一张图，就是直接执行的 `run_page/tcx_sync.py` 和 `run_page/gpx_sync.py`。出来的时间已经是 +8 小时的了。

**Comment by yihong0618** [comment]
好的，我们确定下。。。。

**Comment by viazure** [comment]
> 好的，我们确定下。。。。

好的，我把运动记录文件也传一份，方便你们排查问题。
[20241206户外跑步.zip](https://github.com/user-attachments/files/18056065/20241206.zip)
。

**Comment by yihong0618** [comment]
@viazure 你可以导出 gpx 后用这个方法

#!/bin/bash

ls *.gpx | xargs sed -i 's/Z</+08:00</g'

**Comment by viazure** [comment]
> WTF 小米在北京时间后面加了个 Z????

是的，已无力吐槽。我今天已购佳明 255，再见了小米。

**Comment by viazure** [comment]
> @viazure 你可以导出 gpx 后用这个方法
> 
> #!/bin/bash
> 
> ls *.gpx | xargs sed -i 's/Z</+08:00</g'

嗯，已经按照这个方案做了，现在把数据都导入 Strava 了。感觉小米直接放弃吧，真的太不规范了。
