### ISSUE TITLE
garmin_sync.py 是否可以加个时间参数 ，导出指定时间的数据，默认导出当天的

### ISSUE THREAD

**Issue by chinaphp** [yihong0618/running_page#80]
目前好像默认导出所有数据。

**Comment by yihong0618** [comment]
> 目前好像默认导出所有数据。

@chinaphp 我当时没找到相关的接口。最近再试试。

btw, 其实默认不是导出所有数据，是根据你的 GPX_OUT 里判断的，如果有就不新增加了。
