### ISSUE TITLE
Garmin: Something went wrong when loading GPX. 

### ISSUE THREAD

**Issue by wh1994** [yihong0618/running_page#81]
请问有没有哪位在运行garmin_sync.py时，出现“Something went wrong when loading GPX. for file 6171184463.gpx”这种错误的情况？因为人在国外，用的是“python3(python) scripts/garmin_sync.py ${your email} ${your password}”这个命令。目前卡在这一步，希望有人能帮忙解答。谢谢！

**Comment by yihong0618** [comment]
@wh1994 
Hi, 因为这个 gpx 可能没有数据（例如跑步机跑的或手动添加的），我只是打印出来这个错误提醒用户，但程序是继续往下跑的，你可以继续接下来的命令，请放心。

**Comment by yihong0618** [comment]
@wh1994 
我刚刚增加了一些错误信息。

**Comment by wh1994** [comment]
> @wh1994
> 我刚刚增加了一些错误信息。

谢谢回复。刚发现是由于Garmin的语言设置问题。我手机之前是中文的系统语言，Garmin给跑步起名字时候是用的中文“跑步”，好像是这个引起哪里不对。然后我把所有的记录名字都改成英文后就好了。

**Comment by wh1994** [comment]
非常感谢你做个这个项目，真的太好了。对于一个基本编程基础为零的我，折腾一晚上终于搞定了。
最后有两个小问题想咨询一下：
1. Garmin的数据导出来没有BPM。我的手表应该有记录了的，这个是因为没写在脚本里吗？
2. 请问用vercel布置成功后，怎么修改域名呢？
因为之前没有什么编程经验，好像好多小细节没有设置太对。

**Comment by yihong0618** [comment]
@wh1994 
1. 中文这个我确实应该改下，我需要研究下有什么办法没。
2. 理论是带的，可能是我的问题我也需要研究下
3. vercel 改域名的话 vercel 里面我记得有介绍。或者  google 里面应该能搜到答案。
4. 感谢使用
5. PR 一直开放的~，如果你想 share 主页，或者以上问题你有啥办法提出 pr, always welcome.

**Comment by wh1994** [comment]
刚刚简单弄了一个域名“https://run4life.fun/”，欢迎分享！
再次感谢！

**Comment by yihong0618** [comment]
@wh1994 
需要我帮你加到主页里么？还是你提 pr 自己加？

**Comment by wh1994** [comment]
> @wh1994
> 需要我帮你加到主页里么？还是你提 pr 自己加？

麻烦你帮我加进去吧，我刚接触github还不太懂这些操作。谢谢了！

**Comment by yihong0618** [comment]
> > @wh1994
> > 需要我帮你加到主页里么？还是你提 pr 自己加？
> 
> 麻烦你帮我加进去吧，我刚接触github还不太懂这些操作。谢谢了！

好的。
