### ISSUE TITLE
[NEED FIX] GPX 中文报错问题

### ISSUE THREAD

**Issue by yihong0618** [yihong0618/running_page#82]
> 刚发现是由于Garmin的语言设置问题。我手机之前是中文的系统语言，Garmin给跑步起名字时候是用的中文“跑步”，好像是这个引起哪里不对。然后我把所有的记录名字都改成英文后就好了。

https://github.com/yihong0618/running_page/issues/81

**Comment by nnkn** [comment]
我在不同系统下测试了一下，Windows下会这样，centos下不会，怀疑只有Windows下会
