### ISSUE TITLE
Nike Run Club sync failed

### ISSUE THREAD

**Issue by semico** [yihong0618/running_page#9]
it failed when I try to sync the data from NRC

**Comment by semico** [comment]
Traceback (most recent call last):
22
  File "scripts/nike_sync.py", line 308, in <module>
23
    files = get_to_generate_files()
24
  File "scripts/nike_sync.py", line 147, in get_to_generate_files
25
    for i in os.listdir(OUTPUT_DIR)
26
  File "scripts/nike_sync.py", line 148, in <listcomp>
27
    if int(i.split(".")[0]) > last_time
28
ValueError: invalid literal for int() with base 10: 'README'

**Comment by yihong0618** [comment]
Seems like a bug. let me see~

**Comment by yihong0618** [comment]
@semico can you check if hava any data in `activities` after run.

**Comment by yihong0618** [comment]
@semico can you double check?

**Comment by semico** [comment]
Yes, all the  activities have been retrieved, because the number of files is equal to my running count in NRC app

**Comment by semico** [comment]
1602372752594
Traceback (most recent call last):
  File "scripts/nike_sync.py", line 311, in <module>
    files = get_to_generate_files()
  File "scripts/nike_sync.py", line 148, in get_to_generate_files
    return [
  File "scripts/nike_sync.py", line 151, in <listcomp>
    if int(i.split(".")[0]) > last_time
ValueError: invalid literal for int() with base 10: ''

**Comment by yihong0618** [comment]
@semico can you retry by latest code.

**Comment by semico** [comment]
@yihong0618 still not work, sorry that I cannot debug it by myself, but I'm trying to learn Python and understand the code.

> 1602372752594
> Traceback (most recent call last):
>   File "scripts/nike_sync.py", line 312, in <module>
>     make_new_gpxs(files)
>   File "scripts/nike_sync.py", line 299, in make_new_gpxs
>     parsed_data = parse_activity_data(json_data)
>   File "scripts/nike_sync.py", line 248, in parse_activity_data
>     for i, metric in enumerate(activity["metrics"]):
> KeyError: 'metrics'

But i found a fact, the first time I try from the beginning without remove the test data, it runs well. It failed when I remove all the test data.

**Comment by yihong0618** [comment]
@semico 
Don't worry, my pleasure to fix it.
I think your nrc contains empty run file. I try to fix the bug.
Now please pull the latest code and try again follow the `Readme` thanks.

**Comment by semico** [comment]
> 1602372752594
> The activity 73462884-e16b-49a4-926e-7de35f0469a1 doesn't contain metrics information
> The activity 36790881-d313-414f-b831-9485c349a268 doesn't contain metrics information
> The activity bd05309a-32c9-4183-bcfa-6f7134c1ddc6 doesn't contain metrics information
> The activity 30da853a-4bc8-4f3a-b90c-43c60ac6218e doesn't contain metrics information
> The activity 7b244c7c-92c7-42f4-9840-ca83b231b057 doesn't contain metrics information
> The activity a9133284-e16a-410f-aa23-ca697e3db470 doesn't contain metrics information
> The activity 09afed94-748c-4eb4-bf98-9553bc6267aa doesn't contain metrics information
> The activity 01836ee5-12d3-40cd-aae1-db1bee14dfd0 doesn't contain metrics information
> 425
> Something went wrong when loading GPX. for file 1337958166012.gpx
> 417
> +++++++++++++++++++++++++Traceback (most recent call last):
>   File "scripts/nike_sync.py", line 318, in <module>
>     make_activities_file(SQL_FILE, GPX_FOLDER, JSON_FILE)
>   File "/Users/yubohu/Code/running_page/scripts/utils.py", line 9, in make_activities_file
>     generator.sync_from_gpx(gpx_dir)
>   File "/Users/yubohu/Code/running_page/scripts/generator/__init__.py", line 76, in sync_from_gpx
>     created = update_or_create_activity(self.session, t.to_namedtuple())
>   File "/Users/yubohu/Code/running_page/scripts/generator/db.py", line 92, in update_or_create_activity
>     distance=run_activity.distance,
> AttributeError: 'x' object has no attribute 'distance'

you got it, but new bug appeared... :(

**Comment by yihong0618** [comment]
@semico That is another problem about NRC, I think you can delete the wrong fox file, I will try to fix this tomorrow.

**Comment by yihong0618** [comment]
@semico ads try catch can you try again？

**Comment by semico** [comment]
problem solved 👍
