### ISSUE TITLE
等宽字体

### ISSUE THREAD

**Issue by L1cardo** [yihong0618/running_page#91]
这些数据能不能弄成等宽字体，这看起来好难受呀
<img width="489" alt="image" src="https://user-images.githubusercontent.com/33802186/108623071-e6615200-7477-11eb-9d4b-fd80d69bff79.png">

可以～ 我之后弄一下^_^

**Comment by yihong0618** [comment]
可以，我之后弄一下。。。

**Comment by shaonianche** [comment]
@L1cardo 我去掉了苹果系统的默认字体，您在看看是否修复。
在您的代码中删除掉：-apple-system 就可以。

**Comment by L1cardo** [comment]
可以了，现在舒服多了！！
干洗两位 @yihong0618 @shaonianche 
<img width="489" alt="image" src="https://user-images.githubusercontent.com/33802186/108624924-e286fd00-7482-11eb-9f05-658370307d2e.png">

**Comment by L1cardo** [comment]
还有一个非常小的问题，这个2021的逗号去掉是不是好一点？
无伤大雅，但是好像不太符合习惯，而且强迫症有点。。。。
<img width="264" alt="image" src="https://user-images.githubusercontent.com/33802186/108625107-fbdc7900-7483-11eb-98f8-6be4c9dc0b69.png">

**Comment by yihong0618** [comment]
> 还有一个非常小的问题，这个2021的逗号去掉是不是好一点？
> 无伤大雅，但是好像不太符合习惯，而且强迫症有点。。。。
> <img alt="image" width="264" src="https://user-images.githubusercontent.com/33802186/108625107-fbdc7900-7483-11eb-98f8-6be4c9dc0b69.png">

好滴，我们看一下。

**Comment by yihong0618** [comment]
> 还有一个非常小的问题，这个2021的逗号去掉是不是好一点？
> 无伤大雅，但是好像不太符合习惯，而且强迫症有点。。。。
> <img alt="image" width="264" src="https://user-images.githubusercontent.com/33802186/108625107-fbdc7900-7483-11eb-98f8-6be4c9dc0b69.png">

@L1cardo 去掉了，你可以更新试一下~

**Comment by L1cardo** [comment]
ok了  感谢！！
