### ISSUE TITLE
[BUG] Keep地图偏移与图标异常

### ISSUE THREAD

**Issue by YiHui-Liu** [yihong0618/running_page#92]
README.md中展示的Keep跑步主页都存在地图偏移问题：
<details>
<summary>View Images ...</summary>

![image](https://user-images.githubusercontent.com/30190271/108788514-1feaa800-75b3-11eb-90b8-a14f8e450b51.png)
![image](https://user-images.githubusercontent.com/30190271/108788664-72c45f80-75b3-11eb-9bc8-60aebd2ffd93.png)
![image](https://user-images.githubusercontent.com/30190271/108788677-7eb02180-75b3-11eb-946d-13a31d2402a6.png)
</details>
部分还存在图标放大问题：
<details>
<summary>View Images ...</summary>

![image](https://user-images.githubusercontent.com/30190271/108788569-3abd1c80-75b3-11eb-9ee4-2b9f85ceff66.png)
![image](https://user-images.githubusercontent.com/30190271/108788609-49a3cf00-75b3-11eb-963c-2ef7660f3101.png)</details>

**Comment by yihong0618** [comment]
@YiHui-Liu 

1. 这个使用国内地图软件会修复，但 mapbox 不会自动修复（如果用 keep 的话可以导出 gpx 上传到没有这个问题的软件，之后用它运动，比如佳明，strava）
Keep 偏移是国内地图的特有问题，https://blog.shengbin.me/posts/map-drift-in-chinese-mainland

2. 这个图标过大是电脑显示问题，如果下图改成 150% 会出现特别大的旗，目前已经修复，更新到最新代码即可。
![image](https://user-images.githubusercontent.com/15976103/108789166-a5228c80-75b4-11eb-8aa2-dd6867c59d84.png)

**Comment by YiHui-Liu** [comment]
好的，感谢

**Comment by yihong0618** [comment]
> 好的，感谢

没关系~ Keep 这个确实不少问题，如果你有兴趣 pr 一直欢迎哈哈。

不建议 keep 的原因之一是，不一定什么时候 Keep 就把这个漏洞补上了。很可能像悦跑圈和咕咚一样无法自动化。

**Comment by YiHui-Liu** [comment]
Keep地图偏移问题不知道怎么在`utils.js`中获取软件类型，所以没有pr。解决方法：
1. 安装依赖[gcoord](https://github.com/hujiulong/gcoord)
```
npm install gcoord --save
```
2. 修改`utils.js`中的`pathForRun`函数
```js
import gcoord from 'gcoord';
...
const pathForRun = (run) => {
  try {
    var c = mapboxPolyline.decode(run.summary_polyline);
    // reverse lat long for mapbox
    c.forEach((arr) => {
      [arr[0], arr[1]] = gcoord.transform([arr[1], arr[0]], gcoord.GCJ02, gcoord.WGS84); // 修改在这一行
    });
    return c;
  } catch (err) {
    return [];
  }
};
```
3. 预览查看，问题已解决
![image](https://user-images.githubusercontent.com/30190271/115552773-3e350180-a2df-11eb-994b-0773a44e30c8.png)

**Comment by yihong0618** [comment]
@YiHui-Liu 
感谢，太帅了。如果你感兴趣 PR 欢迎。

一些 app 我做了统一的命名，为了方便整合。

```js
run.name === "run from keep" // keep
```
应该这样能判断是 keep
