### ISSUE TITLE
建议打包个docker版本

### ISSUE THREAD

**Issue by oysmart** [yihong0618/running_page#94]
建议官方打包个docker版本！部署更方便！！！

**Comment by yihong0618** [comment]
@oysmart 

嗯啊，你又兴趣提 PR 么？

**Comment by oysmart** [comment]
> @oysmart
> 
> 嗯啊，你又兴趣提 PR 么？
 尴尬，我部署了几次不是nodejs问题，就是pip3版本问题。无语了。
