### ISSUE TITLE
可以支持一个跑团（多人）版本吗

### ISSUE THREAD

**Issue by Likenttt** [yihong0618/running_page#95]
支持导入多个用户的数据

**Comment by Likenttt** [comment]
我们跑团大约有几百人，分布在北京、南京、上海、深圳、武汉、海外

**Comment by yihong0618** [comment]
> 我们跑团大约有几百人，分布在北京、南京、上海、深圳、武汉、海外

理论是可以的，把所有的生成gpx扔进gpx文件夹，然后用gpx_sync生成，但我感觉会影响性能。

而且自动化比较困难，特定的人一起更新比较好。

**Comment by yihong0618** [comment]
我觉得fork出来做个多人版本好一些～。不过你有更好的办法 pr welcome～^_^

**Comment by geekplux** [comment]
搞个 Strava 上的跑团应该就行吧

**Comment by Likenttt** [comment]
国行garmin不能用strava了

**Comment by Likenttt** [comment]
> > 我们跑团大约有几百人，分布在北京、南京、上海、深圳、武汉、海外
> 
> 理论是可以的，把所有的生成gpx扔进gpx文件夹，然后用gpx_sync生成，但我感觉会影响性能。
> 
> 而且自动化比较困难，特定的人一起更新比较好。

这么说来可以做一个前端页面，让所有参与者输入一下自己的账户密码，导出的数据汇聚到一起这样就可以了。一定非常壮观，单单是北京就能遍地金黄

**Comment by yihong0618** [comment]
> > > 我们跑团大约有几百人，分布在北京、南京、上海、深圳、武汉、海外
> > 
> > 
> > 理论是可以的，把所有的生成gpx扔进gpx文件夹，然后用gpx_sync生成，但我感觉会影响性能。
> > 而且自动化比较困难，特定的人一起更新比较好。
> 
> 这么说来可以做一个前端页面，让所有参与者输入一下自己的账户密码，导出的数据汇聚到一起这样就可以了。一定非常壮观，单单是北京就能遍地金黄

可以，但这需要后端了，这个本质是个个人跑步数据的页面。我暂时不准备加账号这个。不过你可以另起一个多人版本的项目~

不过我有个思路:

因为这里都是用 sqlite3 和 json 管理的数据, 你可以把各个跑步的人的项目列出来

然后有一个主的页面，用 actions 去拿大家的数据，然后汇聚到一起，这样方便些。

**Comment by Likenttt** [comment]
> > > > 我们跑团大约有几百人，分布在北京、南京、上海、深圳、武汉、海外
> > > 
> > > 
> > > 理论是可以的，把所有的生成gpx扔进gpx文件夹，然后用gpx_sync生成，但我感觉会影响性能。
> > > 而且自动化比较困难，特定的人一起更新比较好。
> > 
> > 
> > 这么说来可以做一个前端页面，让所有参与者输入一下自己的账户密码，导出的数据汇聚到一起这样就可以了。一定非常壮观，单单是北京就能遍地金黄
> 
> 可以，但这需要后端了，这个本质是个个人跑步数据的页面。我暂时不准备加账号这个。不过你可以另起一个多人版本的项目~
> 
> 不过我有个思路:
> 
> 因为这里都是用 sqlite3 和 json 管理的数据, 你可以把各个跑步的人的项目列出来
> 
> 然后有一个主的页面，用 actions 去拿大家的数据，然后汇聚到一起，这样方便些。

把各个跑步的人的项目列出来。并不是所有跑团成员都想搞一个这样的界面。所以还是考虑面向普通用户开箱即用
