### ISSUE TITLE
[问题] 请问这个项目不支持室内跑步吗？

### ISSUE THREAD

**Issue by L1cardo** [yihong0618/running_page#97]
昨天在健身房跑的记录没有显示在running page，不支持Nike Run Club的室内跑步吗？
最近下雨，估计都要在室内跑了 :(

**Comment by yihong0618** [comment]
@L1cardo 理论上可以支持，但是 nike 的逻辑需要一些改的。

因为生成的 gpx 是没有经纬度数据的，室内跑步的话。

---

nike 的话
可以改成 json -> data.db 室内不绘制曲线。但是数据可能要重新生成。

我这几天有空做一下。

**Comment by L1cardo** [comment]
太感谢了！

**Comment by yihong0618** [comment]
> 太感谢了！

@L1cardo 
已经支持了，可以更新最新代码尝试。
如果不能直接成功，可以尝试删除 data.db 和 GPX_OUT/* 重新跑一下。

如果还是不成功请留言。

**Comment by L1cardo** [comment]
@yihong0618 有了有了！虽然室内跑步地图，但是看着记录数据也是很激励的。
十分感谢！

**Comment by yihong0618** [comment]
> @yihong0618 有了有了！虽然室内跑步地图，但是看着记录数据也是很激励的。
> 十分感谢！

好的。有 bug 直接 at 我。

**Comment by Quitino** [comment]
佬哥，请问 garmin-cn 支持室内吗？该如何操作啊？

**Comment by yihong0618** [comment]
> 佬哥，请问 garmin-cn 支持室内吗？该如何操作啊？感谢感谢.

目前应该不支持，得改代码，因为现在走的是 gpx

**Comment by Quitino** [comment]
> > 佬哥，请问 garmin-cn 支持室内吗？该如何操作啊？感谢感谢.
> 
> 目前应该不支持，得改代码，因为现在走的是 gpx

期待未来能够支持，是不是可以将tcx转gpx，将经纬高设为一个默认值就行

**Comment by yihong0618** [comment]
> > > 佬哥，请问 garmin-cn 支持室内吗？该如何操作啊？感谢感谢.
> > 
> > 
> > 目前应该不支持，得改代码，因为现在走的是 gpx
> 
> 期待未来能够支持，是不是可以将tcx转gpx，将经纬高设为一个默认值就行

可以直接存数据库不走 gpx 
PR welcome
