### ISSUE TITLE
 省份统计的时候缺少上海市

### ISSUE THREAD

**Issue by ustccuikai** [yihong0618/running_page#98]
省份统计的时候缺少上海市

**Comment by yihong0618** [comment]
理论上在，可能正则哪块匹配错了，你能给出更多信息么？
![image](https://user-images.githubusercontent.com/15976103/110717599-5166a300-8244-11eb-9462-05b92b89bb91.png)

**Comment by ustccuikai** [comment]
打开sqllite的表看了下，地点都是这种格式的
xx路, 唐镇, 浦东新区, 201201, 中国

**Comment by yihong0618** [comment]
> 打开sqllite的表看了下，地点都是这种格式的
> xx路, 唐镇, 浦东新区, 201201, 中国

明白了，这块因为我数据不多，做的不是很健壮。你有兴趣帮我把这个问题修复下么？

正则位置
https://github.com/yihong0618/running_page/blob/master/src/utils/utils.js#L40

**Comment by ustccuikai** [comment]
我估计搞不定，地址的话我估计要先标准化，单纯正则可能搞不定，可以参考下这个https://github.com/DQinYuan/chinese_province_city_area_mapper

**Comment by yihong0618** [comment]
> 我估计搞不定，地址的话我估计要先标准化，单纯正则可能搞不定，可以参考下这个https://github.com/DQinYuan/chinese_province_city_area_mapper

确实，这块返回的数据非常乱，我是根据经纬度 -> 获取的，数据返回不一致。

不过针对你的特殊情况，你可以先特殊处理，我研究下这个项目，谢谢你~
